; Bank $17 description text ($4618-$6117): the room-editor help text plus all
; item / monster / block descriptions, as a 36-tile-wide BG tilemap (ASCII tile
; encoding). One 36-char db row per line: the editor help is indented to col 18,
; the item/monster descriptions start at col 0. Carved from analyzed.asm, byte-exact.

SECTION "Editor descriptions", ROMX

EditorDescriptionText:
	db "                  This is a large   "
	db "                  room called       "
	db "                  This is a small   "
	db "                  room called       "
	db "                  This one is       "
	db "                  open.             "
	db "                  Returns a screen. "
	db "                                    "
	db "                  Select if only    "
	db "                  sending a room.   "
	db "                  Select if only    "
	db "                  receiving a room. "
	db "                  Create a room     "
	db "                  Will lose data.   "
	db "                  Reverts to open.  "
	db "                                    "
	db "                  You can play      "
	db "                  this room.        "
	db "                  You can rename    "
	db "                  this room.        "
	db "                  Return a screen.  "
	db "                                    "
	db "                                    "
	db "                                    "
	db "                  First, choose     "
	db "                  a room size.      "
	db "                  Sets the          "
	db "                  background.       "
	db "                  Sets blocks and   "
	db "                  other things.     "
	db "                  Sets items and    "
	db "                  other things.     "
	db "                  Places the        "
	db "                  characters.       "
	db "                  You can           "
	db "                  test play.        "
	db "                  Saves the         "
	db "                  created room.     "
	db "                  Return a screen.  "
	db "                                    "
	db "                  Data will be      "
	db "                  Saved. OK?        "
	db "                  Details set by    "
	db "                  pressing Select.  "
	db "                  3 monster types   "
	db "                  can be placed.    "
	db "                  Can place up      "
	db "                  to 9 monsters.    "
	db "                  Can place up      "
	db "                  to 10 items.      "
	db "                  Can place up to   "
	db "                  4 saucer stones.  "
	db "                  Hide item by      "
	db "                  pressing Select.  "
	db "                  Sets the speed    "
	db "                  of the monster.   "
	db "                  Sets direction    "
	db "                  of the monster.   "
	db "                  Sets speed of     "
	db "                  special attack.   "
	db "                  Sets facing and   "
	db "                  turn directions.  "
	db "                  Sets life for     "
	db "                  Stone monsters.   "
	db "                  Sets direction    "
	db "                  for monsters.     "
	db "                  Sets speed for    "
	db "                  Stone monsters.   "
	db "                  Picks monster     "
	db "                  for the stone.    "
	db "                  You can't place   "
	db "                  the block there.  "
	db "                  No monster        "
	db "                  chosen for stone. "
	db "                  Can't place any   "
	db "                  more monsters.    "
	db "                  Can't place       "
	db "                  more stones.      "
	db "                  Can't place       "
	db "                  any more items.   "
	db "                  Cannot place a    "
	db "                  monster there.    "
	db "                  Cannot place a    "
	db "                  player there.     "
	db "                  That monster is   "
	db "                  set to the stone. "
	db "                  Gold key or exit  "
	db "                  door not put yet. "
	db "                  Can change wall   "
	db "                  patterns/colors   "
	db "                  Exit door         "
	db "                  Always set it     "
	db "                  Saucer stone      "
	db "                  Releases monsters "
	db "                  Devil's Seal      "
	db "                  Bans block make   "
	db "                  Strong block      "
	db "                  Cannot break      "
	db "                  Breakable block   "
	db "                  Can break         "
	db "Gold key                            "
	db "Must be placed                      "
	db "Bell                                "
	db "Calls Suzurin                       "
	db "Half Tororon                        "
	db "Pill to 2X time                     "
	db "Full Tororon                        "
	db "Pill to 5X time                     "
	db "Orange Hourglass                    "
	db "Time to 5,000                       "
	db "Blue Hourglass                      "
	db "Time to 10,000                      "
	db "Cox's Hat                           "
	db "1 Cox increases                     "
	db "Small Bomb                          "
	db "Firework attacks                    "
	db "Big Bomb                            "
	db "Bigger fireworks                    "
	db "Fireplace                           "
	db "Adds fireworks                      "
	db "Gunpowder                           "
	db "Converts bombs                      "
	db "Blue Crystal                        "
	db "fireworks range   increases         "
	db "Red Crystal                         "
	db "REALLY increases  fireworks range   "
	db "Blue Diamond                        "
	db "500 points                          "
	db "Red Diamond                         "
	db "5,000 points                        "
	db "Platinum Ring                       "
	db "50,000 points                       "
	db "Silver Medal                        "
	db "100 points                          "
	db "Silver Nugget                       "
	db "200 points                          "
	db "Gold Medal                          "
	db "1,000 points                        "
	db "Golden Nugget                       "
	db "2,000 points                        "
	db "Heal Badge                          "
	db "10,000 points                       "
	db "Cake                                "
	db "100,000 points                      "
	db "Golden Peach                        "
	db "500,000 points                      "
	db "Silver Peach                        "
	db "500,000 points                      "
	db "Duck Doll                           "
	db "Destroys monster                    "
	db "Player                              "
	db "Start location                      "
	db "Tacopi                              "
	db "Rotate and moves  left and right    "
	db "Jell                                "
	db "Chases Cox                          "
	db "Naga                                "
	db "Chases for claw   attacks           "
	db "Dino                                "
	db "Breathes fire                       "
	db "Plant                               "
	db "Moves left/right  and shoots seeds  "
	db "Henger                              "
	db "Flies back/forth                    "
	db "Joker                               "
	db "Flies back/forth                    "
	db "Ghost                               "
	db "Flies up/down                       "
	db "Puncho                              "
	db "Turns player      into a pumpkin    "
	db "Psylora                             "
	db "Moves along wall                    "
	db "Ducken                              "
	db "Sticks to wall    Fires missiles    "
	db "Red Flame                           "
	db "Flame disappears  After dropped     "
	db "Blue Flame                          "
	db "Flame doesn't     disappear         "
	db "                                    "
	db "                                    "
	db "                                    "
	db "                                    "
	db "                                    "
	db "                                    "
	db "                                    "
	db "                                    "
	db "                                    "
	db "                                    "
	db "                                    "
	db "                                    "
	db "                                    "
	db "                                    "
