; Kalum's encounter portrait (tower NPC). Drawn by Kalum_StartEncounter
; ($1f:$417b): the tiles are copied to VRAM bank 1 $8000 ($8800 signed tile
; addressing) and arranged by the CopyBgMap descriptor below over the top
; 20x11 cells; see docs/text_engine.md.
;
; Assembled from the editable source under assets/portrait/kalum/ by
; tools/pngasset.py (`portrait` mode, run in the Makefile, output under
; build/assets/). The descriptor references the two maps by *label* (dw), so the
; region is internally relocatable (docs/philosophy.md). The 6 BG + 6 OBJ palettes
; (loaded by Kalum_StartEncounter from $1d:$5800/$5840) are carved here from the
; PNG's colour table, so the portrait carries its real colour.
INCLUDE "util.inc"

SECTION "Kalum graphics", ROMX

ASSET KalumPortraitTiles, "assets/portrait/npc/kalum/tiles.bin"    ; 384 tiles -> VRAM bank 1 $8000
ASSET KalumPortraitPaletteBg, "assets/portrait/npc/kalum/palette_bg.bin"   ; 6 BG palettes (RGB555 LE)

DS $10, 0

ASSET KalumPortraitPaletteObj, "assets/portrait/npc/kalum/palette_obj.bin"  ; 6 OBJ palettes (RGB555 LE)

DS $10, 0

KalumPortraitMapDesc:
	db 11, 20                                    ; rows, cols
	dw KalumPortraitAttrMap                       ; CGB attribute map pointer
	dw KalumPortraitIndexMap                      ; tile index map pointer

KalumPortraitIndexMap:
	INCBIN "assets/portrait/npc/kalum/tilemap.bin"  ; 20x11 tile indices

KalumPortraitAttrMap:
	INCBIN "assets/portrait/npc/kalum/attrmap.bin"  ; 20x11 CGB BG attributes

; Kalum's metasprite/patch overlay region: the eyes blink-animation frames (BG
; eye patches + their OBJ overlays) plus Kalum's shoulder/collar and the eye of
; Selketo (the monster behind him) drawn every frame. Generated byte-exact from
; the layered source (assets/portrait/kalum/sprites/*.png + sprites.yaml) by
; tools/pngasset.py -- see Kalum_AnimateMonsterPortrait ($1f) for the block roles.
	INCLUDE "assets/portrait/npc/kalum/sprites.asm"   ; Kalum_<role> blocks
