; Pashute's encounter portrait (shown during Pashute's encounter); located by following the
; script's far-calls (tools/find_portraits.py). Same 20x11 single-blob layout as
; Kalum: 384 tiles -> VRAM bank 1 $8000 ($8800 signed addressing), arranged by the
; CopyBgMap descriptor below. Assembled from assets/portrait/pashute/ via
; tools/pngasset.py (Makefile, output under build/assets/). The 6 BG + 6 OBJ
; palettes (loaded by Pashute_LoadShrineScene from $1b:$5800/$5840) are carved here
; from the PNG's colour table.

SECTION "Pashute graphics", ROMX

PashutePortraitTiles:
	INCBIN "assets/portrait/npc/pashute/tiles.bin"

PashutePortraitPaletteBg:
	INCBIN "assets/portrait/npc/pashute/palette_bg.bin"   ; 6 BG palettes (RGB555 LE)

Data_1b_5830:
	db $ff, $7f, $3e, $1b, $37, $01, $4b, $00, $ff, $7f, $94, $52, $4a, $29, $00, $00

PashutePortraitPaletteObj:
	INCBIN "assets/portrait/npc/pashute/palette_obj.bin"  ; 6 OBJ palettes (RGB555 LE)

Data_1b_5870:
	db $e0, $03, $e0, $03, $e0, $03, $e0, $03, $00, $00, $00, $00, $00, $00, $00, $00

PashutePortraitMapDesc:
	db 11, 20
	dw PashutePortraitAttrMap
	dw PashutePortraitIndexMap

PashutePortraitIndexMap:
	INCBIN "assets/portrait/npc/pashute/tilemap.bin"

PashutePortraitAttrMap:
	INCBIN "assets/portrait/npc/pashute/attrmap.bin"

; Pashute's metasprite/patch overlay region: the neutral eyes blink-animation
; frames, shoulders, collar, and the sad/shocked expressions. Generated byte-exact
; from the layered source (assets/portrait/pashute/sprites/*.png + sprites.yaml) by
; tools/pngasset.py -- see that manifest for the per-block roles.
	INCLUDE "assets/portrait/npc/pashute/sprites.asm"   ; Pashute_<role> blocks

; Trailing 64 bytes ($5bdd-$5c1c): not yet structured (intro-scene data + zero pad).
Data_1b_5bdd:
	db $44, $18, $df, $3a, $b0, $45, $ed, $20, $44, $18, $44, $18, $44, $18, $44, $18
	db $44, $18, $44, $18, $b0, $45, $df, $3a, $44, $18, $44, $18, $44, $18, $b0, $45
	db $44, $18, $44, $18, $b0, $45, $ed, $20, $b0, $45, $44, $18, $44, $18, $df, $3a
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00

SECTION "analyzed_06dc1d", ROMX[$5c1d], BANK[$1b]

Data_1b_5c1d:
	db $ff, $03, $5a, $24, $aa, $28, $68, $00, $00, $7c, $7b, $6b, $7b, $3a, $68, $00
	db $1f, $7c, $7b, $6b, $f2, $51, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
