; Toamuna's portrait (ranch save NPC, mother of Naji). Shown by her "what do you
; want to do?" menu; located by following her script's far-calls
; (tools/find_portraits.py). Same descriptor layout as Kalum's portrait: the 384
; tiles are copied to VRAM bank 1 $8000 ($8800 signed addressing) and arranged by
; the CopyBgMap descriptor below over the top 20x11 cells.
;
; Assembled from the editable source under assets/portrait/toamuna/ by
; tools/pngasset.py (run in the Makefile, output under build/assets/). The
; descriptor references the two maps by *label* (dw), so the region is internally
; relocatable. The 6 BG + 6 OBJ palettes (loaded by Toamuna_CheckSaveExists from
; $1a:$5800/$5840) are carved here from the PNG's colour table.
INCLUDE "util.inc"

SECTION "Toamuna graphics", ROMX

ASSET ToamunaPortraitTiles, "assets/portrait/npc/toamuna/tiles.bin" ; 384 tiles -> VRAM bank 1 $8000
ASSET ToamunaPortraitPaletteBg, "assets/portrait/npc/toamuna/palette_bg.bin" ; 6 BG palettes (RGB555 LE)

DS $10

ASSET ToamunaPortraitPaletteObj, "assets/portrait/npc/toamuna/palette_obj.bin" ; 6 OBJ palettes (RGB555 LE)

DS $10

MAP_ASSET ToamunaPortraitMapDesc, \
	.Width=20, \
	.Height=11, \
	.Attrs=ToamunaPortraitAttrMap, \
	.Indexes=ToamunaPortraitIndexMap,

ToamunaPortraitIndexMap: INCBIN "assets/portrait/npc/toamuna/tilemap.bin"
ToamunaPortraitAttrMap:  INCBIN "assets/portrait/npc/toamuna/attrmap.bin"

; Toamuna's metasprite/patch overlay region: two static expressions (default + alt),
; each a hair metasprite plus a face patch (-> BG $98c4). Generated byte-exact from
; the layered source (assets/portrait/toamuna/sprites/*.png + sprites.yaml) by
; tools/pngasset.py -- see Toamuna_RenderPortrait / Toamuna_RenderPortraitAlt ($19).
INCLUDE "assets/portrait/npc/toamuna/sprites.asm"   ; Toamuna_face / _hair / _alt_face / _alt_hair
