; Sound id $35 (BGM) -- disc stone regeneration
; Bank $3e, ROM $5ef9-$62f9. Auto-generated by tools/songdisasm.py --split; INCLUDEd by sound/bank_3e.asm into its $4b00 section.

; ===== sound id $35 =====
Snd_3e_5ef9:
	s_chan $f0, Snd_3e_5f05
	s_chan $f0, Snd_3e_60ea
	s_chan $f0, Snd_3e_61bf
	s_chan $f0, Snd_3e_6235
Snd_3e_5f05:
	s_pitchenv 1
	s_set10 0
	s_dutyenv 2
	s_call Snd_3e_5f27
	s_call Snd_3e_5f4a
	s_call Snd_3e_5f6d
	s_call Snd_3e_5f85
	s_call Snd_3e_5fe4
	s_call Snd_3e_6048
	s_call Snd_3e_60bc
	s_call Snd_3e_60d7
	s_call Snd_3e_60e0
	s_end
Snd_3e_5f27:
	s_oct 6	; block 5
	s_instr 3
	s_deflen 28
	s_note SC_D    	; D
	s_deflen 1
	s_instr 5
	s_note SC_F    	; F
	s_keyon
	s_deflen 2
	s_instr 4
	s_note SC_F    	; F
	s_keyon
	s_instr 3
	s_note SC_F    	; F
	s_keyon
	s_instr 2
	s_note SC_F    	; F
	s_keyon
	s_deflen 21
	s_instr 2
	s_note SC_F    	; F
	s_keyon
	s_note_l SC_F, 56	; F dur=56
	s_ret
Snd_3e_5f4a:
	s_keyon
	s_instr 2
	s_note_l SC_F, 56	; F dur=56
	s_oct 5	; block 4
	s_deflen 1
	s_instr 5
	s_note SC_G    	; G
	s_keyon
	s_deflen 2
	s_instr 4
	s_note SC_G    	; G
	s_keyon
	s_instr 3
	s_note SC_G    	; G
	s_keyon
	s_instr 2
	s_note SC_G    	; G
	s_keyon
	s_deflen 21
	s_instr 2
	s_note SC_G    	; G
	s_keyon
	s_note_l SC_G, 28	; G dur=28
	s_ret
Snd_3e_5f6d:
	s_deflen 14
	s_keyon
	s_instr 2
	s_note SC_G    	; G
	s_keyon
	s_instr 3
	s_note SC_G    	; G
	s_keyon
	s_instr 4
	s_note SC_G    	; G
	s_keyon
	s_instr 5
	s_note SC_G    	; G
	s_oct 6	; block 5
	s_instr 3
	s_note_l SC_E, 56	; E dur=56
	s_ret
Snd_3e_5f85:
	s_deflen 5
	s_oct 4	; block 3
	s_instr 1
	s_note SC_GS   	; G#
	s_instr 3
	s_note SC_GS   	; G#
	s_deflen 4
	s_instr 5
	s_note SC_GS   	; G#
	s_deflen 5
	s_oct 5	; block 4
	s_instr 1
	s_note SC_C    	; C
	s_instr 3
	s_note SC_C    	; C
	s_deflen 4
	s_instr 5
	s_note SC_C    	; C
	s_deflen 5
	s_instr 1
	s_note SC_DS   	; D#
	s_instr 3
	s_note SC_DS   	; D#
	s_deflen 4
	s_instr 5
	s_note SC_DS   	; D#
	s_deflen 5
	s_instr 1
	s_note SC_C    	; C
	s_instr 3
	s_note SC_C    	; C
	s_deflen 4
	s_instr 5
	s_note SC_C    	; C
	s_deflen 5
	s_instr 1
	s_note SC_GS   	; G#
	s_instr 3
	s_note SC_GS   	; G#
	s_deflen 4
	s_instr 5
	s_note SC_GS   	; G#
	s_deflen 5
	s_oct 6	; block 5
	s_instr 1
	s_note SC_C    	; C
	s_instr 3
	s_note SC_C    	; C
	s_deflen 4
	s_instr 5
	s_note SC_C    	; C
	s_deflen 7
	s_oct 5	; block 4
	s_instr 1
	s_note SC_DS   	; D#
	s_instr 3
	s_note SC_DS   	; D#
	s_instr 5
	s_note SC_DS   	; D#
	s_note SC_REST 	; rest
	s_ret
Snd_3e_5fe4:
	s_dutyenv 5
	s_deflen 5
	s_oct 4	; block 3
	s_instr 0
	s_note SC_FS   	; F#
	s_instr 2
	s_note SC_FS   	; F#
	s_deflen 4
	s_instr 3
	s_note SC_FS   	; F#
	s_deflen 5
	s_oct 5	; block 4
	s_instr 0
	s_note SC_C    	; C
	s_instr 2
	s_note SC_C    	; C
	s_deflen 4
	s_instr 3
	s_note SC_C    	; C
	s_deflen 5
	s_instr 0
	s_note SC_DS   	; D#
	s_instr 2
	s_note SC_DS   	; D#
	s_deflen 4
	s_instr 3
	s_note SC_DS   	; D#
	s_deflen 5
	s_instr 0
	s_note SC_C    	; C
	s_instr 2
	s_note SC_C    	; C
	s_deflen 4
	s_instr 3
	s_note SC_C    	; C
	s_deflen 5
	s_instr 0
	s_note SC_GS   	; G#
	s_instr 2
	s_note SC_GS   	; G#
	s_deflen 4
	s_instr 3
	s_note SC_GS   	; G#
	s_deflen 5
	s_oct 6	; block 5
	s_instr 0
	s_note SC_C    	; C
	s_instr 2
	s_note SC_C    	; C
	s_deflen 4
	s_instr 3
	s_note SC_C    	; C
	s_dutyenv 2
	s_oct 6	; block 5
	s_deflen 7
	s_instr 0
	s_note SC_DS   	; D#
	s_note SC_CS   	; C#
	s_instr 1
	s_note SC_C    	; C
	s_oct 5	; block 4
	s_instr 2
	s_note SC_B    	; B
	s_ret
Snd_3e_6048:
	s_deflen 2
	s_instr 0
	s_note SC_AS   	; A#
	s_deflen 3
	s_oct 6	; block 5
	s_note SC_C    	; C
	s_oct 5	; block 4
	s_instr 2
	s_note SC_AS   	; A#
	s_oct 6	; block 5
	s_note SC_C    	; C
	s_oct 5	; block 4
	s_instr 1
	s_note SC_AS   	; A#
	s_oct 6	; block 5
	s_note SC_C    	; C
	s_oct 5	; block 4
	s_instr 2
	s_note SC_AS   	; A#
	s_oct 6	; block 5
	s_note SC_C    	; C
	s_oct 5	; block 4
	s_instr 1
	s_note SC_AS   	; A#
	s_oct 6	; block 5
	s_note SC_C    	; C
	s_oct 5	; block 4
	s_instr 3
	s_note SC_AS   	; A#
	s_oct 6	; block 5
	s_note SC_C    	; C
	s_oct 5	; block 4
	s_instr 2
	s_note SC_AS   	; A#
	s_oct 6	; block 5
	s_note SC_C    	; C
	s_oct 5	; block 4
	s_instr 3
	s_note SC_AS   	; A#
	s_oct 6	; block 5
	s_note SC_C    	; C
	s_oct 5	; block 4
	s_instr 2
	s_note SC_AS   	; A#
	s_oct 6	; block 5
	s_note SC_C    	; C
	s_oct 5	; block 4
	s_instr 4
	s_note SC_AS   	; A#
	s_oct 6	; block 5
	s_note SC_C    	; C
	s_oct 5	; block 4
	s_instr 3
	s_note SC_AS   	; A#
	s_oct 6	; block 5
	s_note SC_C    	; C
	s_oct 5	; block 4
	s_instr 4
	s_note SC_AS   	; A#
	s_oct 6	; block 5
	s_note SC_C    	; C
	s_oct 5	; block 4
	s_instr 3
	s_note SC_AS   	; A#
	s_oct 6	; block 5
	s_note SC_C    	; C
	s_oct 5	; block 4
	s_instr 5
	s_note SC_AS   	; A#
	s_deflen 4
	s_oct 6	; block 5
	s_note SC_C    	; C
	s_dutyenv 0
	s_oct 4	; block 3
	s_deflen 4
	s_instr 0
	s_note SC_F    	; F
	s_instr 1
	s_note SC_F    	; F
	s_deflen 5
	s_instr 0
	s_note SC_AS   	; A#
	s_instr 1
	s_note SC_AS   	; A#
	s_oct 5	; block 4
	s_instr 0
	s_note SC_F    	; F
	s_instr 1
	s_note SC_F    	; F
	s_ret
Snd_3e_60bc:
	s_deflen 14
	s_instr 0
	s_note_l SC_FS, 56	; F# dur=56
	s_deflen 10
	s_note SC_DS   	; D#
	s_instr 1
	s_note SC_DS   	; D#
	s_deflen 9
	s_instr 0
	s_note SC_FS   	; F#
	s_instr 1
	s_note SC_FS   	; F#
	s_instr 0
	s_note SC_B    	; B
	s_instr 1
	s_note SC_B    	; B
	s_ret
Snd_3e_60d7:
	s_dutyenv 1
	s_deflen 112
	s_instr 0
	s_note SC_AS   	; A#
	s_keyon
	s_ret
Snd_3e_60e0:
	s_instr 0
	s_note_l SC_AS, 84	; A# dur=84
	s_instr 3
	s_note_l SC_AS, 14	; A# dur=14
	s_note SC_REST 	; rest
	s_ret
Snd_3e_60ea:
	s_pitchenv 1
	s_set10 1
	s_dutyenv 1
	s_call Snd_3e_610c
	s_call Snd_3e_6120
	s_call Snd_3e_6126
	s_call Snd_3e_6128
	s_call Snd_3e_6136
	s_call Snd_3e_6142
	s_call Snd_3e_6191
	s_call Snd_3e_61ae
	s_call Snd_3e_61b5
	s_end
Snd_3e_610c:
	s_oct 5	; block 4
	s_deflen 3
	s_instr 2
	s_note SC_D    	; D
	s_keyon
	s_deflen 4
	s_instr 3
	s_note SC_D    	; D
	s_keyon
	s_deflen 14
	s_instr 2
	s_note_l SC_D, 105	; D dur=105
	s_ret
Snd_3e_6120:
	s_deflen 112
	s_instr 3
	s_note SC_DS   	; D#
	s_ret
Snd_3e_6126:
	s_note SC_D    	; D
	s_ret
Snd_3e_6128:
	s_instr 1
	s_deflen 14
	s_note SC_DS   	; D#
	s_note SC_E    	; E
	s_deflen 28
	s_note_l SC_DS, 56	; D# dur=56
	s_instr 2
	s_note SC_DS   	; D#
	s_ret
Snd_3e_6136:
	s_keyon
	s_note SC_DS   	; D#
	s_instr 3
	s_note SC_DS   	; D#
	s_instr 4
	s_note SC_DS   	; D#
	s_instr 5
	s_note SC_DS   	; D#
	s_ret
Snd_3e_6142:
	s_dutyenv 5
	s_oct 6	; block 5
	s_deflen 3
	s_instr 0
	s_note SC_DS   	; D#
	s_note SC_F    	; F
	s_instr 2
	s_note SC_DS   	; D#
	s_note SC_F    	; F
	s_instr 1
	s_note SC_DS   	; D#
	s_note SC_F    	; F
	s_instr 2
	s_note SC_DS   	; D#
	s_note SC_F    	; F
	s_instr 2
	s_note SC_DS   	; D#
	s_note SC_F    	; F
	s_instr 3
	s_note SC_DS   	; D#
	s_note SC_F    	; F
	s_instr 2
	s_note SC_DS   	; D#
	s_note SC_F    	; F
	s_instr 4
	s_note SC_DS   	; D#
	s_note SC_F    	; F
	s_instr 3
	s_note SC_DS   	; D#
	s_note SC_F    	; F
	s_deflen 2
	s_instr 4
	s_note SC_DS   	; D#
	s_dutyenv 1
	s_deflen 28
	s_oct 5	; block 4
	s_instr 0
	s_note SC_F    	; F
	s_oct 4	; block 3
	s_deflen 4
	s_instr 0
	s_note SC_AS   	; A#
	s_instr 1
	s_note SC_AS   	; A#
	s_oct 5	; block 4
	s_deflen 5
	s_instr 0
	s_note SC_F    	; F
	s_instr 1
	s_note SC_F    	; F
	s_instr 0
	s_note SC_AS   	; A#
	s_instr 1
	s_note SC_AS   	; A#
	s_ret
Snd_3e_6191:
	s_deflen 14
	s_oct 4	; block 3
	s_instr 0
	s_note_l SC_B, 56	; B dur=56
	s_deflen 10
	s_note SC_B    	; B
	s_instr 1
	s_note SC_B    	; B
	s_oct 5	; block 4
	s_deflen 9
	s_instr 0
	s_note SC_DS   	; D#
	s_instr 1
	s_note SC_DS   	; D#
	s_instr 0
	s_note SC_FS   	; F#
	s_instr 1
	s_note SC_FS   	; F#
	s_ret
Snd_3e_61ae:
	s_deflen 112
	s_instr 1
	s_note SC_F    	; F
	s_keyon
	s_ret
Snd_3e_61b5:
	s_instr 1
	s_note_l SC_F, 84	; F dur=84
	s_instr 4
	s_note_l SC_F, 14	; F dur=14
	s_note SC_REST 	; rest
	s_ret
Snd_3e_61bf:
	s_pitchenv 0
	s_set10 0
	s_call Snd_3e_61df
	s_call Snd_3e_61f4
	s_call Snd_3e_61f8
	s_call Snd_3e_61fa
	s_call Snd_3e_61fd
	s_call Snd_3e_6204
	s_call Snd_3e_620c
	s_call Snd_3e_6226
	s_call Snd_3e_622d
	s_end
Snd_3e_61df:
	s_wave 2
	s_deflen 42
	s_oct 3	; block 2
	s_instr 20
	s_note SC_G    	; G
	s_instr 19
	s_note_l SC_G, 14	; G dur=14
	s_oct 3	; block 2
	s_instr 20
	s_note SC_G    	; G
	s_deflen 7
	s_note SC_F    	; F
	s_note SC_E    	; E
	s_ret
Snd_3e_61f4:
	s_deflen 112
	s_note SC_DS   	; D#
	s_ret
Snd_3e_61f8:
	s_note SC_A    	; A
	s_ret
Snd_3e_61fa:
	s_note SC_GS   	; G#
	s_keyon
	s_ret
Snd_3e_61fd:
	s_note_l SC_GS, 98	; G# dur=98
	s_instr 19
	s_note_l SC_GS, 14	; G# dur=14
	s_ret
Snd_3e_6204:
	s_instr 20
	s_note_l SC_F, 56	; F dur=56
	s_oct 4	; block 3
	s_note_l SC_F, 56	; F dur=56
	s_ret
Snd_3e_620c:
	s_oct 3	; block 2
	s_note_l SC_FS, 56	; F# dur=56
	s_oct 4	; block 3
	s_deflen 10
	s_note SC_DS   	; D#
	s_instr 19
	s_note SC_DS   	; D#
	s_deflen 9
	s_instr 20
	s_note SC_CS   	; C#
	s_instr 19
	s_note SC_CS   	; C#
	s_oct 3	; block 2
	s_instr 20
	s_note SC_B    	; B
	s_instr 19
	s_note SC_B    	; B
	s_ret
Snd_3e_6226:
	s_deflen 112
	s_instr 20
	s_note SC_AS   	; A#
	s_keyon
	s_ret
Snd_3e_622d:
	s_note_l SC_AS, 98	; A# dur=98
	s_instr 19
	s_note_l SC_AS, 14	; A# dur=14
	s_note SC_REST 	; rest
	s_ret
Snd_3e_6235:
	s_pitchenv 0
	s_deflen 7
	s_oct 1	; block 0
	s_set10 0
	s_call Snd_3e_6258
	s_call Snd_3e_6258
	s_call Snd_3e_6258
	s_call Snd_3e_6258
	s_call Snd_3e_6258
	s_call Snd_3e_62b2
	s_call Snd_3e_62ce
	s_call Snd_3e_62e4
	s_call Snd_3e_62f1
	s_end
Snd_3e_6258:
	s_deflen 112
	s_note SC_REST 	; rest
	s_ret
Snd_3e_625c:	; unused/dead pattern
	s_deflen 7
	s_instr 10
	s_note_l SC_F, 14	; F dur=14
	s_note SC_C    	; C
	s_note SC_C    	; C
	s_note SC_C    	; C
	s_note_l SC_F, 14	; F dur=14
	s_note SC_C    	; C
	s_note SC_F    	; F
	s_note SC_C    	; C
	s_note SC_C    	; C
	s_note SC_F    	; F
	s_note_l SC_C, 14	; C dur=14
	s_note_l SC_F, 14	; F dur=14
	s_ret
	s_deflen 7
	s_instr 10
	s_note_l SC_F, 14	; F dur=14
	s_note SC_C    	; C
	s_note SC_C    	; C
	s_note SC_C    	; C
	s_note_l SC_F, 14	; F dur=14
	s_note SC_F    	; F
	s_note_l SC_F, 14	; F dur=14
	s_note SC_C    	; C
	s_note SC_C    	; C
	s_note_l SC_C, 14	; C dur=14
	s_note_l SC_F, 14	; F dur=14
	s_ret
	s_deflen 7
	s_instr 10
	s_note_l SC_F, 14	; F dur=14
	s_note SC_C    	; C
	s_note SC_C    	; C
	s_note SC_C    	; C
	s_note SC_C    	; C
	s_note SC_F    	; F
	s_note SC_C    	; C
	s_note_l SC_F, 14	; F dur=14
	s_note SC_C    	; C
	s_note SC_C    	; C
	s_note_l SC_F, 14	; F dur=14
	s_note SC_F    	; F
	s_note SC_C    	; C
	s_ret
	s_deflen 7
	s_instr 10
	s_note_l SC_F, 14	; F dur=14
	s_note SC_C    	; C
	s_note SC_C    	; C
	s_note SC_F    	; F
	s_note SC_C    	; C
	s_note SC_F    	; F
	s_note SC_C    	; C
	s_note_l SC_F, 14	; F dur=14
	s_note_l SC_C, 14	; C dur=14
	s_instr 14
	s_note SC_D    	; D
	s_note SC_D    	; D
	s_note SC_D    	; D
	s_note SC_D    	; D
	s_ret
Snd_3e_62b2:
	s_deflen 7
	s_instr 10
	s_note_l SC_F, 14	; F dur=14
	s_instr 14
	s_note SC_D    	; D
	s_note SC_D    	; D
	s_note SC_D    	; D
	s_note SC_D    	; D
	s_note SC_D    	; D
	s_note SC_D    	; D
	s_instr 13
	s_note_l SC_DS, 28	; D# dur=28
	s_deflen 8
	s_instr 14
	s_note SC_D    	; D
	s_deflen 10
	s_note SC_D    	; D
	s_note SC_D    	; D
	s_ret
Snd_3e_62ce:
	s_deflen 7
	s_instr 13
	s_note_l SC_DS, 42	; D# dur=42
	s_instr 14
	s_note SC_D    	; D
	s_note SC_D    	; D
	s_deflen 20
	s_instr 10
	s_note SC_F    	; F
	s_deflen 18
	s_instr 14
	s_note SC_D    	; D
	s_note SC_D    	; D
	s_ret
Snd_3e_62e4:
	s_deflen 7
	s_instr 13
	s_note_l SC_DS, 56	; D# dur=56
	s_note_l SC_DS, 42	; D# dur=42
	s_instr 14
	s_note SC_D    	; D
	s_note SC_D    	; D
	s_ret
Snd_3e_62f1:
	s_deflen 112
	s_instr 13
	s_note_l SC_DS, 84	; D# dur=84
	s_note SC_DS   	; D#
	s_note SC_REST 	; rest
	s_ret
