; Sound id $2e (BGM) -- ?
; Bank $3f, ROM $6eb6-$7ffe. Auto-generated by tools/songdisasm.py --split; INCLUDEd by sound/bank_3f.asm into its $4b00 section.

; ===== sound id $2e =====
Snd_3f_6eb6:
	s_chan $f0, Snd_3f_6ec2
	s_chan $f0, Snd_3f_6fac
	s_chan $f0, Snd_3f_7081
	s_chan $f0, Snd_3f_710a
Snd_3f_6ec2:
	s_pitchenv 0
	s_set10 0
Snd_3f_6ec6:
	s_dutyenv 5
	s_call Snd_3f_6f0b
	s_call Snd_3f_6f21
	s_call Snd_3f_6f0b
	s_call Snd_3f_6f35
	s_dutyenv 3
	s_call Snd_3f_6f43
	s_call Snd_3f_6f53
	s_call Snd_3f_6f63
	s_call Snd_3f_6f53
	s_call Snd_3f_6f43
	s_call Snd_3f_6f53
	s_call Snd_3f_6f6b
	s_call Snd_3f_6f53
	s_dutyenv 4
	s_call Snd_3f_6f7b
	s_call Snd_3f_6f86
	s_call Snd_3f_6f7b
	s_call Snd_3f_6f86
	s_call Snd_3f_6f8e
	s_call Snd_3f_6f98
	s_call Snd_3f_6f8e
	s_call Snd_3f_6fa1
	s_goto Snd_3f_6ec6
Snd_3f_6f0b:
	s_instr 1
	s_deflen 8
	s_oct 5	; block 4
	s_note_l SC_D, 24	; D dur=24
	s_note SC_REST 	; rest
	s_note SC_D    	; D
	s_note_l SC_REST, 16	; rest dur=16
	s_note SC_DS   	; D#
	s_instr 2
	s_note SC_AS   	; A#
	s_note SC_FS   	; F#
	s_note SC_DS   	; D#
	s_oct 4	; block 3
	s_note SC_AS   	; A#
	s_oct 5	; block 4
	s_note SC_DS   	; D#
	s_ret
Snd_3f_6f21:
	s_deflen 8
	s_instr 1
	s_oct 5	; block 4
	s_note_l SC_D, 24	; D dur=24
	s_note SC_REST 	; rest
	s_note SC_D    	; D
	s_note_l SC_REST, 16	; rest dur=16
	s_note SC_C    	; C
	s_oct 4	; block 3
	s_note SC_DS   	; D#
	s_note SC_F    	; F
	s_note SC_FS   	; F#
	s_note SC_GS   	; G#
	s_oct 5	; block 4
	s_note SC_CS   	; C#
	s_ret
Snd_3f_6f35:
	s_deflen 8
	s_instr 1
	s_oct 5	; block 4
	s_note_l SC_D, 24	; D dur=24
	s_note SC_REST 	; rest
	s_note SC_D    	; D
	s_note_l SC_REST, 16	; rest dur=16
	s_note_l SC_C, 48	; C dur=48
	s_ret
Snd_3f_6f43:
	s_instr 2
	s_oct 5	; block 4
	s_note SC_AS   	; A#
	s_note SC_A    	; A
	s_note SC_AS   	; A#
	s_note SC_A    	; A
	s_note SC_G    	; G
	s_note SC_A    	; A
	s_note SC_G    	; G
	s_note_l SC_AS, 32	; A# dur=32
	s_keyon
	s_note SC_AS   	; A#
	s_note SC_A    	; A
	s_ret
Snd_3f_6f53:
	s_instr 1
	s_oct 4	; block 3
	s_note SC_G    	; G
	s_note SC_C    	; C
	s_note SC_D    	; D
	s_note SC_DS   	; D#
	s_note SC_F    	; F
	s_note_l SC_DS, 16	; D# dur=16
	s_note_l SC_GS, 32	; G# dur=32
	s_keyon
	s_note SC_GS   	; G#
	s_note SC_AS   	; A#
	s_ret
Snd_3f_6f63:
	s_oct 4	; block 3
	s_note_l SC_G, 48	; G dur=48
	s_oct 5	; block 4
	s_note SC_DS   	; D#
	s_note_l SC_GS, 48	; G# dur=48
	s_ret
Snd_3f_6f6b:
	s_oct 5	; block 4
	s_note SC_G    	; G
	s_note SC_C    	; C
	s_note SC_FS   	; F#
	s_note SC_C    	; C
	s_note SC_F    	; F
	s_note SC_C    	; C
	s_oct 5	; block 4
	s_note SC_DS   	; D#
	s_note SC_F    	; F
	s_note SC_C    	; C
	s_note SC_F    	; F
	s_note SC_FS   	; F#
	s_note SC_G    	; G
	s_note SC_GS   	; G#
	s_ret
Snd_3f_6f7b:
	s_instr 1
	s_oct 4	; block 3
	s_note_l SC_G, 48	; G dur=48
	s_note SC_F    	; F
	s_note_l SC_GS, 32	; G# dur=32
	s_note_l SC_AS, 16	; A# dur=16
	s_ret
Snd_3f_6f86:
	s_note_l SC_G, 48	; G dur=48
	s_note SC_FS   	; F#
	s_note_l SC_F, 32	; F dur=32
	s_note_l SC_DS, 16	; D# dur=16
	s_ret
Snd_3f_6f8e:
	s_oct 4	; block 3
	s_note_l SC_A, 48	; A dur=48
	s_note SC_G    	; G
	s_note_l SC_AS, 32	; A# dur=32
	s_oct 5	; block 4
	s_note_l SC_C, 16	; C dur=16
	s_ret
Snd_3f_6f98:
	s_oct 4	; block 3
	s_note_l SC_A, 48	; A dur=48
	s_note SC_GS   	; G#
	s_note_l SC_G, 32	; G dur=32
	s_note_l SC_F, 16	; F dur=16
	s_ret
Snd_3f_6fa1:
	s_oct 4	; block 3
	s_note_l SC_A, 48	; A dur=48
	s_note SC_GS   	; G#
	s_note_l SC_G, 16	; G dur=16
	s_note_l SC_GS, 16	; G# dur=16
	s_note_l SC_A, 16	; A dur=16
	s_ret
Snd_3f_6fac:
	s_pitchenv 1
	s_deflen 8
	s_set10 0
Snd_3f_6fb2:
	s_dutyenv 5
	s_call Snd_3f_6ff7
	s_call Snd_3f_7010
	s_call Snd_3f_6ff7
	s_call Snd_3f_7010
	s_dutyenv 4
	s_call Snd_3f_6ff7
	s_call Snd_3f_7010
	s_call Snd_3f_6ff7
	s_call Snd_3f_7010
	s_call Snd_3f_6ff7
	s_call Snd_3f_7010
	s_call Snd_3f_6ff7
	s_call Snd_3f_7010
	s_dutyenv 2
	s_call Snd_3f_7020
	s_call Snd_3f_7035
	s_call Snd_3f_7020
	s_call Snd_3f_7035
	s_call Snd_3f_704a
	s_call Snd_3f_705d
	s_call Snd_3f_704a
	s_call Snd_3f_706f
	s_goto Snd_3f_6fb2
Snd_3f_6ff7:
	s_instr 2
	s_deflen 8
	s_oct 5	; block 4
	s_note_l SC_C, 24	; C dur=24
	s_note SC_REST 	; rest
	s_note SC_C    	; C
	s_note_l SC_REST, 16	; rest dur=16
	s_note SC_CS   	; C#
	s_keyon
	s_note SC_CS   	; C#
	s_instr 3
	s_note SC_AS   	; A#
	s_note SC_FS   	; F#
	s_note SC_DS   	; D#
	s_oct 4	; block 3
	s_note SC_AS   	; A#
	s_instr 2
	s_oct 5	; block 4
	s_ret
Snd_3f_7010:
	s_note_l SC_C, 24	; C dur=24
	s_note SC_REST 	; rest
	s_note SC_C    	; C
	s_note_l SC_REST, 16	; rest dur=16
	s_oct 4	; block 3
	s_note SC_AS   	; A#
	s_keyon
	s_note SC_AS   	; A#
	s_note SC_DS   	; D#
	s_note SC_F    	; F
	s_note SC_FS   	; F#
	s_note SC_GS   	; G#
	s_oct 5	; block 4
	s_ret
Snd_3f_7020:
	s_instr 0
	s_deflen 8
	s_oct 4	; block 3
	s_note SC_C    	; C
	s_oct 5	; block 4
	s_note SC_C    	; C
	s_oct 4	; block 3
	s_note SC_C    	; C
	s_note SC_REST 	; rest
	s_note SC_C    	; C
	s_note_l SC_REST, 16	; rest dur=16
	s_note SC_CS   	; C#
	s_note SC_C    	; C
	s_note SC_DS   	; D#
	s_note SC_D    	; D
	s_note SC_CS   	; C#
	s_note SC_C    	; C
	s_ret
Snd_3f_7035:
	s_note SC_C    	; C
	s_oct 5	; block 4
	s_note SC_C    	; C
	s_oct 4	; block 3
	s_note SC_C    	; C
	s_note SC_REST 	; rest
	s_note SC_C    	; C
	s_note_l SC_REST, 16	; rest dur=16
	s_oct 4	; block 3
	s_note SC_AS   	; A#
	s_note SC_B    	; B
	s_oct 5	; block 4
	s_note SC_C    	; C
	s_oct 4	; block 3
	s_note SC_AS   	; A#
	s_oct 5	; block 4
	s_note SC_CS   	; C#
	s_oct 5	; block 4
	s_note SC_B    	; B
	s_ret
Snd_3f_704a:
	s_deflen 8
	s_oct 4	; block 3
	s_note SC_D    	; D
	s_oct 5	; block 4
	s_note SC_D    	; D
	s_oct 4	; block 3
	s_note SC_D    	; D
	s_note SC_REST 	; rest
	s_note SC_D    	; D
	s_note_l SC_REST, 16	; rest dur=16
	s_note SC_DS   	; D#
	s_note SC_D    	; D
	s_note SC_F    	; F
	s_note SC_E    	; E
	s_note SC_DS   	; D#
	s_note SC_D    	; D
	s_ret
Snd_3f_705d:
	s_note SC_D    	; D
	s_oct 5	; block 4
	s_note SC_D    	; D
	s_oct 4	; block 3
	s_note SC_D    	; D
	s_note SC_REST 	; rest
	s_note SC_D    	; D
	s_note_l SC_REST, 16	; rest dur=16
	s_oct 5	; block 4
	s_note SC_C    	; C
	s_note SC_CS   	; C#
	s_note SC_D    	; D
	s_note SC_C    	; C
	s_oct 5	; block 4
	s_note SC_DS   	; D#
	s_note SC_CS   	; C#
	s_ret
Snd_3f_706f:
	s_note SC_D    	; D
	s_oct 5	; block 4
	s_note SC_D    	; D
	s_oct 4	; block 3
	s_note SC_D    	; D
	s_note SC_REST 	; rest
	s_note SC_D    	; D
	s_note_l SC_REST, 16	; rest dur=16
	s_oct 5	; block 4
	s_note SC_C    	; C
	s_note SC_CS   	; C#
	s_note SC_D    	; D
	s_note SC_C    	; C
	s_oct 5	; block 4
	s_note SC_DS   	; D#
	s_note SC_F    	; F
	s_ret
Snd_3f_7081:
	s_pitchenv 0
	s_deflen 8
	s_set10 0
Snd_3f_7087:
	s_call Snd_3f_70c6
	s_call Snd_3f_70d7
	s_call Snd_3f_70c6
	s_call Snd_3f_70d7
	s_call Snd_3f_70c6
	s_call Snd_3f_70d7
	s_call Snd_3f_70c6
	s_call Snd_3f_70d7
	s_call Snd_3f_70c6
	s_call Snd_3f_70d7
	s_call Snd_3f_70c6
	s_call Snd_3f_70d7
	s_call Snd_3f_70c6
	s_call Snd_3f_70d7
	s_call Snd_3f_70c6
	s_call Snd_3f_70d7
	s_call Snd_3f_70e1
	s_call Snd_3f_70eb
	s_call Snd_3f_70e1
	s_call Snd_3f_70f5
	s_goto Snd_3f_7087
Snd_3f_70c6:
	s_wave 10
	s_oct 3	; block 2
	s_deflen 16
	s_instr 20
	s_note_l SC_G, 24	; G dur=24
	s_oct 4	; block 3
	s_note SC_D    	; D
	s_note SC_G    	; G
	s_note SC_GS   	; G#
	s_oct 3	; block 2
	s_note_l SC_GS, 32	; G# dur=32
	s_ret
Snd_3f_70d7:
	s_note_l SC_G, 24	; G dur=24
	s_oct 4	; block 3
	s_note SC_D    	; D
	s_note SC_G    	; G
	s_note SC_F    	; F
	s_oct 3	; block 2
	s_note_l SC_F, 32	; F dur=32
	s_ret
Snd_3f_70e1:
	s_note_l SC_A, 24	; A dur=24
	s_oct 4	; block 3
	s_note SC_D    	; D
	s_note SC_A    	; A
	s_note SC_AS   	; A#
	s_oct 3	; block 2
	s_note SC_GS   	; G#
	s_note SC_AS   	; A#
	s_ret
Snd_3f_70eb:
	s_note_l SC_A, 24	; A dur=24
	s_oct 4	; block 3
	s_note SC_E    	; E
	s_note SC_A    	; A
	s_note SC_G    	; G
	s_oct 3	; block 2
	s_note_l SC_G, 32	; G dur=32
	s_ret
Snd_3f_70f5:
	s_note_l SC_A, 24	; A dur=24
	s_oct 4	; block 3
	s_note SC_E    	; E
	s_note SC_A    	; A
	s_deflen 8
	s_note SC_G    	; G
	s_instr 19
	s_note SC_G    	; G
	s_oct 3	; block 2
	s_instr 20
	s_note_l SC_GS, 16	; G# dur=16
	s_note SC_A    	; A
	s_instr 19
	s_note SC_A    	; A
	s_ret
Snd_3f_710a:
	s_pitchenv 0
	s_oct 1	; block 0
	s_deflen 8
	s_set10 0
Snd_3f_7111:
	s_call Snd_3f_7150
	s_call Snd_3f_7164
	s_call Snd_3f_7150
	s_call Snd_3f_7164
	s_call Snd_3f_7150
	s_call Snd_3f_7164
	s_call Snd_3f_7150
	s_call Snd_3f_7164
	s_call Snd_3f_7150
	s_call Snd_3f_7164
	s_call Snd_3f_7150
	s_call Snd_3f_7164
	s_call Snd_3f_7150
	s_call Snd_3f_7164
	s_call Snd_3f_7150
	s_call Snd_3f_7164
	s_call Snd_3f_7150
	s_call Snd_3f_7164
	s_call Snd_3f_7150
	s_call Snd_3f_717c
	s_goto Snd_3f_7111
Snd_3f_7150:
	s_instr 10
	s_note SC_F    	; F
	s_note SC_C    	; C
	s_note SC_C    	; C
	s_instr 14
	s_note SC_F    	; F
	s_instr 10
	s_note SC_C    	; C
	s_note SC_F    	; F
	s_note SC_C    	; C
	s_note_l SC_F, 16	; F dur=16
	s_instr 12
	s_note_l SC_DS, 32	; D# dur=32
	s_ret
Snd_3f_7164:
	s_instr 10
	s_note SC_F    	; F
	s_note SC_C    	; C
	s_note SC_C    	; C
	s_note SC_F    	; F
	s_note SC_C    	; C
	s_instr 14
	s_note SC_F    	; F
	s_instr 10
	s_note SC_C    	; C
	s_note_l SC_F, 16	; F dur=16
	s_instr 14
	s_note_l SC_F, 16	; F dur=16
	s_instr 12
	s_note_l SC_DS, 16	; D# dur=16
	s_ret
Snd_3f_717c:
	s_instr 10
	s_note SC_F    	; F
	s_note SC_C    	; C
	s_note SC_C    	; C
	s_note SC_F    	; F
	s_note SC_C    	; C
	s_instr 14
	s_note SC_F    	; F
	s_instr 10
	s_note SC_C    	; C
	s_note SC_F    	; F
	s_note SC_C    	; C
	s_instr 14
	s_note SC_F    	; F
	s_note SC_F    	; F
	s_instr 12
	s_note_l SC_DS, 16	; D# dur=16
	s_ret
Snd_3f_7194:
	ds 3691, $ff
