; Sound id $2f (BGM) -- town
; Bank $3e, ROM $4d00-$516e. Auto-generated by tools/songdisasm.py --split; INCLUDEd by sound/bank_3e.asm into its $4b00 section.

; ===== sound id $2f =====
Snd_3e_4d00:
	s_chan $f0, Snd_3e_4d0c
	s_chan $f0, Snd_3e_4e83
	s_chan $f0, Snd_3e_4f7b
	s_chan $f0, Snd_3e_504c
Snd_3e_4d0c:
	s_pitchenv 1
	s_set10 0
Snd_3e_4d10:
	s_call Snd_3e_4d69
	s_call Snd_3e_4d69
	s_call Snd_3e_4d69
	s_call Snd_3e_4d69
	s_call Snd_3e_4d6c
	s_call Snd_3e_4d88
	s_call Snd_3e_4d91
	s_call Snd_3e_4d9c
	s_call Snd_3e_4da7
	s_call Snd_3e_4d88
	s_call Snd_3e_4db6
	s_call Snd_3e_4dc1
	s_dutyenv 2
	s_call Snd_3e_4dd7
	s_call Snd_3e_4e12
	s_call Snd_3e_4df3
	s_call Snd_3e_4e3e
	s_call Snd_3e_4dd7
	s_call Snd_3e_4e57
	s_call Snd_3e_4e68
	s_call Snd_3e_4e6f
	s_call Snd_3e_4d6c
	s_call Snd_3e_4d88
	s_call Snd_3e_4d91
	s_call Snd_3e_4d9c
	s_call Snd_3e_4da7
	s_call Snd_3e_4d88
	s_call Snd_3e_4db6
	s_call Snd_3e_4dc1
	s_goto Snd_3e_4d10
Snd_3e_4d69:
	s_note_l SC_REST, 144	; rest dur=144
	s_ret
Snd_3e_4d6c:
	s_dutyenv 5
	s_deflen 9
	s_oct 4	; block 3
	s_instr 0
	s_note_l SC_C, 36	; C dur=36
	s_note_l SC_G, 36	; G dur=36
	s_instr 2
	s_note SC_G    	; G
	s_instr 3
	s_note SC_G    	; G
	s_instr 4
	s_note SC_G    	; G
	s_instr 5
	s_note SC_G    	; G
	s_instr 0
	s_note_l SC_F, 36	; F dur=36
	s_ret
Snd_3e_4d88:
	s_deflen 36
	s_note SC_E    	; E
	s_note SC_C    	; C
	s_oct 3	; block 2
	s_note SC_AS   	; A#
	s_oct 4	; block 3
	s_note SC_D    	; D
	s_ret
Snd_3e_4d91:
	s_note_l SC_E, 72	; E dur=72
	s_keyon
	s_note_l SC_E, 18	; E dur=18
	s_instr 1
	s_note_l SC_E, 54	; E dur=54
	s_keyon
	s_ret
Snd_3e_4d9c:
	s_instr 3
	s_note SC_E    	; E
	s_instr 4
	s_note SC_E    	; E
	s_instr 5
	s_note SC_E    	; E
	s_note SC_REST 	; rest
	s_ret
Snd_3e_4da7:
	s_instr 0
	s_note SC_C    	; C
	s_note SC_G    	; G
	s_deflen 18
	s_instr 5
	s_note SC_G    	; G
	s_instr 0
	s_note_l SC_FS, 36	; F# dur=36
	s_note SC_F    	; F
	s_ret
Snd_3e_4db6:
	s_note_l SC_C, 72	; C dur=72
	s_keyon
	s_note_l SC_C, 18	; C dur=18
	s_instr 1
	s_note_l SC_C, 54	; C dur=54
	s_keyon
	s_ret
Snd_3e_4dc1:
	s_deflen 36
	s_instr 3
	s_note SC_C    	; C
	s_instr 4
	s_note SC_C    	; C
	s_instr 5
	s_note SC_C    	; C
	s_dutyenv 4
	s_deflen 9
	s_instr 0
	s_note SC_REST 	; rest
	s_note SC_AS   	; A#
	s_note SC_A    	; A
	s_note SC_AS   	; A#
	s_ret
Snd_3e_4dd7:
	s_oct 4	; block 3
	s_deflen 18
	s_instr 0
	s_note SC_C    	; C
	s_instr 2
	s_note SC_C    	; C
	s_instr 0
	s_note SC_G    	; G
	s_instr 3
	s_note SC_G    	; G
	s_instr 5
	s_note SC_G    	; G
	s_instr 0
	s_note SC_F    	; F
	s_instr 4
	s_note SC_F    	; F
	s_instr 0
	s_note SC_E    	; E
	s_ret
Snd_3e_4df3:
	s_oct 4	; block 3
	s_deflen 18
	s_instr 0
	s_note SC_C    	; C
	s_instr 2
	s_note SC_C    	; C
	s_instr 0
	s_note SC_G    	; G
	s_instr 3
	s_note SC_G    	; G
	s_instr 5
	s_note SC_G    	; G
	s_instr 0
	s_note_l SC_F, 27	; F dur=27
	s_instr 4
	s_note_l SC_F, 9	; F dur=9
	s_instr 0
	s_note SC_AS   	; A#
	s_keyon
	s_ret
Snd_3e_4e12:
	s_note SC_F    	; F
	s_instr 3
	s_note SC_F    	; F
	s_instr 5
	s_note SC_F    	; F
	s_instr 0
	s_note SC_G    	; G
	s_instr 4
	s_note SC_G    	; G
	s_instr 0
	s_note SC_C    	; C
	s_instr 3
	s_note SC_C    	; C
	s_instr 5
	s_note SC_C    	; C
	s_ret
Snd_3e_4e29:	; unused/dead pattern
	s_note SC_F    	; F
	s_instr 4
	s_note SC_F    	; F
	s_note SC_REST 	; rest
	s_oct 5	; block 4
	s_instr 0
	s_note SC_C    	; C
	s_instr 4
	s_note SC_C    	; C
	s_oct 4	; block 3
	s_instr 0
	s_note SC_AS   	; A#
	s_instr 4
	s_note SC_AS   	; A#
	s_note SC_REST 	; rest
	s_ret
Snd_3e_4e3e:
	s_oct 5	; block 4
	s_note SC_C    	; C
	s_instr 4
	s_note SC_C    	; C
	s_instr 5
	s_note SC_C    	; C
	s_oct 4	; block 3
	s_instr 0
	s_note SC_F    	; F
	s_instr 4
	s_note SC_F    	; F
	s_instr 0
	s_note SC_G    	; G
	s_instr 2
	s_note SC_G    	; G
	s_instr 5
	s_note SC_G    	; G
	s_ret
Snd_3e_4e57:
	s_note SC_F    	; F
	s_instr 4
	s_note SC_F    	; F
	s_instr 5
	s_note SC_F    	; F
	s_note_l SC_REST, 36	; rest dur=36
	s_instr 0
	s_note SC_F    	; F
	s_oct 5	; block 4
	s_note SC_C    	; C
	s_oct 4	; block 3
	s_note SC_F    	; F
	s_ret
Snd_3e_4e68:
	s_note_l SC_D, 108	; D dur=108
	s_instr 1
	s_note_l SC_D, 36	; D dur=36
	s_ret
Snd_3e_4e6f:
	s_instr 2
	s_note_l SC_D, 36	; D dur=36
	s_instr 3
	s_note SC_D    	; D
	s_instr 4
	s_note SC_D    	; D
	s_instr 5
	s_note SC_D    	; D
	s_oct 3	; block 2
	s_instr 1
	s_note SC_A    	; A
	s_note SC_AS   	; A#
	s_note SC_B    	; B
	s_ret
Snd_3e_4e83:
	s_pitchenv 1
	s_set10 0
	s_dutyenv 5
Snd_3e_4e89:
	s_call Snd_3e_4ee0
	s_call Snd_3e_4ee0
	s_call Snd_3e_4ee0
	s_call Snd_3e_4ee0
	s_call Snd_3e_4ee0
	s_call Snd_3e_4ee0
	s_call Snd_3e_4ef8
	s_call Snd_3e_4f49
	s_call Snd_3e_4ee0
	s_call Snd_3e_4ee0
	s_call Snd_3e_4f14
	s_call Snd_3e_4f34
	s_call Snd_3e_4ee0
	s_call Snd_3e_4ee0
	s_call Snd_3e_4ee0
	s_call Snd_3e_4ee0
	s_call Snd_3e_4ee0
	s_call Snd_3e_4ee0
	s_call Snd_3e_4f5c
	s_call Snd_3e_4f68
	s_call Snd_3e_4ee0
	s_call Snd_3e_4ee0
	s_call Snd_3e_4ef8
	s_call Snd_3e_4f49
	s_call Snd_3e_4ee0
	s_call Snd_3e_4ee0
	s_call Snd_3e_4f14
	s_call Snd_3e_4f34
	s_goto Snd_3e_4e89
Snd_3e_4ee0:
	s_dutyenv 5
	s_deflen 9
	s_oct 3	; block 2
	s_instr 0
	s_note SC_G    	; G
	s_instr 2
	s_note SC_G    	; G
	s_instr 0
	s_note SC_G    	; G
	s_note SC_REST 	; rest
	s_note_l SC_REST, 72	; rest dur=72
	s_note_l SC_REST, 18	; rest dur=18
	s_instr 0
	s_note_l SC_F, 18	; F dur=18
	s_ret
Snd_3e_4ef8:
	s_deflen 9
	s_oct 3	; block 2
	s_instr 0
	s_note SC_G    	; G
	s_instr 2
	s_note SC_G    	; G
	s_instr 0
	s_note SC_G    	; G
	s_note SC_REST 	; rest
	s_dutyenv 2
	s_instr 1
	s_oct 4	; block 3
	s_note_l SC_C, 72	; C dur=72
	s_oct 3	; block 2
	s_instr 1
	s_note SC_AS   	; A#
	s_note SC_A    	; A
	s_note SC_AS   	; A#
	s_note SC_B    	; B
	s_ret
Snd_3e_4f14:
	s_dutyenv 5
	s_deflen 9
	s_oct 3	; block 2
	s_instr 0
	s_note SC_G    	; G
	s_instr 2
	s_note SC_G    	; G
	s_instr 0
	s_note SC_REST 	; rest
	s_note SC_REST 	; rest
	s_dutyenv 2
	s_instr 1
	s_note_l SC_G, 36	; G dur=36
	s_deflen 18
	s_instr 3
	s_note SC_G    	; G
	s_instr 1
	s_note SC_A    	; A
	s_note SC_AS   	; A#
	s_note SC_A    	; A
	s_ret
Snd_3e_4f34:
	s_deflen 18
	s_instr 1
	s_note SC_AS   	; A#
	s_instr 3
	s_note SC_AS   	; A#
	s_instr 1
	s_note SC_A    	; A
	s_note_l SC_F, 36	; F dur=36
	s_note SC_G    	; G
	s_instr 3
	s_note SC_G    	; G
	s_instr 1
	s_note SC_F    	; F
	s_ret
Snd_3e_4f49:
	s_deflen 18
	s_oct 4	; block 3
	s_instr 1
	s_note SC_C    	; C
	s_oct 3	; block 2
	s_note SC_C    	; C
	s_instr 2
	s_note SC_C    	; C
	s_instr 1
	s_note_l SC_E, 36	; E dur=36
	s_note_l SC_F, 36	; F dur=36
	s_note SC_G    	; G
	s_ret
Snd_3e_4f5c:
	s_dutyenv 2
	s_oct 4	; block 3
	s_instr 1
	s_note_l SC_G, 108	; G dur=108
	s_note SC_F    	; F
	s_note SC_E    	; E
	s_note SC_F    	; F
	s_note SC_FS   	; F#
	s_ret
Snd_3e_4f68:
	s_deflen 18
	s_note SC_G    	; G
	s_oct 3	; block 2
	s_note SC_G    	; G
	s_instr 2
	s_note SC_G    	; G
	s_instr 0
	s_note_l SC_AS, 36	; A# dur=36
	s_oct 3	; block 2
	s_instr 0
	s_note SC_F    	; F
	s_note SC_FS   	; F#
	s_note SC_G    	; G
	s_ret
Snd_3e_4f7b:
	s_pitchenv 0
	s_wave 2
	s_set10 0
Snd_3e_4f81:
	s_call Snd_3e_4fd8
	s_call Snd_3e_4ff3
	s_call Snd_3e_4fd8
	s_call Snd_3e_4ff3
	s_call Snd_3e_4fd8
	s_call Snd_3e_4ff3
	s_call Snd_3e_4fd8
	s_call Snd_3e_4ff3
	s_call Snd_3e_4fd8
	s_call Snd_3e_4ff3
	s_call Snd_3e_4fd8
	s_call Snd_3e_4ff3
	s_call Snd_3e_4fd8
	s_call Snd_3e_4ff3
	s_call Snd_3e_4fd8
	s_call Snd_3e_4ff3
	s_call Snd_3e_4fd8
	s_call Snd_3e_4ff3
	s_call Snd_3e_5016
	s_call Snd_3e_5031
	s_call Snd_3e_4fd8
	s_call Snd_3e_4ff3
	s_call Snd_3e_4fd8
	s_call Snd_3e_4ff3
	s_call Snd_3e_4fd8
	s_call Snd_3e_4ff3
	s_call Snd_3e_4fd8
	s_call Snd_3e_4ff3
	s_goto Snd_3e_4f81
Snd_3e_4fd8:
	s_deflen 9
	s_oct 4	; block 3
	s_instr 20
	s_note SC_C    	; C
	s_instr 19
	s_note SC_C    	; C
	s_instr 20
	s_note SC_C    	; C
	s_note SC_REST 	; rest
	s_note_l SC_REST, 18	; rest dur=18
	s_oct 3	; block 2
	s_note SC_AS   	; A#
	s_note SC_REST 	; rest
	s_note_l SC_REST, 18	; rest dur=18
	s_note SC_A    	; A
	s_note SC_REST 	; rest
	s_note_l SC_REST, 18	; rest dur=18
	s_note_l SC_AS, 18	; A# dur=18
	s_ret
Snd_3e_4ff3:
	s_deflen 9
	s_oct 4	; block 3
	s_instr 20
	s_note SC_C    	; C
	s_instr 19
	s_note SC_C    	; C
	s_instr 20
	s_note SC_C    	; C
	s_note SC_REST 	; rest
	s_note_l SC_REST, 18	; rest dur=18
	s_oct 3	; block 2
	s_note SC_AS   	; A#
	s_instr 19
	s_note SC_AS   	; A#
	s_note_l SC_REST, 18	; rest dur=18
	s_instr 20
	s_note SC_A    	; A
	s_instr 19
	s_note SC_A    	; A
	s_note_l SC_REST, 18	; rest dur=18
	s_instr 20
	s_note_l SC_AS, 18	; A# dur=18
	s_ret
Snd_3e_5016:
	s_deflen 9
	s_oct 3	; block 2
	s_instr 20
	s_note SC_G    	; G
	s_instr 19
	s_note SC_G    	; G
	s_instr 20
	s_note SC_G    	; G
	s_note SC_REST 	; rest
	s_note_l SC_REST, 18	; rest dur=18
	s_oct 3	; block 2
	s_note SC_F    	; F
	s_note SC_REST 	; rest
	s_note_l SC_REST, 18	; rest dur=18
	s_note SC_E    	; E
	s_note SC_REST 	; rest
	s_note_l SC_REST, 18	; rest dur=18
	s_note_l SC_F, 18	; F dur=18
	s_ret
Snd_3e_5031:
	s_deflen 9
	s_oct 3	; block 2
	s_instr 20
	s_note SC_G    	; G
	s_instr 19
	s_note SC_G    	; G
	s_instr 20
	s_note SC_G    	; G
	s_note SC_REST 	; rest
	s_note_l SC_REST, 18	; rest dur=18
	s_oct 3	; block 2
	s_note SC_F    	; F
	s_note SC_REST 	; rest
	s_note_l SC_REST, 18	; rest dur=18
	s_note SC_D    	; D
	s_note SC_REST 	; rest
	s_note_l SC_REST, 18	; rest dur=18
	s_note_l SC_G, 18	; G dur=18
	s_ret
Snd_3e_504c:
	s_pitchenv 0
	s_deflen 18
	s_oct 1	; block 0
	s_set10 0
Snd_3e_5053:
	s_call Snd_3e_50b5
	s_call Snd_3e_50b5
	s_call Snd_3e_50b5
	s_call Snd_3e_50cd
	s_call Snd_3e_50e7
	s_call Snd_3e_50e7
	s_call Snd_3e_50e7
	s_call Snd_3e_50cd
	s_call Snd_3e_50e7
	s_call Snd_3e_50e7
	s_call Snd_3e_50e7
	s_call Snd_3e_50cd
	s_call Snd_3e_511f
	s_call Snd_3e_511f
	s_call Snd_3e_511f
	s_call Snd_3e_513b
	s_call Snd_3e_511f
	s_call Snd_3e_511f
	s_call Snd_3e_511f
	s_call Snd_3e_5155
	s_call Snd_3e_5103
	s_call Snd_3e_511f
	s_call Snd_3e_5103
	s_call Snd_3e_5155
	s_call Snd_3e_5103
	s_call Snd_3e_511f
	s_call Snd_3e_5103
	s_call Snd_3e_513b
	s_goto Snd_3e_5053
Snd_3e_50aa:	; unused/dead pattern
	s_deflen 18
	s_instr 10
	s_note SC_F    	; F
	s_note SC_F    	; F
	s_note_l SC_REST, 72	; rest dur=72
	s_note SC_REST 	; rest
	s_note SC_F    	; F
	s_ret
Snd_3e_50b5:
	s_deflen 18
	s_instr 10
	s_note SC_F    	; F
	s_note SC_F    	; F
	s_instr 12
	s_note SC_D    	; D
	s_deflen 9
	s_instr 10
	s_note SC_C    	; C
	s_note_l SC_F, 18	; F dur=18
	s_note SC_C    	; C
	s_note_l SC_F, 18	; F dur=18
	s_instr 14
	s_note_l SC_F, 36	; F dur=36
	s_ret
Snd_3e_50cd:
	s_deflen 18
	s_instr 10
	s_note SC_F    	; F
	s_note SC_F    	; F
	s_instr 12
	s_note SC_D    	; D
	s_deflen 9
	s_instr 10
	s_note SC_C    	; C
	s_note_l SC_F, 18	; F dur=18
	s_note SC_C    	; C
	s_note_l SC_F, 18	; F dur=18
	s_instr 14
	s_note_l SC_F, 18	; F dur=18
	s_note SC_F    	; F
	s_note SC_F    	; F
	s_ret
Snd_3e_50e7:
	s_deflen 18
	s_instr 10
	s_note SC_F    	; F
	s_note SC_F    	; F
	s_instr 12
	s_note SC_D    	; D
	s_deflen 9
	s_instr 10
	s_note SC_C    	; C
	s_note_l SC_F, 18	; F dur=18
	s_note SC_C    	; C
	s_note_l SC_F, 18	; F dur=18
	s_instr 14
	s_note_l SC_F, 18	; F dur=18
	s_instr 10
	s_note_l SC_F, 18	; F dur=18
	s_ret
Snd_3e_5103:
	s_deflen 18
	s_instr 10
	s_note SC_F    	; F
	s_note SC_F    	; F
	s_instr 14
	s_note SC_F    	; F
	s_deflen 9
	s_instr 10
	s_note SC_C    	; C
	s_note_l SC_F, 18	; F dur=18
	s_note SC_C    	; C
	s_note SC_F    	; F
	s_note SC_C    	; C
	s_instr 14
	s_note_l SC_F, 18	; F dur=18
	s_instr 10
	s_note SC_F    	; F
	s_note SC_C    	; C
	s_ret
Snd_3e_511f:
	s_deflen 18
	s_instr 10
	s_note SC_F    	; F
	s_note SC_F    	; F
	s_instr 14
	s_note SC_F    	; F
	s_deflen 9
	s_instr 10
	s_note SC_C    	; C
	s_note_l SC_F, 18	; F dur=18
	s_note SC_C    	; C
	s_note_l SC_F, 18	; F dur=18
	s_instr 14
	s_note_l SC_F, 18	; F dur=18
	s_instr 10
	s_note_l SC_F, 18	; F dur=18
	s_ret
Snd_3e_513b:
	s_deflen 18
	s_instr 10
	s_note SC_F    	; F
	s_note SC_F    	; F
	s_instr 14
	s_note SC_F    	; F
	s_deflen 9
	s_instr 10
	s_note SC_C    	; C
	s_note_l SC_F, 18	; F dur=18
	s_note SC_C    	; C
	s_note_l SC_F, 18	; F dur=18
	s_instr 14
	s_note_l SC_F, 18	; F dur=18
	s_note_l SC_F, 18	; F dur=18
	s_ret
Snd_3e_5155:
	s_deflen 18
	s_instr 10
	s_note SC_F    	; F
	s_note SC_F    	; F
	s_instr 14
	s_note SC_F    	; F
	s_deflen 9
	s_instr 10
	s_note SC_C    	; C
	s_note_l SC_F, 18	; F dur=18
	s_note SC_C    	; C
	s_note SC_F    	; F
	s_note SC_C    	; C
	s_instr 14
	s_note_l SC_F, 18	; F dur=18
	s_note SC_F    	; F
	s_note SC_F    	; F
	s_ret
