; Sound id $38 (BGM) -- ?
; Bank $3e, ROM $664d-$6b84. Auto-generated by tools/songdisasm.py --split; INCLUDEd by sound/bank_3e.asm into its $4b00 section.

; ===== sound id $38 =====
Snd_3e_664d:
	s_chan $f0, Snd_3e_6659
	s_chan $f0, Snd_3e_67da
	s_chan $f0, Snd_3e_69bf
	s_chan $f0, Snd_3e_6b67
Snd_3e_6659:
	s_pitchenv 0
	s_instr 1
	s_deflen 20
	s_oct 4	; block 3
	s_set10 0
	s_dutyenv 2
	s_call Snd_3e_669e
	s_call Snd_3e_66b4
	s_call Snd_3e_66b9
	s_call Snd_3e_66ce
	s_call Snd_3e_66d7
	s_call Snd_3e_66e6
	s_call Snd_3e_66fb
	s_call Snd_3e_6714
	s_call Snd_3e_6727
	s_call Snd_3e_674c
	s_call Snd_3e_675b
	s_call Snd_3e_6763
	s_call Snd_3e_676d
	s_call Snd_3e_677a
	s_call Snd_3e_6791
	s_call Snd_3e_679c
	s_call Snd_3e_677a
	s_call Snd_3e_67ac
	s_call Snd_3e_67c0
	s_end
Snd_3e_669e:
	s_deflen 10
	s_oct 4	; block 3
	s_instr 1
	s_note_l SC_G, 30	; G dur=30
	s_note SC_A    	; A
	s_deflen 20
	s_note SC_G    	; G
	s_oct 5	; block 4
	s_note SC_C    	; C
	s_oct 4	; block 3
	s_note SC_AS   	; A#
	s_note_l SC_C, 10	; C dur=10
	s_note_l SC_A, 10	; A dur=10
	s_note SC_G    	; G
	s_note SC_F    	; F
	s_ret
Snd_3e_66b4:
	s_note SC_E    	; E
	s_note_l SC_G, 120	; G dur=120
	s_note SC_REST 	; rest
	s_ret
Snd_3e_66b9:
	s_deflen 10
	s_oct 4	; block 3
	s_instr 1
	s_note_l SC_G, 30	; G dur=30
	s_note SC_A    	; A
	s_note SC_G    	; G
	s_note SC_REST 	; rest
	s_oct 5	; block 4
	s_note SC_C    	; C
	s_note SC_REST 	; rest
	s_oct 4	; block 3
	s_deflen 20
	s_note SC_AS   	; A#
	s_note SC_A    	; A
	s_note SC_G    	; G
	s_note SC_D    	; D
	s_ret
Snd_3e_66ce:
	s_note_l SC_F, 30	; F dur=30
	s_note_l SC_G, 10	; G dur=10
	s_note_l SC_GS, 80	; G# dur=80
	s_note SC_AS   	; A#
	s_note SC_GS   	; G#
	s_ret
Snd_3e_66d7:
	s_note_l SC_G, 40	; G dur=40
	s_oct 5	; block 4
	s_note_l SC_C, 40	; C dur=40
	s_note_l SC_REST, 20	; rest dur=20
	s_oct 4	; block 3
	s_note_l SC_DS, 20	; D# dur=20
	s_note_l SC_F, 20	; F dur=20
	s_note_l SC_DS, 20	; D# dur=20
	s_ret
Snd_3e_66e6:
	s_deflen 10
	s_oct 4	; block 3
	s_instr 0
	s_note SC_G    	; G
	s_note SC_REST 	; rest
	s_instr 2
	s_note SC_GS   	; G#
	s_note SC_REST 	; rest
	s_note SC_A    	; A
	s_note SC_REST 	; rest
	s_note SC_AS   	; A#
	s_note SC_REST 	; rest
	s_note SC_B    	; B
	s_note SC_REST 	; rest
	s_oct 5	; block 4
	s_note SC_C    	; C
	s_note SC_REST 	; rest
	s_ret
Snd_3e_66fb:
	s_oct 4	; block 3
	s_instr 1
	s_note SC_G    	; G
	s_note SC_REST 	; rest
	s_note SC_GS   	; G#
	s_note SC_REST 	; rest
	s_note SC_A    	; A
	s_note SC_REST 	; rest
	s_note SC_AS   	; A#
	s_note SC_REST 	; rest
	s_instr 0
	s_note_l SC_B, 20	; B dur=20
	s_oct 5	; block 4
	s_instr 1
	s_note SC_C    	; C
	s_note SC_CS   	; C#
	s_note SC_D    	; D
	s_note SC_DS   	; D#
	s_note SC_E    	; E
	s_note SC_REST 	; rest
	s_ret
Snd_3e_6714:
	s_instr 2
	s_note_l SC_CS, 20	; C# dur=20
	s_note_l SC_REST, 20	; rest dur=20
	s_instr 1
	s_oct 5	; block 4
	s_note_l SC_E, 60	; E dur=60
	s_note SC_D    	; D
	s_note SC_CS   	; C#
	s_oct 4	; block 3
	s_note_l SC_A, 40	; A dur=40
	s_note_l SC_B, 40	; B dur=40
	s_ret
Snd_3e_6727:
	s_oct 5	; block 4
	s_note_l SC_CS, 30	; C# dur=30
	s_oct 4	; block 3
	s_note_l SC_B, 5	; B dur=5
	s_note_l SC_A, 5	; A dur=5
	s_note_l SC_G, 20	; G dur=20
	s_oct 5	; block 4
	s_note_l SC_D, 20	; D dur=20
	s_note_l SC_E, 20	; E dur=20
	s_note SC_D    	; D
	s_note SC_CS   	; C#
	s_oct 4	; block 3
	s_note SC_A    	; A
	s_note SC_REST 	; rest
	s_note_l SC_A, 20	; A dur=20
	s_instr 0
	s_note_l SC_E, 20	; E dur=20
	s_note SC_D    	; D
	s_note SC_CS   	; C#
	s_oct 4	; block 3
	s_note SC_A    	; A
	s_note SC_REST 	; rest
	s_note_l SC_G, 40	; G dur=40
	s_oct 3	; block 2
	s_note_l SC_G, 20	; G dur=20
	s_ret
Snd_3e_674c:
	s_instr 0
	s_oct 4	; block 3
	s_deflen 10
	s_note_l SC_E, 60	; E dur=60
	s_note SC_REST 	; rest
	s_note SC_E    	; E
	s_note_l SC_G, 30	; G dur=30
	s_note SC_REST 	; rest
	s_note_l SC_G, 40	; G dur=40
	s_ret
Snd_3e_675b:
	s_note_l SC_FS, 30	; F# dur=30
	s_note SC_D    	; D
	s_note_l SC_E, 80	; E dur=80
	s_note_l SC_G, 40	; G dur=40
	s_ret
Snd_3e_6763:
	s_note_l SC_E, 60	; E dur=60
	s_note SC_REST 	; rest
	s_note SC_E    	; E
	s_note_l SC_A, 40	; A dur=40
	s_oct 5	; block 4
	s_note_l SC_D, 40	; D dur=40
	s_ret
Snd_3e_676d:
	s_note_l SC_CS, 30	; C# dur=30
	s_oct 4	; block 3
	s_note SC_A    	; A
	s_oct 5	; block 4
	s_note_l SC_E, 30	; E dur=30
	s_note SC_REST 	; rest
	s_note_l SC_F, 40	; F dur=40
	s_note_l SC_G, 80	; G dur=80
	s_ret
Snd_3e_677a:
	s_deflen 10
	s_oct 4	; block 3
	s_instr 1
	s_note SC_A    	; A
	s_note_l SC_REST, 30	; rest dur=30
	s_oct 5	; block 4
	s_note_l SC_A, 20	; A dur=20
	s_note SC_G    	; G
	s_note SC_A    	; A
	s_note_l SC_E, 20	; E dur=20
	s_note SC_D    	; D
	s_note SC_C    	; C
	s_note_l SC_D, 20	; D dur=20
	s_oct 4	; block 3
	s_note_l SC_B, 20	; B dur=20
	s_ret
Snd_3e_6791:
	s_oct 5	; block 4
	s_note SC_C    	; C
	s_oct 4	; block 3
	s_note SC_B    	; B
	s_note SC_A    	; A
	s_note SC_B    	; B
	s_note_l SC_G, 40	; G dur=40
	s_note_l SC_A, 40	; A dur=40
	s_ret
Snd_3e_679c:
	s_oct 5	; block 4
	s_note SC_C    	; C
	s_oct 4	; block 3
	s_note SC_B    	; B
	s_oct 5	; block 4
	s_note SC_D    	; D
	s_oct 4	; block 3
	s_note SC_B    	; B
	s_note_l SC_G, 40	; G dur=40
	s_note SC_A    	; A
	s_note SC_B    	; B
	s_oct 5	; block 4
	s_note SC_C    	; C
	s_note SC_D    	; D
	s_ret
Snd_3e_67ac:
	s_oct 5	; block 4
	s_note_l SC_C, 20	; C dur=20
	s_instr 5
	s_note SC_C    	; C
	s_instr 1
	s_note SC_C    	; C
	s_note_l SC_G, 40	; G dur=40
	s_instr 3
	s_note_l SC_G, 20	; G dur=20
	s_instr 5
	s_note_l SC_G, 20	; G dur=20
	s_ret
Snd_3e_67c0:
	s_oct 6	; block 5
	s_instr 1
	s_note_l SC_C, 20	; C dur=20
	s_instr 5
	s_note SC_C    	; C
	s_instr 1
	s_note SC_C    	; C
	s_note_l SC_G, 40	; G dur=40
	s_instr 2
	s_note SC_G    	; G
	s_instr 3
	s_note SC_G    	; G
	s_instr 4
	s_note SC_G    	; G
	s_instr 5
	s_note SC_G    	; G
	s_ret
Snd_3e_67da:
	s_pitchenv 0
	s_set10 0
	s_dutyenv 2
	s_call Snd_3e_681e
	s_call Snd_3e_682e
	s_call Snd_3e_683c
	s_call Snd_3e_6849
	s_call Snd_3e_6857
	s_call Snd_3e_6882
	s_call Snd_3e_6892
	s_call Snd_3e_68a7
	s_call Snd_3e_68bb
	s_dutyenv 5
	s_call Snd_3e_68da
	s_call Snd_3e_68f8
	s_call Snd_3e_6919
	s_call Snd_3e_6932
	s_dutyenv 2
	s_call Snd_3e_6947
	s_call Snd_3e_695e
	s_call Snd_3e_6968
	s_call Snd_3e_6972
	s_call Snd_3e_6989
	s_call Snd_3e_699d
	s_end
Snd_3e_681e:
	s_oct 4	; block 3
	s_instr 2
	s_deflen 20
	s_note_l SC_E, 30	; E dur=30
	s_note_l SC_F, 10	; F dur=10
	s_note SC_E    	; E
	s_note SC_G    	; G
	s_note_l SC_F, 40	; F dur=40
	s_note_l SC_D, 40	; D dur=40
	s_ret
Snd_3e_682e:
	s_note_l SC_C, 30	; C dur=30
	s_note_l SC_F, 10	; F dur=10
	s_note SC_E    	; E
	s_oct 5	; block 4
	s_note SC_C    	; C
	s_note SC_REST 	; rest
	s_note SC_C    	; C
	s_oct 4	; block 3
	s_note SC_B    	; B
	s_oct 4	; block 3
	s_note SC_E    	; E
	s_ret
Snd_3e_683c:
	s_oct 4	; block 3
	s_note_l SC_D, 30	; D dur=30
	s_note_l SC_E, 10	; E dur=10
	s_note SC_D    	; D
	s_note_l SC_F, 40	; F dur=40
	s_note SC_D    	; D
	s_note SC_C    	; C
	s_oct 3	; block 2
	s_note SC_A    	; A
	s_ret
Snd_3e_6849:
	s_oct 4	; block 3
	s_note_l SC_D, 30	; D dur=30
	s_note_l SC_E, 10	; E dur=10
	s_note SC_D    	; D
	s_note_l SC_F, 40	; F dur=40
	s_note SC_DS   	; D#
	s_note SC_G    	; G
	s_note SC_F    	; F
	s_deflen 10
	s_ret
Snd_3e_6857:
	s_oct 5	; block 4
	s_instr 4
	s_note SC_E    	; E
	s_instr 5
	s_note SC_E    	; E
	s_instr 4
	s_note SC_F    	; F
	s_instr 5
	s_note SC_F    	; F
	s_instr 4
	s_note SC_G    	; G
	s_instr 5
	s_note SC_G    	; G
	s_instr 4
	s_note SC_A    	; A
	s_instr 5
	s_note SC_A    	; A
	s_instr 4
	s_note SC_E    	; E
	s_instr 5
	s_note SC_E    	; E
	s_instr 4
	s_note_l SC_C, 20	; C dur=20
	s_note SC_REST 	; rest
	s_instr 3
	s_note SC_C    	; C
	s_oct 4	; block 3
	s_note SC_AS   	; A#
	s_note SC_FS   	; F#
	s_ret
Snd_3e_6882:
	s_oct 4	; block 3
	s_instr 3
	s_note SC_D    	; D
	s_note SC_REST 	; rest
	s_note SC_DS   	; D#
	s_note SC_REST 	; rest
	s_note SC_E    	; E
	s_note SC_REST 	; rest
	s_note SC_F    	; F
	s_note SC_REST 	; rest
	s_note SC_FS   	; F#
	s_note SC_REST 	; rest
	s_note SC_G    	; G
	s_note SC_REST 	; rest
	s_ret
Snd_3e_6892:
	s_instr 2
	s_note SC_F    	; F
	s_note SC_REST 	; rest
	s_note SC_F    	; F
	s_note SC_REST 	; rest
	s_note SC_FS   	; F#
	s_note SC_REST 	; rest
	s_note SC_G    	; G
	s_note SC_REST 	; rest
	s_instr 1
	s_note_l SC_GS, 20	; G# dur=20
	s_note SC_A    	; A
	s_note SC_AS   	; A#
	s_note SC_B    	; B
	s_note SC_AS   	; A#
	s_note SC_A    	; A
	s_note SC_REST 	; rest
	s_ret
Snd_3e_68a7:
	s_oct 3	; block 2
	s_note_l SC_AS, 20	; A# dur=20
	s_note_l SC_REST, 20	; rest dur=20
	s_oct 4	; block 3
	s_instr 0
	s_note_l SC_A, 60	; A dur=60
	s_note SC_AS   	; A#
	s_note SC_A    	; A
	s_note_l SC_F, 30	; F dur=30
	s_note SC_DS   	; D#
	s_note SC_D    	; D
	s_note SC_F    	; F
	s_note_l SC_G, 20	; G dur=20
	s_ret
Snd_3e_68bb:
	s_instr 1
	s_note_l SC_A, 30	; A dur=30
	s_note SC_E    	; E
	s_note_l SC_D, 30	; D dur=30
	s_note SC_G    	; G
	s_note_l SC_A, 30	; A dur=30
	s_note SC_E    	; E
	s_note SC_C    	; C
	s_note SC_E    	; E
	s_note SC_F    	; F
	s_note SC_G    	; G
	s_instr 2
	s_note_l SC_A, 20	; A dur=20
	s_note SC_A    	; A
	s_note SC_E    	; E
	s_instr 1
	s_note SC_F    	; F
	s_note SC_REST 	; rest
	s_note_l SC_D, 40	; D dur=40
	s_oct 4	; block 3
	s_note SC_E    	; E
	s_note SC_F    	; F
	s_ret
Snd_3e_68da:
	s_instr 1
	s_oct 4	; block 3
	s_note_l SC_CS, 26	; C# dur=26
	s_oct 3	; block 2
	s_note_l SC_A, 14	; A dur=14
	s_oct 4	; block 3
	s_deflen 10
	s_note_l SC_CS, 30	; C# dur=30
	s_note SC_D    	; D
	s_oct 3	; block 2
	s_deflen 13
	s_note SC_B    	; B
	s_oct 4	; block 3
	s_note SC_D    	; D
	s_oct 3	; block 2
	s_note_l SC_D, 14	; D dur=14
	s_deflen 10
	s_note_l SC_B, 30	; B dur=30
	s_oct 4	; block 3
	s_note SC_C    	; C
	s_ret
Snd_3e_68f8:
	s_oct 4	; block 3
	s_deflen 10
	s_note_l SC_D, 30	; D dur=30
	s_oct 3	; block 2
	s_note SC_A    	; A
	s_deflen 13
	s_oct 4	; block 3
	s_note SC_CS   	; C#
	s_oct 3	; block 2
	s_note SC_A    	; A
	s_oct 3	; block 2
	s_note_l SC_B, 14	; B dur=14
	s_deflen 13
	s_note SC_B    	; B
	s_oct 4	; block 3
	s_note SC_C    	; C
	s_oct 4	; block 3
	s_note_l SC_D, 14	; D dur=14
	s_deflen 13
	s_keyon
	s_note SC_D    	; D
	s_note SC_C    	; C
	s_oct 3	; block 2
	s_note_l SC_B, 14	; B dur=14
	s_ret
Snd_3e_6919:
	s_oct 4	; block 3
	s_deflen 13
	s_note SC_CS   	; C#
	s_oct 3	; block 2
	s_note SC_E    	; E
	s_note_l SC_A, 14	; A dur=14
	s_deflen 10
	s_oct 4	; block 3
	s_note_l SC_CS, 20	; C# dur=20
	s_note SC_E    	; E
	s_note SC_D    	; D
	s_note_l SC_E, 30	; E dur=30
	s_note SC_F    	; F
	s_deflen 13
	s_note SC_E    	; E
	s_note SC_F    	; F
	s_note_l SC_G, 14	; G dur=14
	s_ret
Snd_3e_6932:
	s_deflen 10
	s_note_l SC_A, 30	; A dur=30
	s_note SC_F    	; F
	s_note_l SC_A, 30	; A dur=30
	s_note SC_CS   	; C#
	s_deflen 13
	s_note SC_D    	; D
	s_note SC_CS   	; C#
	s_note_l SC_E, 14	; E dur=14
	s_deflen 10
	s_note_l SC_D, 70	; D dur=70
	s_oct 3	; block 2
	s_note SC_B    	; B
	s_ret
Snd_3e_6947:
	s_deflen 10
	s_oct 3	; block 2
	s_instr 1
	s_note_l SC_E, 20	; E dur=20
	s_note_l SC_G, 20	; G dur=20
	s_oct 4	; block 3
	s_note_l SC_E, 30	; E dur=30
	s_note SC_D    	; D
	s_note_l SC_C, 20	; C dur=20
	s_oct 3	; block 2
	s_note SC_B    	; B
	s_note SC_A    	; A
	s_note_l SC_B, 20	; B dur=20
	s_note SC_G    	; G
	s_note SC_A    	; A
	s_ret
Snd_3e_695e:
	s_deflen 20
	s_oct 4	; block 3
	s_note_l SC_E, 40	; E dur=40
	s_note_l SC_D, 40	; D dur=40
	s_note_l SC_C, 40	; C dur=40
	s_ret
Snd_3e_6968:
	s_deflen 20
	s_oct 4	; block 3
	s_note_l SC_E, 40	; E dur=40
	s_note_l SC_D, 40	; D dur=40
	s_note_l SC_E, 40	; E dur=40
	s_ret
Snd_3e_6972:
	s_deflen 10
	s_oct 3	; block 2
	s_instr 1
	s_note_l SC_E, 20	; E dur=20
	s_note_l SC_G, 20	; G dur=20
	s_oct 4	; block 3
	s_note_l SC_E, 30	; E dur=30
	s_note SC_D    	; D
	s_note_l SC_C, 20	; C dur=20
	s_oct 3	; block 2
	s_note SC_B    	; B
	s_note SC_A    	; A
	s_note_l SC_B, 20	; B dur=20
	s_note SC_G    	; G
	s_note SC_FS   	; F#
	s_ret
Snd_3e_6989:
	s_note_l SC_A, 20	; A dur=20
	s_instr 5
	s_note SC_A    	; A
	s_instr 1
	s_note SC_A    	; A
	s_oct 4	; block 3
	s_note_l SC_E, 40	; E dur=40
	s_instr 3
	s_note_l SC_E, 20	; E dur=20
	s_instr 4
	s_note SC_F    	; F
	s_note SC_G    	; G
	s_ret
Snd_3e_699d:
	s_oct 5	; block 4
	s_instr 1
	s_note_l SC_A, 20	; A dur=20
	s_instr 5
	s_note SC_A    	; A
	s_instr 1
	s_note SC_A    	; A
	s_note SC_A    	; A
	s_instr 3
	s_note SC_A    	; A
	s_oct 6	; block 5
	s_note SC_E    	; E
	s_instr 5
	s_note SC_E    	; E
	s_instr 4
	s_note SC_G    	; G
	s_instr 5
	s_note SC_B    	; B
	s_oct 7	; block 6
	s_instr 4
	s_note SC_D    	; D
	s_instr 5
	s_note SC_E    	; E
	s_ret
Snd_3e_69bf:
	s_pitchenv 0
	s_wave 2
	s_oct 4	; block 3
	s_deflen 20
	s_instr 20
	s_set10 0
	s_call Snd_3e_6a04
	s_call Snd_3e_6a1d
	s_call Snd_3e_6a29
	s_call Snd_3e_6a41
	s_call Snd_3e_6a5d
	s_call Snd_3e_6a7a
	s_call Snd_3e_6a83
	s_call Snd_3e_6a90
	s_call Snd_3e_6a9f
	s_call Snd_3e_6acd
	s_call Snd_3e_6ae9
	s_call Snd_3e_6acd
	s_call Snd_3e_6b02
	s_call Snd_3e_6b1c
	s_call Snd_3e_6b38
	s_call Snd_3e_6b38
	s_call Snd_3e_6b1c
	s_call Snd_3e_6b4d
	s_call Snd_3e_6b57
	s_end
Snd_3e_6a04:
	s_wave 2
	s_deflen 20
	s_oct 4	; block 3
	s_instr 20
	s_note SC_C    	; C
	s_instr 19
	s_note SC_C    	; C
	s_instr 20
	s_note SC_C    	; C
	s_instr 19
	s_note SC_C    	; C
	s_instr 20
	s_note_l SC_G, 40	; G dur=40
	s_oct 3	; block 2
	s_note_l SC_AS, 40	; A# dur=40
	s_ret
Snd_3e_6a1d:
	s_deflen 40
	s_oct 4	; block 3
	s_instr 20
	s_note SC_C    	; C
	s_note SC_G    	; G
	s_oct 5	; block 4
	s_note SC_C    	; C
	s_oct 4	; block 3
	s_note SC_G    	; G
	s_ret
Snd_3e_6a29:
	s_deflen 20
	s_oct 3	; block 2
	s_instr 20
	s_note SC_AS   	; A#
	s_instr 19
	s_note SC_AS   	; A#
	s_instr 20
	s_note SC_AS   	; A#
	s_instr 19
	s_note SC_AS   	; A#
	s_instr 20
	s_oct 4	; block 3
	s_note_l SC_F, 40	; F dur=40
	s_note SC_E    	; E
	s_oct 3	; block 2
	s_note SC_B    	; B
	s_ret
Snd_3e_6a41:
	s_oct 3	; block 2
	s_instr 20
	s_note SC_AS   	; A#
	s_instr 19
	s_note SC_AS   	; A#
	s_instr 20
	s_note SC_AS   	; A#
	s_instr 19
	s_note SC_AS   	; A#
	s_oct 4	; block 3
	s_instr 20
	s_note SC_F    	; F
	s_instr 19
	s_note SC_F    	; F
	s_oct 3	; block 2
	s_instr 20
	s_note SC_AS   	; A#
	s_instr 19
	s_note SC_AS   	; A#
	s_ret
Snd_3e_6a5d:
	s_oct 4	; block 3
	s_instr 20
	s_note SC_C    	; C
	s_instr 19
	s_note SC_C    	; C
	s_oct 3	; block 2
	s_instr 20
	s_note SC_A    	; A
	s_instr 19
	s_note SC_A    	; A
	s_instr 20
	s_note SC_GS   	; G#
	s_instr 19
	s_note SC_GS   	; G#
	s_instr 20
	s_note SC_GS   	; G#
	s_instr 19
	s_note SC_GS   	; G#
	s_instr 20
	s_ret
Snd_3e_6a7a:
	s_instr 20
	s_note_l SC_G, 80	; G dur=80
	s_instr 19
	s_note_l SC_G, 40	; G dur=40
	s_ret
Snd_3e_6a83:
	s_instr 20
	s_note_l SC_G, 80	; G dur=80
	s_note_l SC_FS, 40	; F# dur=40
	s_instr 19
	s_note SC_FS   	; F#
	s_instr 20
	s_note SC_FS   	; F#
	s_ret
Snd_3e_6a90:
	s_instr 20
	s_note SC_FS   	; F#
	s_instr 19
	s_note SC_FS   	; F#
	s_instr 20
	s_note_l SC_FS, 80	; F# dur=80
	s_note_l SC_F, 40	; F dur=40
	s_note_l SC_G, 40	; G dur=40
	s_ret
Snd_3e_6a9f:
	s_oct 3	; block 2
	s_instr 20
	s_note SC_A    	; A
	s_instr 19
	s_note SC_A    	; A
	s_instr 20
	s_note SC_G    	; G
	s_instr 19
	s_note SC_G    	; G
	s_instr 20
	s_note SC_FS   	; F#
	s_instr 19
	s_note SC_FS   	; F#
	s_instr 20
	s_note SC_F    	; F
	s_instr 19
	s_note SC_F    	; F
	s_instr 20
	s_note SC_G    	; G
	s_instr 19
	s_note SC_G    	; G
	s_instr 20
	s_note_l SC_AS, 10	; A# dur=10
	s_instr 19
	s_note_l SC_AS, 10	; A# dur=10
	s_instr 20
	s_note_l SC_AS, 40	; A# dur=40
	s_note_l SC_G, 20	; G dur=20
	s_ret
Snd_3e_6acd:
	s_deflen 20
	s_oct 3	; block 2
	s_instr 20
	s_note SC_A    	; A
	s_instr 19
	s_note SC_A    	; A
	s_instr 20
	s_note SC_A    	; A
	s_instr 19
	s_note SC_A    	; A
	s_instr 20
	s_note SC_G    	; G
	s_instr 19
	s_note SC_G    	; G
	s_instr 20
	s_note SC_G    	; G
	s_instr 19
	s_note SC_G    	; G
	s_ret
Snd_3e_6ae9:
	s_instr 20
	s_note SC_FS   	; F#
	s_instr 19
	s_note SC_FS   	; F#
	s_instr 20
	s_note SC_FS   	; F#
	s_instr 19
	s_note SC_FS   	; F#
	s_instr 20
	s_note SC_F    	; F
	s_instr 19
	s_note SC_F    	; F
	s_instr 20
	s_note SC_F    	; F
	s_instr 19
	s_note SC_F    	; F
	s_ret
Snd_3e_6b02:
	s_instr 20
	s_note SC_FS   	; F#
	s_instr 19
	s_note SC_FS   	; F#
	s_instr 20
	s_note SC_FS   	; F#
	s_instr 19
	s_note SC_FS   	; F#
	s_instr 20
	s_note SC_G    	; G
	s_instr 19
	s_note SC_G    	; G
	s_instr 20
	s_note_l SC_G, 60	; G dur=60
	s_instr 19
	s_note SC_G    	; G
	s_ret
Snd_3e_6b1c:
	s_deflen 20
	s_oct 3	; block 2
	s_instr 20
	s_note SC_A    	; A
	s_instr 19
	s_note SC_A    	; A
	s_instr 20
	s_note SC_A    	; A
	s_instr 19
	s_note SC_A    	; A
	s_instr 20
	s_note SC_G    	; G
	s_instr 19
	s_note SC_G    	; G
	s_instr 20
	s_note SC_G    	; G
	s_instr 19
	s_note SC_G    	; G
	s_ret
Snd_3e_6b38:
	s_oct 3	; block 2
	s_instr 20
	s_note SC_F    	; F
	s_instr 19
	s_note SC_F    	; F
	s_oct 4	; block 3
	s_instr 20
	s_note SC_F    	; F
	s_instr 19
	s_note SC_F    	; F
	s_instr 20
	s_note SC_F    	; F
	s_instr 19
	s_note SC_F    	; F
	s_ret
Snd_3e_6b4d:
	s_oct 3	; block 2
	s_instr 20
	s_note_l SC_F, 80	; F dur=80
	s_instr 19
	s_note_l SC_F, 40	; F dur=40
	s_ret
Snd_3e_6b57:
	s_oct 3	; block 2
	s_instr 20
	s_note SC_F    	; F
	s_instr 19
	s_note SC_F    	; F
	s_oct 4	; block 3
	s_instr 20
	s_note_l SC_F, 60	; F dur=60
	s_instr 19
	s_note SC_F    	; F
	s_ret
Snd_3e_6b67:
	s_pitchenv 0
	s_deflen 10
	s_oct 1	; block 0
	s_set10 0
	s_note_l SC_REST, 40	; rest dur=40
	s_end
Snd_3e_6b71:	; unused/dead pattern
	s_deflen 40
	s_instr 10
	s_note SC_F    	; F
	s_instr 12
	s_note SC_D    	; D
	s_instr 10
	s_note SC_F    	; F
	s_instr 12
	s_note_l SC_D, 20	; D dur=20
	s_instr 10
	s_note_l SC_F, 20	; F dur=20
	s_ret
