; Sound id $3a (BGM) -- ?
; Bank $3e, ROM $6f12-$7ffe. Auto-generated by tools/songdisasm.py --split; INCLUDEd by sound/bank_3e.asm into its $4b00 section.

; ===== sound id $3a =====
Snd_3e_6f12:
	s_chan $f0, Snd_3e_6f1e
	s_chan $f0, Snd_3e_7070
	s_chan $f0, Snd_3e_72ab
	s_chan $f0, Snd_3e_7410
Snd_3e_6f1e:
	s_pitchenv 1
	s_set10 0
	s_dutyenv 2
Snd_3e_6f24:
	s_deflen 12
	s_oct 5	; block 4
	s_instr 2
	s_note SC_B    	; B
	s_instr 4
	s_note SC_B    	; B
	s_oct 6	; block 5
	s_instr 2
	s_note SC_C    	; C
	s_instr 4
	s_note SC_C    	; C
	s_instr 2
	s_note SC_E    	; E
	s_instr 4
	s_note SC_E    	; E
	s_instr 2
	s_note SC_G    	; G
	s_instr 4
	s_note SC_G    	; G
	s_oct 7	; block 6
	s_instr 2
	s_note SC_C    	; C
	s_instr 4
	s_note SC_C    	; C
	s_oct 6	; block 5
	s_instr 3
	s_note_l SC_B, 6	; B dur=6
	s_oct 7	; block 6
	s_note_l SC_C, 6	; C dur=6
	s_oct 6	; block 5
	s_note_l SC_B, 6	; B dur=6
	s_instr 4
	s_note_l SC_B, 6	; B dur=6
	s_instr 2
	s_note SC_G    	; G
	s_instr 4
	s_note SC_G    	; G
	s_instr 2
	s_note SC_E    	; E
	s_instr 4
	s_note SC_E    	; E
	s_oct 6	; block 5
	s_instr 2
	s_note_l SC_B, 24	; B dur=24
	s_keyon
	s_instr 2
	s_note SC_A    	; A
	s_instr 4
	s_note SC_A    	; A
	s_instr 2
	s_note SC_E    	; E
	s_instr 4
	s_note SC_E    	; E
	s_instr 2
	s_note SC_F    	; F
	s_instr 4
	s_note SC_F    	; F
	s_deflen 12
	s_instr 2
	s_note SC_A    	; A
	s_instr 4
	s_note SC_A    	; A
	s_instr 2
	s_note SC_G    	; G
	s_instr 4
	s_note SC_G    	; G
	s_oct 5	; block 4
	s_instr 2
	s_note_l SC_G, 24	; G dur=24
	s_instr 4
	s_note_l SC_G, 24	; G dur=24
	s_call Snd_3e_6fc7
	s_call Snd_3e_6fdc
	s_call Snd_3e_6fec
	s_call Snd_3e_6ff3
	s_call Snd_3e_6fc7
	s_call Snd_3e_6fdc
	s_call Snd_3e_7008
	s_call Snd_3e_7010
	s_call Snd_3e_701f
	s_call Snd_3e_702c
	s_call Snd_3e_701f
	s_call Snd_3e_703e
	s_call Snd_3e_701f
	s_call Snd_3e_702c
	s_call Snd_3e_704b
	s_call Snd_3e_7053
	s_call Snd_3e_7062
	s_goto Snd_3e_6f24
Snd_3e_6fc7:
	s_instr 2
	s_oct 5	; block 4
	s_deflen 24
	s_note_l SC_E, 72	; E dur=72
	s_note SC_G    	; G
	s_note_l SC_G, 48	; G dur=48
	s_keyon
	s_note_l SC_G, 12	; G dur=12
	s_instr 4
	s_note_l SC_G, 12	; G dur=12
	s_instr 1
	s_note SC_G    	; G
	s_ret
Snd_3e_6fdc:
	s_note_l SC_F, 72	; F dur=72
	s_note SC_G    	; G
	s_note_l SC_G, 48	; G dur=48
	s_keyon
	s_note_l SC_G, 12	; G dur=12
	s_instr 4
	s_note_l SC_G, 12	; G dur=12
	s_instr 1
	s_note SC_G    	; G
	s_ret
Snd_3e_6fec:
	s_note_l SC_E, 72	; E dur=72
	s_note SC_G    	; G
	s_note_l SC_F, 72	; F dur=72
	s_note SC_G    	; G
	s_ret
Snd_3e_6ff3:
	s_oct 6	; block 5
	s_note_l SC_C, 72	; C dur=72
	s_oct 5	; block 4
	s_note_l SC_B, 12	; B dur=12
	s_note_l SC_A, 12	; A dur=12
	s_note_l SC_G, 48	; G dur=48
	s_keyon
	s_note_l SC_G, 12	; G dur=12
	s_instr 4
	s_note_l SC_G, 12	; G dur=12
	s_instr 1
	s_note SC_G    	; G
	s_ret
Snd_3e_7008:
	s_note_l SC_E, 72	; E dur=72
	s_note SC_G    	; G
	s_note_l SC_F, 48	; F dur=48
	s_note SC_G    	; G
	s_note SC_B    	; B
	s_ret
Snd_3e_7010:
	s_oct 6	; block 5
	s_note SC_C    	; C
	s_note SC_REST 	; rest
	s_oct 5	; block 4
	s_note_l SC_C, 96	; C dur=96
	s_instr 3
	s_note SC_C    	; C
	s_instr 5
	s_note SC_C    	; C
	s_instr 1
	s_ret
Snd_3e_701f:
	s_oct 6	; block 5
	s_note_l SC_C, 72	; C dur=72
	s_oct 5	; block 4
	s_note_l SC_B, 12	; B dur=12
	s_note_l SC_A, 12	; A dur=12
	s_oct 6	; block 5
	s_note_l SC_D, 72	; D dur=72
	s_note SC_C    	; C
	s_ret
Snd_3e_702c:
	s_oct 5	; block 4
	s_note_l SC_B, 96	; B dur=96
	s_instr 2
	s_note SC_B    	; B
	s_instr 3
	s_note SC_B    	; B
	s_instr 4
	s_note SC_B    	; B
	s_instr 5
	s_note SC_B    	; B
	s_instr 1
	s_ret
Snd_3e_703e:
	s_oct 5	; block 4
	s_note_l SC_B, 72	; B dur=72
	s_oct 6	; block 5
	s_note SC_C    	; C
	s_note_l SC_D, 72	; D dur=72
	s_instr 4
	s_note SC_D    	; D
	s_instr 1
	s_ret
Snd_3e_704b:
	s_oct 6	; block 5
	s_deflen 48
	s_note SC_D    	; D
	s_note SC_C    	; C
	s_note SC_D    	; D
	s_note SC_E    	; E
	s_ret
Snd_3e_7053:
	s_deflen 24
	s_note SC_D    	; D
	s_note SC_C    	; C
	s_oct 5	; block 4
	s_note SC_B    	; B
	s_note SC_A    	; A
	s_note_l SC_B, 72	; B dur=72
	s_instr 4
	s_note SC_B    	; B
	s_instr 1
	s_ret
Snd_3e_7062:
	s_deflen 48
	s_note SC_G    	; G
	s_note SC_FS   	; F#
	s_note_l SC_G, 24	; G dur=24
	s_note_l SC_A, 24	; A dur=24
	s_note_l SC_B, 72	; B dur=72
	s_instr 4
	s_note SC_B    	; B
	s_ret
Snd_3e_7070:
	s_pitchenv 0
	s_set10 0
	s_dutyenv 2
Snd_3e_7076:
	s_oct 5	; block 4
	s_deflen 12
	s_instr 2
	s_note_l SC_G, 24	; G dur=24
	s_keyon
	s_instr 2
	s_note SC_A    	; A
	s_instr 4
	s_note SC_A    	; A
	s_instr 2
	s_note SC_C    	; C
	s_instr 4
	s_note SC_C    	; C
	s_instr 2
	s_note SC_E    	; E
	s_instr 4
	s_note SC_E    	; E
	s_oct 5	; block 4
	s_deflen 12
	s_instr 2
	s_note SC_G    	; G
	s_instr 4
	s_note SC_G    	; G
	s_oct 6	; block 5
	s_instr 2
	s_note SC_C    	; C
	s_instr 4
	s_note SC_C    	; C
	s_oct 5	; block 4
	s_instr 2
	s_note SC_E    	; E
	s_instr 4
	s_note SC_E    	; E
	s_instr 2
	s_note SC_G    	; G
	s_instr 4
	s_note SC_G    	; G
	s_oct 5	; block 4
	s_deflen 12
	s_instr 2
	s_note SC_G    	; G
	s_instr 4
	s_note SC_G    	; G
	s_instr 2
	s_note SC_E    	; E
	s_instr 4
	s_note SC_E    	; E
	s_instr 2
	s_note SC_G    	; G
	s_instr 4
	s_note SC_G    	; G
	s_instr 2
	s_note SC_C    	; C
	s_instr 4
	s_note SC_C    	; C
	s_oct 5	; block 4
	s_deflen 12
	s_instr 2
	s_note SC_E    	; E
	s_instr 4
	s_note SC_E    	; E
	s_instr 4
	s_oct 6	; block 5
	s_note SC_D    	; D
	s_note SC_E    	; E
	s_note SC_F    	; F
	s_note SC_D    	; D
	s_note SC_C    	; C
	s_oct 5	; block 4
	s_note SC_B    	; B
	s_call Snd_3e_7111
	s_call Snd_3e_7130
	s_call Snd_3e_714b
	s_call Snd_3e_716e
	s_call Snd_3e_7111
	s_call Snd_3e_7130
	s_call Snd_3e_717d
	s_call Snd_3e_7195
	s_call Snd_3e_71aa
	s_call Snd_3e_71c7
	s_call Snd_3e_71e6
	s_call Snd_3e_7213
	s_call Snd_3e_723f
	s_call Snd_3e_725f
	s_call Snd_3e_7277
	s_call Snd_3e_728a
	s_call Snd_3e_729f
	s_goto Snd_3e_7076
Snd_3e_7111:
	s_note_l SC_REST, 72	; rest dur=72
	s_oct 5	; block 4
	s_deflen 12
	s_instr 3
	s_note SC_E    	; E
	s_note SC_F    	; F
	s_note SC_E    	; E
	s_instr 4
	s_note SC_E    	; E
	s_instr 2
	s_oct 6	; block 5
	s_note SC_E    	; E
	s_instr 4
	s_note SC_E    	; E
	s_instr 2
	s_oct 5	; block 4
	s_note_l SC_E, 36	; E dur=36
	s_instr 4
	s_note SC_E    	; E
	s_instr 2
	s_ret
Snd_3e_7130:
	s_note_l SC_REST, 72	; rest dur=72
	s_oct 5	; block 4
	s_note SC_D    	; D
	s_note SC_E    	; E
	s_note SC_D    	; D
	s_instr 4
	s_note SC_D    	; D
	s_instr 2
	s_oct 6	; block 5
	s_note SC_D    	; D
	s_instr 4
	s_note SC_D    	; D
	s_instr 2
	s_oct 5	; block 4
	s_note_l SC_D, 36	; D dur=36
	s_instr 4
	s_note SC_D    	; D
	s_instr 2
	s_ret
Snd_3e_714b:
	s_oct 6	; block 5
	s_note_l SC_C, 36	; C dur=36
	s_instr 4
	s_note SC_C    	; C
	s_instr 2
	s_oct 5	; block 4
	s_note SC_C    	; C
	s_note SC_D    	; D
	s_note SC_E    	; E
	s_instr 4
	s_note SC_E    	; E
	s_instr 2
	s_oct 6	; block 5
	s_note_l SC_D, 36	; D dur=36
	s_instr 4
	s_note SC_D    	; D
	s_instr 2
	s_oct 5	; block 4
	s_note SC_D    	; D
	s_note SC_G    	; G
	s_note SC_B    	; B
	s_instr 4
	s_note SC_B    	; B
	s_instr 2
	s_ret
Snd_3e_716e:
	s_note_l SC_G, 72	; G dur=72
	s_oct 6	; block 5
	s_note SC_E    	; E
	s_note SC_F    	; F
	s_note_l SC_D, 72	; D dur=72
	s_keyon
	s_note SC_D    	; D
	s_instr 4
	s_note SC_D    	; D
	s_instr 2
	s_ret
Snd_3e_717d:
	s_note_l SC_G, 36	; G dur=36
	s_instr 4
	s_note SC_G    	; G
	s_instr 2
	s_deflen 24
	s_oct 6	; block 5
	s_note SC_C    	; C
	s_oct 5	; block 4
	s_note SC_E    	; E
	s_note_l SC_B, 36	; B dur=36
	s_instr 4
	s_note_l SC_B, 12	; B dur=12
	s_instr 2
	s_note SC_D    	; D
	s_note SC_F    	; F
	s_ret
Snd_3e_7195:
	s_note SC_E    	; E
	s_instr 4
	s_note SC_E    	; E
	s_instr 2
	s_note SC_G    	; G
	s_instr 4
	s_note SC_G    	; G
	s_instr 2
	s_note SC_E    	; E
	s_instr 4
	s_note SC_E    	; E
	s_instr 2
	s_note SC_D    	; D
	s_note SC_C    	; C
	s_ret
Snd_3e_71aa:
	s_oct 6	; block 5
	s_deflen 12
	s_note_l SC_REST, 48	; rest dur=48
	s_note_l SC_F, 36	; F dur=36
	s_instr 4
	s_note SC_F    	; F
	s_instr 2
	s_oct 5	; block 4
	s_note_l SC_A, 36	; A dur=36
	s_instr 4
	s_note SC_A    	; A
	s_instr 2
	s_oct 6	; block 5
	s_note_l SC_A, 36	; A dur=36
	s_instr 4
	s_note SC_A    	; A
	s_instr 2
	s_ret
Snd_3e_71c7:
	s_note_l SC_G, 36	; G dur=36
	s_instr 4
	s_note SC_G    	; G
	s_instr 2
	s_note_l SC_D, 36	; D dur=36
	s_instr 4
	s_note SC_D    	; D
	s_instr 2
	s_oct 5	; block 4
	s_note_l SC_G, 36	; G dur=36
	s_instr 4
	s_note SC_G    	; G
	s_instr 2
	s_oct 6	; block 5
	s_note_l SC_G, 36	; G dur=36
	s_instr 4
	s_note SC_G    	; G
	s_instr 2
	s_ret
Snd_3e_71e6:
	s_note_l SC_REST, 24	; rest dur=24
	s_oct 5	; block 4
	s_note SC_A    	; A
	s_instr 4
	s_note SC_A    	; A
	s_instr 2
	s_oct 6	; block 5
	s_note SC_F    	; F
	s_instr 4
	s_note SC_F    	; F
	s_instr 2
	s_note SC_A    	; A
	s_instr 4
	s_note SC_A    	; A
	s_instr 2
	s_note_l SC_REST, 24	; rest dur=24
	s_oct 5	; block 4
	s_note SC_B    	; B
	s_instr 4
	s_note SC_B    	; B
	s_instr 2
	s_oct 6	; block 5
	s_note SC_A    	; A
	s_instr 4
	s_note SC_A    	; A
	s_instr 2
	s_note SC_B    	; B
	s_instr 4
	s_note SC_B    	; B
	s_instr 2
	s_ret
Snd_3e_7213:
	s_note_l SC_REST, 24	; rest dur=24
	s_oct 5	; block 4
	s_note SC_B    	; B
	s_instr 4
	s_note SC_B    	; B
	s_instr 2
	s_oct 6	; block 5
	s_note SC_G    	; G
	s_instr 4
	s_note SC_G    	; G
	s_instr 2
	s_note SC_A    	; A
	s_instr 4
	s_note SC_A    	; A
	s_instr 2
	s_note_l SC_REST, 24	; rest dur=24
	s_oct 6	; block 5
	s_note SC_B    	; B
	s_instr 4
	s_note SC_B    	; B
	s_instr 2
	s_note SC_G    	; G
	s_instr 4
	s_note SC_G    	; G
	s_instr 2
	s_note SC_D    	; D
	s_instr 4
	s_note SC_D    	; D
	s_instr 2
	s_ret
Snd_3e_723f:
	s_note_l SC_A, 36	; A dur=36
	s_instr 4
	s_note SC_A    	; A
	s_instr 2
	s_note SC_F    	; F
	s_instr 4
	s_note SC_F    	; F
	s_instr 2
	s_note SC_G    	; G
	s_note SC_F    	; F
	s_note SC_B    	; B
	s_instr 4
	s_note SC_B    	; B
	s_instr 2
	s_note SC_G    	; G
	s_note SC_A    	; A
	s_note SC_B    	; B
	s_instr 4
	s_note SC_B    	; B
	s_instr 2
	s_note SC_G    	; G
	s_note SC_A    	; A
	s_ret
Snd_3e_725f:
	s_deflen 24
	s_note_l SC_G, 48	; G dur=48
	s_note SC_D    	; D
	s_instr 4
	s_note SC_D    	; D
	s_instr 2
	s_note SC_D    	; D
	s_instr 4
	s_note SC_D    	; D
	s_instr 2
	s_oct 5	; block 4
	s_note SC_G    	; G
	s_instr 4
	s_note SC_G    	; G
	s_instr 2
	s_ret
Snd_3e_7277:
	s_oct 5	; block 4
	s_note SC_A    	; A
	s_note SC_B    	; B
	s_note SC_A    	; A
	s_instr 4
	s_note SC_A    	; A
	s_instr 2
	s_note SC_A    	; A
	s_note SC_B    	; B
	s_oct 6	; block 5
	s_note SC_C    	; C
	s_instr 4
	s_note SC_C    	; C
	s_instr 2
	s_ret
Snd_3e_728a:
	s_oct 5	; block 4
	s_note SC_G    	; G
	s_note SC_FS   	; F#
	s_note SC_G    	; G
	s_note SC_FS   	; F#
	s_note_l SC_G, 36	; G dur=36
	s_oct 6	; block 5
	s_note_l SC_F, 6	; F dur=6
	s_keyon
	s_note_l SC_FS, 6	; F# dur=6
	s_keyon
	s_note SC_G    	; G
	s_instr 4
	s_note SC_G    	; G
	s_instr 2
	s_ret
Snd_3e_729f:
	s_deflen 48
	s_oct 6	; block 5
	s_note SC_D    	; D
	s_note SC_CS   	; C#
	s_note SC_C    	; C
	s_note_l SC_D, 72	; D dur=72
	s_instr 4
	s_note SC_D    	; D
	s_ret
Snd_3e_72ab:
	s_pitchenv 0
	s_wave 7
	s_set10 0
	s_instr 20
Snd_3e_72b3:
	s_note_l SC_REST, 192	; rest dur=192
	s_note_l SC_REST, 96	; rest dur=96
	s_deflen 12
	s_note_l SC_REST, 24	; rest dur=24
	s_oct 4	; block 3
	s_instr 20
	s_note SC_G    	; G
	s_instr 19
	s_note SC_G    	; G
	s_instr 20
	s_note SC_F    	; F
	s_note SC_E    	; E
	s_note_l SC_D, 24	; D dur=24
	s_call Snd_3e_72fe
	s_call Snd_3e_7334
	s_call Snd_3e_7367
	s_call Snd_3e_7382
	s_call Snd_3e_72fe
	s_call Snd_3e_7334
	s_call Snd_3e_739b
	s_call Snd_3e_73b8
	s_call Snd_3e_73d2
	s_call Snd_3e_73e8
	s_call Snd_3e_73d2
	s_call Snd_3e_73e8
	s_call Snd_3e_73d2
	s_call Snd_3e_73e8
	s_call Snd_3e_73d2
	s_call Snd_3e_73f3
	s_call Snd_3e_7402
	s_goto Snd_3e_72b3
Snd_3e_72fe:
	s_deflen 12
	s_oct 5	; block 4
	s_instr 20
	s_note SC_C    	; C
	s_instr 19
	s_note SC_C    	; C
	s_instr 20
	s_note SC_E    	; E
	s_instr 19
	s_note SC_E    	; E
	s_instr 20
	s_note SC_G    	; G
	s_instr 19
	s_note SC_G    	; G
	s_instr 20
	s_note SC_E    	; E
	s_instr 19
	s_note SC_E    	; E
	s_oct 6	; block 5
	s_instr 20
	s_note SC_C    	; C
	s_instr 19
	s_note SC_C    	; C
	s_instr 20
	s_note SC_E    	; E
	s_instr 19
	s_note SC_E    	; E
	s_oct 5	; block 4
	s_instr 20
	s_note SC_C    	; C
	s_instr 19
	s_note SC_C    	; C
	s_instr 20
	s_note SC_E    	; E
	s_instr 19
	s_note SC_E    	; E
	s_ret
Snd_3e_7334:
	s_instr 20
	s_note SC_D    	; D
	s_instr 19
	s_note SC_D    	; D
	s_instr 20
	s_note SC_F    	; F
	s_instr 19
	s_note SC_F    	; F
	s_instr 20
	s_note SC_G    	; G
	s_instr 19
	s_note SC_G    	; G
	s_instr 20
	s_note SC_F    	; F
	s_instr 19
	s_note SC_F    	; F
	s_instr 20
	s_note SC_B    	; B
	s_instr 19
	s_note SC_B    	; B
	s_oct 6	; block 5
	s_instr 20
	s_note SC_D    	; D
	s_instr 19
	s_note SC_D    	; D
	s_oct 5	; block 4
	s_instr 20
	s_note SC_G    	; G
	s_instr 19
	s_note SC_G    	; G
	s_instr 20
	s_note SC_F    	; F
	s_instr 19
	s_note SC_F    	; F
	s_ret
Snd_3e_7367:
	s_deflen 24
	s_instr 20
	s_note SC_C    	; C
	s_instr 19
	s_note SC_C    	; C
	s_instr 20
	s_note SC_G    	; G
	s_instr 19
	s_note SC_G    	; G
	s_instr 20
	s_note SC_D    	; D
	s_instr 19
	s_note SC_D    	; D
	s_instr 20
	s_note SC_G    	; G
	s_instr 19
	s_note SC_G    	; G
	s_ret
Snd_3e_7382:
	s_instr 20
	s_note SC_E    	; E
	s_instr 19
	s_note SC_E    	; E
	s_instr 20
	s_note SC_G    	; G
	s_instr 19
	s_note SC_G    	; G
	s_instr 20
	s_note SC_B    	; B
	s_instr 19
	s_note SC_B    	; B
	s_instr 20
	s_note SC_D    	; D
	s_instr 19
	s_note SC_D    	; D
	s_ret
Snd_3e_739b:
	s_deflen 24
	s_instr 20
	s_note SC_C    	; C
	s_instr 19
	s_note SC_C    	; C
	s_instr 20
	s_note SC_G    	; G
	s_instr 19
	s_note SC_G    	; G
	s_oct 6	; block 5
	s_instr 20
	s_note SC_D    	; D
	s_instr 19
	s_note SC_D    	; D
	s_oct 5	; block 4
	s_instr 20
	s_note SC_D    	; D
	s_instr 19
	s_note SC_D    	; D
	s_ret
Snd_3e_73b8:
	s_instr 20
	s_note SC_C    	; C
	s_instr 19
	s_note SC_C    	; C
	s_instr 20
	s_note SC_E    	; E
	s_instr 19
	s_note SC_E    	; E
	s_instr 20
	s_note SC_G    	; G
	s_instr 19
	s_note SC_G    	; G
	s_oct 4	; block 3
	s_instr 20
	s_note SC_G    	; G
	s_instr 19
	s_note SC_G    	; G
	s_ret
Snd_3e_73d2:
	s_deflen 24
	s_oct 5	; block 4
	s_instr 20
	s_note_l SC_F, 48	; F dur=48
	s_instr 19
	s_note SC_F    	; F
	s_instr 20
	s_note SC_F    	; F
	s_note_l SC_FS, 48	; F# dur=48
	s_instr 19
	s_note SC_FS   	; F#
	s_instr 20
	s_note SC_FS   	; F#
	s_ret
Snd_3e_73e8:
	s_oct 5	; block 4
	s_note_l SC_G, 72	; G dur=72
	s_oct 6	; block 5
	s_note SC_D    	; D
	s_oct 5	; block 4
	s_note_l SC_B, 48	; B dur=48
	s_note SC_A    	; A
	s_note SC_G    	; G
	s_ret
Snd_3e_73f3:
	s_oct 5	; block 4
	s_note_l SC_G, 72	; G dur=72
	s_oct 6	; block 5
	s_note SC_D    	; D
	s_oct 5	; block 4
	s_note_l SC_G, 48	; G dur=48
	s_instr 19
	s_note SC_G    	; G
	s_instr 20
	s_note SC_REST 	; rest
	s_ret
Snd_3e_7402:
	s_deflen 48
	s_note_l SC_G, 48	; G dur=48
	s_note SC_FS   	; F#
	s_note SC_F    	; F
	s_note SC_G    	; G
	s_instr 19
	s_note_l SC_G, 72	; G dur=72
	s_instr 20
	s_ret
Snd_3e_7410:
	s_pitchenv 0
	s_deflen 24
	s_oct 1	; block 0
	s_set10 0
	s_note_l SC_REST, 24	; rest dur=24
Snd_3e_7419:
	s_note_l SC_REST, 192	; rest dur=192
	s_goto Snd_3e_7419
Snd_3e_741e:
	ds 3041, $ff
