; Sound id $2a (BGM) -- ?
; Bank $3f, ROM $5ca3-$60be. Auto-generated by tools/songdisasm.py --split; INCLUDEd by sound/bank_3f.asm into its $4b00 section.

; ===== sound id $2a =====
Snd_3f_5ca3:
	s_chan $f0, Snd_3f_5caf
	s_chan $f0, Snd_3f_5d8a
	s_chan $f0, Snd_3f_5e7d
	s_chan $f0, Snd_3f_6020
Snd_3f_5caf:
	s_pitchenv 0
	s_deflen 7
	s_set10 0
	s_dutyenv 5
Snd_3f_5cb7:
	s_call Snd_3f_5cf0
	s_call Snd_3f_5d08
	s_call Snd_3f_5cf0
	s_call Snd_3f_5d08
	s_call Snd_3f_5d23
	s_call Snd_3f_5d3b
	s_call Snd_3f_5d23
	s_call Snd_3f_5d3b
	s_call Snd_3f_5cf0
	s_call Snd_3f_5d08
	s_call Snd_3f_5cf0
	s_call Snd_3f_5d08
	s_call Snd_3f_5d23
	s_call Snd_3f_5d3b
	s_call Snd_3f_5d55
	s_call Snd_3f_5d71
	s_call Snd_3f_5d71
	s_call Snd_3f_5d71
	s_goto Snd_3f_5cb7
Snd_3f_5cf0:
	s_deflen 7
	s_instr 1
	s_oct 4	; block 3
	s_note SC_GS   	; G#
	s_note SC_G    	; G
	s_note_l SC_FS, 14	; F# dur=14
	s_instr 3
	s_note SC_FS   	; F#
	s_instr 1
	s_note SC_F    	; F
	s_note_l SC_C, 28	; C dur=28
	s_note_l SC_FS, 14	; F# dur=14
	s_note SC_D    	; D
	s_note SC_FS   	; F#
	s_note SC_DS   	; D#
	s_note SC_E    	; E
	s_ret
Snd_3f_5d08:
	s_deflen 7
	s_instr 1
	s_oct 4	; block 3
	s_note SC_A    	; A
	s_note SC_GS   	; G#
	s_oct 5	; block 4
	s_note SC_CS   	; C#
	s_oct 4	; block 3
	s_note SC_G    	; G
	s_note SC_A    	; A
	s_oct 4	; block 3
	s_note SC_G    	; G
	s_note SC_CS   	; C#
	s_oct 5	; block 4
	s_note SC_CS   	; C#
	s_oct 4	; block 3
	s_note SC_CS   	; C#
	s_note SC_D    	; D
	s_note SC_G    	; G
	s_note SC_DS   	; D#
	s_note SC_DS   	; D#
	s_note SC_D    	; D
	s_note SC_CS   	; C#
	s_note SC_C    	; C
	s_ret
Snd_3f_5d23:
	s_deflen 7
	s_instr 1
	s_oct 4	; block 3
	s_note SC_AS   	; A#
	s_note SC_A    	; A
	s_note_l SC_GS, 14	; G# dur=14
	s_instr 3
	s_note SC_GS   	; G#
	s_instr 1
	s_note SC_G    	; G
	s_note_l SC_D, 28	; D dur=28
	s_note_l SC_GS, 14	; G# dur=14
	s_note SC_E    	; E
	s_note SC_GS   	; G#
	s_note SC_F    	; F
	s_note SC_FS   	; F#
	s_ret
Snd_3f_5d3b:
	s_deflen 7
	s_instr 1
	s_oct 4	; block 3
	s_note SC_B    	; B
	s_note SC_AS   	; A#
	s_note SC_A    	; A
	s_note SC_GS   	; G#
	s_oct 5	; block 4
	s_note SC_DS   	; D#
	s_oct 4	; block 3
	s_note SC_A    	; A
	s_note SC_DS   	; D#
	s_oct 5	; block 4
	s_note SC_DS   	; D#
	s_oct 4	; block 3
	s_note SC_DS   	; D#
	s_note SC_E    	; E
	s_note SC_A    	; A
	s_note SC_F    	; F
	s_note SC_F    	; F
	s_note SC_E    	; E
	s_note SC_DS   	; D#
	s_note SC_D    	; D
	s_ret
Snd_3f_5d55:
	s_deflen 7
	s_instr 1
	s_oct 5	; block 4
	s_note SC_C    	; C
	s_oct 4	; block 3
	s_note SC_B    	; B
	s_note SC_E    	; E
	s_oct 4	; block 3
	s_note SC_AS   	; A#
	s_oct 5	; block 4
	s_note SC_C    	; C
	s_oct 4	; block 3
	s_note SC_AS   	; A#
	s_note SC_E    	; E
	s_oct 5	; block 4
	s_note SC_E    	; E
	s_oct 4	; block 3
	s_note SC_E    	; E
	s_note SC_F    	; F
	s_note SC_AS   	; A#
	s_note SC_FS   	; F#
	s_note SC_FS   	; F#
	s_note SC_F    	; F
	s_note SC_E    	; E
	s_note SC_DS   	; D#
	s_ret
Snd_3f_5d71:
	s_deflen 7
	s_instr 1
	s_oct 5	; block 4
	s_note SC_CS   	; C#
	s_note SC_C    	; C
	s_oct 4	; block 3
	s_note_l SC_B, 14	; B dur=14
	s_instr 3
	s_note SC_B    	; B
	s_instr 1
	s_note SC_AS   	; A#
	s_note_l SC_F, 28	; F dur=28
	s_note_l SC_B, 14	; B dur=14
	s_note SC_G    	; G
	s_note SC_B    	; B
	s_note SC_GS   	; G#
	s_note SC_A    	; A
	s_ret
Snd_3f_5d8a:
	s_pitchenv 0
	s_deflen 7
	s_set10 0
	s_dutyenv 4
Snd_3f_5d92:
	s_call Snd_3f_5dcb
	s_call Snd_3f_5dec
	s_call Snd_3f_5dcb
	s_call Snd_3f_5dec
	s_call Snd_3f_5e09
	s_call Snd_3f_5e26
	s_call Snd_3f_5e09
	s_call Snd_3f_5e26
	s_call Snd_3f_5dcb
	s_call Snd_3f_5dec
	s_call Snd_3f_5dcb
	s_call Snd_3f_5dec
	s_call Snd_3f_5e09
	s_call Snd_3f_5e26
	s_call Snd_3f_5e43
	s_call Snd_3f_5e60
	s_call Snd_3f_5e60
	s_call Snd_3f_5e60
	s_goto Snd_3f_5d92
Snd_3f_5dcb:
	s_deflen 7
	s_instr 2
	s_oct 4	; block 3
	s_note SC_FS   	; F#
	s_oct 3	; block 2
	s_note SC_FS   	; F#
	s_oct 4	; block 3
	s_note SC_D    	; D
	s_note SC_FS   	; F#
	s_oct 3	; block 2
	s_note SC_FS   	; F#
	s_oct 4	; block 3
	s_note SC_D    	; D
	s_note SC_FS   	; F#
	s_oct 3	; block 2
	s_note SC_FS   	; F#
	s_oct 4	; block 3
	s_note SC_FS   	; F#
	s_oct 3	; block 2
	s_note SC_FS   	; F#
	s_oct 4	; block 3
	s_note SC_D    	; D
	s_note SC_FS   	; F#
	s_oct 3	; block 2
	s_note SC_FS   	; F#
	s_oct 4	; block 3
	s_note SC_D    	; D
	s_note SC_FS   	; F#
	s_oct 3	; block 2
	s_note SC_FS   	; F#
	s_ret
Snd_3f_5dec:
	s_oct 4	; block 3
	s_note SC_G    	; G
	s_oct 3	; block 2
	s_note SC_G    	; G
	s_oct 4	; block 3
	s_note SC_DS   	; D#
	s_note SC_G    	; G
	s_oct 3	; block 2
	s_note SC_G    	; G
	s_oct 4	; block 3
	s_note SC_DS   	; D#
	s_note SC_G    	; G
	s_oct 3	; block 2
	s_note SC_G    	; G
	s_oct 4	; block 3
	s_note SC_G    	; G
	s_oct 3	; block 2
	s_note SC_G    	; G
	s_oct 4	; block 3
	s_note SC_DS   	; D#
	s_note SC_G    	; G
	s_oct 3	; block 2
	s_note SC_G    	; G
	s_oct 4	; block 3
	s_note SC_DS   	; D#
	s_note SC_G    	; G
	s_oct 3	; block 2
	s_note SC_G    	; G
	s_ret
Snd_3f_5e09:
	s_oct 4	; block 3
	s_note SC_GS   	; G#
	s_oct 3	; block 2
	s_note SC_GS   	; G#
	s_oct 4	; block 3
	s_note SC_E    	; E
	s_note SC_GS   	; G#
	s_oct 3	; block 2
	s_note SC_GS   	; G#
	s_oct 4	; block 3
	s_note SC_E    	; E
	s_note SC_GS   	; G#
	s_oct 3	; block 2
	s_note SC_GS   	; G#
	s_oct 4	; block 3
	s_note SC_GS   	; G#
	s_oct 3	; block 2
	s_note SC_GS   	; G#
	s_oct 4	; block 3
	s_note SC_E    	; E
	s_note SC_GS   	; G#
	s_oct 3	; block 2
	s_note SC_GS   	; G#
	s_oct 4	; block 3
	s_note SC_E    	; E
	s_note SC_GS   	; G#
	s_oct 3	; block 2
	s_note SC_GS   	; G#
	s_ret
Snd_3f_5e26:
	s_oct 4	; block 3
	s_note SC_A    	; A
	s_oct 3	; block 2
	s_note SC_A    	; A
	s_oct 4	; block 3
	s_note SC_F    	; F
	s_note SC_A    	; A
	s_oct 3	; block 2
	s_note SC_A    	; A
	s_oct 4	; block 3
	s_note SC_F    	; F
	s_note SC_A    	; A
	s_oct 3	; block 2
	s_note SC_A    	; A
	s_oct 4	; block 3
	s_note SC_A    	; A
	s_oct 3	; block 2
	s_note SC_A    	; A
	s_oct 4	; block 3
	s_note SC_F    	; F
	s_note SC_A    	; A
	s_oct 3	; block 2
	s_note SC_A    	; A
	s_oct 4	; block 3
	s_note SC_F    	; F
	s_note SC_A    	; A
	s_oct 3	; block 2
	s_note SC_A    	; A
	s_ret
Snd_3f_5e43:
	s_oct 4	; block 3
	s_note SC_AS   	; A#
	s_oct 3	; block 2
	s_note SC_AS   	; A#
	s_oct 4	; block 3
	s_note SC_FS   	; F#
	s_note SC_AS   	; A#
	s_oct 3	; block 2
	s_note SC_AS   	; A#
	s_oct 4	; block 3
	s_note SC_FS   	; F#
	s_note SC_AS   	; A#
	s_oct 3	; block 2
	s_note SC_AS   	; A#
	s_oct 4	; block 3
	s_note SC_AS   	; A#
	s_oct 3	; block 2
	s_note SC_AS   	; A#
	s_oct 4	; block 3
	s_note SC_FS   	; F#
	s_note SC_AS   	; A#
	s_oct 3	; block 2
	s_note SC_AS   	; A#
	s_oct 4	; block 3
	s_note SC_FS   	; F#
	s_note SC_AS   	; A#
	s_oct 3	; block 2
	s_note SC_AS   	; A#
	s_ret
Snd_3f_5e60:
	s_oct 4	; block 3
	s_note SC_B    	; B
	s_oct 3	; block 2
	s_note SC_B    	; B
	s_oct 4	; block 3
	s_note SC_G    	; G
	s_note SC_B    	; B
	s_oct 3	; block 2
	s_note SC_B    	; B
	s_oct 4	; block 3
	s_note SC_G    	; G
	s_note SC_B    	; B
	s_oct 3	; block 2
	s_note SC_B    	; B
	s_oct 4	; block 3
	s_note SC_B    	; B
	s_oct 3	; block 2
	s_note SC_B    	; B
	s_oct 4	; block 3
	s_note SC_G    	; G
	s_note SC_B    	; B
	s_oct 3	; block 2
	s_note SC_B    	; B
	s_oct 4	; block 3
	s_note SC_G    	; G
	s_note SC_B    	; B
	s_oct 3	; block 2
	s_note SC_B    	; B
	s_ret
Snd_3f_5e7d:
	s_deflen 7
	s_pitchenv 0
	s_set10 0
Snd_3f_5e83:
	s_call Snd_3f_5ebc
	s_call Snd_3f_5eeb
	s_call Snd_3f_5ebc
	s_call Snd_3f_5eeb
	s_call Snd_3f_5f1a
	s_call Snd_3f_5f49
	s_call Snd_3f_5f1a
	s_call Snd_3f_5f49
	s_call Snd_3f_5ebc
	s_call Snd_3f_5eeb
	s_call Snd_3f_5ebc
	s_call Snd_3f_5eeb
	s_call Snd_3f_5f1a
	s_call Snd_3f_5f49
	s_call Snd_3f_5f74
	s_call Snd_3f_5f9f
	s_call Snd_3f_5f9f
	s_call Snd_3f_5f9f
	s_goto Snd_3f_5e83
Snd_3f_5ebc:
	s_deflen 7
	s_wave 2
	s_oct 3	; block 2
	s_instr 20
	s_note SC_GS   	; G#
	s_instr 19
	s_note SC_GS   	; G#
	s_instr 20
	s_note SC_GS   	; G#
	s_instr 19
	s_note SC_GS   	; G#
	s_note SC_REST 	; rest
	s_instr 20
	s_note_l SC_GS, 14	; G# dur=14
	s_instr 19
	s_note SC_GS   	; G#
	s_oct 3	; block 2
	s_instr 20
	s_note_l SC_GS, 14	; G# dur=14
	s_instr 19
	s_note SC_GS   	; G#
	s_instr 20
	s_note_l SC_GS, 14	; G# dur=14
	s_instr 19
	s_note SC_GS   	; G#
	s_instr 20
	s_note SC_GS   	; G#
	s_instr 19
	s_note SC_GS   	; G#
	s_ret
Snd_3f_5eeb:
	s_deflen 7
	s_wave 2
	s_oct 3	; block 2
	s_instr 20
	s_note SC_A    	; A
	s_instr 19
	s_note SC_A    	; A
	s_instr 20
	s_note SC_A    	; A
	s_instr 19
	s_note SC_A    	; A
	s_note SC_REST 	; rest
	s_instr 20
	s_note_l SC_A, 14	; A dur=14
	s_instr 19
	s_note SC_A    	; A
	s_oct 3	; block 2
	s_instr 20
	s_note_l SC_A, 14	; A dur=14
	s_instr 19
	s_note SC_A    	; A
	s_instr 20
	s_note_l SC_A, 14	; A dur=14
	s_instr 19
	s_note SC_A    	; A
	s_instr 20
	s_note SC_A    	; A
	s_instr 19
	s_note SC_A    	; A
	s_ret
Snd_3f_5f1a:
	s_deflen 7
	s_wave 2
	s_oct 3	; block 2
	s_instr 20
	s_note SC_AS   	; A#
	s_instr 19
	s_note SC_AS   	; A#
	s_instr 20
	s_note SC_AS   	; A#
	s_instr 19
	s_note SC_AS   	; A#
	s_note SC_REST 	; rest
	s_instr 20
	s_note_l SC_AS, 14	; A# dur=14
	s_instr 19
	s_note SC_AS   	; A#
	s_oct 3	; block 2
	s_instr 20
	s_note_l SC_AS, 14	; A# dur=14
	s_instr 19
	s_note SC_AS   	; A#
	s_instr 20
	s_note_l SC_AS, 14	; A# dur=14
	s_instr 19
	s_note SC_AS   	; A#
	s_instr 20
	s_note SC_AS   	; A#
	s_instr 19
	s_note SC_AS   	; A#
	s_ret
Snd_3f_5f49:
	s_oct 3	; block 2
	s_instr 20
	s_note SC_B    	; B
	s_instr 19
	s_note SC_B    	; B
	s_instr 20
	s_note SC_B    	; B
	s_instr 19
	s_note SC_B    	; B
	s_note SC_REST 	; rest
	s_instr 20
	s_note_l SC_B, 14	; B dur=14
	s_instr 19
	s_note SC_B    	; B
	s_oct 3	; block 2
	s_instr 20
	s_note_l SC_B, 14	; B dur=14
	s_instr 19
	s_note SC_B    	; B
	s_instr 20
	s_note_l SC_B, 14	; B dur=14
	s_instr 19
	s_note SC_B    	; B
	s_instr 20
	s_note SC_B    	; B
	s_instr 19
	s_note SC_B    	; B
	s_ret
Snd_3f_5f74:
	s_oct 4	; block 3
	s_instr 20
	s_note SC_C    	; C
	s_instr 19
	s_note SC_C    	; C
	s_instr 20
	s_note SC_C    	; C
	s_instr 19
	s_note SC_C    	; C
	s_note SC_REST 	; rest
	s_instr 20
	s_note_l SC_C, 14	; C dur=14
	s_instr 19
	s_note SC_C    	; C
	s_oct 4	; block 3
	s_instr 20
	s_note_l SC_C, 14	; C dur=14
	s_instr 19
	s_note SC_C    	; C
	s_instr 20
	s_note_l SC_C, 14	; C dur=14
	s_instr 19
	s_note SC_C    	; C
	s_instr 20
	s_note SC_C    	; C
	s_instr 19
	s_note SC_C    	; C
	s_ret
Snd_3f_5f9f:
	s_oct 4	; block 3
	s_instr 20
	s_note SC_CS   	; C#
	s_instr 19
	s_note SC_CS   	; C#
	s_instr 20
	s_note SC_CS   	; C#
	s_instr 19
	s_note SC_CS   	; C#
	s_note SC_REST 	; rest
	s_instr 20
	s_note_l SC_CS, 14	; C# dur=14
	s_instr 19
	s_note SC_CS   	; C#
	s_oct 4	; block 3
	s_instr 20
	s_note_l SC_CS, 14	; C# dur=14
	s_instr 19
	s_note SC_CS   	; C#
	s_instr 20
	s_note_l SC_CS, 14	; C# dur=14
	s_instr 19
	s_note SC_CS   	; C#
	s_instr 20
	s_note SC_CS   	; C#
	s_instr 19
	s_note SC_CS   	; C#
	s_ret
Snd_3f_5fca:	; unused/dead pattern
	s_oct 4	; block 3
	s_instr 20
	s_note SC_D    	; D
	s_instr 19
	s_note SC_D    	; D
	s_instr 20
	s_note SC_D    	; D
	s_instr 19
	s_note SC_D    	; D
	s_note SC_REST 	; rest
	s_instr 20
	s_note_l SC_D, 14	; D dur=14
	s_instr 19
	s_note SC_D    	; D
	s_oct 4	; block 3
	s_instr 20
	s_note_l SC_D, 14	; D dur=14
	s_instr 19
	s_note SC_D    	; D
	s_instr 20
	s_note_l SC_D, 14	; D dur=14
	s_instr 19
	s_note SC_D    	; D
	s_instr 20
	s_note SC_D    	; D
	s_instr 19
	s_note SC_D    	; D
	s_ret
	s_oct 4	; block 3
	s_instr 20
	s_note SC_DS   	; D#
	s_instr 19
	s_note SC_DS   	; D#
	s_instr 20
	s_note SC_DS   	; D#
	s_instr 19
	s_note SC_DS   	; D#
	s_note SC_REST 	; rest
	s_instr 20
	s_note_l SC_DS, 14	; D# dur=14
	s_instr 19
	s_note SC_DS   	; D#
	s_oct 4	; block 3
	s_instr 20
	s_note_l SC_DS, 14	; D# dur=14
	s_instr 19
	s_note SC_DS   	; D#
	s_instr 20
	s_note_l SC_DS, 14	; D# dur=14
	s_instr 19
	s_note SC_DS   	; D#
	s_instr 20
	s_note SC_DS   	; D#
	s_instr 19
	s_note SC_DS   	; D#
	s_ret
Snd_3f_6020:
	s_pitchenv 0
	s_oct 1	; block 0
	s_deflen 7
	s_set10 0
Snd_3f_6027:
	s_call Snd_3f_6060
	s_call Snd_3f_607f
	s_call Snd_3f_6060
	s_call Snd_3f_607f
	s_call Snd_3f_6060
	s_call Snd_3f_607f
	s_call Snd_3f_6060
	s_call Snd_3f_607f
	s_call Snd_3f_6060
	s_call Snd_3f_607f
	s_call Snd_3f_6060
	s_call Snd_3f_607f
	s_call Snd_3f_6060
	s_call Snd_3f_607f
	s_call Snd_3f_607f
	s_call Snd_3f_607f
	s_call Snd_3f_607f
	s_call Snd_3f_609e
	s_goto Snd_3f_6027
Snd_3f_6060:
	s_instr 10
	s_note SC_F    	; F
	s_note SC_C    	; C
	s_note SC_C    	; C
	s_note SC_C    	; C
	s_instr 14
	s_note SC_F    	; F
	s_instr 10
	s_note SC_C    	; C
	s_note SC_C    	; C
	s_note SC_C    	; C
	s_instr 10
	s_note SC_F    	; F
	s_note SC_C    	; C
	s_note SC_C    	; C
	s_note SC_C    	; C
	s_instr 14
	s_note SC_F    	; F
	s_instr 10
	s_note SC_C    	; C
	s_instr 13
	s_note_l SC_C, 14	; C dur=14
	s_ret
Snd_3f_607f:
	s_instr 10
	s_note SC_F    	; F
	s_note SC_C    	; C
	s_note SC_C    	; C
	s_note SC_C    	; C
	s_instr 14
	s_note SC_F    	; F
	s_instr 10
	s_note SC_C    	; C
	s_note SC_C    	; C
	s_note SC_C    	; C
	s_instr 10
	s_note SC_F    	; F
	s_note SC_C    	; C
	s_note SC_C    	; C
	s_note SC_C    	; C
	s_instr 14
	s_note SC_F    	; F
	s_instr 10
	s_note SC_C    	; C
	s_note SC_F    	; F
	s_instr 14
	s_note SC_F    	; F
	s_ret
Snd_3f_609e:
	s_instr 10
	s_note SC_F    	; F
	s_note SC_C    	; C
	s_note SC_C    	; C
	s_note SC_C    	; C
	s_instr 14
	s_note SC_F    	; F
	s_instr 10
	s_note SC_C    	; C
	s_note SC_C    	; C
	s_note SC_C    	; C
	s_instr 14
	s_note SC_F    	; F
	s_instr 10
	s_note SC_F    	; F
	s_instr 14
	s_note SC_F    	; F
	s_instr 10
	s_note SC_F    	; F
	s_instr 14
	s_note SC_F    	; F
	s_note SC_F    	; F
	s_note SC_F    	; F
	s_note SC_F    	; F
	s_ret
