; Sound id $39 (BGM) -- ?
; Bank $3e, ROM $6b85-$6f11. Auto-generated by tools/songdisasm.py --split; INCLUDEd by sound/bank_3e.asm into its $4b00 section.

; ===== sound id $39 =====
Snd_3e_6b85:
	s_chan $f0, Snd_3e_6b91
	s_chan $f0, Snd_3e_6c87
	s_chan $f0, Snd_3e_6e6e
	s_chan $f0, Snd_3e_6f02
Snd_3e_6b91:
	s_pitchenv 1
	s_set10 0
	s_dutyenv 3
Snd_3e_6b97:
	s_deflen 20
	s_oct 5	; block 4
	s_instr 3
	s_note_l SC_F, 4	; F dur=4
	s_note_l SC_FS, 4	; F# dur=4
	s_instr 2
	s_note_l SC_G, 2	; G dur=2
	s_keyon
	s_note_l SC_G, 30	; G dur=30
	s_instr 1
	s_call Snd_3e_6be7
	s_call Snd_3e_6bf7
	s_call Snd_3e_6c07
	s_call Snd_3e_6c0e
	s_call Snd_3e_6be7
	s_call Snd_3e_6bf7
	s_call Snd_3e_6c23
	s_call Snd_3e_6c2b
	s_instr 2
	s_dutyenv 5
	s_call Snd_3e_6c3a
	s_call Snd_3e_6c47
	s_call Snd_3e_6c3a
	s_call Snd_3e_6c59
	s_call Snd_3e_6c3a
	s_call Snd_3e_6c47
	s_call Snd_3e_6c66
	s_call Snd_3e_6c6e
	s_call Snd_3e_6c78
	s_dutyenv 3
	s_instr 1
	s_goto Snd_3e_6b97
Snd_3e_6be7:
	s_note_l SC_E, 60	; E dur=60
	s_note SC_G    	; G
	s_note_l SC_G, 40	; G dur=40
	s_keyon
	s_note_l SC_G, 10	; G dur=10
	s_instr 4
	s_note_l SC_G, 10	; G dur=10
	s_instr 1
	s_note SC_G    	; G
	s_ret
Snd_3e_6bf7:
	s_note_l SC_F, 60	; F dur=60
	s_note SC_G    	; G
	s_note_l SC_G, 40	; G dur=40
	s_keyon
	s_note_l SC_G, 10	; G dur=10
	s_instr 4
	s_note_l SC_G, 10	; G dur=10
	s_instr 1
	s_note SC_G    	; G
	s_ret
Snd_3e_6c07:
	s_note_l SC_E, 60	; E dur=60
	s_note SC_G    	; G
	s_note_l SC_F, 60	; F dur=60
	s_note SC_G    	; G
	s_ret
Snd_3e_6c0e:
	s_oct 6	; block 5
	s_note_l SC_C, 60	; C dur=60
	s_oct 5	; block 4
	s_note_l SC_B, 10	; B dur=10
	s_note_l SC_A, 10	; A dur=10
	s_note_l SC_G, 40	; G dur=40
	s_keyon
	s_note_l SC_G, 10	; G dur=10
	s_instr 4
	s_note_l SC_G, 10	; G dur=10
	s_instr 1
	s_note SC_G    	; G
	s_ret
Snd_3e_6c23:
	s_note_l SC_E, 60	; E dur=60
	s_note SC_G    	; G
	s_note_l SC_F, 40	; F dur=40
	s_note SC_G    	; G
	s_note SC_B    	; B
	s_ret
Snd_3e_6c2b:
	s_oct 6	; block 5
	s_note SC_C    	; C
	s_note SC_REST 	; rest
	s_oct 5	; block 4
	s_note_l SC_C, 80	; C dur=80
	s_instr 3
	s_note SC_C    	; C
	s_instr 5
	s_note SC_C    	; C
	s_instr 1
	s_ret
Snd_3e_6c3a:
	s_oct 6	; block 5
	s_note_l SC_C, 60	; C dur=60
	s_oct 5	; block 4
	s_note_l SC_B, 10	; B dur=10
	s_note_l SC_A, 10	; A dur=10
	s_oct 6	; block 5
	s_note_l SC_D, 60	; D dur=60
	s_note SC_C    	; C
	s_ret
Snd_3e_6c47:
	s_oct 5	; block 4
	s_note_l SC_B, 80	; B dur=80
	s_instr 2
	s_note SC_B    	; B
	s_instr 3
	s_note SC_B    	; B
	s_instr 4
	s_note SC_B    	; B
	s_instr 5
	s_note SC_B    	; B
	s_instr 1
	s_ret
Snd_3e_6c59:
	s_oct 5	; block 4
	s_note_l SC_B, 60	; B dur=60
	s_oct 6	; block 5
	s_note SC_C    	; C
	s_note_l SC_D, 60	; D dur=60
	s_instr 4
	s_note SC_D    	; D
	s_instr 1
	s_ret
Snd_3e_6c66:
	s_oct 6	; block 5
	s_deflen 40
	s_note SC_D    	; D
	s_note SC_C    	; C
	s_note SC_D    	; D
	s_note SC_E    	; E
	s_ret
Snd_3e_6c6e:
	s_deflen 20
	s_note SC_D    	; D
	s_note SC_C    	; C
	s_oct 5	; block 4
	s_note SC_B    	; B
	s_note SC_A    	; A
	s_note_l SC_B, 80	; B dur=80
	s_ret
Snd_3e_6c78:
	s_note_l SC_G, 40	; G dur=40
	s_note_l SC_FS, 40	; F# dur=40
	s_note SC_G    	; G
	s_note SC_A    	; A
	s_note_l SC_B, 60	; B dur=60
	s_instr 4
	s_note_l SC_B, 10	; B dur=10
	s_instr 1
	s_ret
Snd_3e_6c87:
	s_pitchenv 1
	s_set10 0
	s_dutyenv 3
Snd_3e_6c8d:
	s_dutyenv 3
	s_instr 5
	s_deflen 20
	s_oct 5	; block 4
	s_note_l SC_C, 4	; C dur=4
	s_note_l SC_CS, 4	; C# dur=4
	s_note_l SC_D, 2	; D dur=2
	s_keyon
	s_deflen 20
	s_note_l SC_D, 30	; D dur=30
	s_instr 3
	s_call Snd_3e_6cd9
	s_call Snd_3e_6cf6
	s_call Snd_3e_6d11
	s_call Snd_3e_6d34
	s_call Snd_3e_6cd9
	s_call Snd_3e_6cf6
	s_call Snd_3e_6d43
	s_call Snd_3e_6d5b
	s_dutyenv 2
	s_call Snd_3e_6d70
	s_call Snd_3e_6d8c
	s_call Snd_3e_6dab
	s_call Snd_3e_6dd8
	s_call Snd_3e_6e04
	s_call Snd_3e_6e24
	s_call Snd_3e_6e3c
	s_call Snd_3e_6e4f
	s_call Snd_3e_6e60
	s_goto Snd_3e_6c8d
Snd_3e_6cd9:
	s_note_l SC_REST, 60	; rest dur=60
	s_oct 4	; block 3
	s_deflen 10
	s_note SC_E    	; E
	s_note SC_F    	; F
	s_note SC_E    	; E
	s_instr 4
	s_note SC_E    	; E
	s_instr 2
	s_oct 5	; block 4
	s_note SC_E    	; E
	s_instr 4
	s_note SC_E    	; E
	s_instr 2
	s_oct 4	; block 3
	s_note_l SC_E, 30	; E dur=30
	s_instr 4
	s_note SC_E    	; E
	s_instr 2
	s_ret
Snd_3e_6cf6:
	s_note_l SC_REST, 60	; rest dur=60
	s_oct 4	; block 3
	s_note SC_D    	; D
	s_note SC_E    	; E
	s_note SC_D    	; D
	s_instr 4
	s_note SC_D    	; D
	s_instr 2
	s_oct 5	; block 4
	s_note SC_D    	; D
	s_instr 4
	s_note SC_D    	; D
	s_instr 2
	s_oct 4	; block 3
	s_note_l SC_D, 30	; D dur=30
	s_instr 4
	s_note SC_D    	; D
	s_instr 2
	s_ret
Snd_3e_6d11:
	s_oct 5	; block 4
	s_note_l SC_C, 30	; C dur=30
	s_instr 4
	s_note SC_C    	; C
	s_instr 2
	s_oct 4	; block 3
	s_note SC_C    	; C
	s_note SC_D    	; D
	s_note SC_E    	; E
	s_instr 4
	s_note SC_E    	; E
	s_instr 2
	s_oct 5	; block 4
	s_note_l SC_D, 30	; D dur=30
	s_instr 4
	s_note SC_D    	; D
	s_instr 2
	s_oct 4	; block 3
	s_note SC_D    	; D
	s_note SC_G    	; G
	s_note SC_B    	; B
	s_instr 4
	s_note SC_B    	; B
	s_instr 2
	s_ret
Snd_3e_6d34:
	s_note_l SC_G, 60	; G dur=60
	s_oct 5	; block 4
	s_note SC_E    	; E
	s_note SC_F    	; F
	s_note_l SC_D, 60	; D dur=60
	s_keyon
	s_note SC_D    	; D
	s_instr 4
	s_note SC_D    	; D
	s_instr 2
	s_ret
Snd_3e_6d43:
	s_note_l SC_G, 30	; G dur=30
	s_instr 4
	s_note SC_G    	; G
	s_instr 2
	s_deflen 20
	s_oct 5	; block 4
	s_note SC_C    	; C
	s_oct 4	; block 3
	s_note SC_E    	; E
	s_note_l SC_B, 30	; B dur=30
	s_instr 4
	s_note_l SC_B, 10	; B dur=10
	s_instr 2
	s_note SC_G    	; G
	s_note SC_B    	; B
	s_ret
Snd_3e_6d5b:
	s_note SC_E    	; E
	s_instr 4
	s_note SC_E    	; E
	s_instr 2
	s_note SC_G    	; G
	s_instr 4
	s_note SC_G    	; G
	s_instr 2
	s_note SC_E    	; E
	s_instr 4
	s_note SC_E    	; E
	s_instr 2
	s_note SC_D    	; D
	s_note SC_C    	; C
	s_ret
Snd_3e_6d70:
	s_deflen 10
	s_note_l SC_REST, 40	; rest dur=40
	s_note_l SC_F, 30	; F dur=30
	s_instr 4
	s_note SC_F    	; F
	s_instr 2
	s_oct 4	; block 3
	s_note_l SC_A, 30	; A dur=30
	s_instr 4
	s_note SC_A    	; A
	s_instr 2
	s_oct 5	; block 4
	s_note_l SC_A, 30	; A dur=30
	s_instr 4
	s_note SC_A    	; A
	s_instr 2
	s_ret
Snd_3e_6d8c:
	s_note_l SC_G, 30	; G dur=30
	s_instr 4
	s_note SC_G    	; G
	s_instr 2
	s_note_l SC_D, 30	; D dur=30
	s_instr 4
	s_note SC_D    	; D
	s_instr 2
	s_oct 4	; block 3
	s_note_l SC_G, 30	; G dur=30
	s_instr 4
	s_note SC_G    	; G
	s_instr 2
	s_oct 5	; block 4
	s_note_l SC_G, 30	; G dur=30
	s_instr 4
	s_note SC_G    	; G
	s_instr 2
	s_ret
Snd_3e_6dab:
	s_note_l SC_REST, 20	; rest dur=20
	s_oct 4	; block 3
	s_note SC_A    	; A
	s_instr 4
	s_note SC_A    	; A
	s_instr 2
	s_oct 5	; block 4
	s_note SC_F    	; F
	s_instr 4
	s_note SC_F    	; F
	s_instr 2
	s_note SC_A    	; A
	s_instr 4
	s_note SC_A    	; A
	s_instr 2
	s_note_l SC_REST, 20	; rest dur=20
	s_oct 4	; block 3
	s_note SC_B    	; B
	s_instr 4
	s_note SC_B    	; B
	s_instr 2
	s_oct 5	; block 4
	s_note SC_A    	; A
	s_instr 4
	s_note SC_A    	; A
	s_instr 2
	s_note SC_B    	; B
	s_instr 4
	s_note SC_B    	; B
	s_instr 2
	s_ret
Snd_3e_6dd8:
	s_note_l SC_REST, 20	; rest dur=20
	s_oct 4	; block 3
	s_note SC_B    	; B
	s_instr 4
	s_note SC_B    	; B
	s_instr 2
	s_oct 5	; block 4
	s_note SC_G    	; G
	s_instr 4
	s_note SC_G    	; G
	s_instr 2
	s_note SC_A    	; A
	s_instr 4
	s_note SC_A    	; A
	s_instr 2
	s_note_l SC_REST, 20	; rest dur=20
	s_oct 5	; block 4
	s_note SC_B    	; B
	s_instr 4
	s_note SC_B    	; B
	s_instr 2
	s_note SC_G    	; G
	s_instr 4
	s_note SC_G    	; G
	s_instr 2
	s_note SC_D    	; D
	s_instr 4
	s_note SC_D    	; D
	s_instr 2
	s_ret
Snd_3e_6e04:
	s_note_l SC_A, 30	; A dur=30
	s_instr 4
	s_note SC_A    	; A
	s_instr 2
	s_note SC_F    	; F
	s_instr 4
	s_note SC_F    	; F
	s_instr 2
	s_note SC_G    	; G
	s_note SC_F    	; F
	s_note SC_B    	; B
	s_instr 4
	s_note SC_B    	; B
	s_instr 2
	s_note SC_G    	; G
	s_note SC_A    	; A
	s_note SC_B    	; B
	s_instr 4
	s_note SC_B    	; B
	s_instr 2
	s_note SC_G    	; G
	s_note SC_A    	; A
	s_ret
Snd_3e_6e24:
	s_deflen 20
	s_note_l SC_G, 40	; G dur=40
	s_note SC_D    	; D
	s_instr 4
	s_note SC_D    	; D
	s_instr 2
	s_note SC_D    	; D
	s_instr 4
	s_note SC_D    	; D
	s_instr 2
	s_oct 4	; block 3
	s_note SC_G    	; G
	s_instr 4
	s_note SC_G    	; G
	s_instr 2
	s_ret
Snd_3e_6e3c:
	s_oct 4	; block 3
	s_note SC_A    	; A
	s_note SC_B    	; B
	s_note SC_A    	; A
	s_instr 4
	s_note SC_A    	; A
	s_instr 2
	s_note SC_A    	; A
	s_note SC_B    	; B
	s_oct 5	; block 4
	s_note SC_C    	; C
	s_instr 4
	s_note SC_C    	; C
	s_instr 2
	s_ret
Snd_3e_6e4f:
	s_oct 4	; block 3
	s_note SC_G    	; G
	s_note SC_FS   	; F#
	s_note SC_G    	; G
	s_note SC_FS   	; F#
	s_note_l SC_G, 30	; G dur=30
	s_oct 5	; block 4
	s_note_l SC_F, 5	; F dur=5
	s_keyon
	s_note_l SC_FS, 5	; F# dur=5
	s_keyon
	s_note_l SC_G, 40	; G dur=40
	s_ret
Snd_3e_6e60:
	s_deflen 40
	s_oct 5	; block 4
	s_note SC_D    	; D
	s_note SC_CS   	; C#
	s_note SC_C    	; C
	s_oct 4	; block 3
	s_note_l SC_B, 60	; B dur=60
	s_instr 4
	s_note_l SC_B, 10	; B dur=10
	s_ret
Snd_3e_6e6e:
	s_pitchenv 0
	s_wave 2
	s_set10 0
	s_instr 19
Snd_3e_6e76:
	s_note_l SC_REST, 40	; rest dur=40
	s_call Snd_3e_6eae
	s_call Snd_3e_6eb8
	s_call Snd_3e_6ebd
	s_call Snd_3e_6ec2
	s_call Snd_3e_6eae
	s_call Snd_3e_6eb8
	s_call Snd_3e_6ec7
	s_call Snd_3e_6ece
	s_call Snd_3e_6ed4
	s_call Snd_3e_6ee1
	s_call Snd_3e_6ed4
	s_call Snd_3e_6ee1
	s_call Snd_3e_6ed4
	s_call Snd_3e_6ee1
	s_call Snd_3e_6ed4
	s_call Snd_3e_6eec
	s_call Snd_3e_6ef7
	s_goto Snd_3e_6e76
Snd_3e_6eae:
	s_deflen 40
	s_oct 4	; block 3
	s_note SC_C    	; C
	s_note SC_G    	; G
	s_oct 5	; block 4
	s_note SC_C    	; C
	s_oct 4	; block 3
	s_note SC_C    	; C
	s_ret
Snd_3e_6eb8:
	s_note SC_D    	; D
	s_note SC_G    	; G
	s_note SC_B    	; B
	s_note SC_G    	; G
	s_ret
Snd_3e_6ebd:
	s_note SC_C    	; C
	s_note SC_G    	; G
	s_note SC_D    	; D
	s_note SC_G    	; G
	s_ret
Snd_3e_6ec2:
	s_note SC_E    	; E
	s_note SC_G    	; G
	s_note SC_B    	; B
	s_note SC_D    	; D
	s_ret
Snd_3e_6ec7:
	s_note SC_C    	; C
	s_note SC_G    	; G
	s_oct 5	; block 4
	s_note SC_D    	; D
	s_oct 4	; block 3
	s_note SC_D    	; D
	s_ret
Snd_3e_6ece:
	s_note SC_C    	; C
	s_note SC_E    	; E
	s_note SC_G    	; G
	s_oct 3	; block 2
	s_note SC_G    	; G
	s_ret
Snd_3e_6ed4:
	s_deflen 20
	s_oct 4	; block 3
	s_note_l SC_F, 60	; F dur=60
	s_oct 5	; block 4
	s_note SC_F    	; F
	s_oct 4	; block 3
	s_note_l SC_FS, 60	; F# dur=60
	s_oct 5	; block 4
	s_note SC_FS   	; F#
	s_ret
Snd_3e_6ee1:
	s_oct 4	; block 3
	s_note_l SC_G, 60	; G dur=60
	s_oct 5	; block 4
	s_note SC_D    	; D
	s_oct 4	; block 3
	s_note_l SC_B, 40	; B dur=40
	s_note SC_A    	; A
	s_note SC_G    	; G
	s_ret
Snd_3e_6eec:
	s_oct 4	; block 3
	s_note_l SC_G, 60	; G dur=60
	s_oct 5	; block 4
	s_note SC_D    	; D
	s_oct 4	; block 3
	s_note_l SC_G, 40	; G dur=40
	s_note_l SC_REST, 40	; rest dur=40
	s_ret
Snd_3e_6ef7:
	s_note_l SC_G, 40	; G dur=40
	s_note_l SC_FS, 40	; F# dur=40
	s_note SC_G    	; G
	s_note SC_A    	; A
	s_note_l SC_B, 60	; B dur=60
	s_note_l SC_REST, 10	; rest dur=10
	s_ret
Snd_3e_6f02:
	s_pitchenv 0
	s_deflen 20
	s_oct 1	; block 0
	s_set10 0
	s_note_l SC_REST, 20	; rest dur=20
Snd_3e_6f0b:
	s_note_l SC_REST, 160	; rest dur=160
	s_note_l SC_REST, 160	; rest dur=160
	s_goto Snd_3e_6f0b
