; Sound id $31 (BGM) -- room transition (between floors)
; Bank $3e, ROM $559d-$5709. Auto-generated by tools/songdisasm.py --split; INCLUDEd by sound/bank_3e.asm into its $4b00 section.

; ===== sound id $31 =====
Snd_3e_559d:
	s_chan $f0, Snd_3e_55a9
	s_chan $f0, Snd_3e_5624
	s_chan $f0, Snd_3e_565c
	s_chan $f0, Snd_3e_56ae
Snd_3e_55a9:
	s_pitchenv 0
	s_instr 1
	s_note_l SC_REST, 14	; rest dur=14
	s_set10 0
	s_dutyenv 2
Snd_3e_55b3:
	s_call Snd_3e_55ce
	s_call Snd_3e_55e5
	s_call Snd_3e_55ce
	s_call Snd_3e_55e5
	s_call Snd_3e_55ce
	s_call Snd_3e_55e5
	s_call Snd_3e_55ce
	s_call Snd_3e_55fb
	s_goto Snd_3e_55b3
Snd_3e_55ce:
	s_deflen 7
	s_oct 3	; block 2
	s_note_l SC_REST, 14	; rest dur=14
	s_note SC_G    	; G
	s_note SC_A    	; A
	s_note SC_REST 	; rest
	s_oct 4	; block 3
	s_note SC_C    	; C
	s_note SC_REST 	; rest
	s_oct 3	; block 2
	s_note SC_G    	; G
	s_note SC_REST 	; rest
	s_note SC_A    	; A
	s_note SC_REST 	; rest
	s_oct 4	; block 3
	s_note SC_C    	; C
	s_note SC_DS   	; D#
	s_note SC_REST 	; rest
	s_note_l SC_DS, 14	; D# dur=14
	s_ret
Snd_3e_55e5:
	s_oct 3	; block 2
	s_note_l SC_REST, 14	; rest dur=14
	s_note SC_G    	; G
	s_note SC_A    	; A
	s_note SC_REST 	; rest
	s_oct 4	; block 3
	s_note SC_C    	; C
	s_note SC_REST 	; rest
	s_oct 3	; block 2
	s_note SC_G    	; G
	s_note SC_REST 	; rest
	s_note SC_A    	; A
	s_note SC_REST 	; rest
	s_oct 4	; block 3
	s_note SC_C    	; C
	s_oct 3	; block 2
	s_note SC_AS   	; A#
	s_note SC_GS   	; G#
	s_note SC_A    	; A
	s_note SC_G    	; G
	s_ret
Snd_3e_55fb:
	s_note_l SC_G, 14	; G dur=14
	s_note_l SC_REST, 14	; rest dur=14
	s_note SC_G    	; G
	s_note_l SC_A, 21	; A dur=21
	s_note SC_DS   	; D#
	s_note SC_D    	; D
	s_note SC_REST 	; rest
	s_note SC_C    	; C
	s_instr 3
	s_note SC_C    	; C
	s_instr 1
	s_note SC_C    	; C
	s_note SC_D    	; D
	s_note SC_C    	; C
	s_ret
Snd_3e_560f:	; unused/dead pattern
	s_instr 0
	s_note_l SC_F, 14	; F dur=14
	s_note_l SC_REST, 14	; rest dur=14
	s_note_l SC_DS, 28	; D# dur=28
	s_note SC_F    	; F
	s_note SC_DS   	; D#
	s_note SC_REST 	; rest
	s_note SC_F    	; F
	s_instr 3
	s_note SC_F    	; F
	s_note SC_REST 	; rest
	s_instr 0
	s_note_l SC_G, 14	; G dur=14
	s_ret
Snd_3e_5624:
	s_pitchenv 1
	s_note_l SC_REST, 28	; rest dur=28
	s_instr 3
	s_set10 0
	s_dutyenv 2
Snd_3e_562e:
	s_call Snd_3e_55ce
	s_call Snd_3e_55e5
	s_call Snd_3e_55ce
	s_call Snd_3e_55e5
	s_call Snd_3e_55ce
	s_call Snd_3e_55e5
	s_call Snd_3e_55ce
	s_call Snd_3e_564c
	s_goto Snd_3e_562e
Snd_3e_5649:	; unused/dead pattern
	s_note_l SC_REST, 112	; rest dur=112
	s_ret
Snd_3e_564c:
	s_note_l SC_G, 14	; G dur=14
	s_note SC_E    	; E
	s_note_l SC_DS, 21	; D# dur=21
	s_note SC_REST 	; rest
	s_note SC_DS   	; D#
	s_note SC_D    	; D
	s_note SC_REST 	; rest
	s_note SC_C    	; C
	s_note SC_REST 	; rest
	s_note SC_C    	; C
	s_note SC_D    	; D
	s_note_l SC_C, 14	; C dur=14
	s_ret
Snd_3e_565c:
	s_pitchenv 0
	s_note_l SC_REST, 14	; rest dur=14
	s_set10 0
Snd_3e_5662:
	s_call Snd_3e_567d
	s_call Snd_3e_567d
	s_call Snd_3e_567d
	s_call Snd_3e_567d
	s_call Snd_3e_567d
	s_call Snd_3e_567d
	s_call Snd_3e_567d
	s_call Snd_3e_5695
	s_goto Snd_3e_5662
Snd_3e_567d:
	s_wave 2
	s_deflen 7
	s_oct 3	; block 2
	s_instr 20
	s_note SC_C    	; C
	s_instr 19
	s_note SC_C    	; C
	s_deflen 14
	s_instr 20
	s_note SC_C    	; C
	s_note_l SC_E, 21	; E dur=21
	s_note_l SC_F, 21	; F dur=21
	s_note SC_E    	; E
	s_note SC_F    	; F
	s_note SC_G    	; G
	s_ret
Snd_3e_5695:
	s_deflen 7
	s_oct 3	; block 2
	s_instr 20
	s_note_l SC_C, 14	; C dur=14
	s_instr 19
	s_note SC_C    	; C
	s_note SC_REST 	; rest
	s_instr 20
	s_note SC_REST 	; rest
	s_note_l SC_G, 21	; G dur=21
	s_note SC_F    	; F
	s_note_l SC_E, 14	; E dur=14
	s_note_l SC_F, 14	; F dur=14
	s_note SC_E    	; E
	s_note_l SC_G, 14	; G dur=14
	s_ret
Snd_3e_56ae:
	s_pitchenv 0
	s_deflen 7
	s_oct 1	; block 0
	s_instr 14
	s_note SC_F    	; F
	s_note SC_F    	; F
	s_set10 0
Snd_3e_56b9:
	s_call Snd_3e_56d4
	s_call Snd_3e_56d4
	s_call Snd_3e_56d4
	s_call Snd_3e_56d4
	s_call Snd_3e_56d4
	s_call Snd_3e_56d4
	s_call Snd_3e_56d4
	s_call Snd_3e_56ec
	s_goto Snd_3e_56b9
Snd_3e_56d4:
	s_deflen 14
	s_instr 10
	s_note SC_F    	; F
	s_note SC_F    	; F
	s_instr 14
	s_note SC_F    	; F
	s_instr 10
	s_note_l SC_F, 21	; F dur=21
	s_note_l SC_F, 14	; F dur=14
	s_note_l SC_F, 7	; F dur=7
	s_instr 14
	s_note SC_F    	; F
	s_instr 10
	s_note SC_F    	; F
	s_ret
Snd_3e_56ec:
	s_deflen 14
	s_instr 14
	s_note SC_F    	; F
	s_note SC_REST 	; rest
	s_deflen 7
	s_instr 14
	s_note SC_F    	; F
	s_instr 10
	s_note_l SC_F, 21	; F dur=21
	s_instr 14
	s_note SC_F    	; F
	s_instr 10
	s_note_l SC_F, 14	; F dur=14
	s_note_l SC_F, 14	; F dur=14
	s_instr 14
	s_note SC_F    	; F
	s_note SC_F    	; F
	s_note SC_F    	; F
	s_ret
