; Naji's encounter portrait (shown during Naji's encounter); located by following the
; script's far-calls (tools/find_portraits.py). Same 20x11 single-blob layout as
; Kalum: 384 tiles -> VRAM bank 1 $8000 ($8800 signed addressing), arranged by the
; CopyBgMap descriptor below. Assembled from assets/portrait/naji/ via
; tools/pngasset.py (Makefile, output under build/assets/). The 6 BG + 6 OBJ
; palettes (loaded by Naji_BuildPortraitScene from $1a:$72e8/$7328) are carved here from the
; PNG's colour table.

SECTION "Naji graphics", ROMX

NajiPortraitTiles:
	INCBIN "assets/naji/tiles.bin"

NajiPortraitPaletteBg:
	INCBIN "assets/naji/palette_bg.bin"   ; 6 BG palettes (RGB555 LE)

DS $10

NajiPortraitPaletteObj:
	INCBIN "assets/naji/palette_obj.bin"  ; 6 OBJ palettes (RGB555 LE)

DS $10

NajiPortraitMapDesc:
	db 11, 20
	dw NajiPortraitAttrMap
	dw NajiPortraitIndexMap

NajiPortraitIndexMap:
	INCBIN "assets/naji/tilemap.bin"

NajiPortraitAttrMap:
	INCBIN "assets/naji/attrmap.bin"

; Naji's metasprite/patch overlay region: the talking eyes-animation frames (BG eye
; patches + their OBJ face-shadow overlays), the smile expression, and the vest and
; collar drawn every frame. Generated byte-exact from the layered source (assets/
; portrait/naji/sprites/*.png + sprites.yaml) by tools/pngasset.py -- see Naji_Render-
; PortraitTalking / Naji_RenderPortraitAlt ($18) for the per-block roles.
	INCLUDE "assets/naji/sprites.asm"   ; Naji_<role> blocks
