; Pashute's encounter portrait (shown during Pashute's encounter); located by following the
; script's far-calls (tools/find_portraits.py). Same 20x11 single-blob layout as
; Kalum: 384 tiles -> VRAM bank 1 $8000 ($8800 signed addressing), arranged by the
; CopyBgMap descriptor below. Assembled from assets/portrait/pashute/ via
; tools/pngasset.py (Makefile, output under build/assets/). The 6 BG + 6 OBJ
; palettes (loaded by Pashute_LoadShrineScene from $1b:$5800/$5840) are carved here
; from the PNG's colour table.

SECTION "Pashute graphics", ROMX

PashutePortraitTiles:
	INCBIN "assets/pashute/tiles.bin"

PashutePortraitPaletteBg:
	INCBIN "assets/pashute/palette_bg.bin"   ; 6 BG palettes (RGB555 LE)

Data_1b_5830:
	db $ff, $7f, $3e, $1b, $37, $01, $4b, $00, $ff, $7f, $94, $52, $4a, $29, $00, $00

PashutePortraitPaletteObj:
	INCBIN "assets/pashute/palette_obj.bin"  ; 6 OBJ palettes (RGB555 LE)

Data_1b_5870:
	db $e0, $03, $e0, $03, $e0, $03, $e0, $03, $00, $00, $00, $00, $00, $00, $00, $00

PashutePortraitMapDesc:
	db 11, 20
	dw PashutePortraitAttrMap
	dw PashutePortraitIndexMap

PashutePortraitIndexMap:
	INCBIN "assets/pashute/tilemap.bin"

PashutePortraitAttrMap:
	INCBIN "assets/pashute/attrmap.bin"

; Pashute's metasprite/patch overlay region: the neutral eyes blink-animation
; frames, shoulders, collar, and the sad/shocked expressions. Generated byte-exact
; from the layered source (assets/portrait/pashute/sprites/*.png + sprites.yaml) by
; tools/pngasset.py -- see that manifest for the per-block roles.
Data_1b_5a3e:
	INCBIN "assets/pashute/sprites.bin"

; Trailing 64 bytes ($5bdd-$5c1c): not yet structured (intro-scene data + zero pad).
Data_1b_5bdd:
	db $44, $18, $df, $3a, $b0, $45, $ed, $20, $44, $18, $44, $18, $44, $18, $44, $18
	db $44, $18, $44, $18, $b0, $45, $df, $3a, $44, $18, $44, $18, $44, $18, $b0, $45
	db $44, $18, $44, $18, $b0, $45, $ed, $20, $b0, $45, $44, $18, $44, $18, $df, $3a
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00

SECTION "analyzed_06dc1d", ROMX[$5c1d], BANK[$1b]

Data_1b_5c1d:
	db $ff, $03, $5a, $24, $aa, $28, $68, $00, $00, $7c, $7b, $6b, $7b, $3a, $68, $00
	db $1f, $7c, $7b, $6b, $f2, $51, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00

SECTION "analyzed_06dc5d", ROMX[$5c5d], BANK[$1b]

Data_1b_5c5d:
	INCBIN "gfx/raw/Data_1b_5c5d.2bpp", 0, 1424

Data_1b_61ed:
	db $00, $10, $00, $78, $00, $f8, $00, $f0, $00, $c0

SECTION "analyzed_06e45d", ROMX[$645d], BANK[$1b]

Data_1b_645d:
	INCBIN "gfx/raw/Data_1b_645d.2bpp", 0, 3696

Data_1b_72cd:
	db $00, $00, $00, $00, $00, $00, $04, $04, $13, $13, $44, $44, $30, $30

SECTION "analyzed_06f45d", ROMX[$745d], BANK[$1b]

Data_1b_745d:
	db $ec, $28, $75, $3a, $7b, $0e, $b4, $01, $ec, $28, $75, $3a, $de, $63, $13, $49
	db $ec, $28, $13, $72, $7b, $0e, $b4, $01, $ec, $28, $13, $49, $7b, $0e, $b4, $01
	db $ec, $28, $13, $49, $13, $72, $b4, $01, $cb, $24, $13, $49, $13, $72, $3d, $77

SECTION "analyzed_06f49d", ROMX[$749d], BANK[$1b]

Data_1b_749d:
	db $e0, $03, $1f, $43, $fc, $21, $de, $63, $00, $7c, $1f, $43, $cc, $01, $f0, $12
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00

SECTION "analyzed_06f4dd", ROMX[$74dd], BANK[$1b]

Data_1b_74dd:
	db $0b, $14, $bf, $75, $e3, $74, $80, $88, $90, $98, $a0, $a8, $b0, $b8, $c0, $c8
	db $d0, $d8, $e0, $e8, $f0, $f8, $00, $08, $10, $18, $81, $89, $91, $99, $a1, $a9
	db $b1, $b9, $c1, $c9, $d1, $d9, $e1, $e9, $f1, $f9, $01, $09, $11, $19, $82, $8a
	db $92, $9a, $a2, $aa, $b2, $ba, $c2, $ca, $d2, $da, $e2, $ea, $f2, $fa, $02, $0a
	db $12, $1a, $83, $8b, $93, $9b, $a3, $ab, $b3, $bb, $c3, $cb, $d3, $db, $e3, $eb
	db $f3, $fb, $03, $0b, $13, $1b, $84, $8c, $94, $9c, $a4, $ac, $b4, $bc, $c4, $cc
	db $d4, $dc, $e4, $ec, $f4, $fc, $04, $0c, $14, $1c, $85, $8d, $95, $9d, $a5, $ad
	db $b5, $bd, $c5, $cd, $d5, $dd, $e5, $ed, $f5, $fd, $05, $0d, $15, $1d, $86, $8e
	db $96, $9e, $a6, $ae, $b6, $be, $c6, $ce, $d6, $de, $e6, $ee, $f6, $fe, $06, $0e
	db $16, $1e, $87, $8f, $97, $9f, $a7, $af, $b7, $bf, $c7, $cf, $d7, $df, $e7, $ef
	db $f7, $ff, $07, $0f, $17, $1f, $20, $28, $30, $38, $40, $48, $50, $58, $23, $2b
	db $33, $3b, $43, $4b, $53, $5b, $26, $2e, $36, $3e, $21, $29, $31, $39, $41, $49
	db $51, $59, $24, $2c, $34, $3c, $44, $4c, $54, $5c, $27, $2f, $37, $3f, $22, $2a
	db $32, $3a, $42, $4a, $52, $5a, $25, $2d, $35, $3d, $45, $4d, $55, $5d, $46, $47
	db $4e, $4f, $0d, $0d, $0d, $0d, $0d, $0d, $0d, $0d, $0d, $0d, $0d, $0d, $0d, $0d
	db $0d, $0d, $0d, $0d, $0d, $0d, $0d, $0d, $0d, $0d, $0d, $0d, $0d, $0d, $0d, $0d
	db $0d, $0d, $0d, $0d, $0d, $0d, $0d, $0d, $0d, $0d, $0d, $0d, $0d, $0d, $0d, $0a
	db $0a, $0a, $0a, $0a, $0d, $0d, $0d, $0d, $0d, $0d, $0d, $0d, $0d, $0d, $0d, $0d
	db $0d, $0d, $0c, $0a, $0a, $0a, $0a, $0a, $0d, $0d, $0d, $0d, $0d, $0d, $0d, $0d
	db $0d, $0d, $0d, $0d, $0d, $0d, $0c, $0b, $0b, $0b, $0b, $0a, $0d, $0d, $0d, $0d
	db $0d, $0d, $0d, $0d, $0d, $0d, $0d, $0d, $0d, $0d, $0b, $08, $08, $08, $08, $0b
	db $0b, $0d, $0d, $0d, $0d, $0d, $0d, $0d, $0d, $0d, $0d, $0d, $0d, $0d, $0d, $08
	db $08, $08, $08, $0b, $0b, $0d, $0d, $0d, $0d, $0d, $0d, $0d, $0d, $0d, $0d, $0d
	db $0d, $0d, $0d, $08, $08, $08, $08, $0b, $0b, $0d, $0d, $0d, $0d, $0d, $0d, $0d
	db $0d, $0d, $0d, $0d, $0d, $0d, $09, $09, $09, $09, $09, $09, $09, $0d, $0d, $0d
	db $0d, $0d, $0d, $0d, $0d, $0d, $0d, $0d, $0d, $09, $09, $09, $09, $09, $09, $09
	db $09, $09, $0d, $0d, $0d, $0d, $0d, $0d, $0d, $0d, $0d, $0d, $0d, $09, $09, $09
	db $09, $09, $09, $09, $09, $09, $0d, $0d, $0d, $0d, $0d, $0d, $0d, $0d, $01, $04
	db $a5, $76, $a1, $76, $ad, $b5, $bd, $c5, $08, $08, $08, $08, $0f, $00, $00, $14
	db $09, $00, $08, $16, $09, $00, $10, $18, $09, $00, $18, $1a, $09, $00, $20, $14
	db $09, $10, $00, $1c, $09, $10, $08, $1e, $09, $10, $10, $20, $09, $10, $18, $22
	db $09, $10, $20, $24, $09, $20, $00, $26, $08, $20, $08, $28, $08, $20, $10, $2a
	db $08, $20, $18, $2c, $08, $20, $20, $2e, $09, $01, $04, $f0, $76, $ec, $76, $56
	db $57, $be, $c5, $08, $08, $08, $08, $0f, $00, $00, $14, $09, $00, $08, $16, $09
	db $00, $10, $18, $09, $00, $18, $1a, $09, $00, $20, $14, $09, $10, $00, $1c, $09
	db $10, $08, $1e, $09, $10, $10, $20, $09, $10, $18, $22, $09, $10, $20, $24, $09
	db $20, $00, $26, $08, $20, $08, $36, $08, $20, $10, $38, $08, $20, $18, $3a, $08
	db $20, $20, $2e, $09, $01, $04, $3b, $77, $37, $77, $56, $57, $be, $c5, $08, $08
	db $08, $08, $0f, $00, $00, $14, $09, $00, $08, $16, $09, $00, $10, $18, $09, $00
	db $18, $1a, $09, $00, $20, $14, $09, $10, $00, $1c, $09, $10, $08, $1e, $09, $10
	db $10, $20, $09, $10, $18, $22, $09, $10, $20, $24, $09, $20, $00, $26, $08, $20
	db $08, $3c, $08, $20, $10, $3e, $08, $20, $18, $40, $08, $20, $20, $2e, $09, $03
	db $00, $00, $30, $08, $00, $08, $32, $08, $00, $10, $34, $08, $0a, $00, $00, $00
	db $09, $00, $08, $02, $09, $00, $10, $04, $09, $00, $18, $06, $09, $00, $20, $08
	db $09, $10, $00, $0a, $09, $10, $08, $0c, $09, $10, $10, $0e, $09, $10, $18, $10
	db $09, $10, $20, $12, $09, $03, $03, $c1, $77, $b8, $77, $ad, $b5, $bd, $ae, $b6
	db $be, $af, $b7, $bf, $08, $08, $08, $08, $08, $08, $08, $08, $08, $03, $03, $d9
	db $77, $d0, $77, $ad, $b5, $bd, $ae, $b6, $be, $af, $5e, $bf, $08, $08, $08, $08
	db $08, $08, $08, $08, $08, $0f, $00, $00, $14, $09, $00, $08, $16, $09, $00, $10
	db $18, $09, $00, $18, $1a, $09, $00, $20, $14, $09, $10, $00, $1c, $09, $10, $08
	db $1e, $09, $10, $10, $20, $09, $10, $18, $22, $09, $10, $20, $24, $09, $20, $00
	db $26, $08, $20, $08, $42, $08, $20, $10, $44, $08, $20, $18, $46, $08, $20, $20
	db $2e, $09, $03, $00, $00, $48, $08, $00, $08, $4a, $08, $00, $10, $4c, $08, $03
	db $03, $3b, $78, $32, $78, $5f, $62, $65, $60, $63, $66, $61, $64, $67, $08, $08
	db $08, $08, $08, $08, $08, $08, $08, $0f, $00, $00, $14, $09, $00, $08, $16, $09
	db $00, $10, $18, $09, $00, $18, $1a, $09, $00, $20, $14, $09, $10, $00, $1c, $09
	db $10, $08, $1e, $09, $10, $10, $20, $09, $10, $18, $22, $09, $10, $20, $24, $09
	db $20, $00, $26, $08, $20, $08, $4e, $08, $20, $10, $50, $08, $20, $18, $52, $08
	db $20, $20, $2e, $09, $03, $00, $00, $54, $08, $00, $08, $56, $08, $00, $10, $58
	db $08, $44, $18, $75, $3a, $3b, $22, $2f, $31, $44, $18, $11, $4e, $de, $63, $44
	db $18, $44, $18, $44, $18, $3b, $22, $2f, $31, $44, $18, $44, $18, $3b, $22, $2f
	db $31, $44, $18, $44, $18, $44, $18, $2f, $31, $44, $18, $44, $18, $44, $18, $44
	db $18

SECTION "analyzed_06f8ce", ROMX[$78ce], BANK[$1b]

Data_1b_78ce:
	db $e0, $03, $fe, $46, $b1, $49, $de, $63, $00, $7c, $fe, $46, $69, $3d, $8c, $26

