; Floor 1 (record 0) -- 11 wide x 10 tall. Tower floor data; see docs/floor_data.md.

INCLUDE "room.inc"

SECTION "room01", ROMX[$4000], BANK[$2d]
Room01:
    ; header: Type, SpawnX, SpawnY, Unknown[3], Height, Width
    db $61, 2, 7, $00, $00, $01, 10, 11

    ; collision grid (10 rows x 11)
    db COLL_BORDER, COLL_BORDER, COLL_BORDER, COLL_BORDER, COLL_BORDER, COLL_BORDER, COLL_BORDER, COLL_BORDER, COLL_BORDER, COLL_BORDER, COLL_BORDER
    db COLL_BORDER, COLL_WALL  , COLL_WALL  , COLL_WALL  , COLL_WALL  , COLL_WALL  , COLL_WALL  , COLL_WALL  , COLL_WALL  , COLL_WALL  , COLL_BORDER
    db COLL_BORDER, COLL_WALL  , COLL_FLOOR , COLL_FLOOR , COLL_FLOOR , COLL_FLOOR , COLL_FLOOR , COLL_FLOOR , COLL_FLOOR , COLL_WALL  , COLL_BORDER
    db COLL_BORDER, COLL_WALL  , COLL_FLOOR , COLL_FLOOR , COLL_FLOOR , COLL_FLOOR , COLL_FLOOR , COLL_FLOOR , COLL_WALL  , COLL_WALL  , COLL_BORDER
    db COLL_BORDER, COLL_WALL  , COLL_FLOOR , COLL_CRATE , COLL_FLOOR , COLL_FLOOR , COLL_FLOOR , COLL_CRATE , COLL_WALL  , COLL_WALL  , COLL_BORDER
    db COLL_BORDER, COLL_WALL  , COLL_FLOOR , COLL_FLOOR , COLL_FLOOR , COLL_FLOOR , COLL_CRATE , COLL_WALL  , COLL_WALL  , COLL_WALL  , COLL_BORDER
    db COLL_BORDER, COLL_WALL  , COLL_FLOOR , COLL_FLOOR , COLL_FLOOR , COLL_CRATE , COLL_WALL  , COLL_WALL  , COLL_WALL  , COLL_WALL  , COLL_BORDER
    db COLL_BORDER, COLL_WALL  , COLL_FLOOR , COLL_FLOOR , COLL_WALL  , COLL_WALL  , COLL_WALL  , COLL_WALL  , COLL_WALL  , COLL_WALL  , COLL_BORDER
    db COLL_BORDER, COLL_WALL  , COLL_WALL  , COLL_WALL  , COLL_WALL  , COLL_WALL  , COLL_WALL  , COLL_WALL  , COLL_WALL  , COLL_WALL  , COLL_BORDER
    db COLL_BORDER, COLL_BORDER, COLL_BORDER, COLL_BORDER, COLL_BORDER, COLL_BORDER, COLL_BORDER, COLL_BORDER, COLL_BORDER, COLL_BORDER, COLL_BORDER

    ; piece/object grid (10 rows x 11)
    db COLL_BORDER, COLL_BORDER, COLL_BORDER, COLL_BORDER, COLL_BORDER, COLL_BORDER, COLL_BORDER, COLL_BORDER, COLL_BORDER, COLL_BORDER, COLL_BORDER
    db COLL_BORDER, COLL_FLOOR , COLL_FLOOR , COLL_FLOOR , COLL_FLOOR , COLL_FLOOR , COLL_FLOOR , COLL_FLOOR , COLL_FLOOR , COLL_FLOOR , COLL_BORDER
    db COLL_BORDER, COLL_FLOOR , COLL_FLOOR , COLL_FLOOR , COLL_FLOOR , COLL_FLOOR , COLL_FLOOR , COLL_FLOOR , TILE_EXIT  , COLL_FLOOR , COLL_BORDER
    db COLL_BORDER, COLL_FLOOR , COLL_FLOOR , ITEM_FLAG | ITEM_OPEN | ITEM_GOLD_KEY, COLL_FLOOR , COLL_FLOOR , COLL_FLOOR , COLL_FLOOR , COLL_FLOOR , COLL_FLOOR , COLL_BORDER
    db COLL_BORDER, COLL_FLOOR , COLL_FLOOR , ITEM_FLAG | ITEM_OPEN | ITEM_SILVER_MEDAL, COLL_FLOOR , COLL_FLOOR , COLL_FLOOR , COLL_FLOOR , COLL_FLOOR , COLL_FLOOR , COLL_BORDER
    db COLL_BORDER, COLL_FLOOR , COLL_FLOOR , COLL_FLOOR , COLL_FLOOR , ITEM_FLAG | ITEM_OPEN | ITEM_BOMB_SMALL, COLL_FLOOR , COLL_FLOOR , COLL_FLOOR , COLL_FLOOR , COLL_BORDER
    db COLL_BORDER, COLL_FLOOR , COLL_FLOOR , COLL_FLOOR , COLL_FLOOR , COLL_FLOOR , COLL_FLOOR , COLL_FLOOR , COLL_FLOOR , COLL_FLOOR , COLL_BORDER
    db COLL_BORDER, COLL_FLOOR , COLL_FLOOR , COLL_FLOOR , COLL_FLOOR , COLL_FLOOR , COLL_FLOOR , COLL_FLOOR , COLL_FLOOR , COLL_FLOOR , COLL_BORDER
    db COLL_BORDER, COLL_FLOOR , COLL_FLOOR , COLL_FLOOR , COLL_FLOOR , COLL_FLOOR , COLL_FLOOR , COLL_FLOOR , COLL_FLOOR , COLL_FLOOR , COLL_BORDER
    db COLL_BORDER, COLL_BORDER, COLL_BORDER, COLL_BORDER, COLL_BORDER, COLL_BORDER, COLL_BORDER, COLL_BORDER, COLL_BORDER, COLL_BORDER, COLL_BORDER

    ; arr1: per-floor sprite/species table (indexed by a monster's GfxIndex)
    db MONSTER_TACOPI, MONSTER_JELL, MONSTER_NAGA, MONSTER_TIGER

    ; arr2: 9 monster slots (Monster: Col,Row,Type,Param,GfxIndex); GfxIndex INERT = empty
.monsters
    db 6, 4, $22, $00, 1   ; JELL (MonsterSprites[1]) at col 6, row 4
    db INERT, INERT, INERT, $01, INERT
    db INERT, INERT, INERT, $01, INERT
    db INERT, INERT, INERT, $01, INERT
    db INERT, INERT, INERT, $01, INERT
    db INERT, INERT, INERT, $01, INERT
    db INERT, INERT, INERT, $01, INERT
    db INERT, INERT, INERT, $01, INERT
    db INERT, INERT, INERT, $01, INERT
    assert @ - .monsters == sizeof_Monster * 9

    ; arr3: 8 spawner slots (Spawner: Col,Row,P0,P1,P2,GfxIndex); all inert here
.spawners
    ds sizeof_Spawner * 8, INERT
    assert @ - .spawners == sizeof_Spawner * 8
