; Song/SFX data for sound driver bank $3f (ids $00-$2e).
; The $4b00 pointer table + one INCLUDE per song (address order).
; Auto-generated by tools/songdisasm.py --split.

SECTION "snd_data_3f", ROMX[$4b00], BANK[$3f]

Snd_3f_4b00:		; $4b00 song pointer table (256 entries)
	s_songptr Snd_3f_4d00	; id $00
	s_songptr Snd_3f_4d0f	; id $01
	s_songptr Snd_3f_4d39	; id $02
	s_songptr Snd_3f_4d5f	; id $03
	s_songptr Snd_3f_4d79	; id $04
	s_songptr Snd_3f_4d95	; id $05
	s_songptr Snd_3f_4dd0	; id $06
	s_songptr Snd_3f_4e15	; id $07
	s_songptr Snd_3f_4e52	; id $08
	s_songptr Snd_3f_4eaa	; id $09
	s_songptr Snd_3f_4f05	; id $0a
	s_songptr Snd_3f_4f90	; id $0b
	s_songptr Snd_3f_4faf	; id $0c
	s_songptr Snd_3f_5031	; id $0d
	s_songptr Snd_3f_505b	; id $0e
	s_songptr Snd_3f_5085	; id $0f
	s_songptr Snd_3f_5098	; id $10
	s_songptr Snd_3f_50b1	; id $11
	s_songptr Snd_3f_5198	; id $12
	s_songptr Snd_3f_524c	; id $13
	s_songptr Snd_3f_5283	; id $14
	s_songptr Snd_3f_52ce	; id $15
	s_songptr Snd_3f_534b	; id $16
	s_songptr Snd_3f_539e	; id $17
	s_songptr Snd_3f_5433	; id $18
	s_songptr Snd_3f_547a	; id $19
	s_songptr Snd_3f_54b7	; id $1a
	s_songptr Snd_3f_5514	; id $1b
	s_songptr Snd_3f_55a3	; id $1c
	s_songptr Snd_3f_55ef	; id $1d
	s_songptr Snd_3f_55fe	; id $1e
	s_songptr Snd_3f_5630	; id $1f
	s_songptr Snd_3f_5652	; id $20
	s_songptr Snd_3f_5689	; id $21
	s_songptr Snd_3f_56bd	; id $22
	s_songptr Snd_3f_56ee	; id $23
	s_songptr Snd_3f_5724	; id $24
	s_songptr Snd_3f_5760	; id $25
	s_songptr Snd_3f_579c	; id $26
	s_songptr Snd_3f_57fb	; id $27
	s_songptr Snd_3f_580a	; id $28
	s_songptr Snd_3f_581b	; id $29
	s_songptr Snd_3f_5ca3	; id $2a
	s_songptr Snd_3f_60bf	; id $2b
	s_songptr Snd_3f_660d	; id $2c
	s_songptr Snd_3f_6a2f	; id $2d
	s_songptr Snd_3f_6eb6	; id $2e
	REPT 209  ; ids $2f-$ff -> id $00 (default)
		s_songptr Snd_3f_4d00
	ENDR

INCLUDE "sound/sfx/sfx_00.asm"
INCLUDE "sound/sfx/sfx_01.asm"
INCLUDE "sound/sfx/sfx_02.asm"
INCLUDE "sound/sfx/sfx_03.asm"
INCLUDE "sound/sfx/sfx_04.asm"
INCLUDE "sound/sfx/sfx_05.asm"
INCLUDE "sound/sfx/sfx_06.asm"
INCLUDE "sound/sfx/sfx_07.asm"
INCLUDE "sound/sfx/sfx_08.asm"
INCLUDE "sound/sfx/sfx_09.asm"
INCLUDE "sound/sfx/sfx_0a.asm"
INCLUDE "sound/sfx/sfx_0b.asm"
INCLUDE "sound/sfx/sfx_0c.asm"
INCLUDE "sound/sfx/sfx_0d.asm"
INCLUDE "sound/sfx/sfx_0e.asm"
INCLUDE "sound/sfx/sfx_0f.asm"
INCLUDE "sound/sfx/sfx_10.asm"
INCLUDE "sound/sfx/sfx_11.asm"
INCLUDE "sound/sfx/sfx_12.asm"
INCLUDE "sound/sfx/sfx_13.asm"
INCLUDE "sound/sfx/sfx_14.asm"
INCLUDE "sound/sfx/sfx_15.asm"
INCLUDE "sound/sfx/sfx_16.asm"
INCLUDE "sound/sfx/sfx_17.asm"
INCLUDE "sound/sfx/sfx_18.asm"
INCLUDE "sound/sfx/sfx_19.asm"
INCLUDE "sound/sfx/sfx_1a.asm"
INCLUDE "sound/sfx/sfx_1b.asm"
INCLUDE "sound/sfx/sfx_1c.asm"
INCLUDE "sound/sfx/sfx_1d.asm"
INCLUDE "sound/sfx/sfx_1e.asm"
INCLUDE "sound/sfx/sfx_1f.asm"
INCLUDE "sound/sfx/sfx_20.asm"
INCLUDE "sound/sfx/sfx_21.asm"
INCLUDE "sound/sfx/sfx_22.asm"
INCLUDE "sound/sfx/sfx_23.asm"
INCLUDE "sound/sfx/sfx_24.asm"
INCLUDE "sound/sfx/sfx_25.asm"
INCLUDE "sound/sfx/sfx_26.asm"
INCLUDE "sound/sfx/sfx_27.asm"
INCLUDE "sound/bgm/bgm_28.asm"
INCLUDE "sound/bgm/bgm_29.asm"
INCLUDE "sound/bgm/bgm_2a.asm"
INCLUDE "sound/bgm/bgm_2b.asm"
INCLUDE "sound/bgm/bgm_2c.asm"
INCLUDE "sound/bgm/bgm_2d.asm"
INCLUDE "sound/bgm/bgm_2e.asm"
