; Sound id $10 (SFX) -- ?
; Bank $3f, ROM $5098-$50b0. Auto-generated by tools/songdisasm.py --split; INCLUDEd by sound/bank_3f.asm into its $4b00 section.

; ===== sound id $10 =====
Snd_3f_5098:
	s_chan $00, Snd_3f_50b0
	s_chan $00, Snd_3f_50b0
	s_chan $00, Snd_3f_50b0
	s_chan $f0, Snd_3f_50a4
Snd_3f_50a4:
	s_pitchenv 0
	s_oct 1	; block 0
	s_deflen 3
	s_instr 13
	s_note SC_E    	; E
	s_note SC_F    	; F
	s_note_l SC_G, 36	; G dur=36
	s_end
Snd_3f_50b0:
	s_end
