; Sound id $16 (SFX) -- ?
; Bank $3f, ROM $534b-$539d. Auto-generated by tools/songdisasm.py --split; INCLUDEd by sound/bank_3f.asm into its $4b00 section.

; ===== sound id $16 =====
Snd_3f_534b:
	s_chan $00, Snd_3f_539d
	s_chan $f0, Snd_3f_5357
	s_chan $00, Snd_3f_539d
	s_chan $00, Snd_3f_539d
Snd_3f_5357:
	s_deflen 1
	s_pitchenv 2
	s_set10 0
	s_dutyenv 5
	s_oct 3	; block 2
	s_instr 0
	s_note SC_A    	; A
	s_oct 4	; block 3
	s_note SC_A    	; A
	s_oct 3	; block 2
	s_note SC_B    	; B
	s_oct 4	; block 3
	s_note SC_B    	; B
	s_oct 3	; block 2
	s_note SC_B    	; B
	s_oct 4	; block 3
	s_note SC_D    	; D
	s_oct 3	; block 2
	s_instr 1
	s_note SC_A    	; A
	s_oct 4	; block 3
	s_note SC_A    	; A
	s_oct 3	; block 2
	s_note SC_B    	; B
	s_oct 4	; block 3
	s_note SC_B    	; B
	s_instr 3
	s_oct 3	; block 2
	s_note SC_B    	; B
	s_oct 4	; block 3
	s_note SC_D    	; D
	s_oct 4	; block 3
	s_instr 2
	s_note SC_A    	; A
	s_oct 3	; block 2
	s_note SC_B    	; B
	s_oct 4	; block 3
	s_note SC_D    	; D
	s_note SC_E    	; E
	s_oct 3	; block 2
	s_instr 1
	s_note SC_B    	; B
	s_oct 4	; block 3
	s_instr 2
	s_note SC_D    	; D
	s_note SC_F    	; F
	s_note SC_A    	; A
	s_note SC_B    	; B
	s_oct 5	; block 4
	s_instr 3
	s_note SC_C    	; C
	s_note SC_D    	; D
	s_note SC_E    	; E
	s_note SC_E    	; E
	s_instr 5
	s_note SC_D    	; D
	s_note SC_C    	; C
	s_end
Snd_3f_539d:
	s_end
