; Sound id $1d (SFX) -- ?
; Bank $3f, ROM $55ef-$55fd. Auto-generated by tools/songdisasm.py --split; INCLUDEd by sound/bank_3f.asm into its $4b00 section.

; ===== sound id $1d =====
Snd_3f_55ef:
	s_chan $ff, Snd_3f_55fb
	s_chan $ff, Snd_3f_55fb
	s_chan $ff, Snd_3f_55fb
	s_chan $ff, Snd_3f_55fb
Snd_3f_55fb:
	s_note_l SC_REST, 1	; rest dur=1
	s_end
