; Sound id $04 (SFX) -- UI cursor move
; Bank $3f, ROM $4d79-$4d94. Auto-generated by tools/songdisasm.py --split; INCLUDEd by sound/bank_3f.asm into its $4b00 section.

; ===== sound id $04 =====
Snd_3f_4d79:
	s_chan $00, Snd_3f_4d94
	s_chan $f0, Snd_3f_4d85
	s_chan $00, Snd_3f_4d94
	s_chan $00, Snd_3f_4d94
Snd_3f_4d85:
	s_pitchenv 0
	s_set10 0
	s_dutyenv 5
	s_instr 1
	s_oct 6	; block 5
	s_note_l SC_G, 2	; G dur=2
	s_oct 7	; block 6
	s_note_l SC_G, 4	; G dur=4
	s_end
Snd_3f_4d94:
	s_end
