; Sound id $1b (SFX) -- ?
; Bank $3f, ROM $5514-$55a2. Auto-generated by tools/songdisasm.py --split; INCLUDEd by sound/bank_3f.asm into its $4b00 section.

; ===== sound id $1b =====
Snd_3f_5514:
	s_chan $f0, Snd_3f_5520
	s_chan $f0, Snd_3f_5554
	s_chan $f0, Snd_3f_557b
	s_chan $00, Snd_3f_55a2
Snd_3f_5520:
	s_pitchenv 0
	s_set10 0
	s_dutyenv 1
	s_instr 1
	s_deflen 2
	s_instr 4
	s_oct 5	; block 4
	s_note_l SC_A, 2	; A dur=2
	s_oct 6	; block 5
	s_note SC_C    	; C
	s_note SC_E    	; E
	s_note SC_G    	; G
	s_note SC_C    	; C
	s_oct 6	; block 5
	s_note SC_GS   	; G#
	s_note SC_A    	; A
	s_note SC_AS   	; A#
	s_note SC_B    	; B
	s_oct 5	; block 4
	s_note SC_C    	; C
	s_note SC_CS   	; C#
	s_note SC_D    	; D
	s_note SC_DS   	; D#
	s_note SC_E    	; E
	s_note SC_F    	; F
	s_note SC_FS   	; F#
	s_note SC_G    	; G
	s_instr 5
	s_oct 7	; block 6
	s_note SC_GS   	; G#
	s_note SC_A    	; A
	s_note SC_AS   	; A#
	s_note SC_B    	; B
	s_oct 8	; block 7
	s_note SC_C    	; C
	s_note SC_CS   	; C#
	s_note SC_D    	; D
	s_note SC_DS   	; D#
	s_note SC_E    	; E
	s_note SC_F    	; F
	s_note SC_FS   	; F#
	s_note SC_G    	; G
	s_note SC_REST 	; rest
	s_end
Snd_3f_5554:
	s_pitchenv 0
	s_set10 0
	s_dutyenv 2
	s_oct 6	; block 5
	s_deflen 6
	s_instr 2
	s_note_l SC_A, 6	; A dur=6
	s_deflen 6
	s_oct 7	; block 6
	s_note SC_C    	; C
	s_note SC_E    	; E
	s_note SC_G    	; G
	s_instr 3
	s_deflen 6
	s_oct 6	; block 5
	s_note SC_A    	; A
	s_oct 7	; block 6
	s_note SC_C    	; C
	s_note SC_E    	; E
	s_note SC_G    	; G
	s_instr 4
	s_oct 7	; block 6
	s_note SC_A    	; A
	s_oct 8	; block 7
	s_note SC_C    	; C
	s_note SC_E    	; E
	s_note SC_G    	; G
	s_note SC_REST 	; rest
	s_end
Snd_3f_557b:
	s_pitchenv 0
	s_set10 0
	s_wave 8
	s_instr 20
	s_note_l SC_REST, 6	; rest dur=6
	s_deflen 3
	s_oct 7	; block 6
	s_note SC_C    	; C
	s_oct 6	; block 5
	s_note SC_B    	; B
	s_note SC_A    	; A
	s_note SC_G    	; G
	s_note SC_F    	; F
	s_note SC_E    	; E
	s_note SC_D    	; D
	s_note SC_C    	; C
	s_oct 5	; block 4
	s_note SC_B    	; B
	s_note SC_A    	; A
	s_note SC_G    	; G
	s_note SC_F    	; F
	s_note SC_E    	; E
	s_note SC_D    	; D
	s_note SC_C    	; C
	s_oct 4	; block 3
	s_note SC_B    	; B
	s_note SC_A    	; A
	s_note SC_G    	; G
	s_note SC_F    	; F
	s_note SC_E    	; E
	s_note SC_D    	; D
	s_note SC_C    	; C
	s_end
Snd_3f_55a2:
	s_end
