; Sound id $25 (SFX) -- player lift
; Bank $3f, ROM $5760-$579b. Auto-generated by tools/songdisasm.py --split; INCLUDEd by sound/bank_3f.asm into its $4b00 section.

; ===== sound id $25 =====
Snd_3f_5760:
	s_chan $00, Snd_3f_579b
	s_chan $f0, Snd_3f_576c
	s_chan $00, Snd_3f_579b
	s_chan $00, Snd_3f_579b
Snd_3f_576c:
	s_set10 0
	s_dutyenv 5
	s_deflen 1
	s_pitchenv 0
	s_instr 0
	s_call Snd_3f_577f
	s_instr 5
	s_call Snd_3f_577f
	s_end
Snd_3f_577f:
	s_oct 4	; block 3
	s_note SC_C    	; C
	s_keyon
	s_note SC_D    	; D
	s_keyon
	s_note SC_E    	; E
	s_keyon
	s_note SC_F    	; F
	s_keyon
	s_note SC_G    	; G
	s_keyon
	s_note SC_A    	; A
	s_keyon
	s_note SC_B    	; B
	s_oct 5	; block 4
	s_keyon
	s_note SC_C    	; C
	s_keyon
	s_note SC_D    	; D
	s_keyon
	s_note SC_E    	; E
	s_keyon
	s_note SC_F    	; F
	s_keyon
	s_note SC_G    	; G
	s_keyon
	s_note SC_A    	; A
	s_ret
Snd_3f_579b:
	s_end
