; Sound id $0f (SFX) -- ?
; Bank $3f, ROM $5085-$5097. Auto-generated by tools/songdisasm.py --split; INCLUDEd by sound/bank_3f.asm into its $4b00 section.

; ===== sound id $0f =====
Snd_3f_5085:
	s_chan $00, Snd_3f_5097
	s_chan $00, Snd_3f_5097
	s_chan $00, Snd_3f_5097
	s_chan $f0, Snd_3f_5091
Snd_3f_5091:
	s_oct 1	; block 0
	s_instr 0
	s_note_l SC_F, 24	; F dur=24
	s_end
Snd_3f_5097:
	s_end
