#!/usr/bin/env python3
"""Generate docs/bankmap.md from the linker map (build/rom.gbc.map): a per-bank index of
sections, their sizes, and which source file each comes from. Answers "what's in bank
$NN" and "where does $NN:$AAAA live" without grepping section addresses.

`analyzed_HEX` sections are address-named carve residue (still-undigested ROM); their
per-bank count is the "left to understand" gauge. Run by `make` after linking.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MAP = ROOT / "build" / "rom.gbc.map"
SRC = ROOT / "src"
OUT = ROOT / "docs" / "bankmap.md"

BANK_RE = re.compile(r"^(ROM0|ROMX|WRAM0|WRAMX|HRAM|SRAM|VRAM|OAM) bank #(\d+):")
SEC_RE = re.compile(
    r"^\tSECTION: \$([0-9A-Fa-f]+)-\$([0-9A-Fa-f]+) \(\$([0-9A-Fa-f]+) bytes\) \[\"(.*)\"\]"
)
SRC_SEC_RE = re.compile(r'^\s*SECTION\s+"([^"]+)"')

# Region -> bank capacity in bytes (for free-space calc); others left blank.
CAP = {"ROM0": 0x4000, "ROMX": 0x4000}


def section_to_file() -> dict[str, str]:
    """Map each SECTION name to its source file (relative to repo root)."""
    out: dict[str, str] = {}
    for f in sorted(SRC.rglob("*.asm")):
        rel = str(f.relative_to(ROOT))
        for ln in f.read_text(errors="replace").splitlines():
            m = SRC_SEC_RE.match(ln)
            if m:
                out.setdefault(m.group(1), rel)
    return out


def parse_map(text: str):
    """[(region, bank_num, [ (start, end, size, name) ... ]) ...] in file order."""
    banks = []
    cur = None
    for ln in text.splitlines():
        mb = BANK_RE.match(ln)
        if mb:
            cur = (mb.group(1), int(mb.group(2)), [])
            banks.append(cur)
            continue
        ms = SEC_RE.match(ln)
        if ms and cur is not None:
            cur[2].append(
                (int(ms.group(1), 16), int(ms.group(2), 16), int(ms.group(3), 16), ms.group(4))
            )
    return banks


def bank_label(region: str, num: int) -> str:
    if region in ("ROM0", "ROMX"):
        return f"${num:02x}"
    return f"{region}#{num}"


def files_for(secs, s2f) -> list[str]:
    """Distinct source files in a bank, ordered by total bytes (dominant first)."""
    tot: dict[str, int] = {}
    for _s, _e, size, name in secs:
        tot[s2f.get(name, "?")] = tot.get(s2f.get(name, "?"), 0) + size
    return [Path(f).name for f in sorted(tot, key=lambda f: -tot[f])]


def main() -> int:
    if not MAP.exists():
        sys.exit(f"bankmap: {MAP} not found (build the ROM first)")
    s2f = section_to_file()
    banks = parse_map(MAP.read_text())
    summary = []
    for ln in MAP.read_text().splitlines():
        if ln.startswith("SUMMARY:"):
            continue
        if ln.startswith("\t") and "used" in ln:
            summary.append(ln.strip())
        elif summary:
            break

    out = []
    out.append("# Bank map\n")
    out.append(
        "_Auto-generated by `tools/bankmap.py` from `build/rom.gbc.map`; `make` "
        "regenerates it — do not edit by hand._\n"
    )
    out.append(
        "Per-bank index of sections + their source file. `analyzed_HEX` sections are "
        "address-named carve residue (still-undigested ROM); the **analyzed** column is "
        "the per-bank \"left to understand\" gauge.\n"
    )
    out.append("## Usage\n")
    out.append("```\n" + "\n".join(summary) + "\n```\n")

    # At-a-glance index
    out.append("## Banks at a glance\n")
    out.append("| bank | region | used | free | sections | analyzed | source file(s) |")
    out.append("|---|---|--:|--:|--:|--:|---|")
    for region, num, secs in banks:
        if not secs:
            continue
        used = sum(s[2] for s in secs)
        cap = CAP.get(region)
        free = f"{cap - used}" if cap else "—"
        nanalyzed = sum(1 for s in secs if s[3].startswith("analyzed_"))
        files = ", ".join(files_for(secs, s2f)) or "—"
        out.append(
            f"| {bank_label(region, num)} | {region} | {used} | {free} | "
            f"{len(secs)} | {nanalyzed} | {files} |"
        )

    # Per-bank detail
    out.append("\n## Sections by bank\n")
    for region, num, secs in banks:
        if not secs:
            continue
        nanalyzed = sum(1 for s in secs if s[3].startswith("analyzed_"))
        out.append(f"### {bank_label(region, num)} — {region}"
                   f" ({len(secs)} sections, {nanalyzed} analyzed)\n")
        out.append("| range | size | file | section |")
        out.append("|---|--:|---|---|")
        for start, end, size, name in sorted(secs):
            f = s2f.get(name, "?")
            fname = Path(f).name if f != "?" else "?"
            out.append(f"| ${start:04x}-${end:04x} | {size} | {fname} | {name} |")
        out.append("")

    OUT.write_text("\n".join(out) + "\n")
    nsec = sum(len(s) for _, _, s in banks)
    nbank = sum(1 for _, _, s in banks if s)
    print(f"bankmap: wrote {OUT.relative_to(ROOT)} ({nbank} banks, {nsec} sections)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
