; Auto-generated by tools/extract.py. Do not edit.

SECTION "analyzed_000000", ROM0[$0000]

Section_000000:
	db $85, $6f

SECTION "analyzed_000018", ROM0[$0018]

Section_000018:
	ld a, [hl+]
	ld h, [hl]
	ld l, a
	ret

SECTION "analyzed_000020", ROM0[$0020]

Section_000020:
	ld a, [$c284]
	and a
	ret

SECTION "analyzed_000030", ROM0[$0030]

Section_000030:
	add a, e
	ld e, a
	ret nc
	inc d
	ret

SECTION "analyzed_000040", ROM0[$0040]

Section_000040:
	jp $c28d

SECTION "analyzed_000150", ROM0[$0150]

Section_000150:
	ld [$c283], a
	di
	ld sp, $de00
	call $01e2
	xor a
	ld [$c285], a
	call $01ca
	call $018f
	call $0a30
	call $0bd7
	ld a, $c7
	ldh [$ff40], a
	ei
	push af
	ld a, $00
	call $0a85
	pop af
	push af
	ld a, $28
	call $0a63
	pop af
	ld c, $0a
	push bc
	call $02e6
	pop bc
	dec c
	jr nz, $017f
	call $35c8

SECTION "analyzed_00018f", ROM0[$018f]

Section_00018f:
	xor a
	ldh [$ff0f], a
	ldh [$ffff], a
	ld de, $c28d
	ld c, $05
	ld b, $03
	ld hl, $01c6
	ld a, [hl+]
	ld [de], a
	inc de
	dec b
	jr nz, $019e
	dec c
	jr nz, $0199
	ld a, [$c284]
	cp $01
	jr z, $01b3
	ld hl, $02a4
	jr $01b6

SECTION "analyzed_0001b6", ROM0[$01b6]

Section_0001b6:
	ld a, l
	ld [$c28e], a
	ld a, h
	ld [$c28f], a
	xor a
	ldh [$ff0f], a
	ld a, $03
	ldh [$ffff], a
	ret

SECTION "analyzed_0001c6", ROM0[$01c6]

Section_0001c6:
	db $c3, $c9, $01

SECTION "analyzed_0001ca", ROM0[$01ca]

Section_0001ca:
	ld c, $80
	ld b, $0a
	ld hl, $01d8
	ld a, [hl+]
	ldh [c], a
	inc c
	dec b
	jr nz, $01d1
	ret

SECTION "analyzed_0001d8", ROM0[$01d8]

Section_0001d8:
	db $3e, $c0, $e0, $46, $3e, $40, $3d, $20, $fd, $c9

SECTION "analyzed_0001e2", ROM0[$01e2]

Section_0001e2:
	ld a, [$c283]
	cp $11
	jr z, $01ee
	xor a
	ld [$c284], a
	ret

SECTION "analyzed_0002a4", ROM0[$02a4]

Section_0002a4:
	push af
	push bc
	push de
	push hl
	call $ff80
	ld a, $01
	ld [$c286], a
	ei
	call $0a45
	pop hl
	pop de
	pop bc
	pop af
	ret

SECTION "analyzed_0002d1", ROM0[$02d1]

Section_0002d1:
	ldh a, [$ff40]
	rla
	ret nc
	ldh a, [$ff41]
	and $03
	cp $03
	jr nz, $02d5
	ldh a, [$ff41]
	and $03
	cp $03
	jr z, $02dd
	ret
	ld a, [$c287]
	inc a
	ld [$c287], a
	ldh a, [$ffff]
	rra
	ret nc
	rst $20
	jr z, $02fc

SECTION "analyzed_0002fc", ROM0[$02fc]

Section_0002fc:
	halt
	nop
	ld a, [$c286]
	and a
	jr z, $02fc
	xor a
	ld [$c286], a
	rst $20
	ret nz
	ret

SECTION "analyzed_000348", ROM0[$0348]

Section_000348:
	rst $20
	jr nz, $0361
	di
	ldh a, [$ff41]
	bit 1, a
	jr nz, $034c
	ld a, [hl]
	ld [de], a
	ldh a, [$ff41]
	bit 1, a
	jr nz, $034c
	ei
	inc hl
	inc de
	dec c
	jr nz, $034b
	ret

SECTION "analyzed_000394", ROM0[$0394]

Section_000394:
	ld a, c
	and c
	jr z, $039e
	call $0348
	ld a, b
	and b
	ret z
	call $0348
	dec b
	jr nz, $039e
	ret

SECTION "analyzed_000a30", ROM0[$0a30]

Section_000a30:
	ld a, [$7fff]
	push af
	ld a, $3f
	ld [$2fff], a
	call $4000
	pop af
	ld [$2fff], a
	xor a
	ld [$c28c], a
	ret
	ld a, [$7fff]
	push af
	ld a, $3f
	ld [$2fff], a
	call $4003
	pop af
	ld [$2fff], a
	ret

SECTION "analyzed_000a63", ROM0[$0a63]

Section_000a63:
	ld [$c28c], a
	push bc
	push de
	push hl
	ld c, a
	ld b, $00
	ld a, [$7fff]
	push af
	ld hl, $0ad8
	add hl, bc
	add hl, bc
	ld a, [hl+]
	ld [$2fff], a
	ld a, [hl]
	call $4006
	pop af
	ld [$2fff], a
	pop hl
	pop de
	pop bc
	ret
	push bc
	push de
	push hl
	ld c, a
	ld b, $00
	ld a, [$7fff]
	push af
	ld hl, $0ad8
	add hl, bc
	add hl, bc
	ld a, [hl+]
	ld [$2fff], a
	ld a, [hl]
	call $4009
	pop af
	ld [$2fff], a
	pop hl
	pop de
	pop bc
	ret

SECTION "analyzed_000ad8", ROM0[$0ad8]

Section_000ad8:
	db $3f, $00

SECTION "analyzed_000b28", ROM0[$0b28]

Section_000b28:
	db $3f, $28

SECTION "analyzed_000b4e", ROM0[$0b4e]

Section_000b4e:
	ld a, [hl+]
	ld b, a
	ld a, [hl+]
	ld c, a
	rst $20
	jr z, $0b65

SECTION "analyzed_000b65", ROM0[$0b65]

Section_000b65:
	inc hl
	inc hl
	rst $18
	push bc
	ld b, $00
	push de
	call $0394
	pop de
	ld a, $20
	rst $30
	pop bc
	dec b
	jr nz, $0b68
	ret

SECTION "analyzed_000bc9", ROM0[$0bc9]

Section_000bc9:
	ld hl, $ffa8
	ld a, b
	ld [hl+], a
	ld [hl], c
	ret

SECTION "analyzed_000bd7", ROM0[$0bd7]

Section_000bd7:
	ld bc, $0000
	call $0bc9
	ld c, $28
	ld hl, $fe00
	call $02d1
	xor a
	ld [hl+], a
	inc hl
	inc hl
	inc hl
	dec c
	jr nz, $0be6
	ld a, $00
	ldh [$ffa7], a
	ldh a, [$ffa7]
	cp $a0
	jr nc, $0c04
	ld l, a
	ld h, $c0
	xor a
	ld [hl+], a
	inc hl
	inc hl
	inc hl
	ld a, l
	cp $a0
	jr c, $0bfa
	ld a, $00
	ldh [$ffa7], a
	ret

SECTION "analyzed_001863", ROM0[$1863]

Section_001863:
	xor a
	ld [$c289], a
	ld [$c28a], a
	ldh [$ffa8], a
	ldh [$ffa9], a
	ldh [$ff43], a
	ldh [$ff42], a
	ret

SECTION "analyzed_0035c8", ROM0[$35c8]

Section_0035c8:
	call $1863
	ld a, $30
	ld [$2fff], a
	call $547f

SECTION "analyzed_0035e9", ROM0[$35e9]

Section_0035e9:
	ld a, [$7fff]
	push af
	ld a, b
	ld [$2fff], a
	call $0b4e
	pop af
	ld [$2fff], a
	ret

SECTION "analyzed_00392d", ROM0[$392d]

Section_00392d:
	ld [$c29c], a
	ld a, [$7fff]
	push af
	ld a, [$c29c]
	ld [$2fff], a
	call $0394
	pop af
	ld [$2fff], a
	ret

SECTION "analyzed_007fff", ROMX[$7fff], BANK[$01]

Section_007fff:
	db $01

SECTION "analyzed_09dade", ROMX[$5ade], BANK[$27]

Section_09dade:
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $82, $82, $42, $c2, $46, $42, $04, $04, $0c, $04, $18, $08, $30, $70, $00, $00
	db $fe, $fe, $82, $82, $82, $82, $82, $82, $82, $82, $fe, $fe, $02, $82, $00, $00
	db $00, $00, $00, $00, $18, $18, $18, $18, $00, $00, $00, $00, $00, $00, $00, $00
	db $7c, $7c, $20, $20, $fe, $fe, $20, $20, $20, $20, $20, $32, $1e, $1e, $00, $00
	db $c0, $c0, $22, $62, $02, $02, $02, $02, $02, $06, $04, $0c, $f8, $f8, $00, $00
	db $44, $44, $be, $be, $84, $84, $84, $84, $9c, $bc, $a4, $a6, $5a, $da, $00, $00
	db $40, $40, $7e, $7e, $44, $44, $84, $c4, $04, $04, $08, $0c, $70, $78, $00, $00
	db $00, $00, $00, $00, $00, $00, $fe, $fe, $00, $00, $00, $00, $00, $00, $00, $00
	db $20, $20, $20, $20, $40, $60, $44, $44, $82, $c6, $82, $82, $fe, $fe, $00, $00
	db $10, $10, $fe, $fe, $10, $10, $54, $54, $54, $54, $92, $d6, $92, $92, $00, $00
	db $04, $04, $04, $04, $04, $04, $08, $1c, $e8, $f8, $08, $08, $08, $08, $00, $00
	db $20, $20, $fe, $fe, $22, $22, $22, $22, $22, $22, $42, $62, $c6, $46, $00, $00
	db $7c, $7c, $00, $00, $fe, $fe, $02, $02, $02, $02, $04, $06, $38, $3c, $00, $00
	db $44, $44, $44, $44, $fe, $fe, $44, $44, $4c, $4c, $40, $60, $7e, $3e, $00, $00
	db $20, $20, $20, $20, $60, $20, $60, $40, $f0, $70, $d2, $d2, $de, $8c, $00, $00
	db $30, $20, $1e, $1e, $10, $10, $10, $10, $f8, $7c, $9c, $96, $62, $f2, $00, $00
	db $38, $38, $00, $00, $7e, $7c, $46, $82, $02, $02, $04, $06, $38, $3c, $00, $00
	db $fe, $fe, $0a, $0c, $38, $10, $20, $20, $20, $20, $38, $10, $0c, $0c, $00, $00
	db $04, $04, $fe, $fe, $38, $1c, $24, $24, $1c, $3c, $04, $04, $3c, $78, $00, $00
	db $80, $80, $80, $80, $80, $80, $82, $82, $c6, $82, $64, $c6, $38, $78, $00, $00
	db $04, $06, $18, $0c, $18, $30, $60, $e0, $30, $18, $06, $0c, $02, $06, $00, $00
	db $40, $40, $fc, $fc, $40, $40, $5e, $de, $c0, $80, $98, $90, $9e, $8e, $00, $00
	db $10, $10, $fe, $fe, $18, $08, $4c, $24, $46, $42, $60, $40, $7c, $3c, $00, $00
	db $40, $40, $86, $84, $86, $82, $82, $82, $82, $a2, $e2, $a2, $e0, $40, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $0a, $0a, $05, $05, $00, $00
	db $3c, $7e, $66, $c3, $db, $b9, $a1, $a1, $a1, $a1, $db, $b9, $66, $c3, $3c, $7e
	db $00, $00, $7e, $7e, $18, $18, $18, $18, $18, $18, $18, $18, $18, $18, $18, $18
	db $00, $00, $7f, $7f, $60, $60, $60, $60, $7e, $7e, $60, $60, $60, $60, $7f, $7f
	db $00, $00, $3e, $1e, $21, $73, $60, $60, $60, $60, $60, $60, $21, $73, $3e, $1e
	db $00, $00, $41, $63, $63, $77, $7f, $7f, $7f, $7f, $7f, $6b, $6b, $63, $63, $63
	db $00, $00, $1c, $3e, $22, $63, $63, $63, $63, $63, $63, $63, $22, $63, $1c, $3e
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $0d, $0d, $0d, $0d, $0d, $0d, $0d, $0d, $0d, $0d, $07, $07
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $02, $01
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $9e, $9e, $b6, $b6, $b6, $b6, $b6, $b6, $b6, $b6, $9e, $9e
	db $06, $06, $3c, $3c, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $05, $03, $29, $1e, $80, $ff
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $c0, $c0, $c0, $c0, $f0, $f0, $d8, $d8, $f8, $d8, $df, $d8, $d9, $d8, $db, $d9
	db $03, $00, $07, $00, $07, $00, $07, $00, $0f, $00, $0f, $00, $1e, $00, $1e, $00
	db $1d, $00, $1d, $00, $1d, $00, $1d, $00, $1d, $00, $1d, $00, $0f, $00, $0d, $00
	db $0d, $00, $05, $00, $0a, $00, $10, $00, $20, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $38, $00, $b7, $70, $70, $90, $e0, $10, $88, $30
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $20, $03, $10, $0f, $00, $1f, $00, $7f, $00, $ff, $00, $ff, $00, $ff, $50
	db $f5, $08, $f4, $08, $ec, $10, $e8, $10, $58, $20, $50, $20, $d1, $20, $f1, $00
	db $e1, $00, $e3, $00, $e3, $00, $e7, $00, $c7, $00, $c6, $00, $c1, $00, $c7, $00
	db $c7, $00, $c7, $00, $c4, $00, $c7, $00, $43, $00, $23, $00, $03, $00, $03, $00
	db $03, $00, $03, $00, $01, $00, $01, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $01, $00, $09, $07
	db $00, $1f, $20, $1f, $80, $7f, $00, $e0, $0e, $07, $c3, $1f, $06, $01, $03, $00
	db $00, $00, $00, $00, $00, $00, $00, $04, $00, $08, $08, $00, $04, $00, $1f, $00
	db $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $f8, $07, $cc, $33, $8e, $71
	db $ce, $31, $41, $38, $65, $18, $64, $18, $74, $08, $36, $08, $36, $08, $16, $08
	db $14, $08, $87, $08, $87, $08, $87, $08, $0f, $00, $4f, $00, $df, $00, $df, $00
	db $ff, $00, $bf, $00, $7f, $00, $bf, $00, $bf, $00, $9f, $00, $3f, $00, $ff, $00
	db $f7, $00, $f3, $00, $ff, $00, $ff, $00, $ff, $00, $3f, $00, $0f, $00, $01, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $a0, $c0, $e8, $f0
	db $0a, $fc, $76, $80, $ce, $00, $1c, $00, $80, $00, $d0, $e0, $68, $f0, $84, $78
	db $00, $00, $00, $00, $00, $00, $00, $00, $07, $00, $00, $00, $fe, $00, $81, $7e
	db $f8, $07, $fe, $01, $ff, $00, $f0, $0f, $00, $ff, $82, $6d, $00, $f6, $40, $b7
	db $08, $f3, $20, $d9, $20, $d9, $95, $68, $94, $68, $94, $68, $5c, $20, $5e, $20
	db $1e, $20, $0e, $00, $20, $00, $7f, $00, $7f, $00, $7c, $00, $83, $00, $ff, $00
	db $f7, $00, $f7, $00, $e0, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00
	db $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $9f, $00, $fe, $01, $fd, $02
	db $3c, $00, $00, $00, $00, $00, $10, $00, $1d, $00, $30, $08, $60, $10, $c2, $20
	db $a4, $42, $80, $46, $49, $06, $10, $0f, $10, $0f, $20, $1f, $00, $3f, $40, $3f
	db $00, $00, $00, $00, $00, $00, $3f, $00, $f8, $07, $7e, $01, $07, $00, $f9, $00
	db $13, $ec, $1c, $ff, $7f, $ff, $3f, $ff, $1f, $ff, $8f, $ff, $47, $ff, $27, $7f
	db $a3, $3f, $1b, $b7, $17, $bb, $09, $bb, $09, $9b, $4b, $99, $40, $89, $c5, $08
	db $cd, $00, $4d, $00, $0c, $00, $d8, $00, $9d, $00, $7b, $04, $f3, $0c, $f5, $0e
	db $ad, $1e, $5e, $3f, $ce, $3f, $ee, $1f, $ee, $1f, $ee, $1f, $cf, $3e, $cd, $3e
	db $df, $3c, $d9, $3e, $df, $3a, $9b, $76, $b9, $66, $3a, $c4, $5d, $80, $1a, $01
	db $17, $03, $2c, $07, $10, $0f, $c0, $3f, $00, $ff, $00, $fe, $81, $7c, $02, $79
	db $53, $20, $29, $00, $14, $00, $e7, $10, $8f, $60, $1f, $e0, $3f, $c0, $3f, $c0
	db $00, $00, $00, $00, $00, $00, $e0, $00, $e8, $f0, $34, $f8, $cd, $3e, $f8, $07
	db $3e, $01, $9f, $00, $4f, $80, $a7, $c0, $c7, $e0, $d3, $e0, $e5, $f0, $e7, $f0
	db $7a, $f1, $72, $f9, $b2, $79, $b1, $78, $e9, $30, $c9, $30, $c8, $30, $d8, $20
	db $d8, $20, $70, $00, $4c, $18, $04, $24, $54, $04, $70, $04, $d8, $2c, $dc, $28
	db $c0, $38, $c8, $30, $90, $20, $a0, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $80, $00, $80, $40, $c0, $e0
	db $60, $f0, $78, $f0, $60, $ee, $c0, $9d, $0e, $31, $f8, $03, $f4, $03, $e0, $07
	db $d8, $07, $20, $0f, $60, $0f, $d0, $0f, $c0, $1f, $a8, $17, $a0, $1f, $90, $2f
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $80, $00
	db $00, $80, $40, $80, $a0, $40, $80, $60, $90, $60, $c0, $30, $c8, $30, $e0, $18
	db $f4, $08, $70, $8c, $78, $84, $3a, $c4, $3e, $c0, $1e, $e0, $1e, $e0, $1e, $e0
	db $3f, $e0, $3f, $e0, $2f, $f0, $1f, $f0, $97, $78, $9f, $78, $0f, $78, $0f, $7c
	db $4d, $3e, $06, $3f, $07, $3f, $27, $1f, $03, $1f, $11, $0e, $02, $0c, $08, $00
	db $01, $00, $03, $00, $07, $00, $0f, $00, $0b, $00, $0b, $00, $05, $00, $05, $00
	db $01, $00, $78, $00, $84, $7b, $01, $ff, $03, $ff, $0b, $ff, $09, $ff, $1b, $fd
	db $1b, $fd, $3a, $fd, $3b, $fc, $77, $f8, $66, $f9, $64, $fb, $88, $f7, $81, $ff
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $80, $00, $40, $00, $30, $00, $0c, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $80, $00, $80, $80, $80, $80, $00, $00, $00, $00, $00, $00, $00, $80
	db $00, $80, $00, $80, $40, $80, $80, $40, $80, $40, $80, $40, $80, $40, $c0, $00
	db $c0, $20, $e0, $00, $f0, $00, $70, $80, $98, $c0, $e0, $c0, $c0, $e0, $d0, $e0
	db $d0, $e0, $e0, $f0, $f8, $f0, $f8, $f0, $f0, $f8, $f8, $f8, $fc, $f8, $f4, $f8
	db $03, $00, $03, $00, $03, $00, $03, $00, $03, $00, $03, $00, $03, $00, $03, $00
	db $03, $00, $02, $00, $02, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $e0, $00, $3c, $c0, $0f, $f0, $0f, $f0
	db $fd, $00, $fe, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00
	db $ff, $00, $07, $00, $00, $00, $00, $00, $0f, $00, $7f, $00, $c0, $3f, $00, $ff
	db $00, $fc, $00, $fc, $00, $fc, $02, $fc, $00, $fe, $00, $fe, $00, $fe, $00, $fe
	db $00, $fe, $00, $fe, $f0, $0e, $04, $02, $1a, $00, $88, $f8, $b8, $f8, $f8, $f8
	db $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $e0, $00, $00, $00
	db $00, $00, $00, $00, $60, $00, $81, $7e, $00, $ff, $00, $7f, $40, $7f, $40, $7f
	db $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $1f, $00
	db $03, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $01, $00, $83, $00
	db $ee, $01, $ad, $42, $4e, $21, $ad, $12, $d6, $09, $e2, $05, $e9, $02, $e5, $08
	db $e2, $0d, $fc, $03, $07, $00, $00, $00, $80, $00, $e1, $1f, $03, $ff, $0f, $ff
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $0a, $07, $04, $0f, $0c, $06, $08, $06, $04, $02, $04, $00, $01, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $01, $f8, $0f, $80, $7e, $00, $f0, $00, $c0, $00, $00, $00, $80, $00, $60, $00
	db $03, $00, $47, $00, $bf, $40, $1e, $e0, $19, $60, $07, $00, $03, $0c, $10, $02
	db $18, $00, $1c, $00, $1f, $00, $1f, $00, $0f, $00, $0f, $00, $0f, $00, $07, $00
	db $07, $00, $07, $00, $03, $00, $01, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $88, $30, $90, $20, $00, $00, $00, $00, $00, $00, $07, $00, $0f, $00, $00, $00
	db $81, $00, $80, $00, $30, $00, $70, $00, $e0, $00, $d4, $00, $34, $00, $e8, $00
	db $30, $00, $00, $00, $00, $00, $80, $00, $f0, $00, $fc, $00, $ff, $00, $ff, $00
	db $ff, $00, $ff, $00, $ff, $00, $fe, $00, $7c, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $01, $00, $01, $00, $01, $00
	db $01, $00, $01, $00, $01, $00, $01, $00, $01, $00, $01, $00, $01, $00, $03, $00
	db $03, $00, $07, $00, $0f, $00, $0f, $00, $3f, $00, $ff, $00, $ff, $00, $ff, $00
	db $fe, $00, $71, $00, $0f, $00, $01, $00, $00, $00, $00, $00, $00, $00, $03, $00
	db $0f, $00, $0f, $00, $07, $00, $07, $00, $03, $00, $01, $00, $01, $00, $81, $00
	db $81, $00, $81, $00, $01, $00, $00, $00, $00, $00, $01, $00, $01, $00, $02, $01
	db $03, $00, $05, $02, $09, $06, $00, $0f, $07, $08, $1f, $00, $1f, $00, $1f, $00
	db $3f, $00, $3f, $00, $3f, $00, $7f, $00, $7f, $00, $7f, $00, $ff, $00, $ff, $00
	db $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00
	db $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00
	db $c2, $3c, $f2, $0c, $ff, $00, $fe, $01, $ff, $00, $ff, $00, $ff, $00, $ff, $00
	db $7f, $00, $ff, $00, $3f, $00, $e3, $00, $01, $00, $00, $00, $40, $00, $f0, $00
	db $fc, $00, $fe, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00
	db $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $00, $ff, $1f, $e0
	db $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00
	db $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00
	db $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00
	db $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00
	db $80, $7f, $80, $7f, $43, $3c, $6f, $10, $9f, $00, $a7, $40, $d9, $30, $cd, $3e
	db $e3, $1f, $f0, $0f, $fc, $03, $fe, $01, $ff, $00, $ff, $00, $3f, $00, $1f, $00
	db $0f, $00, $07, $00, $81, $00, $c0, $00, $e0, $00, $f0, $00, $f8, $00, $fc, $00
	db $fe, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00
	db $fe, $01, $f8, $07, $ff, $00, $ff, $00, $fe, $01, $f0, $0f, $0f, $f0, $ff, $00
	db $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00
	db $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00
	db $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00
	db $7f, $80, $ff, $00, $ff, $00, $ff, $00, $fe, $00, $fe, $00, $fe, $00, $7c, $00
	db $0d, $80, $a1, $c0, $29, $f0, $1a, $fc, $00, $ff, $c0, $3f, $e0, $1f, $f0, $0f
	db $fc, $03, $ff, $00, $ff, $00, $ff, $00, $7f, $00, $1f, $00, $07, $00, $01, $00
	db $00, $00, $80, $00, $e0, $00, $fe, $00, $fc, $00, $f2, $0d, $b8, $07, $c4, $1b
	db $24, $c9, $15, $e8, $f0, $03, $82, $79, $02, $f9, $3d, $c0, $fc, $00, $fd, $00
	db $fd, $02, $f8, $01, $fe, $00, $ff, $00, $ff, $00, $ff, $00, $fe, $01, $fc, $00
	db $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $fe, $00, $ff, $00, $ff, $00
	db $ff, $00, $ff, $00, $fd, $00, $fe, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00
	db $91, $2f, $20, $1f, $21, $1f, $5e, $3f, $7c, $3f, $40, $7f, $bc, $43, $7f, $80
	db $c0, $3f, $80, $7f, $00, $ff, $23, $1f, $05, $03, $21, $c0, $08, $f0, $02, $fc
	db $01, $fe, $00, $ff, $c0, $3f, $f9, $06, $ff, $00, $ff, $00, $ff, $00, $ff, $00
	db $7f, $00, $3c, $03, $07, $00, $00, $00, $00, $00, $40, $80, $c0, $00, $60, $80
	db $20, $c0, $00, $e0, $90, $60, $48, $b0, $20, $d8, $14, $e8, $90, $6c, $22, $0c
	db $80, $4e, $40, $be, $a1, $5e, $30, $0f, $28, $57, $50, $2f, $a8, $17, $14, $eb
	db $08, $37, $c4, $0b, $d2, $05, $cc, $13, $d4, $0b, $6a, $95, $04, $3b, $d2, $0d
	db $e4, $03, $e6, $09, $6a, $85, $25, $4a, $8a, $35, $d5, $0a, $e2, $05, $e8, $03
	db $01, $ff, $01, $ff, $03, $ff, $03, $ff, $07, $ff, $06, $ff, $08, $ff, $80, $7f
	db $60, $9f, $11, $ef, $09, $f7, $05, $fb, $c7, $f9, $63, $fd, $a2, $7d, $46, $39
	db $27, $18, $ac, $10, $dc, $00, $e8, $00, $e8, $00, $e0, $00, $e0, $00, $80, $40
	db $40, $80, $80, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $80, $00, $00, $80, $00, $80, $00, $80
	db $40, $80, $00, $c0, $00, $c0, $20, $c0, $00, $e0, $00, $e0, $00, $e0, $10, $e0
	db $00, $f0, $08, $f0, $08, $f0, $00, $f8, $00, $f8, $00, $f8, $04, $f8, $00, $fc
	db $f4, $f8, $e8, $f0, $f0, $c0, $d0, $a0, $a0, $40, $20, $c0, $20, $c0, $20, $c0
	db $80, $c0, $c0, $80, $c0, $80, $c0, $80, $c0, $80, $00, $80, $00, $80, $80, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $c6, $c6, $ee, $ee, $fe, $fe, $d6, $fe, $d6, $d6, $c6, $c6, $c6, $c6, $00, $00
	db $f8, $fc, $cc, $cc, $cc, $cc, $f8, $fc, $f0, $f8, $d8, $dc, $cc, $ce, $00, $00
	db $fe, $fe, $c0, $c0, $c0, $c0, $fc, $fc, $c0, $c0, $c0, $c0, $fe, $fe, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $c6, $c6, $c6, $d6, $d6, $d6, $54, $fe, $7c, $6c, $00, $00
	db $00, $00, $00, $00, $73, $fb, $db, $db, $db, $db, $db, $db, $73, $fb, $00, $00
	db $38, $7c, $64, $c6, $c0, $c0, $c0, $c0, $c0, $c0, $64, $c6, $38, $7c, $00, $00
	db $00, $00, $00, $00, $73, $fb, $db, $db, $db, $db, $db, $db, $73, $fb, $00, $00
	db $00, $00, $00, $00, $f1, $f9, $19, $19, $79, $f9, $d9, $d9, $7d, $fd, $00, $00
	db $00, $00, $00, $00, $c6, $ee, $6c, $6c, $38, $38, $6c, $6c, $c6, $ee, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $73, $fb, $db, $db, $db, $db, $db, $db, $73, $fb, $00, $00
	db $06, $06, $06, $06, $66, $76, $b6, $b6, $36, $36, $36, $36, $36, $36, $00, $00
	db $38, $7c, $64, $c6, $c0, $c0, $ce, $ce, $c6, $c6, $66, $c6, $3c, $7e, $00, $00
	db $00, $00, $00, $00, $63, $77, $b6, $b6, $33, $37, $30, $30, $37, $37, $00, $00
	db $00, $00, $00, $00, $b1, $bb, $db, $db, $9b, $9b, $9b, $9b, $99, $9b, $00, $00
	db $03, $03, $03, $03, $73, $fb, $db, $db, $db, $db, $f3, $fb, $c3, $c3, $c0, $c0
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $0c, $0c, $0c, $0c, $6d, $6d, $8e, $cf, $0e, $8e, $0f, $0f, $0d, $0d, $00, $00
	db $00, $00, $00, $00, $d8, $d8, $d8, $d8, $d8, $d8, $58, $f8, $30, $78, $e0, $f0
	db $f8, $fc, $c4, $c6, $c4, $c6, $f8, $fc, $c4, $c6, $c4, $c6, $f8, $fc, $00, $00
	db $0c, $0c, $0c, $0c, $de, $de, $0c, $0c, $8c, $cc, $cc, $cc, $86, $ce, $00, $00
	db $0c, $0c, $0c, $0c, $ce, $ef, $6d, $6d, $0d, $0d, $6d, $6d, $cd, $ed, $00, $00
	db $00, $00, $00, $00, $39, $7d, $6d, $6d, $6d, $6d, $6d, $6d, $39, $7d, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $9e, $be, $30, $30, $1c, $3e, $06, $06, $bc, $be, $00, $00
	db $00, $00, $00, $00, $c6, $c6, $c6, $d6, $d6, $d6, $54, $fe, $7c, $6c, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $40, $40, $00, $00
	db $00, $00, $00, $00, $73, $fb, $cb, $cb, $fb, $fb, $c3, $c3, $7b, $fb, $00, $00
	db $00, $00, $00, $00, $1c, $3e, $32, $b2, $be, $be, $b0, $b0, $9e, $be, $00, $00
	db $00, $00, $00, $00, $b3, $b7, $c6, $e6, $87, $c7, $86, $86, $83, $87, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $0c, $0c, $cc, $cc, $1e, $1e, $cc, $cc, $cc, $cc, $cc, $cc, $c6, $ce, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $60, $60, $80, $c0, $00, $80, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $d8, $d8, $e0, $f0, $c0, $e0, $c0, $c0, $c0, $c0, $00, $00
	db $00, $00, $00, $00, $9b, $db, $5c, $5e, $d8, $dc, $18, $18, $d8, $d8, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $c0, $c0, $c0, $c0, $e0, $f0, $d0, $d8, $d8, $d8, $d8, $d8, $d8, $d8, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $12, $14

SECTION "analyzed_09eae2", ROMX[$6ae2], BANK[$27]

Section_09eae2:
	db $e4, $6a, $a0, $a8, $b0, $b8, $c0, $c8, $d0, $d8, $e0, $e8, $80, $80, $80, $80
	db $80, $80, $80, $80, $80, $80, $a1, $a9, $b1, $b9, $c1, $c9, $d1, $d9, $e1, $e9
	db $80, $80, $80, $80, $80, $80, $80, $80, $80, $80, $a2, $aa, $b2, $ba, $c2, $ca
	db $d2, $da, $e2, $ea, $80, $80, $80, $80, $80, $80, $80, $80, $80, $80, $a3, $ab
	db $b3, $bb, $c3, $cb, $d3, $db, $e3, $eb, $80, $80, $80, $80, $80, $80, $80, $80
	db $80, $80, $a4, $ac, $b4, $bc, $c4, $cc, $d4, $dc, $e4, $ec, $80, $50, $58, $60
	db $68, $70, $78, $80, $80, $80, $a5, $ad, $b5, $bd, $c5, $cd, $d5, $dd, $e5, $ed
	db $80, $51, $59, $61, $69, $71, $79, $80, $80, $80, $a6, $ae, $b6, $be, $c6, $ce
	db $d6, $de, $e6, $ee, $80, $52, $5a, $62, $6a, $72, $7a, $80, $80, $80, $a7, $af
	db $b7, $bf, $c7, $cf, $d7, $df, $e7, $ef, $80, $80, $80, $80, $80, $80, $80, $80
	db $80, $80, $00, $08, $10, $18, $20, $28, $30, $38, $40, $48, $80, $55, $5d, $65
	db $6d, $80, $56, $5e, $66, $80, $01, $09, $11, $19, $21, $29, $31, $39, $41, $49
	db $80, $6e, $76, $7e, $80, $57, $5f, $67, $6f, $80, $02, $0a, $12, $1a, $22, $2a
	db $32, $3a, $42, $4a, $80, $80, $80, $80, $80, $80, $80, $80, $80, $80, $03, $0b
	db $13, $1b, $23, $2b, $33, $3b, $43, $4b, $80, $80, $80, $80, $80, $80, $80, $80
	db $80, $80, $04, $0c, $14, $1c, $24, $2c, $34, $3c, $44, $4c, $80, $80, $80, $80
	db $80, $80, $80, $80, $80, $80, $05, $0d, $15, $1d, $25, $2d, $35, $3d, $45, $80
	db $80, $80, $80, $80, $80, $80, $80, $80, $80, $80, $06, $0e, $16, $1e, $26, $2e
	db $36, $3e, $46, $4e, $80, $80, $80, $80, $80, $80, $80, $80, $80, $80, $07, $0f
	db $17, $1f, $27, $2f, $37, $3f, $47, $4f, $80, $80, $80, $80, $80, $80, $80, $80
	db $80, $80, $80, $80, $f0, $f8, $f2, $fa, $f4, $fc, $f6, $fe, $80, $80, $80, $80
	db $9a, $9b, $9c, $9d, $9e, $9f, $80, $80, $f1, $f9, $f3, $fb, $f5, $fd, $f7, $ff
	db $80, $80, $80, $80, $80, $80, $80, $80, $80, $80

SECTION "analyzed_09ffff", ROMX[$7fff], BANK[$27]

Section_09ffff:
	db $27

SECTION "analyzed_0c147f", ROMX[$547f], BANK[$30]

Section_0c147f:
	rst $20
	ret nz
	call $02e6
	ld a, $80
	ldh [$ff40], a
	xor a
	ldh [$ff4f], a
	ld a, $27
	ld hl, $5ade
	ld de, $8800
	ld bc, $1000
	call $392d
	ld b, $27
	ld hl, $6ade
	ld de, $9800
	call $35e9
	call $02d1
	ld a, $1b
	ldh [$ff47], a
	call $02e6
	ld a, $81
	ldh [$ff40], a
	call $02e6
	jp $54b2

SECTION "analyzed_0c3fff", ROMX[$7fff], BANK[$30]

Section_0c3fff:
	db $30

SECTION "analyzed_0fc000", ROMX[$4000], BANK[$3f]

Section_0fc000:
	jp $4012
	jp $4059
	jp $409c
	jp $40b4

SECTION "analyzed_0fc012", ROMX[$4012], BANK[$3f]

Section_0fc012:
	ld hl, $de80
	ld de, $0180
	xor a
	ld [hl+], a
	dec de
	ld a, d
	or e
	jr nz, $4018
	xor a
	ld hl, $ff10
	ld b, $15
	ld [hl+], a
	dec b
	jr nz, $4025
	ld a, $77
	ldh [$ff24], a
	xor a
	ldh [$ff25], a
	ld a, $8f
	ldh [$ff26], a
	xor a
	call $409c
	xor a
	call $40b4
	call $4059
	xor a
	ld [$dee0], a
	ld [$dee4], a
	ld [$dee8], a
	ld [$deec], a
	ld [$def0], a
	ld [$def4], a
	ld [$def8], a
	ld [$defc], a
	ret
	ld hl, $de92
	ld a, [hl+]
	or [hl]
	ret nz
	ld a, [$de80]
	or a
	ret nz
	ld a, [$ded0]
	or a
	ret nz
	call $4113
	call $4070
	ret
	ld hl, $ded3
	ld a, [hl+]
	or a
	ret z

SECTION "analyzed_0fc09c", ROMX[$409c], BANK[$3f]

Section_0fc09c:
	ld [$dec0], a
	call $40c4
	ld de, $dee0
	ld bc, $df00
	call $40d2
	xor a
	ld [$ded3], a
	ld a, $77
	ldh [$ff24], a
	ret
	ld [$dec1], a
	call $40c4
	ld de, $def0
	ld bc, $df80
	call $40d2
	ret
	sla a
	ld l, a
	ld h, $00
	ld de, $4b00
	add hl, de
	ld a, [hl+]
	ld h, [hl]
	ld l, a
	add hl, de
	ret
	ld a, $01
	ld [$de80], a
	ld a, $04
	push af
	push bc
	ld a, [de]
	ld b, a
	ld a, [hl]
	cp b
	pop bc
	jr c, $40fe
	push de
	push hl
	ld a, [hl+]
	ld [de], a
	inc de
	ld a, [$7fff]
	ld [de], a
	inc de
	ld a, [hl+]
	ld h, [hl]
	ld l, a
	push de
	ld de, $4b00
	add hl, de
	pop de
	ld a, l
	ld [de], a
	inc de
	ld a, h
	ld [de], a
	pop hl
	pop de
	xor a
	ld [bc], a
	inc hl
	inc hl
	inc hl
	inc de
	inc de
	inc de
	inc de
	ld a, c
	add a, $20
	ld c, a
	pop af
	dec a
	jr nz, $40d9
	ld a, $00
	ld [$de80], a
	ret
	xor a
	ld [$dec3], a
	ld hl, $df00
	ld a, h
	ld [$dec6], a
	ld a, l
	ld [$dec7], a
	ld hl, $dee2
	ld a, h
	ld [$dec4], a
	ld a, l
	ld [$dec5], a
	dec hl
	dec hl
	ld a, [hl]
	inc hl
	inc hl
	or a
	jr z, $4158
	dec hl
	ld a, [hl]
	ld [$2000], a
	inc hl
	ld a, [hl+]
	ld h, [hl]
	ld l, a
	ld a, [$dec6]
	ld d, a
	ld a, [$dec7]
	ld e, a
	ld a, [de]
	or a
	jr nz, $41ac
	ld a, [hl]
	cp $ff
	jp z, $418c
	bit 7, a
	jp z, $432c
	jp nz, $452e
	ld a, [$dec6]
	ld h, a
	ld a, [$dec7]
	ld l, a
	ld de, $0020
	add hl, de
	ld a, h
	ld [$dec6], a
	ld a, l
	ld [$dec7], a
	ld a, [$dec4]
	ld h, a
	ld a, [$dec5]
	ld l, a
	inc hl
	inc hl
	inc hl
	inc hl
	ld a, h
	ld [$dec4], a
	ld a, l
	ld [$dec5], a
	ld a, [$dec3]
	inc a
	ld [$dec3], a
	cp $08
	jr nz, $412d
	ret
	ld a, [$dec4]
	ld b, a
	ld a, [$dec5]
	ld c, a
	dec bc
	dec bc
	xor a
	ld [bc], a
	ld b, $01
	jr $41d5
	ld a, [$dec4]
	ld h, a
	ld a, [$dec5]
	ld l, a
	dec hl
	dec hl
	ld a, [hl]
	or a
	jr z, $41e5
	jr $41c3
	ld a, [$dec3]
	cp $04
	jr nc, $419c
	ld a, [$dec4]
	ld h, a
	ld a, [$dec5]
	ld l, a
	ld a, $0e
	add a, l
	ld l, a
	ld a, [hl]
	or a
	jr nz, $41d8
	ld a, [$dec3]
	and $03
	cp $03
	jr z, $41d2
	call $41e8
	call $422e
	call $4257
	call $42c5
	ld a, [$dec6]
	ld h, a
	ld a, [$dec7]
	ld l, a
	ld a, [hl]
	or a
	jr z, $41e5
	dec [hl]
	jp $4158
	ld a, [$dec3]
	and $03
	cp $02
	ret z
	ld d, $df
	ld a, [$dec7]
	ld e, a
	ld a, $0f
	add a, e
	ld e, a
	ld a, [de]
	or a
	jr nz, $4218

SECTION "analyzed_0fc218", ROMX[$4218], BANK[$3f]

Section_0fc218:
	dec a
	ld [de], a
	dec de
	ld a, [de]
	ld b, a
	ld a, [$dec3]
	and $03
	cp $00
	jr z, $422a
	ld a, b
	ldh [$ff16], a
	ret
	ld a, b
	ldh [$ff11], a
	ret
	ld d, $df
	ld a, [$dec7]
	ld e, a
	ld hl, $001f
	add hl, de
	ld a, [hl]
	or a
	jr nz, $4254

SECTION "analyzed_0fc254", ROMX[$4254], BANK[$3f]

Section_0fc254:
	dec a
	ld [hl], a
	ret
	ld d, $df
	ld a, [$dec7]
	ld e, a
	inc de
	inc de
	ld a, [de]
	ld l, a
	inc de
	ld a, [de]
	ld h, a
	or l
	jr z, $42be

SECTION "analyzed_0fc28a", ROMX[$428a], BANK[$3f]

Section_0fc28a:
	ld a, [$dec3]
	and $03
	cp $00
	jr z, $429f
	cp $01
	jr z, $42a9
	cp $02
	jr z, $42b3
	ld a, l
	ldh [$ff22], a
	ret
	ld a, l
	ldh [$ff13], a
	ld a, h
	ldh [$ff14], a
	ld [$ded2], a
	ret
	ld a, l
	ldh [$ff18], a
	ld a, h
	ldh [$ff19], a
	ld [$ded2], a
	ret
	ld a, l
	ldh [$ff1d], a
	ld a, h
	ldh [$ff1e], a
	ld a, $00
	ldh [$ff1b], a
	ret
	ld b, $01
	ld [$ded2], a
	jr $428a
	ld d, $df
	ld a, [$dec7]
	ld e, a
	ld hl, $0018
	add hl, de
	ld a, b
	cp $01
	jr z, $4326

SECTION "analyzed_0fc2ea", ROMX[$42ea], BANK[$3f]

Section_0fc2ea:
	ld a, [$dec3]
	and $03
	cp $00
	jr z, $4318
	cp $01
	jr z, $430b
	cp $02
	jr z, $4305
	ld a, c
	ldh [$ff21], a
	ld a, $80
	ldh [$ff23], a
	ld a, b
	jr $4323
	ld a, c
	ldh [$ff1c], a
	ld a, b
	jr $4323
	ld a, c
	ldh [$ff17], a
	ld a, [$ded2]
	or $80
	ldh [$ff19], a
	ld a, b
	jr $4323
	ld a, c
	ldh [$ff12], a
	ld a, [$ded2]
	or $80
	ldh [$ff14], a
	ld a, b
	dec a
	ld [hl], a
	ret
	ld b, $ff
	ld c, $08
	jr $42ea
	ld b, a
	and $70
	bit 4, a
	jr z, $4347
	ld a, [$dec6]
	ld d, a
	ld a, [$dec7]
	ld e, a
	inc hl
	ld a, [hl]
	ld [de], a
	inc de
	inc de
	inc de
	inc de
	inc de
	inc de
	ld a, $01
	ld [de], a
	ld a, [$dec3]
	cp $04
	jr nc, $435e
	ld a, [$dec4]
	ld d, a
	ld a, [$dec5]
	ld e, a
	ld a, $0e
	add a, e
	ld e, a
	ld a, [de]
	or a
	jr nz, $4382
	ldh a, [$ff24]
	or a
	jr nz, $4365

SECTION "analyzed_0fc365", ROMX[$4365], BANK[$3f]

Section_0fc365:
	ld a, b
	and $0f
	cp $07
	jr z, $4382

SECTION "analyzed_0fc382", ROMX[$4382], BANK[$3f]

Section_0fc382:
	inc hl
	ld a, [$dec4]
	ld d, a
	ld a, [$dec5]
	ld e, a
	ld a, l
	ld [de], a
	inc de
	ld a, h
	ld [de], a
	ld a, b
	and $0f
	sla a
	ld l, a
	ld h, $00
	ld de, $442e
	add hl, de
	ld d, $df
	ld a, [$dec7]
	ld e, a
	inc de
	ld a, [de]
	sla a
	sla a
	sla a
	sla a
	sla a
	ld c, a
	ld b, $00
	add hl, bc
	inc de
	ld a, [hl+]
	ld [de], a
	inc de
	ld a, [hl]
	ld [de], a
	inc de
	ld a, [de]
	or a
	jr nz, $43e8
	ld hl, $0006
	add hl, de
	ld a, [hl+]
	inc hl
	ld [hl-], a
	ld b, a
	ld a, [hl+]
	inc hl
	ld [hl+], a
	ld c, a
	ld a, [bc]
	ld [hl+], a
	inc bc
	ld a, [bc]
	ld [hl+], a
	ld bc, $0004
	add hl, bc
	ld a, [hl+]
	inc hl
	ld [hl-], a
	ld a, [hl+]
	inc hl
	ld [hl+], a
	xor a
	ld [hl+], a
	inc hl
	ld a, [hl+]
	inc hl
	ld [hl-], a
	ld b, a
	ld a, [hl+]
	inc hl
	ld [hl+], a
	ld c, a
	ld a, [bc]
	ld [hl+], a
	inc bc
	ld a, [bc]
	ld [hl], a
	xor a
	ld [de], a
	inc de
	inc de
	ld a, [de]
	or a
	jr nz, $43fb

SECTION "analyzed_0fc3f8", ROMX[$43f8], BANK[$3f]

Section_0fc3f8:
	jp $41ac
	xor a
	ld [de], a
	jr $43f8

SECTION "analyzed_0fc43c", ROMX[$443c], BANK[$3f]

Section_0fc43c:
	db $00, $00

SECTION "analyzed_0fc52e", ROMX[$452e], BANK[$3f]

Section_0fc52e:
	ld b, a
	and $f0
	cp $90
	jp z, $46cc
	ld d, h
	ld e, l
	ld a, b
	sub $ea
	sla a
	ld hl, $454b
	ld b, $00
	ld c, a
	add hl, bc
	ld a, [hl+]
	ld h, [hl]
	ld l, a
	push hl
	ld h, d
	ld l, e
	ret

SECTION "analyzed_0fc56b", ROMX[$456b], BANK[$3f]

Section_0fc56b:
	db $ef, $45

SECTION "analyzed_0fc5ef", ROMX[$45ef], BANK[$3f]

Section_0fc5ef:
	inc hl
	ld e, [hl]
	inc hl
	ld d, [hl]
	add hl, de
	dec hl
	dec hl
	jp $414a

SECTION "analyzed_0fcb00", ROMX[$4b00], BANK[$3f]

Section_0fcb00:
	db $00, $02

SECTION "analyzed_0fcb50", ROMX[$4b50], BANK[$3f]

Section_0fcb50:
	db $0a, $0d

SECTION "analyzed_0fcd00", ROMX[$4d00], BANK[$3f]

Section_0fcd00:
	db $ff, $0c, $02, $ff, $0c, $02, $ff, $0c, $02, $ff, $0c, $02, $77, $01, $ff

SECTION "analyzed_0fd80a", ROMX[$580a], BANK[$3f]

Section_0fd80a:
	db $f0, $16, $0d, $f0, $16, $0d, $f0, $16, $0d, $f0, $16, $0d, $77, $01, $fa, $fe
	db $ff

SECTION "analyzed_0fffff", ROMX[$7fff], BANK[$3f]

Section_0fffff:
	db $3f
