; Bank-number tags. Every 16 KiB bank ends with a byte equal to its own bank
; number ($7fff for ROMX banks, $3fff for ROM0) -- a common integrity/identity
; convention. Generated by a FOR loop rather than 64 hand-written SECTIONs, so
; this file is marked "generate": false in map.json: the extractor INCLUDEs it
; and counts its coverage, but never regenerates it.

SECTION "bank_tag_00", ROM0[$3fff]

DB $00

; Banks $01..$3f (ROMX, tag at $7fff)
MACRO BANK_TAG
    SECTION "Bank tag ${02X:\1}", ROMX[$7fff], BANK[\1]

BANK_TAG_{02X:\1}:
    DB \1
ENDM

FOR N, 1, $40
    BANK_TAG N
ENDR
