; Bank $17 description text ($4618-$6117): the room-editor help text plus all
; item / monster / block descriptions. Stored as an 18-tile-wide BG tilemap
; (ASCII tile encoding): each text line is one 18-char row, left-aligned, with
; all-space rows as vertical spacers. Carved from analyzed.asm, byte-exact.

SECTION "Editor description text", ROMX[$4618], BANK[$17]

EditorDescriptionText:
	db "                  "
	db "This is a large   "
	db "                  "
	db "room called       "
	db "                  "
	db "This is a small   "
	db "                  "
	db "room called       "
	db "                  "
	db "This one is       "
	db "                  "
	db "open.             "
	db "                  "
	db "Returns a screen. "
	db "                  "
	db "                  "
	db "                  "
	db "Select if only    "
	db "                  "
	db "sending a room.   "
	db "                  "
	db "Select if only    "
	db "                  "
	db "receiving a room. "
	db "                  "
	db "Create a room     "
	db "                  "
	db "Will lose data.   "
	db "                  "
	db "Reverts to open.  "
	db "                  "
	db "                  "
	db "                  "
	db "You can play      "
	db "                  "
	db "this room.        "
	db "                  "
	db "You can rename    "
	db "                  "
	db "this room.        "
	db "                  "
	db "Return a screen.  "
	db "                  "
	db "                  "
	db "                  "
	db "                  "
	db "                  "
	db "                  "
	db "                  "
	db "First, choose     "
	db "                  "
	db "a room size.      "
	db "                  "
	db "Sets the          "
	db "                  "
	db "background.       "
	db "                  "
	db "Sets blocks and   "
	db "                  "
	db "other things.     "
	db "                  "
	db "Sets items and    "
	db "                  "
	db "other things.     "
	db "                  "
	db "Places the        "
	db "                  "
	db "characters.       "
	db "                  "
	db "You can           "
	db "                  "
	db "test play.        "
	db "                  "
	db "Saves the         "
	db "                  "
	db "created room.     "
	db "                  "
	db "Return a screen.  "
	db "                  "
	db "                  "
	db "                  "
	db "Data will be      "
	db "                  "
	db "Saved. OK?        "
	db "                  "
	db "Details set by    "
	db "                  "
	db "pressing Select.  "
	db "                  "
	db "3 monster types   "
	db "                  "
	db "can be placed.    "
	db "                  "
	db "Can place up      "
	db "                  "
	db "to 9 monsters.    "
	db "                  "
	db "Can place up      "
	db "                  "
	db "to 10 items.      "
	db "                  "
	db "Can place up to   "
	db "                  "
	db "4 saucer stones.  "
	db "                  "
	db "Hide item by      "
	db "                  "
	db "pressing Select.  "
	db "                  "
	db "Sets the speed    "
	db "                  "
	db "of the monster.   "
	db "                  "
	db "Sets direction    "
	db "                  "
	db "of the monster.   "
	db "                  "
	db "Sets speed of     "
	db "                  "
	db "special attack.   "
	db "                  "
	db "Sets facing and   "
	db "                  "
	db "turn directions.  "
	db "                  "
	db "Sets life for     "
	db "                  "
	db "Stone monsters.   "
	db "                  "
	db "Sets direction    "
	db "                  "
	db "for monsters.     "
	db "                  "
	db "Sets speed for    "
	db "                  "
	db "Stone monsters.   "
	db "                  "
	db "Picks monster     "
	db "                  "
	db "for the stone.    "
	db "                  "
	db "You can't place   "
	db "                  "
	db "the block there.  "
	db "                  "
	db "No monster        "
	db "                  "
	db "chosen for stone. "
	db "                  "
	db "Can't place any   "
	db "                  "
	db "more monsters.    "
	db "                  "
	db "Can't place       "
	db "                  "
	db "more stones.      "
	db "                  "
	db "Can't place       "
	db "                  "
	db "any more items.   "
	db "                  "
	db "Cannot place a    "
	db "                  "
	db "monster there.    "
	db "                  "
	db "Cannot place a    "
	db "                  "
	db "player there.     "
	db "                  "
	db "That monster is   "
	db "                  "
	db "set to the stone. "
	db "                  "
	db "Gold key or exit  "
	db "                  "
	db "door not put yet. "
	db "                  "
	db "Can change wall   "
	db "                  "
	db "patterns/colors   "
	db "                  "
	db "Exit door         "
	db "                  "
	db "Always set it     "
	db "                  "
	db "Saucer stone      "
	db "                  "
	db "Releases monsters "
	db "                  "
	db "Devil's Seal      "
	db "                  "
	db "Bans block make   "
	db "                  "
	db "Strong block      "
	db "                  "
	db "Cannot break      "
	db "                  "
	db "Breakable block   "
	db "                  "
	db "Can break         "
	db "Gold key          "
	db "                  "
	db "Must be placed    "
	db "                  "
	db "Bell              "
	db "                  "
	db "Calls Suzurin     "
	db "                  "
	db "Half Tororon      "
	db "                  "
	db "Pill to 2X time   "
	db "                  "
	db "Full Tororon      "
	db "                  "
	db "Pill to 5X time   "
	db "                  "
	db "Orange Hourglass  "
	db "                  "
	db "Time to 5,000     "
	db "                  "
	db "Blue Hourglass    "
	db "                  "
	db "Time to 10,000    "
	db "                  "
	db "Cox's Hat         "
	db "                  "
	db "1 Cox increases   "
	db "                  "
	db "Small Bomb        "
	db "                  "
	db "Firework attacks  "
	db "                  "
	db "Big Bomb          "
	db "                  "
	db "Bigger fireworks  "
	db "                  "
	db "Fireplace         "
	db "                  "
	db "Adds fireworks    "
	db "                  "
	db "Gunpowder         "
	db "                  "
	db "Converts bombs    "
	db "                  "
	db "Blue Crystal      "
	db "                  "
	db "fireworks range   "
	db "increases         "
	db "Red Crystal       "
	db "                  "
	db "REALLY increases  "
	db "fireworks range   "
	db "Blue Diamond      "
	db "                  "
	db "500 points        "
	db "                  "
	db "Red Diamond       "
	db "                  "
	db "5,000 points      "
	db "                  "
	db "Platinum Ring     "
	db "                  "
	db "50,000 points     "
	db "                  "
	db "Silver Medal      "
	db "                  "
	db "100 points        "
	db "                  "
	db "Silver Nugget     "
	db "                  "
	db "200 points        "
	db "                  "
	db "Gold Medal        "
	db "                  "
	db "1,000 points      "
	db "                  "
	db "Golden Nugget     "
	db "                  "
	db "2,000 points      "
	db "                  "
	db "Heal Badge        "
	db "                  "
	db "10,000 points     "
	db "                  "
	db "Cake              "
	db "                  "
	db "100,000 points    "
	db "                  "
	db "Golden Peach      "
	db "                  "
	db "500,000 points    "
	db "                  "
	db "Silver Peach      "
	db "                  "
	db "500,000 points    "
	db "                  "
	db "Duck Doll         "
	db "                  "
	db "Destroys monster  "
	db "                  "
	db "Player            "
	db "                  "
	db "Start location    "
	db "                  "
	db "Tacopi            "
	db "                  "
	db "Rotate and moves  "
	db "left and right    "
	db "Jell              "
	db "                  "
	db "Chases Cox        "
	db "                  "
	db "Naga              "
	db "                  "
	db "Chases for claw   "
	db "attacks           "
	db "Dino              "
	db "                  "
	db "Breathes fire     "
	db "                  "
	db "Plant             "
	db "                  "
	db "Moves left/right  "
	db "and shoots seeds  "
	db "Henger            "
	db "                  "
	db "Flies back/forth  "
	db "                  "
	db "Joker             "
	db "                  "
	db "Flies back/forth  "
	db "                  "
	db "Ghost             "
	db "                  "
	db "Flies up/down     "
	db "                  "
	db "Puncho            "
	db "                  "
	db "Turns player      "
	db "into a pumpkin    "
	db "Psylora           "
	db "                  "
	db "Moves along wall  "
	db "                  "
	db "Ducken            "
	db "                  "
	db "Sticks to wall    "
	db "Fires missiles    "
	db "Red Flame         "
	db "                  "
	db "Flame disappears  "
	db "After dropped     "
	db "Blue Flame        "
	db "                  "
	db "Flame doesn't     "
	db "disappear         "
	db "                  "
	db "                  "
	db "                  "
	db "                  "
	db "                  "
	db "                  "
	db "                  "
	db "                  "
	db "                  "
	db "                  "
	db "                  "
	db "                  "
	db "                  "
	db "                  "
	db "                  "
	db "                  "
	db "                  "
	db "                  "
	db "                  "
	db "                  "
	db "                  "
	db "                  "
	db "                  "
	db "                  "
	db "                  "
	db "                  "
	db "                  "
	db "                  "
