; Bank $17 description text ($4618-$6117): the room-editor help text
; plus all item / monster / block descriptions, laid out as a 32-tile-
; wide BG tilemap (text wraps across rows). ASCII tile encoding, so each
; row is one 32-char db string. Carved from analyzed.asm, byte-exact.

SECTION "Editor description text", ROMX[$4618], BANK[$17]

EditorDescriptionText:
	db "                  This is a larg"
	db "e                     room calle"
	db "d                         This i"
	db "s a small                     ro"
	db "om called                       "
	db "  This one is                   "
	db "      open.                     "
	db "          Returns a screen.     "
	db "                                "
	db "                  Select if only"
	db "                      sending a "
	db "room.                     Select"
	db " if only                      re"
	db "ceiving a room.                 "
	db "  Create a room                 "
	db "      Will lose data.           "
	db "          Reverts to open.      "
	db "                                "
	db "                  You can play  "
	db "                      this room."
	db "                          You ca"
	db "n rename                      th"
	db "is room.                        "
	db "  Return a screen.              "
	db "                                "
	db "                                "
	db "                                "
	db "                  First, choose "
	db "                      a room siz"
	db "e.                        Sets t"
	db "he                            ba"
	db "ckground.                       "
	db "  Sets blocks and               "
	db "      other things.             "
	db "          Sets items and        "
	db "              other things.     "
	db "                  Places the    "
	db "                      characters"
	db ".                         You ca"
	db "n                             te"
	db "st play.                        "
	db "  Saves the                     "
	db "      created room.             "
	db "          Return a screen.      "
	db "                                "
	db "                  Data will be  "
	db "                      Saved. OK?"
	db "                          Detail"
	db "s set by                      pr"
	db "essing Select.                  "
	db "  3 monster types               "
	db "      can be placed.            "
	db "          Can place up          "
	db "              to 9 monsters.    "
	db "                  Can place up  "
	db "                      to 10 item"
	db "s.                        Can pl"
	db "ace up to                     4 "
	db "saucer stones.                  "
	db "  Hide item by                  "
	db "      pressing Select.          "
	db "          Sets the speed        "
	db "              of the monster.   "
	db "                  Sets direction"
	db "                      of the mon"
	db "ster.                     Sets s"
	db "peed of                       sp"
	db "ecial attack.                   "
	db "  Sets facing and               "
	db "      turn directions.          "
	db "          Sets life for         "
	db "              Stone monsters.   "
	db "                  Sets direction"
	db "                      for monste"
	db "rs.                       Sets s"
	db "peed for                      St"
	db "one monsters.                   "
	db "  Picks monster                 "
	db "      for the stone.            "
	db "          You can't place       "
	db "              the block there.  "
	db "                  No monster    "
	db "                      chosen for"
	db " stone.                   Can't "
	db "place any                     mo"
	db "re monsters.                    "
	db "  Can't place                   "
	db "      more stones.              "
	db "          Can't place           "
	db "              any more items.   "
	db "                  Cannot place a"
	db "                      monster th"
	db "ere.                      Cannot"
	db " place a                      pl"
	db "ayer there.                     "
	db "  That monster is               "
	db "      set to the stone.         "
	db "          Gold key or exit      "
	db "              door not put yet. "
	db "                  Can change wal"
	db "l                     patterns/c"
	db "olors                     Exit d"
	db "oor                           Al"
	db "ways set it                     "
	db "  Saucer stone                  "
	db "      Releases monsters         "
	db "          Devil's Seal          "
	db "              Bans block make   "
	db "                  Strong block  "
	db "                      Cannot bre"
	db "ak                        Breaka"
	db "ble block                     Ca"
	db "n break         Gold key        "
	db "                    Must be plac"
	db "ed                      Bell    "
	db "                            Call"
	db "s Suzurin                       "
	db "Half Tororon                    "
	db "    Pill to 2X time             "
	db "        Full Tororon            "
	db "            Pill to 5X time     "
	db "                Orange Hourglass"
	db "                    Time to 5,00"
	db "0                       Blue Hou"
	db "rglass                      Time"
	db " to 10,000                      "
	db "Cox's Hat                       "
	db "    1 Cox increases             "
	db "        Small Bomb              "
	db "            Firework attacks    "
	db "                Big Bomb        "
	db "                    Bigger firew"
	db "orks                    Fireplac"
	db "e                           Adds"
	db " fireworks                      "
	db "Gunpowder                       "
	db "    Converts bombs              "
	db "        Blue Crystal            "
	db "            fireworks range   in"
	db "creases         Red Crystal     "
	db "                    REALLY incre"
	db "ases  fireworks range   Blue Dia"
	db "mond                        500 "
	db "points                          "
	db "Red Diamond                     "
	db "    5,000 points                "
	db "        Platinum Ring           "
	db "            50,000 points       "
	db "                Silver Medal    "
	db "                    100 points  "
	db "                        Silver N"
	db "ugget                       200 "
	db "points                          "
	db "Gold Medal                      "
	db "    1,000 points                "
	db "        Golden Nugget           "
	db "            2,000 points        "
	db "                Heal Badge      "
	db "                    10,000 point"
	db "s                       Cake    "
	db "                            100,"
	db "000 points                      "
	db "Golden Peach                    "
	db "    500,000 points              "
	db "        Silver Peach            "
	db "            500,000 points      "
	db "                Duck Doll       "
	db "                    Destroys mon"
	db "ster                    Player  "
	db "                            Star"
	db "t location                      "
	db "Tacopi                          "
	db "    Rotate and moves  left and r"
	db "ight    Jell                    "
	db "            Chases Cox          "
	db "                Naga            "
	db "                    Chases for c"
	db "law   attacks           Dino    "
	db "                            Brea"
	db "thes fire                       "
	db "Plant                           "
	db "    Moves left/right  and shoots"
	db " seeds  Henger                  "
	db "            Flies back/forth    "
	db "                Joker           "
	db "                    Flies back/f"
	db "orth                    Ghost   "
	db "                            Flie"
	db "s up/down                       "
	db "Puncho                          "
	db "    Turns player      into a pum"
	db "pkin    Psylora                 "
	db "            Moves along wall    "
	db "                Ducken          "
	db "                    Sticks to wa"
	db "ll    Fires missiles    Red Flam"
	db "e                           Flam"
	db "e disappears  After dropped     "
	db "Blue Flame                      "
	db "    Flame doesn't     disappear "
	db "                                "
	db "                                "
	db "                                "
	db "                                "
	db "                                "
	db "                                "
	db "                                "
	db "                                "
	db "                                "
	db "                                "
	db "                                "
	db "                                "
	db "                                "
	db "                                "
	db "                                "
	db "                                "
