; Auto-generated by tools/extract.py. Do not edit.

SECTION "Header", ROM0[$0100]

EntryPoint:
	nop
	jp $0150

; Nintendo logo ($0104-$0133)
	db $ce, $ed, $66, $66, $cc, $0d, $00, $0b, $03, $73, $00, $83, $00, $0c, $00, $0d
	db $00, $08, $11, $1f, $88, $89, $00, $0e, $dc, $cc, $6e, $e6, $dd, $dd, $d9, $99
	db $bb, $bb, $67, $63, $6e, $0e, $ec, $cc, $dd, $dc, $99, $9f, $bb, $b9, $33, $3e

; Title ($0134-$0142)
	db $4d, $52, $45, $58, $50, $4c, $4f, $52, $45, $52, $00, $42, $53, $4f, $45

; CGB flag ($0143-$0143)
	db $c0

; New licensee code ($0144-$0145)
	db $39, $42

; SGB flag ($0146-$0146)
	db $00

; Cartridge type ($0147-$0147)
	db $1b

; ROM size ($0148-$0148)
	db $05

; RAM size ($0149-$0149)
	db $02

; Destination code ($014a-$014a)
	db $01

; Old licensee code ($014b-$014b)
	db $33

; Mask ROM version ($014c-$014c)
	db $00

; Header checksum ($014d-$014d)
	db $1d

; Global checksum ($014e-$014f)
	db $2d, $b2
