; Auto-generated by tools/extract.py. Do not edit.

INCLUDE "header.asm"
INCLUDE "analyzed.asm"

SECTION "data_000003", ROM0[$0003]
	INCBIN "data_000003.bin"

SECTION "data_00001c", ROM0[$001c]
	INCBIN "data_00001c.bin"

SECTION "data_000025", ROM0[$0025]
	INCBIN "data_000025.bin"

SECTION "data_000035", ROM0[$0035]
	INCBIN "data_000035.bin"

SECTION "data_000043", ROM0[$0043]
	INCBIN "data_000043.bin"

SECTION "data_00018d", ROM0[$018d]
	INCBIN "data_00018d.bin"

SECTION "data_0001ae", ROM0[$01ae]
	INCBIN "data_0001ae.bin"

SECTION "data_0001c9", ROM0[$01c9]
	INCBIN "data_0001c9.bin"

SECTION "data_0001e9", ROM0[$01e9]
	INCBIN "data_0001e9.bin"

SECTION "data_0001fe", ROM0[$01fe]
	INCBIN "data_0001fe.bin"

SECTION "data_000288", ROM0[$0288]
	INCBIN "data_000288.bin"

SECTION "data_00029b", ROM0[$029b]
	INCBIN "data_00029b.bin"

SECTION "data_00030a", ROM0[$030a]
	INCBIN "data_00030a.bin"

SECTION "data_000312", ROM0[$0312]
	INCBIN "data_000312.bin"

SECTION "data_00034b", ROM0[$034b]
	INCBIN "data_00034b.bin"

SECTION "data_0003a5", ROM0[$03a5]
	INCBIN "data_0003a5.bin"

SECTION "data_0003c4", ROM0[$03c4]
	INCBIN "data_0003c4.bin"

SECTION "data_000447", ROM0[$0447]
	INCBIN "data_000447.bin"

SECTION "data_00052e", ROM0[$052e]
	INCBIN "data_00052e.bin"

SECTION "data_000583", ROM0[$0583]
	INCBIN "data_000583.bin"

SECTION "data_0005ca", ROM0[$05ca]
	INCBIN "data_0005ca.bin"

SECTION "data_00061e", ROM0[$061e]
	INCBIN "data_00061e.bin"

SECTION "data_0006ce", ROM0[$06ce]
	INCBIN "data_0006ce.bin"

SECTION "data_0006e3", ROM0[$06e3]
	INCBIN "data_0006e3.bin"

SECTION "data_0006f2", ROM0[$06f2]
	INCBIN "data_0006f2.bin"

SECTION "data_000716", ROM0[$0716]
	INCBIN "data_000716.bin"

SECTION "data_0007a7", ROM0[$07a7]
	INCBIN "data_0007a7.bin"

SECTION "data_000834", ROM0[$0834]
	INCBIN "data_000834.bin"

SECTION "data_000897", ROM0[$0897]
	INCBIN "data_000897.bin"

SECTION "data_000a1a", ROM0[$0a1a]
	INCBIN "data_000a1a.bin"

SECTION "data_000a56", ROM0[$0a56]
	INCBIN "data_000a56.bin"

SECTION "data_000aa4", ROM0[$0aa4]
	INCBIN "data_000aa4.bin"

SECTION "data_000ada", ROM0[$0ada]
	INCBIN "data_000ada.bin"

SECTION "data_000b2a", ROM0[$0b2a]
	INCBIN "data_000b2a.bin"

SECTION "data_000b78", ROM0[$0b78]
	INCBIN "data_000b78.bin"

SECTION "data_000bd0", ROM0[$0bd0]
	INCBIN "data_000bd0.bin"

SECTION "data_000c09", ROM0[$0c09]
	INCBIN "data_000c09.bin"

SECTION "data_000f6e", ROM0[$0f6e]
	INCBIN "data_000f6e.bin"

SECTION "data_000f77", ROM0[$0f77]
	INCBIN "data_000f77.bin"

SECTION "data_0012e1", ROM0[$12e1]
	INCBIN "data_0012e1.bin"

SECTION "data_0012fa", ROM0[$12fa]
	INCBIN "data_0012fa.bin"

SECTION "data_001873", ROM0[$1873]
	INCBIN "data_001873.bin"

SECTION "data_00358b", ROM0[$358b]
	INCBIN "data_00358b.bin"

SECTION "data_0035d4", ROM0[$35d4]
	INCBIN "data_0035d4.bin"

SECTION "data_0035f9", ROM0[$35f9]
	INCBIN "data_0035f9.bin"

SECTION "data_003646", ROM0[$3646]
	INCBIN "data_003646.bin"

SECTION "data_003942", ROM0[$3942]
	INCBIN "data_003942.bin"

SECTION "data_0039c0", ROM0[$39c0]
	INCBIN "data_0039c0.bin"

SECTION "data_004000", ROMX[$4000], BANK[$01]
	INCBIN "data_004000.bin"

SECTION "data_008000", ROMX[$4000], BANK[$02]
	INCBIN "data_008000.bin"

SECTION "data_00c000", ROMX[$4000], BANK[$03]
	INCBIN "data_00c000.bin"

SECTION "data_010000", ROMX[$4000], BANK[$04]
	INCBIN "data_010000.bin"

SECTION "data_014000", ROMX[$4000], BANK[$05]
	INCBIN "data_014000.bin"

SECTION "data_0146ba", ROMX[$46ba], BANK[$05]
	INCBIN "data_0146ba.bin"

SECTION "data_018000", ROMX[$4000], BANK[$06]
	INCBIN "data_018000.bin"

SECTION "data_01c000", ROMX[$4000], BANK[$07]
	INCBIN "data_01c000.bin"

SECTION "data_020000", ROMX[$4000], BANK[$08]
	INCBIN "data_020000.bin"

SECTION "data_024000", ROMX[$4000], BANK[$09]
	INCBIN "data_024000.bin"

SECTION "data_028000", ROMX[$4000], BANK[$0a]
	INCBIN "data_028000.bin"

SECTION "data_02c000", ROMX[$4000], BANK[$0b]
	INCBIN "data_02c000.bin"

SECTION "data_030000", ROMX[$4000], BANK[$0c]
	INCBIN "data_030000.bin"

SECTION "data_034000", ROMX[$4000], BANK[$0d]
	INCBIN "data_034000.bin"

SECTION "data_038000", ROMX[$4000], BANK[$0e]
	INCBIN "data_038000.bin"

SECTION "data_03c000", ROMX[$4000], BANK[$0f]
	INCBIN "data_03c000.bin"

SECTION "data_040000", ROMX[$4000], BANK[$10]
	INCBIN "data_040000.bin"

SECTION "data_044000", ROMX[$4000], BANK[$11]
	INCBIN "data_044000.bin"

SECTION "data_048000", ROMX[$4000], BANK[$12]
	INCBIN "data_048000.bin"

SECTION "data_048a52", ROMX[$4a52], BANK[$12]
	INCBIN "data_048a52.bin"

SECTION "data_048a59", ROMX[$4a59], BANK[$12]
	INCBIN "data_048a59.bin"

SECTION "data_048a60", ROMX[$4a60], BANK[$12]
	INCBIN "data_048a60.bin"

SECTION "data_048a73", ROMX[$4a73], BANK[$12]
	INCBIN "data_048a73.bin"

SECTION "data_048b67", ROMX[$4b67], BANK[$12]
	INCBIN "data_048b67.bin"

SECTION "data_048bde", ROMX[$4bde], BANK[$12]
	INCBIN "data_048bde.bin"

SECTION "data_048bef", ROMX[$4bef], BANK[$12]
	INCBIN "data_048bef.bin"

SECTION "data_048c2b", ROMX[$4c2b], BANK[$12]
	INCBIN "data_048c2b.bin"

SECTION "data_048cad", ROMX[$4cad], BANK[$12]
	INCBIN "data_048cad.bin"

SECTION "data_048cb5", ROMX[$4cb5], BANK[$12]
	INCBIN "data_048cb5.bin"

SECTION "data_048ccb", ROMX[$4ccb], BANK[$12]
	INCBIN "data_048ccb.bin"

SECTION "data_04c000", ROMX[$4000], BANK[$13]
	INCBIN "data_04c000.bin"

SECTION "data_050000", ROMX[$4000], BANK[$14]
	INCBIN "data_050000.bin"

SECTION "data_054000", ROMX[$4000], BANK[$15]
	INCBIN "data_054000.bin"

SECTION "data_058000", ROMX[$4000], BANK[$16]
	INCBIN "data_058000.bin"

SECTION "data_05c000", ROMX[$4000], BANK[$17]
	INCBIN "data_05c000.bin"

SECTION "data_060000", ROMX[$4000], BANK[$18]
	INCBIN "data_060000.bin"

SECTION "data_064000", ROMX[$4000], BANK[$19]
	INCBIN "data_064000.bin"

SECTION "data_068000", ROMX[$4000], BANK[$1a]
	INCBIN "data_068000.bin"

SECTION "data_06c000", ROMX[$4000], BANK[$1b]
	INCBIN "data_06c000.bin"

SECTION "data_070000", ROMX[$4000], BANK[$1c]
	INCBIN "data_070000.bin"

SECTION "data_074000", ROMX[$4000], BANK[$1d]
	INCBIN "data_074000.bin"

SECTION "data_078000", ROMX[$4000], BANK[$1e]
	INCBIN "data_078000.bin"

SECTION "data_07c000", ROMX[$4000], BANK[$1f]
	INCBIN "data_07c000.bin"

SECTION "data_080000", ROMX[$4000], BANK[$20]
	INCBIN "data_080000.bin"

SECTION "data_084000", ROMX[$4000], BANK[$21]
	INCBIN "data_084000.bin"

SECTION "data_088000", ROMX[$4000], BANK[$22]
	INCBIN "data_088000.bin"

SECTION "data_08c000", ROMX[$4000], BANK[$23]
	INCBIN "data_08c000.bin"

SECTION "data_090000", ROMX[$4000], BANK[$24]
	INCBIN "data_090000.bin"

SECTION "data_094000", ROMX[$4000], BANK[$25]
	INCBIN "data_094000.bin"

SECTION "data_098000", ROMX[$4000], BANK[$26]
	INCBIN "data_098000.bin"

SECTION "data_09f000", ROMX[$7000], BANK[$27]
	INCBIN "data_09f000.bin"

SECTION "data_0a0000", ROMX[$4000], BANK[$28]
	INCBIN "data_0a0000.bin"

SECTION "data_0a4000", ROMX[$4000], BANK[$29]
	INCBIN "data_0a4000.bin"

SECTION "data_0a8000", ROMX[$4000], BANK[$2a]
	INCBIN "data_0a8000.bin"

SECTION "data_0ac000", ROMX[$4000], BANK[$2b]
	INCBIN "data_0ac000.bin"

SECTION "data_0b0000", ROMX[$4000], BANK[$2c]
	INCBIN "data_0b0000.bin"

SECTION "data_0b4000", ROMX[$4000], BANK[$2d]
	INCBIN "data_0b4000.bin"

SECTION "data_0b8000", ROMX[$4000], BANK[$2e]
	INCBIN "data_0b8000.bin"

SECTION "data_0bc000", ROMX[$4000], BANK[$2f]
	INCBIN "data_0bc000.bin"

SECTION "data_0c0000", ROMX[$4000], BANK[$30]
	INCBIN "data_0c0000.bin"

SECTION "data_0c1478", ROMX[$5478], BANK[$30]
	INCBIN "data_0c1478.bin"

SECTION "data_0c1481", ROMX[$5481], BANK[$30]
	INCBIN "data_0c1481.bin"

SECTION "data_0c4000", ROMX[$4000], BANK[$31]
	INCBIN "data_0c4000.bin"

SECTION "data_0c8000", ROMX[$4000], BANK[$32]
	INCBIN "data_0c8000.bin"

SECTION "data_0cc000", ROMX[$4000], BANK[$33]
	INCBIN "data_0cc000.bin"

SECTION "data_0d0000", ROMX[$4000], BANK[$34]
	INCBIN "data_0d0000.bin"

SECTION "data_0d4000", ROMX[$4000], BANK[$35]
	INCBIN "data_0d4000.bin"

SECTION "data_0d8000", ROMX[$4000], BANK[$36]
	INCBIN "data_0d8000.bin"

SECTION "data_0dc000", ROMX[$4000], BANK[$37]
	INCBIN "data_0dc000.bin"

SECTION "data_0e0000", ROMX[$4000], BANK[$38]
	INCBIN "data_0e0000.bin"

SECTION "data_0e4000", ROMX[$4000], BANK[$39]
	INCBIN "data_0e4000.bin"

SECTION "data_0e8000", ROMX[$4000], BANK[$3a]
	INCBIN "data_0e8000.bin"

SECTION "data_0ec000", ROMX[$4000], BANK[$3b]
	INCBIN "data_0ec000.bin"

SECTION "data_0f0000", ROMX[$4000], BANK[$3c]
	INCBIN "data_0f0000.bin"

SECTION "data_0f4000", ROMX[$4000], BANK[$3d]
	INCBIN "data_0f4000.bin"

SECTION "data_0f8000", ROMX[$4000], BANK[$3e]
	INCBIN "data_0f8000.bin"

SECTION "data_0fc00c", ROMX[$400c], BANK[$3f]
	INCBIN "data_0fc00c.bin"

SECTION "data_0fc076", ROMX[$4076], BANK[$3f]
	INCBIN "data_0fc076.bin"

SECTION "data_0fc1fe", ROMX[$41fe], BANK[$3f]
	INCBIN "data_0fc1fe.bin"

SECTION "data_0fc23c", ROMX[$423c], BANK[$3f]
	INCBIN "data_0fc23c.bin"

SECTION "data_0fc267", ROMX[$4267], BANK[$3f]
	INCBIN "data_0fc267.bin"

SECTION "data_0fc2d4", ROMX[$42d4], BANK[$3f]
	INCBIN "data_0fc2d4.bin"

SECTION "data_0fc363", ROMX[$4363], BANK[$3f]
	INCBIN "data_0fc363.bin"

SECTION "data_0fc36c", ROMX[$436c], BANK[$3f]
	INCBIN "data_0fc36c.bin"

SECTION "data_0fc3f0", ROMX[$43f0], BANK[$3f]
	INCBIN "data_0fc3f0.bin"

SECTION "data_0fc3ff", ROMX[$43ff], BANK[$3f]
	INCBIN "data_0fc3ff.bin"

SECTION "data_0fc43e", ROMX[$443e], BANK[$3f]
	INCBIN "data_0fc43e.bin"

SECTION "data_0fc54b", ROMX[$454b], BANK[$3f]
	INCBIN "data_0fc54b.bin"

SECTION "data_0fc56d", ROMX[$456d], BANK[$3f]
	INCBIN "data_0fc56d.bin"

SECTION "data_0fc5f9", ROMX[$45f9], BANK[$3f]
	INCBIN "data_0fc5f9.bin"

SECTION "data_0fcb02", ROMX[$4b02], BANK[$3f]
	INCBIN "data_0fcb02.bin"

SECTION "data_0fcb52", ROMX[$4b52], BANK[$3f]
	INCBIN "data_0fcb52.bin"

SECTION "data_0fcd0f", ROMX[$4d0f], BANK[$3f]
	INCBIN "data_0fcd0f.bin"

SECTION "data_0fd81b", ROMX[$581b], BANK[$3f]
	INCBIN "data_0fd81b.bin"
