; Auto-generated by tools/extract.py. Do not edit.

INCLUDE "header.asm"
INCLUDE "analyzed.asm"

SECTION "data_000002", ROM0[$0002]
	INCBIN "data_000002.bin"

SECTION "data_00001c", ROM0[$001c]
	INCBIN "data_00001c.bin"

SECTION "data_000025", ROM0[$0025]
	INCBIN "data_000025.bin"

SECTION "data_000035", ROM0[$0035]
	INCBIN "data_000035.bin"

SECTION "data_000043", ROM0[$0043]
	INCBIN "data_000043.bin"

SECTION "data_00018a", ROM0[$018a]
	INCBIN "data_00018a.bin"

SECTION "data_0001b3", ROM0[$01b3]
	INCBIN "data_0001b3.bin"

SECTION "data_0001c9", ROM0[$01c9]
	INCBIN "data_0001c9.bin"

SECTION "data_0001ee", ROM0[$01ee]
	INCBIN "data_0001ee.bin"

SECTION "data_0002b9", ROM0[$02b9]
	INCBIN "data_0002b9.bin"

SECTION "data_0002f4", ROM0[$02f4]
	INCBIN "data_0002f4.bin"

SECTION "data_00030b", ROM0[$030b]
	INCBIN "data_00030b.bin"

SECTION "data_000361", ROM0[$0361]
	INCBIN "data_000361.bin"

SECTION "data_0003a5", ROM0[$03a5]
	INCBIN "data_0003a5.bin"

SECTION "data_000a56", ROM0[$0a56]
	INCBIN "data_000a56.bin"

SECTION "data_000aa4", ROM0[$0aa4]
	INCBIN "data_000aa4.bin"

SECTION "data_000ada", ROM0[$0ada]
	INCBIN "data_000ada.bin"

SECTION "data_000b2a", ROM0[$0b2a]
	INCBIN "data_000b2a.bin"

SECTION "data_000b55", ROM0[$0b55]
	INCBIN "data_000b55.bin"

SECTION "data_000b78", ROM0[$0b78]
	INCBIN "data_000b78.bin"

SECTION "data_000bd0", ROM0[$0bd0]
	INCBIN "data_000bd0.bin"

SECTION "data_000c09", ROM0[$0c09]
	INCBIN "data_000c09.bin"

SECTION "data_001873", ROM0[$1873]
	INCBIN "data_001873.bin"

SECTION "data_0035d3", ROM0[$35d3]
	INCBIN "data_0035d3.bin"

SECTION "data_0035f9", ROM0[$35f9]
	INCBIN "data_0035f9.bin"

SECTION "data_003942", ROM0[$3942]
	INCBIN "data_003942.bin"

SECTION "data_004000", ROMX[$4000], BANK[$01]
	INCBIN "data_004000.bin"

SECTION "data_008000", ROMX[$4000], BANK[$02]
	INCBIN "data_008000.bin"

SECTION "data_00c000", ROMX[$4000], BANK[$03]
	INCBIN "data_00c000.bin"

SECTION "data_010000", ROMX[$4000], BANK[$04]
	INCBIN "data_010000.bin"

SECTION "data_014000", ROMX[$4000], BANK[$05]
	INCBIN "data_014000.bin"

SECTION "data_018000", ROMX[$4000], BANK[$06]
	INCBIN "data_018000.bin"

SECTION "data_01c000", ROMX[$4000], BANK[$07]
	INCBIN "data_01c000.bin"

SECTION "data_020000", ROMX[$4000], BANK[$08]
	INCBIN "data_020000.bin"

SECTION "data_024000", ROMX[$4000], BANK[$09]
	INCBIN "data_024000.bin"

SECTION "data_028000", ROMX[$4000], BANK[$0a]
	INCBIN "data_028000.bin"

SECTION "data_02c000", ROMX[$4000], BANK[$0b]
	INCBIN "data_02c000.bin"

SECTION "data_030000", ROMX[$4000], BANK[$0c]
	INCBIN "data_030000.bin"

SECTION "data_034000", ROMX[$4000], BANK[$0d]
	INCBIN "data_034000.bin"

SECTION "data_038000", ROMX[$4000], BANK[$0e]
	INCBIN "data_038000.bin"

SECTION "data_03c000", ROMX[$4000], BANK[$0f]
	INCBIN "data_03c000.bin"

SECTION "data_040000", ROMX[$4000], BANK[$10]
	INCBIN "data_040000.bin"

SECTION "data_044000", ROMX[$4000], BANK[$11]
	INCBIN "data_044000.bin"

SECTION "data_048000", ROMX[$4000], BANK[$12]
	INCBIN "data_048000.bin"

SECTION "data_04c000", ROMX[$4000], BANK[$13]
	INCBIN "data_04c000.bin"

SECTION "data_050000", ROMX[$4000], BANK[$14]
	INCBIN "data_050000.bin"

SECTION "data_054000", ROMX[$4000], BANK[$15]
	INCBIN "data_054000.bin"

SECTION "data_058000", ROMX[$4000], BANK[$16]
	INCBIN "data_058000.bin"

SECTION "data_05c000", ROMX[$4000], BANK[$17]
	INCBIN "data_05c000.bin"

SECTION "data_060000", ROMX[$4000], BANK[$18]
	INCBIN "data_060000.bin"

SECTION "data_064000", ROMX[$4000], BANK[$19]
	INCBIN "data_064000.bin"

SECTION "data_068000", ROMX[$4000], BANK[$1a]
	INCBIN "data_068000.bin"

SECTION "data_06c000", ROMX[$4000], BANK[$1b]
	INCBIN "data_06c000.bin"

SECTION "data_070000", ROMX[$4000], BANK[$1c]
	INCBIN "data_070000.bin"

SECTION "data_074000", ROMX[$4000], BANK[$1d]
	INCBIN "data_074000.bin"

SECTION "data_078000", ROMX[$4000], BANK[$1e]
	INCBIN "data_078000.bin"

SECTION "data_07c000", ROMX[$4000], BANK[$1f]
	INCBIN "data_07c000.bin"

SECTION "data_080000", ROMX[$4000], BANK[$20]
	INCBIN "data_080000.bin"

SECTION "data_084000", ROMX[$4000], BANK[$21]
	INCBIN "data_084000.bin"

SECTION "data_088000", ROMX[$4000], BANK[$22]
	INCBIN "data_088000.bin"

SECTION "data_08c000", ROMX[$4000], BANK[$23]
	INCBIN "data_08c000.bin"

SECTION "data_090000", ROMX[$4000], BANK[$24]
	INCBIN "data_090000.bin"

SECTION "data_094000", ROMX[$4000], BANK[$25]
	INCBIN "data_094000.bin"

SECTION "data_098000", ROMX[$4000], BANK[$26]
	INCBIN "data_098000.bin"

SECTION "data_09c000", ROMX[$4000], BANK[$27]
	INCBIN "data_09c000.bin"

SECTION "data_09eae0", ROMX[$6ae0], BANK[$27]
	INCBIN "data_09eae0.bin"

SECTION "data_09ec4c", ROMX[$6c4c], BANK[$27]
	INCBIN "data_09ec4c.bin"

SECTION "data_0a0000", ROMX[$4000], BANK[$28]
	INCBIN "data_0a0000.bin"

SECTION "data_0a4000", ROMX[$4000], BANK[$29]
	INCBIN "data_0a4000.bin"

SECTION "data_0a8000", ROMX[$4000], BANK[$2a]
	INCBIN "data_0a8000.bin"

SECTION "data_0ac000", ROMX[$4000], BANK[$2b]
	INCBIN "data_0ac000.bin"

SECTION "data_0b0000", ROMX[$4000], BANK[$2c]
	INCBIN "data_0b0000.bin"

SECTION "data_0b4000", ROMX[$4000], BANK[$2d]
	INCBIN "data_0b4000.bin"

SECTION "data_0b8000", ROMX[$4000], BANK[$2e]
	INCBIN "data_0b8000.bin"

SECTION "data_0bc000", ROMX[$4000], BANK[$2f]
	INCBIN "data_0bc000.bin"

SECTION "data_0c0000", ROMX[$4000], BANK[$30]
	INCBIN "data_0c0000.bin"

SECTION "data_0c14b8", ROMX[$54b8], BANK[$30]
	INCBIN "data_0c14b8.bin"

SECTION "data_0c4000", ROMX[$4000], BANK[$31]
	INCBIN "data_0c4000.bin"

SECTION "data_0c8000", ROMX[$4000], BANK[$32]
	INCBIN "data_0c8000.bin"

SECTION "data_0cc000", ROMX[$4000], BANK[$33]
	INCBIN "data_0cc000.bin"

SECTION "data_0d0000", ROMX[$4000], BANK[$34]
	INCBIN "data_0d0000.bin"

SECTION "data_0d4000", ROMX[$4000], BANK[$35]
	INCBIN "data_0d4000.bin"

SECTION "data_0d8000", ROMX[$4000], BANK[$36]
	INCBIN "data_0d8000.bin"

SECTION "data_0dc000", ROMX[$4000], BANK[$37]
	INCBIN "data_0dc000.bin"

SECTION "data_0e0000", ROMX[$4000], BANK[$38]
	INCBIN "data_0e0000.bin"

SECTION "data_0e4000", ROMX[$4000], BANK[$39]
	INCBIN "data_0e4000.bin"

SECTION "data_0e8000", ROMX[$4000], BANK[$3a]
	INCBIN "data_0e8000.bin"

SECTION "data_0ec000", ROMX[$4000], BANK[$3b]
	INCBIN "data_0ec000.bin"

SECTION "data_0f0000", ROMX[$4000], BANK[$3c]
	INCBIN "data_0f0000.bin"

SECTION "data_0f4000", ROMX[$4000], BANK[$3d]
	INCBIN "data_0f4000.bin"

SECTION "data_0f8000", ROMX[$4000], BANK[$3e]
	INCBIN "data_0f8000.bin"

SECTION "data_0fc00c", ROMX[$400c], BANK[$3f]
	INCBIN "data_0fc00c.bin"

SECTION "data_0fc076", ROMX[$4076], BANK[$3f]
	INCBIN "data_0fc076.bin"

SECTION "data_0fc1fe", ROMX[$41fe], BANK[$3f]
	INCBIN "data_0fc1fe.bin"

SECTION "data_0fc23c", ROMX[$423c], BANK[$3f]
	INCBIN "data_0fc23c.bin"

SECTION "data_0fc267", ROMX[$4267], BANK[$3f]
	INCBIN "data_0fc267.bin"

SECTION "data_0fc2d4", ROMX[$42d4], BANK[$3f]
	INCBIN "data_0fc2d4.bin"

SECTION "data_0fc363", ROMX[$4363], BANK[$3f]
	INCBIN "data_0fc363.bin"

SECTION "data_0fc36c", ROMX[$436c], BANK[$3f]
	INCBIN "data_0fc36c.bin"

SECTION "data_0fc3f0", ROMX[$43f0], BANK[$3f]
	INCBIN "data_0fc3f0.bin"

SECTION "data_0fc3ff", ROMX[$43ff], BANK[$3f]
	INCBIN "data_0fc3ff.bin"

SECTION "data_0fc43e", ROMX[$443e], BANK[$3f]
	INCBIN "data_0fc43e.bin"

SECTION "data_0fc54b", ROMX[$454b], BANK[$3f]
	INCBIN "data_0fc54b.bin"

SECTION "data_0fc56d", ROMX[$456d], BANK[$3f]
	INCBIN "data_0fc56d.bin"

SECTION "data_0fc5f9", ROMX[$45f9], BANK[$3f]
	INCBIN "data_0fc5f9.bin"

SECTION "data_0fcb02", ROMX[$4b02], BANK[$3f]
	INCBIN "data_0fcb02.bin"

SECTION "data_0fcb52", ROMX[$4b52], BANK[$3f]
	INCBIN "data_0fcb52.bin"

SECTION "data_0fcd0f", ROMX[$4d0f], BANK[$3f]
	INCBIN "data_0fcd0f.bin"

SECTION "data_0fd81b", ROMX[$581b], BANK[$3f]
	INCBIN "data_0fd81b.bin"
