; Auto-generated by tools/extract.py. Do not edit.

INCLUDE "hardware.inc"
INCLUDE "wram.inc"

INCLUDE "header.asm"
INCLUDE "analyzed.asm"
INCLUDE "bodka_portrait.asm"
INCLUDE "ferious_portrait.asm"
INCLUDE "intro_book.asm"
INCLUDE "item_data.asm"
INCLUDE "item_effects.asm"
INCLUDE "kalum_portrait.asm"
INCLUDE "nada_intro.asm"
INCLUDE "nada_scene2.asm"
INCLUDE "naji_portrait.asm"
INCLUDE "padding.asm"
INCLUDE "pashute_portrait.asm"
INCLUDE "rafaga_portrait.asm"
INCLUDE "room.asm"
INCLUDE "room/room01.asm"
INCLUDE "room/room02.asm"
INCLUDE "room/room03.asm"
INCLUDE "room/room04.asm"
INCLUDE "room/room05.asm"
INCLUDE "room/room06.asm"
INCLUDE "room/room07.asm"
INCLUDE "room/room08.asm"
INCLUDE "room/room09.asm"
INCLUDE "room/room10.asm"
INCLUDE "room/room11.asm"
INCLUDE "room/room12.asm"
INCLUDE "room/room13.asm"
INCLUDE "room/room14.asm"
INCLUDE "room/room15.asm"
INCLUDE "room/room16.asm"
INCLUDE "room/room17.asm"
INCLUDE "room/room18.asm"
INCLUDE "room/room19.asm"
INCLUDE "room/room20.asm"
INCLUDE "room/room21.asm"
INCLUDE "room/room22.asm"
INCLUDE "room/room23.asm"
INCLUDE "room/room24.asm"
INCLUDE "room/room25.asm"
INCLUDE "room/room26.asm"
INCLUDE "room/room27.asm"
INCLUDE "room/room28.asm"
INCLUDE "room/room29.asm"
INCLUDE "room/room30.asm"
INCLUDE "room/room31.asm"
INCLUDE "room/room32.asm"
INCLUDE "room/room33.asm"
INCLUDE "room/room34.asm"
INCLUDE "room/room35.asm"
INCLUDE "room/room36.asm"
INCLUDE "room/room37.asm"
INCLUDE "room/room38.asm"
INCLUDE "room/room39.asm"
INCLUDE "room/room40.asm"
INCLUDE "room/room41.asm"
INCLUDE "room/room42.asm"
INCLUDE "room/room43.asm"
INCLUDE "room/room44.asm"
INCLUDE "room/room45.asm"
INCLUDE "room/room46.asm"
INCLUDE "room/room47.asm"
INCLUDE "room/room48.asm"
INCLUDE "room/room49.asm"
INCLUDE "room/room50.asm"
INCLUDE "room/room51.asm"
INCLUDE "room/room52.asm"
INCLUDE "room/room53.asm"
INCLUDE "room/room54.asm"
INCLUDE "room/room55.asm"
INCLUDE "room/room56.asm"
INCLUDE "room/room57.asm"
INCLUDE "room/room58.asm"
INCLUDE "room/room59.asm"
INCLUDE "room/room60.asm"
INCLUDE "room/roomB01.asm"
INCLUDE "room/roomB02.asm"
INCLUDE "room/roomB03.asm"
INCLUDE "room/roomB04.asm"
INCLUDE "room/roomB05.asm"
INCLUDE "room/roomB06.asm"
INCLUDE "room/roomB07.asm"
INCLUDE "room/roomB08.asm"
INCLUDE "room/roomB09.asm"
INCLUDE "room/roomB10.asm"
INCLUDE "room_clear.asm"
INCLUDE "room_start.asm"
INCLUDE "script.asm"
INCLUDE "scripts/kalum.asm"
INCLUDE "scripts/letter_from_cox.asm"
INCLUDE "scripts/mistral.asm"
INCLUDE "scripts/nada.asm"
INCLUDE "scripts/naji.asm"
INCLUDE "scripts/nox.asm"
INCLUDE "scripts/pashute.asm"
INCLUDE "scripts/rafaga.asm"
INCLUDE "scripts/tempest.asm"
INCLUDE "scripts/toamuna.asm"
INCLUDE "scripts/verde.asm"
INCLUDE "tecmo_logo.asm"
INCLUDE "tempest_portrait.asm"
INCLUDE "title_screen.asm"
INCLUDE "toamuna_portrait.asm"
INCLUDE "tower_entrance.asm"
INCLUDE "tower_entrance_open.asm"
INCLUDE "town_screen.asm"

SECTION "data_00018d", ROM0[$018d]
Data_00_018d:
	INCBIN "data/data_00018d.bin"

SECTION "data_0001ae", ROM0[$01ae]
Data_00_01ae:
	INCBIN "data/data_0001ae.bin"

SECTION "data_0001c9", ROM0[$01c9]
Data_00_01c9:
	INCBIN "data/data_0001c9.bin"

SECTION "data_0002a4", ROM0[$02a4]
Data_00_02a4:
	INCBIN "data/data_0002a4.bin"

SECTION "data_00030a", ROM0[$030a]
Data_00_030a:
	INCBIN "data/data_00030a.bin"

SECTION "data_00031b", ROM0[$031b]
Data_00_031b:
	INCBIN "data/data_00031b.bin"

SECTION "data_00034b", ROM0[$034b]
Data_00_034b:
	INCBIN "data/data_00034b.bin"

SECTION "data_000447", ROM0[$0447]
Data_00_0447:
	INCBIN "data/data_000447.bin"

SECTION "data_00059c", ROM0[$059c]
Data_00_059c:
	INCBIN "data/data_00059c.bin"

SECTION "data_00074e", ROM0[$074e]
Data_00_074e:
	INCBIN "data/data_00074e.bin"

SECTION "data_000a1a", ROM0[$0a1a]
Data_00_0a1a:
	INCBIN "data/data_000a1a.bin"

SECTION "data_000aa4", ROM0[$0aa4]
Data_00_0aa4:
	INCBIN "data/data_000aa4.bin"

SECTION "data_000b00", ROM0[$0b00]
Data_00_0b00:
	INCBIN "data/data_000b00.bin"

SECTION "data_000b24", ROM0[$0b24]
Data_00_0b24:
	INCBIN "data/data_000b24.bin"

SECTION "data_000bd0", ROM0[$0bd0]
Data_00_0bd0:
	INCBIN "data/data_000bd0.bin"

SECTION "data_000c72", ROM0[$0c72]
Data_00_0c72:
	INCBIN "data/data_000c72.bin"

SECTION "data_000f70", ROM0[$0f70]
Data_00_0f70:
	INCBIN "data/data_000f70.bin"

SECTION "data_00117f", ROM0[$117f]
Data_00_117f:
	INCBIN "data/data_00117f.bin"

SECTION "data_0011f2", ROM0[$11f2]
Data_00_11f2:
	INCBIN "data/data_0011f2.bin"

SECTION "data_0011ff", ROM0[$11ff]
Data_00_11ff:
	INCBIN "data/data_0011ff.bin"

SECTION "data_001211", ROM0[$1211]
Data_00_1211:
	INCBIN "data/data_001211.bin"

SECTION "data_001235", ROM0[$1235]
Data_00_1235:
	INCBIN "data/data_001235.bin"

SECTION "data_00123c", ROM0[$123c]
Data_00_123c:
	INCBIN "data/data_00123c.bin"

SECTION "data_001242", ROM0[$1242]
Data_00_1242:
	INCBIN "data/data_001242.bin"

SECTION "data_001246", ROM0[$1246]
Data_00_1246:
	INCBIN "data/data_001246.bin"

SECTION "data_00124b", ROM0[$124b]
Data_00_124b:
	INCBIN "data/data_00124b.bin"

SECTION "data_00130c", ROM0[$130c]
Data_00_130c:
	INCBIN "data/data_00130c.bin"

SECTION "data_00132a", ROM0[$132a]
Data_00_132a:
	INCBIN "data/data_00132a.bin"

SECTION "data_00133e", ROM0[$133e]
Data_00_133e:
	INCBIN "data/data_00133e.bin"

SECTION "data_001343", ROM0[$1343]
Data_00_1343:
	INCBIN "data/data_001343.bin"

SECTION "data_001352", ROM0[$1352]
Data_00_1352:
	INCBIN "data/data_001352.bin"

SECTION "data_001357", ROM0[$1357]
Data_00_1357:
	INCBIN "data/data_001357.bin"

SECTION "data_00135c", ROM0[$135c]
Data_00_135c:
	INCBIN "data/data_00135c.bin"

SECTION "data_00139d", ROM0[$139d]
Data_00_139d:
	INCBIN "data/data_00139d.bin"

SECTION "data_0013ac", ROM0[$13ac]
Data_00_13ac:
	INCBIN "data/data_0013ac.bin"

SECTION "data_0013ca", ROM0[$13ca]
Data_00_13ca:
	INCBIN "data/data_0013ca.bin"

SECTION "data_0013cf", ROM0[$13cf]
Data_00_13cf:
	INCBIN "data/data_0013cf.bin"

SECTION "data_001477", ROM0[$1477]
Data_00_1477:
	INCBIN "data/data_001477.bin"

SECTION "data_001481", ROM0[$1481]
Data_00_1481:
	INCBIN "data/data_001481.bin"

SECTION "data_001486", ROM0[$1486]
Data_00_1486:
	INCBIN "data/data_001486.bin"

SECTION "data_00148b", ROM0[$148b]
Data_00_148b:
	INCBIN "data/data_00148b.bin"

SECTION "data_001490", ROM0[$1490]
Data_00_1490:
	INCBIN "data/data_001490.bin"

SECTION "data_001495", ROM0[$1495]
Data_00_1495:
	INCBIN "data/data_001495.bin"

SECTION "data_00149a", ROM0[$149a]
Data_00_149a:
	INCBIN "data/data_00149a.bin"

SECTION "data_0014b3", ROM0[$14b3]
Data_00_14b3:
	INCBIN "data/data_0014b3.bin"

SECTION "data_0014bd", ROM0[$14bd]
Data_00_14bd:
	INCBIN "data/data_0014bd.bin"

SECTION "data_0014c2", ROM0[$14c2]
Data_00_14c2:
	INCBIN "data/data_0014c2.bin"

SECTION "data_0014ea", ROM0[$14ea]
Data_00_14ea:
	INCBIN "data/data_0014ea.bin"

SECTION "data_0014ef", ROM0[$14ef]
Data_00_14ef:
	INCBIN "data/data_0014ef.bin"

SECTION "data_0014f4", ROM0[$14f4]
Data_00_14f4:
	INCBIN "data/data_0014f4.bin"

SECTION "data_001503", ROM0[$1503]
Data_00_1503:
	INCBIN "data/data_001503.bin"

SECTION "data_001508", ROM0[$1508]
Data_00_1508:
	INCBIN "data/data_001508.bin"

SECTION "data_00150d", ROM0[$150d]
Data_00_150d:
	INCBIN "data/data_00150d.bin"

SECTION "data_001512", ROM0[$1512]
Data_00_1512:
	INCBIN "data/data_001512.bin"

SECTION "data_001519", ROM0[$1519]
Data_00_1519:
	INCBIN "data/data_001519.bin"

SECTION "data_00154e", ROM0[$154e]
Data_00_154e:
	INCBIN "data/data_00154e.bin"

SECTION "data_001553", ROM0[$1553]
Data_00_1553:
	INCBIN "data/data_001553.bin"

SECTION "data_001558", ROM0[$1558]
Data_00_1558:
	INCBIN "data/data_001558.bin"

SECTION "data_00155f", ROM0[$155f]
Data_00_155f:
	INCBIN "data/data_00155f.bin"

SECTION "data_0015b2", ROM0[$15b2]
Data_00_15b2:
	INCBIN "data/data_0015b2.bin"

SECTION "data_0015b4", ROM0[$15b4]
Data_00_15b4:
	INCBIN "data/data_0015b4.bin"

SECTION "data_001655", ROM0[$1655]
Data_00_1655:
	INCBIN "data/data_001655.bin"

SECTION "data_001659", ROM0[$1659]
Data_00_1659:
	INCBIN "data/data_001659.bin"

SECTION "data_0018a7", ROM0[$18a7]
Data_00_18a7:
	INCBIN "data/data_0018a7.bin"

SECTION "data_001937", ROM0[$1937]
Data_00_1937:
	INCBIN "data/data_001937.bin"

SECTION "data_001ad7", ROM0[$1ad7]
Data_00_1ad7:
	INCBIN "data/data_001ad7.bin"

SECTION "data_001b01", ROM0[$1b01]
Data_00_1b01:
	INCBIN "data/data_001b01.bin"

SECTION "data_001c08", ROM0[$1c08]
Data_00_1c08:
	INCBIN "data/data_001c08.bin"

SECTION "data_001c3f", ROM0[$1c3f]
Data_00_1c3f:
	INCBIN "data/data_001c3f.bin"

SECTION "data_001d2e", ROM0[$1d2e]
Data_00_1d2e:
	INCBIN "data/data_001d2e.bin"

SECTION "data_001d50", ROM0[$1d50]
Data_00_1d50:
	INCBIN "data/data_001d50.bin"

SECTION "data_001d80", ROM0[$1d80]
Data_00_1d80:
	INCBIN "data/data_001d80.bin"

SECTION "data_001dbc", ROM0[$1dbc]
Data_00_1dbc:
	INCBIN "data/data_001dbc.bin"

SECTION "data_001e8c", ROM0[$1e8c]
Data_00_1e8c:
	INCBIN "data/data_001e8c.bin"

SECTION "data_001ea6", ROM0[$1ea6]
Data_00_1ea6:
	INCBIN "data/data_001ea6.bin"

SECTION "data_001ec3", ROM0[$1ec3]
Data_00_1ec3:
	INCBIN "data/data_001ec3.bin"

SECTION "data_001ee4", ROM0[$1ee4]
Data_00_1ee4:
	INCBIN "data/data_001ee4.bin"

SECTION "data_001f05", ROM0[$1f05]
Data_00_1f05:
	INCBIN "data/data_001f05.bin"

SECTION "data_001f31", ROM0[$1f31]
Data_00_1f31:
	INCBIN "data/data_001f31.bin"

SECTION "data_001f50", ROM0[$1f50]
Data_00_1f50:
	INCBIN "data/data_001f50.bin"

SECTION "data_001feb", ROM0[$1feb]
Data_00_1feb:
	INCBIN "data/data_001feb.bin"

SECTION "data_002006", ROM0[$2006]
Data_00_2006:
	INCBIN "data/data_002006.bin"

SECTION "data_002030", ROM0[$2030]
Data_00_2030:
	INCBIN "data/data_002030.bin"

SECTION "data_002040", ROM0[$2040]
Data_00_2040:
	INCBIN "data/data_002040.bin"

SECTION "data_002094", ROM0[$2094]
Data_00_2094:
	INCBIN "data/data_002094.bin"

SECTION "data_00213b", ROM0[$213b]
Data_00_213b:
	INCBIN "data/data_00213b.bin"

SECTION "data_0021db", ROM0[$21db]
Data_00_21db:
	INCBIN "data/data_0021db.bin"

SECTION "data_0021f0", ROM0[$21f0]
Data_00_21f0:
	INCBIN "data/data_0021f0.bin"

SECTION "data_002211", ROM0[$2211]
Data_00_2211:
	INCBIN "data/data_002211.bin"

SECTION "data_002273", ROM0[$2273]
Data_00_2273:
	INCBIN "data/data_002273.bin"

SECTION "data_00227a", ROM0[$227a]
Data_00_227a:
	INCBIN "data/data_00227a.bin"

SECTION "data_002285", ROM0[$2285]
Data_00_2285:
	INCBIN "data/data_002285.bin"

SECTION "data_00228a", ROM0[$228a]
Data_00_228a:
	INCBIN "data/data_00228a.bin"

SECTION "data_00229e", ROM0[$229e]
Data_00_229e:
	INCBIN "data/data_00229e.bin"

SECTION "data_0022b3", ROM0[$22b3]
Data_00_22b3:
	INCBIN "data/data_0022b3.bin"

SECTION "data_0022b7", ROM0[$22b7]
Data_00_22b7:
	INCBIN "data/data_0022b7.bin"

SECTION "data_0022cc", ROM0[$22cc]
Data_00_22cc:
	INCBIN "data/data_0022cc.bin"

SECTION "data_0022d4", ROM0[$22d4]
Data_00_22d4:
	INCBIN "data/data_0022d4.bin"

SECTION "data_0022fc", ROM0[$22fc]
Data_00_22fc:
	INCBIN "data/data_0022fc.bin"

SECTION "data_00237f", ROM0[$237f]
Data_00_237f:
	INCBIN "data/data_00237f.bin"

SECTION "data_00238d", ROM0[$238d]
Data_00_238d:
	INCBIN "data/data_00238d.bin"

SECTION "data_0023a6", ROM0[$23a6]
Data_00_23a6:
	INCBIN "data/data_0023a6.bin"

SECTION "data_002446", ROM0[$2446]
Data_00_2446:
	INCBIN "data/data_002446.bin"

SECTION "data_002495", ROM0[$2495]
Data_00_2495:
	INCBIN "data/data_002495.bin"

SECTION "data_002d99", ROM0[$2d99]
Data_00_2d99:
	INCBIN "data/data_002d99.bin"

SECTION "data_002e1f", ROM0[$2e1f]
Data_00_2e1f:
	INCBIN "data/data_002e1f.bin"

SECTION "data_002e36", ROM0[$2e36]
Data_00_2e36:
	INCBIN "data/data_002e36.bin"

SECTION "data_002eae", ROM0[$2eae]
Data_00_2eae:
	INCBIN "data/data_002eae.bin"

SECTION "data_002ebb", ROM0[$2ebb]
Data_00_2ebb:
	INCBIN "data/data_002ebb.bin"

SECTION "data_002f0f", ROM0[$2f0f]
Data_00_2f0f:
	INCBIN "data/data_002f0f.bin"

SECTION "data_002fcc", ROM0[$2fcc]
Data_00_2fcc:
	INCBIN "data/data_002fcc.bin"

SECTION "data_003190", ROM0[$3190]
Data_00_3190:
	INCBIN "data/data_003190.bin"

SECTION "data_0031a0", ROM0[$31a0]
Data_00_31a0:
	INCBIN "data/data_0031a0.bin"

SECTION "data_0031f9", ROM0[$31f9]
Data_00_31f9:
	INCBIN "data/data_0031f9.bin"

SECTION "data_00320d", ROM0[$320d]
Data_00_320d:
	INCBIN "data/data_00320d.bin"

SECTION "data_0032b6", ROM0[$32b6]
Data_00_32b6:
	INCBIN "data/data_0032b6.bin"

SECTION "data_003308", ROM0[$3308]
Data_00_3308:
	INCBIN "data/data_003308.bin"

SECTION "data_003649", ROM0[$3649]
Data_00_3649:
	INCBIN "data/data_003649.bin"

SECTION "data_003696", ROM0[$3696]
Data_00_3696:
	INCBIN "data/data_003696.bin"

SECTION "data_003728", ROM0[$3728]
Data_00_3728:
	INCBIN "data/data_003728.bin"

SECTION "data_003d4a", ROM0[$3d4a]
Data_00_3d4a:
	INCBIN "data/data_003d4a.bin"

SECTION "data_003d61", ROM0[$3d61]
Data_00_3d61:
	INCBIN "data/data_003d61.bin"

SECTION "data_003d68", ROM0[$3d68]
Data_00_3d68:
	INCBIN "data/data_003d68.bin"

SECTION "data_003d6a", ROM0[$3d6a]
Data_00_3d6a:
	INCBIN "data/data_003d6a.bin"

SECTION "data_003d8b", ROM0[$3d8b]
Data_00_3d8b:
	INCBIN "data/data_003d8b.bin"

SECTION "data_003db6", ROM0[$3db6]
Data_00_3db6:
	INCBIN "data/data_003db6.bin"

SECTION "data_0042d1", ROMX[$42d1], BANK[$01]
Data_01_42d1:
	INCBIN "data/data_0042d1.bin"

SECTION "data_00460d", ROMX[$460d], BANK[$01]
Data_01_460d:
	INCBIN "data/data_00460d.bin"

SECTION "data_0046e0", ROMX[$46e0], BANK[$01]
Data_01_46e0:
	INCBIN "data/data_0046e0.bin"

SECTION "data_004706", ROMX[$4706], BANK[$01]
Data_01_4706:
	INCBIN "data/data_004706.bin"

SECTION "data_00483e", ROMX[$483e], BANK[$01]
Data_01_483e:
	INCBIN "data/data_00483e.bin"

SECTION "data_004951", ROMX[$4951], BANK[$01]
Data_01_4951:
	INCBIN "data/data_004951.bin"

SECTION "data_0049ac", ROMX[$49ac], BANK[$01]
Data_01_49ac:
	INCBIN "data/data_0049ac.bin"

SECTION "data_004b6a", ROMX[$4b6a], BANK[$01]
Data_01_4b6a:
	INCBIN "data/data_004b6a.bin"

SECTION "data_004d5c", ROMX[$4d5c], BANK[$01]
Data_01_4d5c:
	INCBIN "data/data_004d5c.bin"

SECTION "data_005553", ROMX[$5553], BANK[$01]
Data_01_5553:
	INCBIN "data/data_005553.bin"

SECTION "data_005623", ROMX[$5623], BANK[$01]
Data_01_5623:
	INCBIN "data/data_005623.bin"

SECTION "data_00566e", ROMX[$566e], BANK[$01]
Data_01_566e:
	INCBIN "data/data_00566e.bin"

SECTION "data_005aaf", ROMX[$5aaf], BANK[$01]
Data_01_5aaf:
	INCBIN "data/data_005aaf.bin"

SECTION "data_005ba6", ROMX[$5ba6], BANK[$01]
Data_01_5ba6:
	INCBIN "data/data_005ba6.bin"

SECTION "data_005be0", ROMX[$5be0], BANK[$01]
Data_01_5be0:
	INCBIN "data/data_005be0.bin"

SECTION "data_005c3b", ROMX[$5c3b], BANK[$01]
Data_01_5c3b:
	INCBIN "data/data_005c3b.bin"

SECTION "data_005c5e", ROMX[$5c5e], BANK[$01]
Data_01_5c5e:
	INCBIN "data/data_005c5e.bin"

SECTION "data_005ce1", ROMX[$5ce1], BANK[$01]
Data_01_5ce1:
	INCBIN "data/data_005ce1.bin"

SECTION "data_005d82", ROMX[$5d82], BANK[$01]
Data_01_5d82:
	INCBIN "data/data_005d82.bin"

SECTION "data_0066ba", ROMX[$66ba], BANK[$01]
Data_01_66ba:
	INCBIN "data/data_0066ba.bin"

SECTION "data_0066f8", ROMX[$66f8], BANK[$01]
Data_01_66f8:
	INCBIN "data/data_0066f8.bin"

SECTION "data_006ba6", ROMX[$6ba6], BANK[$01]
Data_01_6ba6:
	INCBIN "data/data_006ba6.bin"

SECTION "data_006bc7", ROMX[$6bc7], BANK[$01]
Data_01_6bc7:
	INCBIN "data/data_006bc7.bin"

SECTION "data_006c3d", ROMX[$6c3d], BANK[$01]
Data_01_6c3d:
	INCBIN "data/data_006c3d.bin"

SECTION "data_006cf1", ROMX[$6cf1], BANK[$01]
Data_01_6cf1:
	INCBIN "data/data_006cf1.bin"

SECTION "data_006d13", ROMX[$6d13], BANK[$01]
Data_01_6d13:
	INCBIN "data/data_006d13.bin"

SECTION "data_006d40", ROMX[$6d40], BANK[$01]
Data_01_6d40:
	INCBIN "data/data_006d40.bin"

SECTION "data_006d80", ROMX[$6d80], BANK[$01]
Data_01_6d80:
	INCBIN "data/data_006d80.bin"

SECTION "data_006d8e", ROMX[$6d8e], BANK[$01]
Data_01_6d8e:
	INCBIN "data/data_006d8e.bin"

SECTION "data_006d9a", ROMX[$6d9a], BANK[$01]
Data_01_6d9a:
	INCBIN "data/data_006d9a.bin"

SECTION "data_006da2", ROMX[$6da2], BANK[$01]
Data_01_6da2:
	INCBIN "data/data_006da2.bin"

SECTION "data_006dac", ROMX[$6dac], BANK[$01]
Data_01_6dac:
	INCBIN "data/data_006dac.bin"

SECTION "data_00785b", ROMX[$785b], BANK[$01]
Data_01_785b:
	INCBIN "data/data_00785b.bin"

SECTION "data_007870", ROMX[$7870], BANK[$01]
Data_01_7870:
	INCBIN "data/data_007870.bin"

SECTION "data_007882", ROMX[$7882], BANK[$01]
Data_01_7882:
	INCBIN "data/data_007882.bin"

SECTION "data_00788e", ROMX[$788e], BANK[$01]
Data_01_788e:
	INCBIN "data/data_00788e.bin"

SECTION "data_00789d", ROMX[$789d], BANK[$01]
Data_01_789d:
	INCBIN "data/data_00789d.bin"

SECTION "data_00791e", ROMX[$791e], BANK[$01]
Data_01_791e:
	INCBIN "data/data_00791e.bin"

SECTION "data_007996", ROMX[$7996], BANK[$01]
Data_01_7996:
	INCBIN "data/data_007996.bin"

SECTION "data_0079a4", ROMX[$79a4], BANK[$01]
Data_01_79a4:
	INCBIN "data/data_0079a4.bin"

SECTION "data_0079b0", ROMX[$79b0], BANK[$01]
Data_01_79b0:
	INCBIN "data/data_0079b0.bin"

SECTION "data_0079b8", ROMX[$79b8], BANK[$01]
Data_01_79b8:
	INCBIN "data/data_0079b8.bin"

SECTION "data_0079c2", ROMX[$79c2], BANK[$01]
Data_01_79c2:
	INCBIN "data/data_0079c2.bin"

SECTION "data_007cb3", ROMX[$7cb3], BANK[$01]
Data_01_7cb3:
	INCBIN "data/data_007cb3.bin"

SECTION "data_0090b1", ROMX[$50b1], BANK[$02]
Data_02_50b1:
	INCBIN "data/data_0090b1.bin"

SECTION "data_0092cd", ROMX[$52cd], BANK[$02]
Data_02_52cd:
	INCBIN "data/data_0092cd.bin"

SECTION "data_0093b0", ROMX[$53b0], BANK[$02]
Data_02_53b0:
	INCBIN "data/data_0093b0.bin"

SECTION "data_0093dd", ROMX[$53dd], BANK[$02]
Data_02_53dd:
	INCBIN "data/data_0093dd.bin"

SECTION "data_009545", ROMX[$5545], BANK[$02]
Data_02_5545:
	INCBIN "data/data_009545.bin"

SECTION "data_0095b1", ROMX[$55b1], BANK[$02]
Data_02_55b1:
	INCBIN "data/data_0095b1.bin"

SECTION "data_00961d", ROMX[$561d], BANK[$02]
Data_02_561d:
	INCBIN "data/data_00961d.bin"

SECTION "data_009689", ROMX[$5689], BANK[$02]
Data_02_5689:
	INCBIN "data/data_009689.bin"

SECTION "data_0096b6", ROMX[$56b6], BANK[$02]
Data_02_56b6:
	INCBIN "data/data_0096b6.bin"

SECTION "data_0096ec", ROMX[$56ec], BANK[$02]
Data_02_56ec:
	INCBIN "data/data_0096ec.bin"

SECTION "data_00972b", ROMX[$572b], BANK[$02]
Data_02_572b:
	INCBIN "data/data_00972b.bin"

SECTION "data_009758", ROMX[$5758], BANK[$02]
Data_02_5758:
	INCBIN "data/data_009758.bin"

SECTION "data_009be3", ROMX[$5be3], BANK[$02]
Data_02_5be3:
	INCBIN "data/data_009be3.bin"

SECTION "data_009d2b", ROMX[$5d2b], BANK[$02]
Data_02_5d2b:
	INCBIN "data/data_009d2b.bin"

SECTION "data_00c0aa", ROMX[$40aa], BANK[$03]
Data_03_40aa:
	INCBIN "data/data_00c0aa.bin"

SECTION "data_00c0b4", ROMX[$40b4], BANK[$03]
Data_03_40b4:
	INCBIN "data/data_00c0b4.bin"

SECTION "data_00c0ca", ROMX[$40ca], BANK[$03]
Data_03_40ca:
	INCBIN "data/data_00c0ca.bin"

SECTION "data_00c0ce", ROMX[$40ce], BANK[$03]
Data_03_40ce:
	INCBIN "data/data_00c0ce.bin"

SECTION "data_00c0e8", ROMX[$40e8], BANK[$03]
Data_03_40e8:
	INCBIN "data/data_00c0e8.bin"

SECTION "data_00c16b", ROMX[$416b], BANK[$03]
Data_03_416b:
	INCBIN "data/data_00c16b.bin"

SECTION "data_00c1ac", ROMX[$41ac], BANK[$03]
Data_03_41ac:
	INCBIN "data/data_00c1ac.bin"

SECTION "data_00c1e0", ROMX[$41e0], BANK[$03]
Data_03_41e0:
	INCBIN "data/data_00c1e0.bin"

SECTION "data_00c20e", ROMX[$420e], BANK[$03]
Data_03_420e:
	INCBIN "data/data_00c20e.bin"

SECTION "data_00c22a", ROMX[$422a], BANK[$03]
Data_03_422a:
	INCBIN "data/data_00c22a.bin"

SECTION "data_00c246", ROMX[$4246], BANK[$03]
Data_03_4246:
	INCBIN "data/data_00c246.bin"

SECTION "data_00c2bd", ROMX[$42bd], BANK[$03]
Data_03_42bd:
	INCBIN "data/data_00c2bd.bin"

SECTION "data_00c2ed", ROMX[$42ed], BANK[$03]
Data_03_42ed:
	INCBIN "data/data_00c2ed.bin"

SECTION "data_00c587", ROMX[$4587], BANK[$03]
Data_03_4587:
	INCBIN "data/data_00c587.bin"

SECTION "data_00c59a", ROMX[$459a], BANK[$03]
Data_03_459a:
	INCBIN "data/data_00c59a.bin"

SECTION "data_00c909", ROMX[$4909], BANK[$03]
Data_03_4909:
	INCBIN "data/data_00c909.bin"

SECTION "data_00ca4f", ROMX[$4a4f], BANK[$03]
Data_03_4a4f:
	INCBIN "data/data_00ca4f.bin"

SECTION "data_00ce47", ROMX[$4e47], BANK[$03]
Data_03_4e47:
	INCBIN "data/data_00ce47.bin"

SECTION "data_00cef9", ROMX[$4ef9], BANK[$03]
Data_03_4ef9:
	INCBIN "data/data_00cef9.bin"

SECTION "data_00d15f", ROMX[$515f], BANK[$03]
Data_03_515f:
	INCBIN "data/data_00d15f.bin"

SECTION "data_00d1f0", ROMX[$51f0], BANK[$03]
Data_03_51f0:
	INCBIN "data/data_00d1f0.bin"

SECTION "data_00d370", ROMX[$5370], BANK[$03]
Data_03_5370:
	INCBIN "data/data_00d370.bin"

SECTION "data_00d40f", ROMX[$540f], BANK[$03]
Data_03_540f:
	INCBIN "data/data_00d40f.bin"

SECTION "data_00d468", ROMX[$5468], BANK[$03]
Data_03_5468:
	INCBIN "data/data_00d468.bin"

SECTION "data_00d616", ROMX[$5616], BANK[$03]
Data_03_5616:
	INCBIN "data/data_00d616.bin"

SECTION "data_00d8d7", ROMX[$58d7], BANK[$03]
Data_03_58d7:
	INCBIN "data/data_00d8d7.bin"

SECTION "data_00e5a4", ROMX[$65a4], BANK[$03]
Data_03_65a4:
	INCBIN "data/data_00e5a4.bin"

SECTION "data_00e5b5", ROMX[$65b5], BANK[$03]
Data_03_65b5:
	INCBIN "data/data_00e5b5.bin"

SECTION "data_00e5c2", ROMX[$65c2], BANK[$03]
Data_03_65c2:
	INCBIN "data/data_00e5c2.bin"

SECTION "data_00e80d", ROMX[$680d], BANK[$03]
Data_03_680d:
	INCBIN "data/data_00e80d.bin"

SECTION "data_00e816", ROMX[$6816], BANK[$03]
Data_03_6816:
	INCBIN "data/data_00e816.bin"

SECTION "data_00ea17", ROMX[$6a17], BANK[$03]
Data_03_6a17:
	INCBIN "data/data_00ea17.bin"

SECTION "data_00efc4", ROMX[$6fc4], BANK[$03]
Data_03_6fc4:
	INCBIN "data/data_00efc4.bin"

SECTION "data_00efca", ROMX[$6fca], BANK[$03]
Data_03_6fca:
	INCBIN "data/data_00efca.bin"

SECTION "data_00efd4", ROMX[$6fd4], BANK[$03]
Data_03_6fd4:
	INCBIN "data/data_00efd4.bin"

SECTION "data_00efde", ROMX[$6fde], BANK[$03]
Data_03_6fde:
	INCBIN "data/data_00efde.bin"

SECTION "data_00eff2", ROMX[$6ff2], BANK[$03]
Data_03_6ff2:
	INCBIN "data/data_00eff2.bin"

SECTION "data_00effc", ROMX[$6ffc], BANK[$03]
Data_03_6ffc:
	INCBIN "data/data_00effc.bin"

SECTION "data_00f012", ROMX[$7012], BANK[$03]
Data_03_7012:
	INCBIN "data/data_00f012.bin"

SECTION "data_00f028", ROMX[$7028], BANK[$03]
Data_03_7028:
	INCBIN "data/data_00f028.bin"

SECTION "data_00f02e", ROMX[$702e], BANK[$03]
Data_03_702e:
	INCBIN "data/data_00f02e.bin"

SECTION "data_00f038", ROMX[$7038], BANK[$03]
Data_03_7038:
	INCBIN "data/data_00f038.bin"

SECTION "data_00f042", ROMX[$7042], BANK[$03]
Data_03_7042:
	INCBIN "data/data_00f042.bin"

SECTION "data_00f0ce", ROMX[$70ce], BANK[$03]
Data_03_70ce:
	INCBIN "data/data_00f0ce.bin"

SECTION "data_00f0de", ROMX[$70de], BANK[$03]
Data_03_70de:
	INCBIN "data/data_00f0de.bin"

SECTION "data_00f0e9", ROMX[$70e9], BANK[$03]
Data_03_70e9:
	INCBIN "data/data_00f0e9.bin"

SECTION "data_00f0f9", ROMX[$70f9], BANK[$03]
Data_03_70f9:
	INCBIN "data/data_00f0f9.bin"

SECTION "data_00f106", ROMX[$7106], BANK[$03]
Data_03_7106:
	INCBIN "data/data_00f106.bin"

SECTION "data_00f126", ROMX[$7126], BANK[$03]
Data_03_7126:
	INCBIN "data/data_00f126.bin"

SECTION "data_00f139", ROMX[$7139], BANK[$03]
Data_03_7139:
	INCBIN "data/data_00f139.bin"

SECTION "data_00f157", ROMX[$7157], BANK[$03]
Data_03_7157:
	INCBIN "data/data_00f157.bin"

SECTION "data_00f173", ROMX[$7173], BANK[$03]
Data_03_7173:
	INCBIN "data/data_00f173.bin"

SECTION "data_00f192", ROMX[$7192], BANK[$03]
Data_03_7192:
	INCBIN "data/data_00f192.bin"

SECTION "data_00f493", ROMX[$7493], BANK[$03]
Data_03_7493:
	INCBIN "data/data_00f493.bin"

SECTION "data_00f4b2", ROMX[$74b2], BANK[$03]
Data_03_74b2:
	INCBIN "data/data_00f4b2.bin"

SECTION "data_00f75b", ROMX[$775b], BANK[$03]
Data_03_775b:
	INCBIN "data/data_00f75b.bin"

SECTION "data_00f782", ROMX[$7782], BANK[$03]
Data_03_7782:
	INCBIN "data/data_00f782.bin"

SECTION "data_00f9a2", ROMX[$79a2], BANK[$03]
Data_03_79a2:
	INCBIN "data/data_00f9a2.bin"

SECTION "data_00f9b9", ROMX[$79b9], BANK[$03]
Data_03_79b9:
	INCBIN "data/data_00f9b9.bin"

SECTION "data_00f9f5", ROMX[$79f5], BANK[$03]
Data_03_79f5:
	INCBIN "data/data_00f9f5.bin"

SECTION "data_00fa0b", ROMX[$7a0b], BANK[$03]
Data_03_7a0b:
	INCBIN "data/data_00fa0b.bin"

SECTION "data_00fa35", ROMX[$7a35], BANK[$03]
Data_03_7a35:
	INCBIN "data/data_00fa35.bin"

SECTION "data_00fa4b", ROMX[$7a4b], BANK[$03]
Data_03_7a4b:
	INCBIN "data/data_00fa4b.bin"

SECTION "data_00fb80", ROMX[$7b80], BANK[$03]
Data_03_7b80:
	INCBIN "data/data_00fb80.bin"

SECTION "data_00fbce", ROMX[$7bce], BANK[$03]
Data_03_7bce:
	INCBIN "data/data_00fbce.bin"

SECTION "data_00fce9", ROMX[$7ce9], BANK[$03]
Data_03_7ce9:
	INCBIN "data/data_00fce9.bin"

SECTION "data_00fcfb", ROMX[$7cfb], BANK[$03]
Data_03_7cfb:
	INCBIN "data/data_00fcfb.bin"

SECTION "data_00fd41", ROMX[$7d41], BANK[$03]
Data_03_7d41:
	INCBIN "data/data_00fd41.bin"

SECTION "data_00fd70", ROMX[$7d70], BANK[$03]
Data_03_7d70:
	INCBIN "data/data_00fd70.bin"

SECTION "data_00fd7c", ROMX[$7d7c], BANK[$03]
Data_03_7d7c:
	INCBIN "data/data_00fd7c.bin"

SECTION "data_00fd88", ROMX[$7d88], BANK[$03]
Data_03_7d88:
	INCBIN "data/data_00fd88.bin"

SECTION "data_010398", ROMX[$4398], BANK[$04]
Data_04_4398:
	INCBIN "data/data_010398.bin"

SECTION "data_01043c", ROMX[$443c], BANK[$04]
Data_04_443c:
	INCBIN "data/data_01043c.bin"

SECTION "data_010474", ROMX[$4474], BANK[$04]
Data_04_4474:
	INCBIN "data/data_010474.bin"

SECTION "data_010491", ROMX[$4491], BANK[$04]
Data_04_4491:
	INCBIN "data/data_010491.bin"

SECTION "data_010498", ROMX[$4498], BANK[$04]
Data_04_4498:
	INCBIN "data/data_010498.bin"

SECTION "data_01049e", ROMX[$449e], BANK[$04]
Data_04_449e:
	INCBIN "data/data_01049e.bin"

SECTION "data_0104a2", ROMX[$44a2], BANK[$04]
Data_04_44a2:
	INCBIN "data/data_0104a2.bin"

SECTION "data_0104a7", ROMX[$44a7], BANK[$04]
Data_04_44a7:
	INCBIN "data/data_0104a7.bin"

SECTION "data_0104f6", ROMX[$44f6], BANK[$04]
Data_04_44f6:
	INCBIN "data/data_0104f6.bin"

SECTION "data_0104fe", ROMX[$44fe], BANK[$04]
Data_04_44fe:
	INCBIN "data/data_0104fe.bin"

SECTION "data_010506", ROMX[$4506], BANK[$04]
Data_04_4506:
	INCBIN "data/data_010506.bin"

SECTION "data_01050e", ROMX[$450e], BANK[$04]
Data_04_450e:
	INCBIN "data/data_01050e.bin"

SECTION "data_01051e", ROMX[$451e], BANK[$04]
Data_04_451e:
	INCBIN "data/data_01051e.bin"

SECTION "data_01052e", ROMX[$452e], BANK[$04]
Data_04_452e:
	INCBIN "data/data_01052e.bin"

SECTION "data_010536", ROMX[$4536], BANK[$04]
Data_04_4536:
	INCBIN "data/data_010536.bin"

SECTION "data_01053e", ROMX[$453e], BANK[$04]
Data_04_453e:
	INCBIN "data/data_01053e.bin"

SECTION "data_010546", ROMX[$4546], BANK[$04]
Data_04_4546:
	INCBIN "data/data_010546.bin"

SECTION "data_01054e", ROMX[$454e], BANK[$04]
Data_04_454e:
	INCBIN "data/data_01054e.bin"

SECTION "data_010556", ROMX[$4556], BANK[$04]
Data_04_4556:
	INCBIN "data/data_010556.bin"

SECTION "data_01055e", ROMX[$455e], BANK[$04]
Data_04_455e:
	INCBIN "data/data_01055e.bin"

SECTION "data_010566", ROMX[$4566], BANK[$04]
Data_04_4566:
	INCBIN "data/data_010566.bin"

SECTION "data_01056e", ROMX[$456e], BANK[$04]
Data_04_456e:
	INCBIN "data/data_01056e.bin"

SECTION "data_010576", ROMX[$4576], BANK[$04]
Data_04_4576:
	INCBIN "data/data_010576.bin"

SECTION "data_01057e", ROMX[$457e], BANK[$04]
Data_04_457e:
	INCBIN "data/data_01057e.bin"

SECTION "data_0105ab", ROMX[$45ab], BANK[$04]
Data_04_45ab:
	INCBIN "data/data_0105ab.bin"

SECTION "data_0105ee", ROMX[$45ee], BANK[$04]
Data_04_45ee:
	INCBIN "data/data_0105ee.bin"

SECTION "data_0105f6", ROMX[$45f6], BANK[$04]
Data_04_45f6:
	INCBIN "data/data_0105f6.bin"

SECTION "data_0105fe", ROMX[$45fe], BANK[$04]
Data_04_45fe:
	INCBIN "data/data_0105fe.bin"

SECTION "data_010606", ROMX[$4606], BANK[$04]
Data_04_4606:
	INCBIN "data/data_010606.bin"

SECTION "data_01060e", ROMX[$460e], BANK[$04]
Data_04_460e:
	INCBIN "data/data_01060e.bin"

SECTION "data_010616", ROMX[$4616], BANK[$04]
Data_04_4616:
	INCBIN "data/data_010616.bin"

SECTION "data_01061e", ROMX[$461e], BANK[$04]
Data_04_461e:
	INCBIN "data/data_01061e.bin"

SECTION "data_010626", ROMX[$4626], BANK[$04]
Data_04_4626:
	INCBIN "data/data_010626.bin"

SECTION "data_01062e", ROMX[$462e], BANK[$04]
Data_04_462e:
	INCBIN "data/data_01062e.bin"

SECTION "data_010636", ROMX[$4636], BANK[$04]
Data_04_4636:
	INCBIN "data/data_010636.bin"

SECTION "data_01063e", ROMX[$463e], BANK[$04]
Data_04_463e:
	INCBIN "data/data_01063e.bin"

SECTION "data_010646", ROMX[$4646], BANK[$04]
Data_04_4646:
	INCBIN "data/data_010646.bin"

SECTION "data_01064e", ROMX[$464e], BANK[$04]
Data_04_464e:
	INCBIN "data/data_01064e.bin"

SECTION "data_010656", ROMX[$4656], BANK[$04]
Data_04_4656:
	INCBIN "data/data_010656.bin"

SECTION "data_01065e", ROMX[$465e], BANK[$04]
Data_04_465e:
	INCBIN "data/data_01065e.bin"

SECTION "data_010666", ROMX[$4666], BANK[$04]
Data_04_4666:
	INCBIN "data/data_010666.bin"

SECTION "data_01066e", ROMX[$466e], BANK[$04]
Data_04_466e:
	INCBIN "data/data_01066e.bin"

SECTION "data_010676", ROMX[$4676], BANK[$04]
Data_04_4676:
	INCBIN "data/data_010676.bin"

SECTION "data_01067e", ROMX[$467e], BANK[$04]
Data_04_467e:
	INCBIN "data/data_01067e.bin"

SECTION "data_010686", ROMX[$4686], BANK[$04]
Data_04_4686:
	INCBIN "data/data_010686.bin"

SECTION "data_01068e", ROMX[$468e], BANK[$04]
Data_04_468e:
	INCBIN "data/data_01068e.bin"

SECTION "data_010696", ROMX[$4696], BANK[$04]
Data_04_4696:
	INCBIN "data/data_010696.bin"

SECTION "data_01069e", ROMX[$469e], BANK[$04]
Data_04_469e:
	INCBIN "data/data_01069e.bin"

SECTION "data_0106a6", ROMX[$46a6], BANK[$04]
Data_04_46a6:
	INCBIN "data/data_0106a6.bin"

SECTION "data_0106ae", ROMX[$46ae], BANK[$04]
Data_04_46ae:
	INCBIN "data/data_0106ae.bin"

SECTION "data_0106b6", ROMX[$46b6], BANK[$04]
Data_04_46b6:
	INCBIN "data/data_0106b6.bin"

SECTION "data_0106be", ROMX[$46be], BANK[$04]
Data_04_46be:
	INCBIN "data/data_0106be.bin"

SECTION "data_0106c6", ROMX[$46c6], BANK[$04]
Data_04_46c6:
	INCBIN "data/data_0106c6.bin"

SECTION "data_0106ce", ROMX[$46ce], BANK[$04]
Data_04_46ce:
	INCBIN "data/data_0106ce.bin"

SECTION "data_0106d6", ROMX[$46d6], BANK[$04]
Data_04_46d6:
	INCBIN "data/data_0106d6.bin"

SECTION "data_0106eb", ROMX[$46eb], BANK[$04]
Data_04_46eb:
	INCBIN "data/data_0106eb.bin"

SECTION "data_01070b", ROMX[$470b], BANK[$04]
Data_04_470b:
	INCBIN "data/data_01070b.bin"

SECTION "data_01072b", ROMX[$472b], BANK[$04]
Data_04_472b:
	INCBIN "data/data_01072b.bin"

SECTION "data_01075e", ROMX[$475e], BANK[$04]
Data_04_475e:
	INCBIN "data/data_01075e.bin"

SECTION "data_010766", ROMX[$4766], BANK[$04]
Data_04_4766:
	INCBIN "data/data_010766.bin"

SECTION "data_01076e", ROMX[$476e], BANK[$04]
Data_04_476e:
	INCBIN "data/data_01076e.bin"

SECTION "data_010776", ROMX[$4776], BANK[$04]
Data_04_4776:
	INCBIN "data/data_010776.bin"

SECTION "data_01077e", ROMX[$477e], BANK[$04]
Data_04_477e:
	INCBIN "data/data_01077e.bin"

SECTION "data_010786", ROMX[$4786], BANK[$04]
Data_04_4786:
	INCBIN "data/data_010786.bin"

SECTION "data_01078e", ROMX[$478e], BANK[$04]
Data_04_478e:
	INCBIN "data/data_01078e.bin"

SECTION "data_0107be", ROMX[$47be], BANK[$04]
Data_04_47be:
	INCBIN "data/data_0107be.bin"

SECTION "data_0107c6", ROMX[$47c6], BANK[$04]
Data_04_47c6:
	INCBIN "data/data_0107c6.bin"

SECTION "data_0107ce", ROMX[$47ce], BANK[$04]
Data_04_47ce:
	INCBIN "data/data_0107ce.bin"

SECTION "data_0107d6", ROMX[$47d6], BANK[$04]
Data_04_47d6:
	INCBIN "data/data_0107d6.bin"

SECTION "data_0107de", ROMX[$47de], BANK[$04]
Data_04_47de:
	INCBIN "data/data_0107de.bin"

SECTION "data_0107e6", ROMX[$47e6], BANK[$04]
Data_04_47e6:
	INCBIN "data/data_0107e6.bin"

SECTION "data_0107ee", ROMX[$47ee], BANK[$04]
Data_04_47ee:
	INCBIN "data/data_0107ee.bin"

SECTION "data_0107f6", ROMX[$47f6], BANK[$04]
Data_04_47f6:
	INCBIN "data/data_0107f6.bin"

SECTION "data_0107fe", ROMX[$47fe], BANK[$04]
Data_04_47fe:
	INCBIN "data/data_0107fe.bin"

SECTION "data_010823", ROMX[$4823], BANK[$04]
Data_04_4823:
	INCBIN "data/data_010823.bin"

SECTION "data_01084e", ROMX[$484e], BANK[$04]
Data_04_484e:
	INCBIN "data/data_01084e.bin"

SECTION "data_010852", ROMX[$4852], BANK[$04]
Data_04_4852:
	INCBIN "data/data_010852.bin"

SECTION "data_010860", ROMX[$4860], BANK[$04]
Data_04_4860:
	INCBIN "data/data_010860.bin"

SECTION "data_010864", ROMX[$4864], BANK[$04]
Data_04_4864:
	INCBIN "data/data_010864.bin"

SECTION "data_01086e", ROMX[$486e], BANK[$04]
Data_04_486e:
	INCBIN "data/data_01086e.bin"

SECTION "data_010888", ROMX[$4888], BANK[$04]
Data_04_4888:
	INCBIN "data/data_010888.bin"

SECTION "data_010890", ROMX[$4890], BANK[$04]
Data_04_4890:
	INCBIN "data/data_010890.bin"

SECTION "data_01089a", ROMX[$489a], BANK[$04]
Data_04_489a:
	INCBIN "data/data_01089a.bin"

SECTION "data_010a08", ROMX[$4a08], BANK[$04]
Data_04_4a08:
	INCBIN "data/data_010a08.bin"

SECTION "data_010a12", ROMX[$4a12], BANK[$04]
Data_04_4a12:
	INCBIN "data/data_010a12.bin"

SECTION "data_010a30", ROMX[$4a30], BANK[$04]
Data_04_4a30:
	INCBIN "data/data_010a30.bin"

SECTION "data_010a3a", ROMX[$4a3a], BANK[$04]
Data_04_4a3a:
	INCBIN "data/data_010a3a.bin"

SECTION "data_010a79", ROMX[$4a79], BANK[$04]
Data_04_4a79:
	INCBIN "data/data_010a79.bin"

SECTION "data_010ac2", ROMX[$4ac2], BANK[$04]
Data_04_4ac2:
	INCBIN "data/data_010ac2.bin"

SECTION "data_010ae6", ROMX[$4ae6], BANK[$04]
Data_04_4ae6:
	INCBIN "data/data_010ae6.bin"

SECTION "data_010b26", ROMX[$4b26], BANK[$04]
Data_04_4b26:
	INCBIN "data/data_010b26.bin"

SECTION "data_010be9", ROMX[$4be9], BANK[$04]
Data_04_4be9:
	INCBIN "data/data_010be9.bin"

SECTION "data_010ca9", ROMX[$4ca9], BANK[$04]
Data_04_4ca9:
	INCBIN "data/data_010ca9.bin"

SECTION "data_010cd5", ROMX[$4cd5], BANK[$04]
Data_04_4cd5:
	INCBIN "data/data_010cd5.bin"

SECTION "data_010d29", ROMX[$4d29], BANK[$04]
Data_04_4d29:
	INCBIN "data/data_010d29.bin"

SECTION "data_010d36", ROMX[$4d36], BANK[$04]
Data_04_4d36:
	INCBIN "data/data_010d36.bin"

SECTION "data_010d62", ROMX[$4d62], BANK[$04]
Data_04_4d62:
	INCBIN "data/data_010d62.bin"

SECTION "data_010d7a", ROMX[$4d7a], BANK[$04]
Data_04_4d7a:
	INCBIN "data/data_010d7a.bin"

SECTION "data_010de1", ROMX[$4de1], BANK[$04]
Data_04_4de1:
	INCBIN "data/data_010de1.bin"

SECTION "data_010de9", ROMX[$4de9], BANK[$04]
Data_04_4de9:
	INCBIN "data/data_010de9.bin"

SECTION "data_010dee", ROMX[$4dee], BANK[$04]
Data_04_4dee:
	INCBIN "data/data_010dee.bin"

SECTION "data_010e1d", ROMX[$4e1d], BANK[$04]
Data_04_4e1d:
	INCBIN "data/data_010e1d.bin"

SECTION "data_010e2d", ROMX[$4e2d], BANK[$04]
Data_04_4e2d:
	INCBIN "data/data_010e2d.bin"

SECTION "data_010e37", ROMX[$4e37], BANK[$04]
Data_04_4e37:
	INCBIN "data/data_010e37.bin"

SECTION "data_010e85", ROMX[$4e85], BANK[$04]
Data_04_4e85:
	INCBIN "data/data_010e85.bin"

SECTION "data_010e89", ROMX[$4e89], BANK[$04]
Data_04_4e89:
	INCBIN "data/data_010e89.bin"

SECTION "data_010e8d", ROMX[$4e8d], BANK[$04]
Data_04_4e8d:
	INCBIN "data/data_010e8d.bin"

SECTION "data_010e97", ROMX[$4e97], BANK[$04]
Data_04_4e97:
	INCBIN "data/data_010e97.bin"

SECTION "data_010f29", ROMX[$4f29], BANK[$04]
Data_04_4f29:
	INCBIN "data/data_010f29.bin"

SECTION "data_010f57", ROMX[$4f57], BANK[$04]
Data_04_4f57:
	INCBIN "data/data_010f57.bin"

SECTION "data_010f67", ROMX[$4f67], BANK[$04]
Data_04_4f67:
	INCBIN "data/data_010f67.bin"

SECTION "data_010fd0", ROMX[$4fd0], BANK[$04]
Data_04_4fd0:
	INCBIN "data/data_010fd0.bin"

SECTION "data_011003", ROMX[$5003], BANK[$04]
Data_04_5003:
	INCBIN "data/data_011003.bin"

SECTION "data_011064", ROMX[$5064], BANK[$04]
Data_04_5064:
	INCBIN "data/data_011064.bin"

SECTION "data_01106f", ROMX[$506f], BANK[$04]
Data_04_506f:
	INCBIN "data/data_01106f.bin"

SECTION "data_0110a9", ROMX[$50a9], BANK[$04]
Data_04_50a9:
	INCBIN "data/data_0110a9.bin"

SECTION "data_01110a", ROMX[$510a], BANK[$04]
Data_04_510a:
	INCBIN "data/data_01110a.bin"

SECTION "data_011115", ROMX[$5115], BANK[$04]
Data_04_5115:
	INCBIN "data/data_011115.bin"

SECTION "data_01113e", ROMX[$513e], BANK[$04]
Data_04_513e:
	INCBIN "data/data_01113e.bin"

SECTION "data_011174", ROMX[$5174], BANK[$04]
Data_04_5174:
	INCBIN "data/data_011174.bin"

SECTION "data_011194", ROMX[$5194], BANK[$04]
Data_04_5194:
	INCBIN "data/data_011194.bin"

SECTION "data_01119b", ROMX[$519b], BANK[$04]
Data_04_519b:
	INCBIN "data/data_01119b.bin"

SECTION "data_01119f", ROMX[$519f], BANK[$04]
Data_04_519f:
	INCBIN "data/data_01119f.bin"

SECTION "data_0111be", ROMX[$51be], BANK[$04]
Data_04_51be:
	INCBIN "data/data_0111be.bin"

SECTION "data_011229", ROMX[$5229], BANK[$04]
Data_04_5229:
	INCBIN "data/data_011229.bin"

SECTION "data_011234", ROMX[$5234], BANK[$04]
Data_04_5234:
	INCBIN "data/data_011234.bin"

SECTION "data_011267", ROMX[$5267], BANK[$04]
Data_04_5267:
	INCBIN "data/data_011267.bin"

SECTION "data_0112c0", ROMX[$52c0], BANK[$04]
Data_04_52c0:
	INCBIN "data/data_0112c0.bin"

SECTION "data_0112cd", ROMX[$52cd], BANK[$04]
Data_04_52cd:
	INCBIN "data/data_0112cd.bin"

SECTION "data_0112f4", ROMX[$52f4], BANK[$04]
Data_04_52f4:
	INCBIN "data/data_0112f4.bin"

SECTION "data_01130e", ROMX[$530e], BANK[$04]
Data_04_530e:
	INCBIN "data/data_01130e.bin"

SECTION "data_011372", ROMX[$5372], BANK[$04]
Data_04_5372:
	INCBIN "data/data_011372.bin"

SECTION "data_01137f", ROMX[$537f], BANK[$04]
Data_04_537f:
	INCBIN "data/data_01137f.bin"

SECTION "data_01143c", ROMX[$543c], BANK[$04]
Data_04_543c:
	INCBIN "data/data_01143c.bin"

SECTION "data_01148c", ROMX[$548c], BANK[$04]
Data_04_548c:
	INCBIN "data/data_01148c.bin"

SECTION "data_0115be", ROMX[$55be], BANK[$04]
Data_04_55be:
	INCBIN "data/data_0115be.bin"

SECTION "data_0115c6", ROMX[$55c6], BANK[$04]
Data_04_55c6:
	INCBIN "data/data_0115c6.bin"

SECTION "data_0115de", ROMX[$55de], BANK[$04]
Data_04_55de:
	INCBIN "data/data_0115de.bin"

SECTION "data_0115e7", ROMX[$55e7], BANK[$04]
Data_04_55e7:
	INCBIN "data/data_0115e7.bin"

SECTION "data_01160d", ROMX[$560d], BANK[$04]
Data_04_560d:
	INCBIN "data/data_01160d.bin"

SECTION "data_011678", ROMX[$5678], BANK[$04]
Data_04_5678:
	INCBIN "data/data_011678.bin"

SECTION "data_01167f", ROMX[$567f], BANK[$04]
Data_04_567f:
	INCBIN "data/data_01167f.bin"

SECTION "data_0116f7", ROMX[$56f7], BANK[$04]
Data_04_56f7:
	INCBIN "data/data_0116f7.bin"

SECTION "data_011726", ROMX[$5726], BANK[$04]
Data_04_5726:
	INCBIN "data/data_011726.bin"

SECTION "data_011753", ROMX[$5753], BANK[$04]
Data_04_5753:
	INCBIN "data/data_011753.bin"

SECTION "data_01178c", ROMX[$578c], BANK[$04]
Data_04_578c:
	INCBIN "data/data_01178c.bin"

SECTION "data_011794", ROMX[$5794], BANK[$04]
Data_04_5794:
	INCBIN "data/data_011794.bin"

SECTION "data_01179c", ROMX[$579c], BANK[$04]
Data_04_579c:
	INCBIN "data/data_01179c.bin"

SECTION "data_0117bf", ROMX[$57bf], BANK[$04]
Data_04_57bf:
	INCBIN "data/data_0117bf.bin"

SECTION "data_01180c", ROMX[$580c], BANK[$04]
Data_04_580c:
	INCBIN "data/data_01180c.bin"

SECTION "data_011850", ROMX[$5850], BANK[$04]
Data_04_5850:
	INCBIN "data/data_011850.bin"

SECTION "data_011858", ROMX[$5858], BANK[$04]
Data_04_5858:
	INCBIN "data/data_011858.bin"

SECTION "data_011860", ROMX[$5860], BANK[$04]
Data_04_5860:
	INCBIN "data/data_011860.bin"

SECTION "data_011865", ROMX[$5865], BANK[$04]
Data_04_5865:
	INCBIN "data/data_011865.bin"

SECTION "data_011870", ROMX[$5870], BANK[$04]
Data_04_5870:
	INCBIN "data/data_011870.bin"

SECTION "data_0118a3", ROMX[$58a3], BANK[$04]
Data_04_58a3:
	INCBIN "data/data_0118a3.bin"

SECTION "data_0118b3", ROMX[$58b3], BANK[$04]
Data_04_58b3:
	INCBIN "data/data_0118b3.bin"

SECTION "data_0118e1", ROMX[$58e1], BANK[$04]
Data_04_58e1:
	INCBIN "data/data_0118e1.bin"

SECTION "data_0118f9", ROMX[$58f9], BANK[$04]
Data_04_58f9:
	INCBIN "data/data_0118f9.bin"

SECTION "data_01191a", ROMX[$591a], BANK[$04]
Data_04_591a:
	INCBIN "data/data_01191a.bin"

SECTION "data_011948", ROMX[$5948], BANK[$04]
Data_04_5948:
	INCBIN "data/data_011948.bin"

SECTION "data_01196c", ROMX[$596c], BANK[$04]
Data_04_596c:
	INCBIN "data/data_01196c.bin"

SECTION "data_01199b", ROMX[$599b], BANK[$04]
Data_04_599b:
	INCBIN "data/data_01199b.bin"

SECTION "data_0119bb", ROMX[$59bb], BANK[$04]
Data_04_59bb:
	INCBIN "data/data_0119bb.bin"

SECTION "data_011a2d", ROMX[$5a2d], BANK[$04]
Data_04_5a2d:
	INCBIN "data/data_011a2d.bin"

SECTION "data_011a4e", ROMX[$5a4e], BANK[$04]
Data_04_5a4e:
	INCBIN "data/data_011a4e.bin"

SECTION "data_011a83", ROMX[$5a83], BANK[$04]
Data_04_5a83:
	INCBIN "data/data_011a83.bin"

SECTION "data_011aea", ROMX[$5aea], BANK[$04]
Data_04_5aea:
	INCBIN "data/data_011aea.bin"

SECTION "data_011b0a", ROMX[$5b0a], BANK[$04]
Data_04_5b0a:
	INCBIN "data/data_011b0a.bin"

SECTION "data_011b22", ROMX[$5b22], BANK[$04]
Data_04_5b22:
	INCBIN "data/data_011b22.bin"

SECTION "data_011b35", ROMX[$5b35], BANK[$04]
Data_04_5b35:
	INCBIN "data/data_011b35.bin"

SECTION "data_011b74", ROMX[$5b74], BANK[$04]
Data_04_5b74:
	INCBIN "data/data_011b74.bin"

SECTION "data_011b88", ROMX[$5b88], BANK[$04]
Data_04_5b88:
	INCBIN "data/data_011b88.bin"

SECTION "data_011bf8", ROMX[$5bf8], BANK[$04]
Data_04_5bf8:
	INCBIN "data/data_011bf8.bin"

SECTION "data_011c18", ROMX[$5c18], BANK[$04]
Data_04_5c18:
	INCBIN "data/data_011c18.bin"

SECTION "data_011c20", ROMX[$5c20], BANK[$04]
Data_04_5c20:
	INCBIN "data/data_011c20.bin"

SECTION "data_011c2f", ROMX[$5c2f], BANK[$04]
Data_04_5c2f:
	INCBIN "data/data_011c2f.bin"

SECTION "data_011c35", ROMX[$5c35], BANK[$04]
Data_04_5c35:
	INCBIN "data/data_011c35.bin"

SECTION "data_011c8b", ROMX[$5c8b], BANK[$04]
Data_04_5c8b:
	INCBIN "data/data_011c8b.bin"

SECTION "data_011cb6", ROMX[$5cb6], BANK[$04]
Data_04_5cb6:
	INCBIN "data/data_011cb6.bin"

SECTION "data_011d04", ROMX[$5d04], BANK[$04]
Data_04_5d04:
	INCBIN "data/data_011d04.bin"

SECTION "data_011d0c", ROMX[$5d0c], BANK[$04]
Data_04_5d0c:
	INCBIN "data/data_011d0c.bin"

SECTION "data_011d14", ROMX[$5d14], BANK[$04]
Data_04_5d14:
	INCBIN "data/data_011d14.bin"

SECTION "data_011d1c", ROMX[$5d1c], BANK[$04]
Data_04_5d1c:
	INCBIN "data/data_011d1c.bin"

SECTION "data_011d21", ROMX[$5d21], BANK[$04]
Data_04_5d21:
	INCBIN "data/data_011d21.bin"

SECTION "data_011d27", ROMX[$5d27], BANK[$04]
Data_04_5d27:
	INCBIN "data/data_011d27.bin"

SECTION "data_011d5e", ROMX[$5d5e], BANK[$04]
Data_04_5d5e:
	INCBIN "data/data_011d5e.bin"

SECTION "data_011d89", ROMX[$5d89], BANK[$04]
Data_04_5d89:
	INCBIN "data/data_011d89.bin"

SECTION "data_011d91", ROMX[$5d91], BANK[$04]
Data_04_5d91:
	INCBIN "data/data_011d91.bin"

SECTION "data_011d99", ROMX[$5d99], BANK[$04]
Data_04_5d99:
	INCBIN "data/data_011d99.bin"

SECTION "data_011da1", ROMX[$5da1], BANK[$04]
Data_04_5da1:
	INCBIN "data/data_011da1.bin"

SECTION "data_011da9", ROMX[$5da9], BANK[$04]
Data_04_5da9:
	INCBIN "data/data_011da9.bin"

SECTION "data_011db1", ROMX[$5db1], BANK[$04]
Data_04_5db1:
	INCBIN "data/data_011db1.bin"

SECTION "data_011db9", ROMX[$5db9], BANK[$04]
Data_04_5db9:
	INCBIN "data/data_011db9.bin"

SECTION "data_011dc1", ROMX[$5dc1], BANK[$04]
Data_04_5dc1:
	INCBIN "data/data_011dc1.bin"

SECTION "data_011dc6", ROMX[$5dc6], BANK[$04]
Data_04_5dc6:
	INCBIN "data/data_011dc6.bin"

SECTION "data_011e11", ROMX[$5e11], BANK[$04]
Data_04_5e11:
	INCBIN "data/data_011e11.bin"

SECTION "data_011e2e", ROMX[$5e2e], BANK[$04]
Data_04_5e2e:
	INCBIN "data/data_011e2e.bin"

SECTION "data_011e83", ROMX[$5e83], BANK[$04]
Data_04_5e83:
	INCBIN "data/data_011e83.bin"

SECTION "data_011ee8", ROMX[$5ee8], BANK[$04]
Data_04_5ee8:
	INCBIN "data/data_011ee8.bin"

SECTION "data_011f07", ROMX[$5f07], BANK[$04]
Data_04_5f07:
	INCBIN "data/data_011f07.bin"

SECTION "data_011f10", ROMX[$5f10], BANK[$04]
Data_04_5f10:
	INCBIN "data/data_011f10.bin"

SECTION "data_011f1e", ROMX[$5f1e], BANK[$04]
Data_04_5f1e:
	INCBIN "data/data_011f1e.bin"

SECTION "data_011f41", ROMX[$5f41], BANK[$04]
Data_04_5f41:
	INCBIN "data/data_011f41.bin"

SECTION "data_0140cf", ROMX[$40cf], BANK[$05]
Data_05_40cf:
	INCBIN "data/data_0140cf.bin"

SECTION "data_0140df", ROMX[$40df], BANK[$05]
Data_05_40df:
	INCBIN "data/data_0140df.bin"

SECTION "data_0142a7", ROMX[$42a7], BANK[$05]
Data_05_42a7:
	INCBIN "data/data_0142a7.bin"

SECTION "data_014a0c", ROMX[$4a0c], BANK[$05]
Data_05_4a0c:
	INCBIN "data/data_014a0c.bin"

SECTION "data_014a1c", ROMX[$4a1c], BANK[$05]
Data_05_4a1c:
	INCBIN "data/data_014a1c.bin"

SECTION "data_014b46", ROMX[$4b46], BANK[$05]
Data_05_4b46:
	INCBIN "data/data_014b46.bin"

SECTION "data_014be2", ROMX[$4be2], BANK[$05]
Data_05_4be2:
	INCBIN "data/data_014be2.bin"

SECTION "data_014d53", ROMX[$4d53], BANK[$05]
Data_05_4d53:
	INCBIN "data/data_014d53.bin"

SECTION "data_015057", ROMX[$5057], BANK[$05]
Data_05_5057:
	INCBIN "data/data_015057.bin"

SECTION "data_015587", ROMX[$5587], BANK[$05]
Data_05_5587:
	INCBIN "data/data_015587.bin"

SECTION "data_01596d", ROMX[$596d], BANK[$05]
Data_05_596d:
	INCBIN "data/data_01596d.bin"

SECTION "data_03c10a", ROMX[$410a], BANK[$0f]
Data_0f_410a:
	INCBIN "data/data_03c10a.bin"

SECTION "data_03c2ce", ROMX[$42ce], BANK[$0f]
Data_0f_42ce:
	INCBIN "data/data_03c2ce.bin"

SECTION "data_03c66a", ROMX[$466a], BANK[$0f]
Data_0f_466a:
	INCBIN "data/data_03c66a.bin"

SECTION "data_03c784", ROMX[$4784], BANK[$0f]
Data_0f_4784:
	INCBIN "data/data_03c784.bin"

SECTION "data_03c9b9", ROMX[$49b9], BANK[$0f]
Data_0f_49b9:
	INCBIN "data/data_03c9b9.bin"

SECTION "data_03cab7", ROMX[$4ab7], BANK[$0f]
Data_0f_4ab7:
	INCBIN "data/data_03cab7.bin"

SECTION "data_03cc83", ROMX[$4c83], BANK[$0f]
Data_0f_4c83:
	INCBIN "data/data_03cc83.bin"

SECTION "data_03e84e", ROMX[$684e], BANK[$0f]
Data_0f_684e:
	INCBIN "data/data_03e84e.bin"

SECTION "data_03f12f", ROMX[$712f], BANK[$0f]
Data_0f_712f:
	INCBIN "data/data_03f12f.bin"

SECTION "data_03f1c9", ROMX[$71c9], BANK[$0f]
Data_0f_71c9:
	INCBIN "data/data_03f1c9.bin"

SECTION "data_03f211", ROMX[$7211], BANK[$0f]
Data_0f_7211:
	INCBIN "data/data_03f211.bin"

SECTION "data_03f249", ROMX[$7249], BANK[$0f]
Data_0f_7249:
	INCBIN "data/data_03f249.bin"

SECTION "data_03f291", ROMX[$7291], BANK[$0f]
Data_0f_7291:
	INCBIN "data/data_03f291.bin"

SECTION "data_03f2c9", ROMX[$72c9], BANK[$0f]
Data_0f_72c9:
	INCBIN "data/data_03f2c9.bin"

SECTION "data_03f311", ROMX[$7311], BANK[$0f]
Data_0f_7311:
	INCBIN "data/data_03f311.bin"

SECTION "data_03f349", ROMX[$7349], BANK[$0f]
Data_0f_7349:
	INCBIN "data/data_03f349.bin"

SECTION "data_03f391", ROMX[$7391], BANK[$0f]
Data_0f_7391:
	INCBIN "data/data_03f391.bin"

SECTION "data_03f3c9", ROMX[$73c9], BANK[$0f]
Data_0f_73c9:
	INCBIN "data/data_03f3c9.bin"

SECTION "data_03f411", ROMX[$7411], BANK[$0f]
Data_0f_7411:
	INCBIN "data/data_03f411.bin"

SECTION "data_03f449", ROMX[$7449], BANK[$0f]
Data_0f_7449:
	INCBIN "data/data_03f449.bin"

SECTION "data_03f491", ROMX[$7491], BANK[$0f]
Data_0f_7491:
	INCBIN "data/data_03f491.bin"

SECTION "data_03f4c9", ROMX[$74c9], BANK[$0f]
Data_0f_74c9:
	INCBIN "data/data_03f4c9.bin"

SECTION "data_040000", ROMX[$4000], BANK[$10]
Data_10_4000:
	INCBIN "data/data_040000.bin"

SECTION "data_04003a", ROMX[$403a], BANK[$10]
Data_10_403a:
	INCBIN "data/data_04003a.bin"

SECTION "data_0420ef", ROMX[$60ef], BANK[$10]
Data_10_60ef:
	INCBIN "data/data_0420ef.bin"

SECTION "data_04216f", ROMX[$616f], BANK[$10]
Data_10_616f:
	INCBIN "data/data_04216f.bin"

SECTION "data_0421ef", ROMX[$61ef], BANK[$10]
Data_10_61ef:
	INCBIN "data/data_0421ef.bin"

SECTION "data_04226f", ROMX[$626f], BANK[$10]
Data_10_626f:
	INCBIN "data/data_04226f.bin"

SECTION "data_0422ef", ROMX[$62ef], BANK[$10]
Data_10_62ef:
	INCBIN "data/data_0422ef.bin"

SECTION "data_04236f", ROMX[$636f], BANK[$10]
Data_10_636f:
	INCBIN "data/data_04236f.bin"

SECTION "data_0423ef", ROMX[$63ef], BANK[$10]
Data_10_63ef:
	INCBIN "data/data_0423ef.bin"

SECTION "data_04246f", ROMX[$646f], BANK[$10]
Data_10_646f:
	INCBIN "data/data_04246f.bin"

SECTION "data_0424ef", ROMX[$64ef], BANK[$10]
Data_10_64ef:
	INCBIN "data/data_0424ef.bin"

SECTION "data_04256f", ROMX[$656f], BANK[$10]
Data_10_656f:
	INCBIN "data/data_04256f.bin"

SECTION "data_0425ef", ROMX[$65ef], BANK[$10]
Data_10_65ef:
	INCBIN "data/data_0425ef.bin"

SECTION "data_04266f", ROMX[$666f], BANK[$10]
Data_10_666f:
	INCBIN "data/data_04266f.bin"

SECTION "data_044109", ROMX[$4109], BANK[$11]
Data_11_4109:
	INCBIN "data/data_044109.bin"

SECTION "data_044131", ROMX[$4131], BANK[$11]
Data_11_4131:
	INCBIN "data/data_044131.bin"

SECTION "data_04685c", ROMX[$685c], BANK[$11]
Data_11_685c:
	INCBIN "data/data_04685c.bin"

SECTION "data_047dc4", ROMX[$7dc4], BANK[$11]
Data_11_7dc4:
	INCBIN "data/data_047dc4.bin"

SECTION "data_048215", ROMX[$4215], BANK[$12]
Data_12_4215:
	INCBIN "data/data_048215.bin"

SECTION "data_04822c", ROMX[$422c], BANK[$12]
Data_12_422c:
	INCBIN "data/data_04822c.bin"

SECTION "data_048243", ROMX[$4243], BANK[$12]
Data_12_4243:
	INCBIN "data/data_048243.bin"

SECTION "data_048266", ROMX[$4266], BANK[$12]
Data_12_4266:
	INCBIN "data/data_048266.bin"

SECTION "data_0482e8", ROMX[$42e8], BANK[$12]
Data_12_42e8:
	INCBIN "data/data_0482e8.bin"

SECTION "data_0482fd", ROMX[$42fd], BANK[$12]
Data_12_42fd:
	INCBIN "data/data_0482fd.bin"

SECTION "data_048312", ROMX[$4312], BANK[$12]
Data_12_4312:
	INCBIN "data/data_048312.bin"

SECTION "data_048348", ROMX[$4348], BANK[$12]
Data_12_4348:
	INCBIN "data/data_048348.bin"

SECTION "data_0483e8", ROMX[$43e8], BANK[$12]
Data_12_43e8:
	INCBIN "data/data_0483e8.bin"

SECTION "data_0483ee", ROMX[$43ee], BANK[$12]
Data_12_43ee:
	INCBIN "data/data_0483ee.bin"

SECTION "data_0483f4", ROMX[$43f4], BANK[$12]
Data_12_43f4:
	INCBIN "data/data_0483f4.bin"

SECTION "data_0483fa", ROMX[$43fa], BANK[$12]
Data_12_43fa:
	INCBIN "data/data_0483fa.bin"

SECTION "data_04851e", ROMX[$451e], BANK[$12]
Data_12_451e:
	INCBIN "data/data_04851e.bin"

SECTION "data_04853b", ROMX[$453b], BANK[$12]
Data_12_453b:
	INCBIN "data/data_04853b.bin"

SECTION "data_04855b", ROMX[$455b], BANK[$12]
Data_12_455b:
	INCBIN "data/data_04855b.bin"

SECTION "data_048571", ROMX[$4571], BANK[$12]
Data_12_4571:
	INCBIN "data/data_048571.bin"

SECTION "data_048589", ROMX[$4589], BANK[$12]
Data_12_4589:
	INCBIN "data/data_048589.bin"

SECTION "data_0485b2", ROMX[$45b2], BANK[$12]
Data_12_45b2:
	INCBIN "data/data_0485b2.bin"

SECTION "data_0485cf", ROMX[$45cf], BANK[$12]
Data_12_45cf:
	INCBIN "data/data_0485cf.bin"

SECTION "data_048614", ROMX[$4614], BANK[$12]
Data_12_4614:
	INCBIN "data/data_048614.bin"

SECTION "data_048636", ROMX[$4636], BANK[$12]
Data_12_4636:
	INCBIN "data/data_048636.bin"

SECTION "data_048695", ROMX[$4695], BANK[$12]
Data_12_4695:
	INCBIN "data/data_048695.bin"

SECTION "data_0486e8", ROMX[$46e8], BANK[$12]
Data_12_46e8:
	INCBIN "data/data_0486e8.bin"

SECTION "data_0488e8", ROMX[$48e8], BANK[$12]
Data_12_48e8:
	INCBIN "data/data_0488e8.bin"

SECTION "data_048a75", ROMX[$4a75], BANK[$12]
Data_12_4a75:
	INCBIN "data/data_048a75.bin"

SECTION "data_048b44", ROMX[$4b44], BANK[$12]
Data_12_4b44:
	INCBIN "data/data_048b44.bin"

SECTION "data_048b9c", ROMX[$4b9c], BANK[$12]
Data_12_4b9c:
	INCBIN "data/data_048b9c.bin"

SECTION "data_048bfd", ROMX[$4bfd], BANK[$12]
Data_12_4bfd:
	INCBIN "data/data_048bfd.bin"

SECTION "data_048cad", ROMX[$4cad], BANK[$12]
Data_12_4cad:
	INCBIN "data/data_048cad.bin"

SECTION "data_048cb5", ROMX[$4cb5], BANK[$12]
Data_12_4cb5:
	INCBIN "data/data_048cb5.bin"

SECTION "data_048ccb", ROMX[$4ccb], BANK[$12]
Data_12_4ccb:
	INCBIN "data/data_048ccb.bin"

SECTION "data_049a4b", ROMX[$5a4b], BANK[$12]
Data_12_5a4b:
	INCBIN "data/data_049a4b.bin"

SECTION "data_049c90", ROMX[$5c90], BANK[$12]
Data_12_5c90:
	INCBIN "data/data_049c90.bin"

SECTION "data_049ed5", ROMX[$5ed5], BANK[$12]
Data_12_5ed5:
	INCBIN "data/data_049ed5.bin"

SECTION "data_04a11a", ROMX[$611a], BANK[$12]
Data_12_611a:
	INCBIN "data/data_04a11a.bin"

SECTION "data_04a35f", ROMX[$635f], BANK[$12]
Data_12_635f:
	INCBIN "data/data_04a35f.bin"

SECTION "data_04a5a4", ROMX[$65a4], BANK[$12]
Data_12_65a4:
	INCBIN "data/data_04a5a4.bin"

SECTION "data_04c398", ROMX[$4398], BANK[$13]
Data_13_4398:
	INCBIN "data/data_04c398.bin"

SECTION "data_04c3b7", ROMX[$43b7], BANK[$13]
Data_13_43b7:
	INCBIN "data/data_04c3b7.bin"

SECTION "data_04e2fc", ROMX[$62fc], BANK[$13]
Data_13_62fc:
	INCBIN "data/data_04e2fc.bin"

SECTION "data_04e317", ROMX[$6317], BANK[$13]
Data_13_6317:
	INCBIN "data/data_04e317.bin"

SECTION "data_04e332", ROMX[$6332], BANK[$13]
Data_13_6332:
	INCBIN "data/data_04e332.bin"

SECTION "data_050228", ROMX[$4228], BANK[$14]
Data_14_4228:
	INCBIN "data/data_050228.bin"

SECTION "data_054002", ROMX[$4002], BANK[$15]
Data_15_4002:
	INCBIN "data/data_054002.bin"

SECTION "data_05400a", ROMX[$400a], BANK[$15]
Data_15_400a:
	INCBIN "data/data_05400a.bin"

SECTION "data_054080", ROMX[$4080], BANK[$15]
Data_15_4080:
	INCBIN "data/data_054080.bin"

SECTION "data_054086", ROMX[$4086], BANK[$15]
Data_15_4086:
	INCBIN "data/data_054086.bin"

SECTION "data_0540d1", ROMX[$40d1], BANK[$15]
Data_15_40d1:
	INCBIN "data/data_0540d1.bin"

SECTION "data_0540ef", ROMX[$40ef], BANK[$15]
Data_15_40ef:
	INCBIN "data/data_0540ef.bin"

SECTION "data_05410e", ROMX[$410e], BANK[$15]
Data_15_410e:
	INCBIN "data/data_05410e.bin"

SECTION "data_054143", ROMX[$4143], BANK[$15]
Data_15_4143:
	INCBIN "data/data_054143.bin"

SECTION "data_054227", ROMX[$4227], BANK[$15]
Data_15_4227:
	INCBIN "data/data_054227.bin"

SECTION "data_05624e", ROMX[$624e], BANK[$15]
Data_15_624e:
	INCBIN "data/data_05624e.bin"

SECTION "data_05b57f", ROMX[$757f], BANK[$16]
Data_16_757f:
	INCBIN "data/data_05b57f.bin"

SECTION "data_05c218", ROMX[$4218], BANK[$17]
Data_17_4218:
	INCBIN "data/data_05c218.bin"

SECTION "data_05c298", ROMX[$4298], BANK[$17]
Data_17_4298:
	INCBIN "data/data_05c298.bin"

SECTION "data_05c2d8", ROMX[$42d8], BANK[$17]
Data_17_42d8:
	INCBIN "data/data_05c2d8.bin"

SECTION "data_05c328", ROMX[$4328], BANK[$17]
Data_17_4328:
	INCBIN "data/data_05c328.bin"

SECTION "data_05c3c8", ROMX[$43c8], BANK[$17]
Data_17_43c8:
	INCBIN "data/data_05c3c8.bin"

SECTION "data_05c438", ROMX[$4438], BANK[$17]
Data_17_4438:
	INCBIN "data/data_05c438.bin"

SECTION "data_05c548", ROMX[$4548], BANK[$17]
Data_17_4548:
	INCBIN "data/data_05c548.bin"

SECTION "data_05c578", ROMX[$4578], BANK[$17]
Data_17_4578:
	INCBIN "data/data_05c578.bin"

SECTION "data_060054", ROMX[$4054], BANK[$18]
Data_18_4054:
	INCBIN "data/data_060054.bin"

SECTION "data_060086", ROMX[$4086], BANK[$18]
Data_18_4086:
	INCBIN "data/data_060086.bin"

SECTION "data_061de3", ROMX[$5de3], BANK[$18]
Data_18_5de3:
	INCBIN "data/data_061de3.bin"

SECTION "data_06688f", ROMX[$688f], BANK[$19]
Data_19_688f:
	INCBIN "data/data_06688f.bin"

SECTION "data_06d830", ROMX[$5830], BANK[$1b]
Data_1b_5830:
	INCBIN "data/data_06d830.bin"

SECTION "data_06d870", ROMX[$5870], BANK[$1b]
Data_1b_5870:
	INCBIN "data/data_06d870.bin"

SECTION "data_073030", ROMX[$7030], BANK[$1c]
Data_1c_7030:
	INCBIN "data/data_073030.bin"

SECTION "data_073070", ROMX[$7070], BANK[$1c]
Data_1c_7070:
	INCBIN "data/data_073070.bin"

SECTION "data_079b89", ROMX[$5b89], BANK[$1e]
Data_1e_5b89:
	INCBIN "data/data_079b89.bin"

SECTION "data_07c120", ROMX[$4120], BANK[$1f]
Data_1f_4120:
	INCBIN "data/data_07c120.bin"

SECTION "data_07dc51", ROMX[$5c51], BANK[$1f]
Data_1f_5c51:
	INCBIN "data/data_07dc51.bin"

SECTION "data_083925", ROMX[$7925], BANK[$20]
Data_20_7925:
	INCBIN "data/data_083925.bin"

SECTION "data_083941", ROMX[$7941], BANK[$20]
Data_20_7941:
	INCBIN "data/data_083941.bin"

SECTION "data_08394b", ROMX[$794b], BANK[$20]
Data_20_794b:
	INCBIN "data/data_08394b.bin"

SECTION "data_08398b", ROMX[$798b], BANK[$20]
Data_20_798b:
	INCBIN "data/data_08398b.bin"

SECTION "data_0873aa", ROMX[$73aa], BANK[$21]
Data_21_73aa:
	INCBIN "data/data_0873aa.bin"

SECTION "data_08fb8a", ROMX[$7b8a], BANK[$23]
Data_23_7b8a:
	INCBIN "data/data_08fb8a.bin"

SECTION "data_08fbb0", ROMX[$7bb0], BANK[$23]
Data_23_7bb0:
	INCBIN "data/data_08fbb0.bin"

SECTION "data_091800", ROMX[$5800], BANK[$24]
Data_24_5800:
	INCBIN "data/data_091800.bin"

SECTION "data_09197c", ROMX[$597c], BANK[$24]
Data_24_597c:
	INCBIN "data/data_09197c.bin"

SECTION "data_09197e", ROMX[$597e], BANK[$24]
Data_24_597e:
	INCBIN "data/data_09197e.bin"

SECTION "data_09b692", ROMX[$7692], BANK[$26]
Data_26_7692:
	INCBIN "data/data_09b692.bin"

SECTION "data_0a3462", ROMX[$7462], BANK[$28]
Data_28_7462:
	INCBIN "data/data_0a3462.bin"

SECTION "data_0a3547", ROMX[$7547], BANK[$28]
Data_28_7547:
	INCBIN "data/data_0a3547.bin"

SECTION "data_0a7a8e", ROMX[$7a8e], BANK[$29]
Data_29_7a8e:
	INCBIN "data/data_0a7a8e.bin"

SECTION "data_0b3fff", ROMX[$7fff], BANK[$2c]
Data_2c_7fff:
	INCBIN "data/data_0b3fff.bin"

SECTION "data_0b4145", ROMX[$4145], BANK[$2d]
Data_2d_4145:
	INCBIN "data/data_0b4145.bin"

SECTION "data_0b45cf", ROMX[$45cf], BANK[$2d]
Data_2d_45cf:
	INCBIN "data/data_0b45cf.bin"

SECTION "data_0b4814", ROMX[$4814], BANK[$2d]
Data_2d_4814:
	INCBIN "data/data_0b4814.bin"

SECTION "data_0b4a59", ROMX[$4a59], BANK[$2d]
Data_2d_4a59:
	INCBIN "data/data_0b4a59.bin"

SECTION "data_0b4c9e", ROMX[$4c9e], BANK[$2d]
Data_2d_4c9e:
	INCBIN "data/data_0b4c9e.bin"

SECTION "data_0b536d", ROMX[$536d], BANK[$2d]
Data_2d_536d:
	INCBIN "data/data_0b536d.bin"

SECTION "data_0b55b2", ROMX[$55b2], BANK[$2d]
Data_2d_55b2:
	INCBIN "data/data_0b55b2.bin"

SECTION "data_0b57f7", ROMX[$57f7], BANK[$2d]
Data_2d_57f7:
	INCBIN "data/data_0b57f7.bin"

SECTION "data_0b5a3c", ROMX[$5a3c], BANK[$2d]
Data_2d_5a3c:
	INCBIN "data/data_0b5a3c.bin"

SECTION "data_0b5c81", ROMX[$5c81], BANK[$2d]
Data_2d_5c81:
	INCBIN "data/data_0b5c81.bin"

SECTION "data_0b5ec6", ROMX[$5ec6], BANK[$2d]
Data_2d_5ec6:
	INCBIN "data/data_0b5ec6.bin"

SECTION "data_0b610b", ROMX[$610b], BANK[$2d]
Data_2d_610b:
	INCBIN "data/data_0b610b.bin"

SECTION "data_0b6350", ROMX[$6350], BANK[$2d]
Data_2d_6350:
	INCBIN "data/data_0b6350.bin"

SECTION "data_0b6595", ROMX[$6595], BANK[$2d]
Data_2d_6595:
	INCBIN "data/data_0b6595.bin"

SECTION "data_0b67da", ROMX[$67da], BANK[$2d]
Data_2d_67da:
	INCBIN "data/data_0b67da.bin"

SECTION "data_0b6a1f", ROMX[$6a1f], BANK[$2d]
Data_2d_6a1f:
	INCBIN "data/data_0b6a1f.bin"

SECTION "data_0b6ea9", ROMX[$6ea9], BANK[$2d]
Data_2d_6ea9:
	INCBIN "data/data_0b6ea9.bin"

SECTION "data_0b70ee", ROMX[$70ee], BANK[$2d]
Data_2d_70ee:
	INCBIN "data/data_0b70ee.bin"

SECTION "data_0b7333", ROMX[$7333], BANK[$2d]
Data_2d_7333:
	INCBIN "data/data_0b7333.bin"

SECTION "data_0b7578", ROMX[$7578], BANK[$2d]
Data_2d_7578:
	INCBIN "data/data_0b7578.bin"

SECTION "data_0b7a02", ROMX[$7a02], BANK[$2d]
Data_2d_7a02:
	INCBIN "data/data_0b7a02.bin"

SECTION "data_0b7c47", ROMX[$7c47], BANK[$2d]
Data_2d_7c47:
	INCBIN "data/data_0b7c47.bin"

SECTION "data_0b8145", ROMX[$4145], BANK[$2e]
Data_2e_4145:
	INCBIN "data/data_0b8145.bin"

SECTION "data_0b838a", ROMX[$438a], BANK[$2e]
Data_2e_438a:
	INCBIN "data/data_0b838a.bin"

SECTION "data_0b8a59", ROMX[$4a59], BANK[$2e]
Data_2e_4a59:
	INCBIN "data/data_0b8a59.bin"

SECTION "data_0b8c9e", ROMX[$4c9e], BANK[$2e]
Data_2e_4c9e:
	INCBIN "data/data_0b8c9e.bin"

SECTION "data_0b8ee3", ROMX[$4ee3], BANK[$2e]
Data_2e_4ee3:
	INCBIN "data/data_0b8ee3.bin"

SECTION "data_0b9128", ROMX[$5128], BANK[$2e]
Data_2e_5128:
	INCBIN "data/data_0b9128.bin"

SECTION "data_0b936d", ROMX[$536d], BANK[$2e]
Data_2e_536d:
	INCBIN "data/data_0b936d.bin"

SECTION "data_0b95b2", ROMX[$55b2], BANK[$2e]
Data_2e_55b2:
	INCBIN "data/data_0b95b2.bin"

SECTION "data_0b9c81", ROMX[$5c81], BANK[$2e]
Data_2e_5c81:
	INCBIN "data/data_0b9c81.bin"

SECTION "data_0b9ec6", ROMX[$5ec6], BANK[$2e]
Data_2e_5ec6:
	INCBIN "data/data_0b9ec6.bin"

SECTION "data_0ba350", ROMX[$6350], BANK[$2e]
Data_2e_6350:
	INCBIN "data/data_0ba350.bin"

SECTION "data_0ba7da", ROMX[$67da], BANK[$2e]
Data_2e_67da:
	INCBIN "data/data_0ba7da.bin"

SECTION "data_0baa1f", ROMX[$6a1f], BANK[$2e]
Data_2e_6a1f:
	INCBIN "data/data_0baa1f.bin"

SECTION "data_0baea9", ROMX[$6ea9], BANK[$2e]
Data_2e_6ea9:
	INCBIN "data/data_0baea9.bin"

SECTION "data_0bb0ee", ROMX[$70ee], BANK[$2e]
Data_2e_70ee:
	INCBIN "data/data_0bb0ee.bin"

SECTION "data_0bb333", ROMX[$7333], BANK[$2e]
Data_2e_7333:
	INCBIN "data/data_0bb333.bin"

SECTION "data_0bb578", ROMX[$7578], BANK[$2e]
Data_2e_7578:
	INCBIN "data/data_0bb578.bin"

SECTION "data_0bb7bd", ROMX[$77bd], BANK[$2e]
Data_2e_77bd:
	INCBIN "data/data_0bb7bd.bin"

SECTION "data_0bba02", ROMX[$7a02], BANK[$2e]
Data_2e_7a02:
	INCBIN "data/data_0bba02.bin"

SECTION "data_0bbc47", ROMX[$7c47], BANK[$2e]
Data_2e_7c47:
	INCBIN "data/data_0bbc47.bin"

SECTION "data_0bc145", ROMX[$4145], BANK[$2f]
Data_2f_4145:
	INCBIN "data/data_0bc145.bin"

SECTION "data_0bc38a", ROMX[$438a], BANK[$2f]
Data_2f_438a:
	INCBIN "data/data_0bc38a.bin"

SECTION "data_0bc5cf", ROMX[$45cf], BANK[$2f]
Data_2f_45cf:
	INCBIN "data/data_0bc5cf.bin"

SECTION "data_0bc814", ROMX[$4814], BANK[$2f]
Data_2f_4814:
	INCBIN "data/data_0bc814.bin"

SECTION "data_0bcee3", ROMX[$4ee3], BANK[$2f]
Data_2f_4ee3:
	INCBIN "data/data_0bcee3.bin"

SECTION "data_0bd128", ROMX[$5128], BANK[$2f]
Data_2f_5128:
	INCBIN "data/data_0bd128.bin"

SECTION "data_0bd36d", ROMX[$536d], BANK[$2f]
Data_2f_536d:
	INCBIN "data/data_0bd36d.bin"

SECTION "data_0bd5b2", ROMX[$55b2], BANK[$2f]
Data_2f_55b2:
	INCBIN "data/data_0bd5b2.bin"

SECTION "data_0bd7f7", ROMX[$57f7], BANK[$2f]
Data_2f_57f7:
	INCBIN "data/data_0bd7f7.bin"

SECTION "data_0bda3c", ROMX[$5a3c], BANK[$2f]
Data_2f_5a3c:
	INCBIN "data/data_0bda3c.bin"

SECTION "data_0be350", ROMX[$6350], BANK[$2f]
Data_2f_6350:
	INCBIN "data/data_0be350.bin"

SECTION "data_0c0169", ROMX[$4169], BANK[$30]
Data_30_4169:
	INCBIN "data/data_0c0169.bin"

SECTION "data_0c016d", ROMX[$416d], BANK[$30]
Data_30_416d:
	INCBIN "data/data_0c016d.bin"

SECTION "data_0c0175", ROMX[$4175], BANK[$30]
Data_30_4175:
	INCBIN "data/data_0c0175.bin"

SECTION "data_0c017d", ROMX[$417d], BANK[$30]
Data_30_417d:
	INCBIN "data/data_0c017d.bin"

SECTION "data_0c0188", ROMX[$4188], BANK[$30]
Data_30_4188:
	INCBIN "data/data_0c0188.bin"

SECTION "data_0c0298", ROMX[$4298], BANK[$30]
Data_30_4298:
	INCBIN "data/data_0c0298.bin"

SECTION "data_0c0315", ROMX[$4315], BANK[$30]
Data_30_4315:
	INCBIN "data/data_0c0315.bin"

SECTION "data_0c06e4", ROMX[$46e4], BANK[$30]
Data_30_46e4:
	INCBIN "data/data_0c06e4.bin"

SECTION "data_0c0705", ROMX[$4705], BANK[$30]
Data_30_4705:
	INCBIN "data/data_0c0705.bin"

SECTION "data_0c0742", ROMX[$4742], BANK[$30]
Data_30_4742:
	INCBIN "data/data_0c0742.bin"

SECTION "data_0c075f", ROMX[$475f], BANK[$30]
Data_30_475f:
	INCBIN "data/data_0c075f.bin"

SECTION "data_0c0e70", ROMX[$4e70], BANK[$30]
Data_30_4e70:
	INCBIN "data/data_0c0e70.bin"

SECTION "data_0c0e7a", ROMX[$4e7a], BANK[$30]
Data_30_4e7a:
	INCBIN "data/data_0c0e7a.bin"

SECTION "data_0c11a0", ROMX[$51a0], BANK[$30]
Data_30_51a0:
	INCBIN "data/data_0c11a0.bin"

SECTION "data_0c120e", ROMX[$520e], BANK[$30]
Data_30_520e:
	INCBIN "data/data_0c120e.bin"

SECTION "data_0c1481", ROMX[$5481], BANK[$30]
Data_30_5481:
	INCBIN "data/data_0c1481.bin"

SECTION "data_0c1544", ROMX[$5544], BANK[$30]
Data_30_5544:
	INCBIN "data/data_0c1544.bin"

SECTION "data_0c15b7", ROMX[$55b7], BANK[$30]
Data_30_55b7:
	INCBIN "data/data_0c15b7.bin"

SECTION "data_0c16f8", ROMX[$56f8], BANK[$30]
Data_30_56f8:
	INCBIN "data/data_0c16f8.bin"

SECTION "data_0c186a", ROMX[$586a], BANK[$30]
Data_30_586a:
	INCBIN "data/data_0c186a.bin"

SECTION "data_0c1889", ROMX[$5889], BANK[$30]
Data_30_5889:
	INCBIN "data/data_0c1889.bin"

SECTION "data_0c1891", ROMX[$5891], BANK[$30]
Data_30_5891:
	INCBIN "data/data_0c1891.bin"

SECTION "data_0c18cf", ROMX[$58cf], BANK[$30]
Data_30_58cf:
	INCBIN "data/data_0c18cf.bin"

SECTION "data_0c1934", ROMX[$5934], BANK[$30]
Data_30_5934:
	INCBIN "data/data_0c1934.bin"

SECTION "data_0c1d23", ROMX[$5d23], BANK[$30]
Data_30_5d23:
	INCBIN "data/data_0c1d23.bin"

SECTION "data_0c408c", ROMX[$408c], BANK[$31]
Data_31_408c:
	INCBIN "data/data_0c408c.bin"

SECTION "data_0cf030", ROMX[$7030], BANK[$33]
Data_33_7030:
	INCBIN "data/data_0cf030.bin"

SECTION "data_0d0000", ROMX[$4000], BANK[$34]
Data_34_4000:
	INCBIN "data/data_0d0000.bin"

SECTION "data_0d08a8", ROMX[$48a8], BANK[$34]
Data_34_48a8:
	INCBIN "data/data_0d08a8.bin"

SECTION "data_0d20ca", ROMX[$60ca], BANK[$34]
Data_34_60ca:
	INCBIN "data/data_0d20ca.bin"

SECTION "data_0d28a8", ROMX[$68a8], BANK[$34]
Data_34_68a8:
	INCBIN "data/data_0d28a8.bin"

SECTION "data_0d3fff", ROMX[$7fff], BANK[$34]
Data_34_7fff:
	INCBIN "data/data_0d3fff.bin"

SECTION "data_0d6030", ROMX[$6030], BANK[$35]
Data_35_6030:
	INCBIN "data/data_0d6030.bin"

SECTION "data_0d6070", ROMX[$6070], BANK[$35]
Data_35_6070:
	INCBIN "data/data_0d6070.bin"

SECTION "data_0dbfff", ROMX[$7fff], BANK[$36]
Data_36_7fff:
	INCBIN "data/data_0dbfff.bin"

SECTION "data_0dffff", ROMX[$7fff], BANK[$37]
Data_37_7fff:
	INCBIN "data/data_0dffff.bin"

SECTION "data_0e7fff", ROMX[$7fff], BANK[$39]
Data_39_7fff:
	INCBIN "data/data_0e7fff.bin"

SECTION "data_0ebfff", ROMX[$7fff], BANK[$3a]
Data_3a_7fff:
	INCBIN "data/data_0ebfff.bin"

SECTION "data_0ec022", ROMX[$4022], BANK[$3b]
Data_3b_4022:
	INCBIN "data/data_0ec022.bin"

SECTION "data_0ed434", ROMX[$5434], BANK[$3b]
Data_3b_5434:
	INCBIN "data/data_0ed434.bin"

SECTION "data_0f8000", ROMX[$4000], BANK[$3e]
Data_3e_4000:
	INCBIN "data/data_0f8000.bin"

SECTION "data_0f8009", ROMX[$4009], BANK[$3e]
Data_3e_4009:
	INCBIN "data/data_0f8009.bin"

SECTION "data_0f8076", ROMX[$4076], BANK[$3e]
Data_3e_4076:
	INCBIN "data/data_0f8076.bin"

SECTION "data_0f80b4", ROMX[$40b4], BANK[$3e]
Data_3e_40b4:
	INCBIN "data/data_0f80b4.bin"

SECTION "data_0f8113", ROMX[$4113], BANK[$3e]
Data_3e_4113:
	INCBIN "data/data_0f8113.bin"

SECTION "data_0f8285", ROMX[$4285], BANK[$3e]
Data_3e_4285:
	INCBIN "data/data_0f8285.bin"

SECTION "data_0f8363", ROMX[$4363], BANK[$3e]
Data_3e_4363:
	INCBIN "data/data_0f8363.bin"

SECTION "data_0f8378", ROMX[$4378], BANK[$3e]
Data_3e_4378:
	INCBIN "data/data_0f8378.bin"

SECTION "data_0f8432", ROMX[$4432], BANK[$3e]
Data_3e_4432:
	INCBIN "data/data_0f8432.bin"

SECTION "data_0f8436", ROMX[$4436], BANK[$3e]
Data_3e_4436:
	INCBIN "data/data_0f8436.bin"

SECTION "data_0f843e", ROMX[$443e], BANK[$3e]
Data_3e_443e:
	INCBIN "data/data_0f843e.bin"

SECTION "data_0f8442", ROMX[$4442], BANK[$3e]
Data_3e_4442:
	INCBIN "data/data_0f8442.bin"

SECTION "data_0f8456", ROMX[$4456], BANK[$3e]
Data_3e_4456:
	INCBIN "data/data_0f8456.bin"

SECTION "data_0f845e", ROMX[$445e], BANK[$3e]
Data_3e_445e:
	INCBIN "data/data_0f845e.bin"

SECTION "data_0f846a", ROMX[$446a], BANK[$3e]
Data_3e_446a:
	INCBIN "data/data_0f846a.bin"

SECTION "data_0f8482", ROMX[$4482], BANK[$3e]
Data_3e_4482:
	INCBIN "data/data_0f8482.bin"

SECTION "data_0f848a", ROMX[$448a], BANK[$3e]
Data_3e_448a:
	INCBIN "data/data_0f848a.bin"

SECTION "data_0f84a2", ROMX[$44a2], BANK[$3e]
Data_3e_44a2:
	INCBIN "data/data_0f84a2.bin"

SECTION "data_0f84aa", ROMX[$44aa], BANK[$3e]
Data_3e_44aa:
	INCBIN "data/data_0f84aa.bin"

SECTION "data_0f84c2", ROMX[$44c2], BANK[$3e]
Data_3e_44c2:
	INCBIN "data/data_0f84c2.bin"

SECTION "data_0f84ca", ROMX[$44ca], BANK[$3e]
Data_3e_44ca:
	INCBIN "data/data_0f84ca.bin"

SECTION "data_0f84e2", ROMX[$44e2], BANK[$3e]
Data_3e_44e2:
	INCBIN "data/data_0f84e2.bin"

SECTION "data_0f84f2", ROMX[$44f2], BANK[$3e]
Data_3e_44f2:
	INCBIN "data/data_0f84f2.bin"

SECTION "data_0f854d", ROMX[$454d], BANK[$3e]
Data_3e_454d:
	INCBIN "data/data_0f854d.bin"

SECTION "data_0f8553", ROMX[$4553], BANK[$3e]
Data_3e_4553:
	INCBIN "data/data_0f8553.bin"

SECTION "data_0f8626", ROMX[$4626], BANK[$3e]
Data_3e_4626:
	INCBIN "data/data_0f8626.bin"

SECTION "data_0f863c", ROMX[$463c], BANK[$3e]
Data_3e_463c:
	INCBIN "data/data_0f863c.bin"

SECTION "data_0f8671", ROMX[$4671], BANK[$3e]
Data_3e_4671:
	INCBIN "data/data_0f8671.bin"

SECTION "data_0f86db", ROMX[$46db], BANK[$3e]
Data_3e_46db:
	INCBIN "data/data_0f86db.bin"

SECTION "data_0f8714", ROMX[$4714], BANK[$3e]
Data_3e_4714:
	INCBIN "data/data_0f8714.bin"

SECTION "data_0f8726", ROMX[$4726], BANK[$3e]
Data_3e_4726:
	INCBIN "data/data_0f8726.bin"

SECTION "data_0f8750", ROMX[$4750], BANK[$3e]
Data_3e_4750:
	INCBIN "data/data_0f8750.bin"

SECTION "data_0f8766", ROMX[$4766], BANK[$3e]
Data_3e_4766:
	INCBIN "data/data_0f8766.bin"

SECTION "data_0f8770", ROMX[$4770], BANK[$3e]
Data_3e_4770:
	INCBIN "data/data_0f8770.bin"

SECTION "data_0f8788", ROMX[$4788], BANK[$3e]
Data_3e_4788:
	INCBIN "data/data_0f8788.bin"

SECTION "data_0f87a0", ROMX[$47a0], BANK[$3e]
Data_3e_47a0:
	INCBIN "data/data_0f87a0.bin"

SECTION "data_0f87b2", ROMX[$47b2], BANK[$3e]
Data_3e_47b2:
	INCBIN "data/data_0f87b2.bin"

SECTION "data_0f890e", ROMX[$490e], BANK[$3e]
Data_3e_490e:
	INCBIN "data/data_0f890e.bin"

SECTION "data_0f896a", ROMX[$496a], BANK[$3e]
Data_3e_496a:
	INCBIN "data/data_0f896a.bin"

SECTION "data_0f8974", ROMX[$4974], BANK[$3e]
Data_3e_4974:
	INCBIN "data/data_0f8974.bin"

SECTION "data_0f89a4", ROMX[$49a4], BANK[$3e]
Data_3e_49a4:
	INCBIN "data/data_0f89a4.bin"

SECTION "data_0f89f4", ROMX[$49f4], BANK[$3e]
Data_3e_49f4:
	INCBIN "data/data_0f89f4.bin"

SECTION "data_0f8b18", ROMX[$4b18], BANK[$3e]
Data_3e_4b18:
	INCBIN "data/data_0f8b18.bin"

SECTION "data_0f8e29", ROMX[$4e29], BANK[$3e]
Data_3e_4e29:
	INCBIN "data/data_0f8e29.bin"

SECTION "data_0f90aa", ROMX[$50aa], BANK[$3e]
Data_3e_50aa:
	INCBIN "data/data_0f90aa.bin"

SECTION "data_0f926c", ROMX[$526c], BANK[$3e]
Data_3e_526c:
	INCBIN "data/data_0f926c.bin"

SECTION "data_0f95bf", ROMX[$55bf], BANK[$3e]
Data_3e_55bf:
	INCBIN "data/data_0f95bf.bin"

SECTION "data_0f963a", ROMX[$563a], BANK[$3e]
Data_3e_563a:
	INCBIN "data/data_0f963a.bin"

SECTION "data_0f966e", ROMX[$566e], BANK[$3e]
Data_3e_566e:
	INCBIN "data/data_0f966e.bin"

SECTION "data_0f9695", ROMX[$5695], BANK[$3e]
Data_3e_5695:
	INCBIN "data/data_0f9695.bin"

SECTION "data_0f96c5", ROMX[$56c5], BANK[$3e]
Data_3e_56c5:
	INCBIN "data/data_0f96c5.bin"

SECTION "data_0f96ec", ROMX[$56ec], BANK[$3e]
Data_3e_56ec:
	INCBIN "data/data_0f96ec.bin"

SECTION "data_0f99b8", ROMX[$59b8], BANK[$3e]
Data_3e_59b8:
	INCBIN "data/data_0f99b8.bin"

SECTION "data_0f9a29", ROMX[$5a29], BANK[$3e]
Data_3e_5a29:
	INCBIN "data/data_0f9a29.bin"

SECTION "data_0f9c0e", ROMX[$5c0e], BANK[$3e]
Data_3e_5c0e:
	INCBIN "data/data_0f9c0e.bin"

SECTION "data_0f9df9", ROMX[$5df9], BANK[$3e]
Data_3e_5df9:
	INCBIN "data/data_0f9df9.bin"

SECTION "data_0f9e94", ROMX[$5e94], BANK[$3e]
Data_3e_5e94:
	INCBIN "data/data_0f9e94.bin"

SECTION "data_0f9ed2", ROMX[$5ed2], BANK[$3e]
Data_3e_5ed2:
	INCBIN "data/data_0f9ed2.bin"

SECTION "data_0fa5bf", ROMX[$65bf], BANK[$3e]
Data_3e_65bf:
	INCBIN "data/data_0fa5bf.bin"

SECTION "data_0fa5fb", ROMX[$65fb], BANK[$3e]
Data_3e_65fb:
	INCBIN "data/data_0fa5fb.bin"

SECTION "data_0fa7d6", ROMX[$67d6], BANK[$3e]
Data_3e_67d6:
	INCBIN "data/data_0fa7d6.bin"

SECTION "data_0fa9bb", ROMX[$69bb], BANK[$3e]
Data_3e_69bb:
	INCBIN "data/data_0fa9bb.bin"

SECTION "data_0fab66", ROMX[$6b66], BANK[$3e]
Data_3e_6b66:
	INCBIN "data/data_0fab66.bin"

SECTION "data_0fab71", ROMX[$6b71], BANK[$3e]
Data_3e_6b71:
	INCBIN "data/data_0fab71.bin"

SECTION "data_0fafb8", ROMX[$6fb8], BANK[$3e]
Data_3e_6fb8:
	INCBIN "data/data_0fafb8.bin"

SECTION "data_0fb102", ROMX[$7102], BANK[$3e]
Data_3e_7102:
	INCBIN "data/data_0fb102.bin"

SECTION "data_0fb25d", ROMX[$725d], BANK[$3e]
Data_3e_725d:
	INCBIN "data/data_0fb25d.bin"

SECTION "data_0fb2ef", ROMX[$72ef], BANK[$3e]
Data_3e_72ef:
	INCBIN "data/data_0fb2ef.bin"

SECTION "data_0fb3f3", ROMX[$73f3], BANK[$3e]
Data_3e_73f3:
	INCBIN "data/data_0fb3f3.bin"

SECTION "data_0fc00c", ROMX[$400c], BANK[$3f]
Data_3f_400c:
	INCBIN "data/data_0fc00c.bin"

SECTION "data_0fc076", ROMX[$4076], BANK[$3f]
Data_3f_4076:
	INCBIN "data/data_0fc076.bin"

SECTION "data_0fc27a", ROMX[$427a], BANK[$3f]
Data_3f_427a:
	INCBIN "data/data_0fc27a.bin"

SECTION "data_0fc285", ROMX[$4285], BANK[$3f]
Data_3f_4285:
	INCBIN "data/data_0fc285.bin"

SECTION "data_0fc363", ROMX[$4363], BANK[$3f]
Data_3f_4363:
	INCBIN "data/data_0fc363.bin"

SECTION "data_0fc378", ROMX[$4378], BANK[$3f]
Data_3f_4378:
	INCBIN "data/data_0fc378.bin"

SECTION "data_0fc43a", ROMX[$443a], BANK[$3f]
Data_3f_443a:
	INCBIN "data/data_0fc43a.bin"

SECTION "data_0fc442", ROMX[$4442], BANK[$3f]
Data_3f_4442:
	INCBIN "data/data_0fc442.bin"

SECTION "data_0fc448", ROMX[$4448], BANK[$3f]
Data_3f_4448:
	INCBIN "data/data_0fc448.bin"

SECTION "data_0fc460", ROMX[$4460], BANK[$3f]
Data_3f_4460:
	INCBIN "data/data_0fc460.bin"

SECTION "data_0fc468", ROMX[$4468], BANK[$3f]
Data_3f_4468:
	INCBIN "data/data_0fc468.bin"

SECTION "data_0fc482", ROMX[$4482], BANK[$3f]
Data_3f_4482:
	INCBIN "data/data_0fc482.bin"

SECTION "data_0fc48a", ROMX[$448a], BANK[$3f]
Data_3f_448a:
	INCBIN "data/data_0fc48a.bin"

SECTION "data_0fc4a2", ROMX[$44a2], BANK[$3f]
Data_3f_44a2:
	INCBIN "data/data_0fc4a2.bin"

SECTION "data_0fc4aa", ROMX[$44aa], BANK[$3f]
Data_3f_44aa:
	INCBIN "data/data_0fc4aa.bin"

SECTION "data_0fc4c2", ROMX[$44c2], BANK[$3f]
Data_3f_44c2:
	INCBIN "data/data_0fc4c2.bin"

SECTION "data_0fc4ca", ROMX[$44ca], BANK[$3f]
Data_3f_44ca:
	INCBIN "data/data_0fc4ca.bin"

SECTION "data_0fc4de", ROMX[$44de], BANK[$3f]
Data_3f_44de:
	INCBIN "data/data_0fc4de.bin"

SECTION "data_0fc4e2", ROMX[$44e2], BANK[$3f]
Data_3f_44e2:
	INCBIN "data/data_0fc4e2.bin"

SECTION "data_0fc4ea", ROMX[$44ea], BANK[$3f]
Data_3f_44ea:
	INCBIN "data/data_0fc4ea.bin"

SECTION "data_0fc502", ROMX[$4502], BANK[$3f]
Data_3f_4502:
	INCBIN "data/data_0fc502.bin"

SECTION "data_0fc50a", ROMX[$450a], BANK[$3f]
Data_3f_450a:
	INCBIN "data/data_0fc50a.bin"

SECTION "data_0fc522", ROMX[$4522], BANK[$3f]
Data_3f_4522:
	INCBIN "data/data_0fc522.bin"

SECTION "data_0fc526", ROMX[$4526], BANK[$3f]
Data_3f_4526:
	INCBIN "data/data_0fc526.bin"

SECTION "data_0fc54d", ROMX[$454d], BANK[$3f]
Data_3f_454d:
	INCBIN "data/data_0fc54d.bin"

SECTION "data_0fc553", ROMX[$4553], BANK[$3f]
Data_3f_4553:
	INCBIN "data/data_0fc553.bin"

SECTION "data_0fc626", ROMX[$4626], BANK[$3f]
Data_3f_4626:
	INCBIN "data/data_0fc626.bin"

SECTION "data_0fc63c", ROMX[$463c], BANK[$3f]
Data_3f_463c:
	INCBIN "data/data_0fc63c.bin"

SECTION "data_0fc671", ROMX[$4671], BANK[$3f]
Data_3f_4671:
	INCBIN "data/data_0fc671.bin"

SECTION "data_0fc6db", ROMX[$46db], BANK[$3f]
Data_3f_46db:
	INCBIN "data/data_0fc6db.bin"

SECTION "data_0fc714", ROMX[$4714], BANK[$3f]
Data_3f_4714:
	INCBIN "data/data_0fc714.bin"

SECTION "data_0fc726", ROMX[$4726], BANK[$3f]
Data_3f_4726:
	INCBIN "data/data_0fc726.bin"

SECTION "data_0fc752", ROMX[$4752], BANK[$3f]
Data_3f_4752:
	INCBIN "data/data_0fc752.bin"

SECTION "data_0fc766", ROMX[$4766], BANK[$3f]
Data_3f_4766:
	INCBIN "data/data_0fc766.bin"

SECTION "data_0fc772", ROMX[$4772], BANK[$3f]
Data_3f_4772:
	INCBIN "data/data_0fc772.bin"

SECTION "data_0fc788", ROMX[$4788], BANK[$3f]
Data_3f_4788:
	INCBIN "data/data_0fc788.bin"

SECTION "data_0fc7a0", ROMX[$47a0], BANK[$3f]
Data_3f_47a0:
	INCBIN "data/data_0fc7a0.bin"

SECTION "data_0fc7b2", ROMX[$47b2], BANK[$3f]
Data_3f_47b2:
	INCBIN "data/data_0fc7b2.bin"

SECTION "data_0fc814", ROMX[$4814], BANK[$3f]
Data_3f_4814:
	INCBIN "data/data_0fc814.bin"

SECTION "data_0fc93e", ROMX[$493e], BANK[$3f]
Data_3f_493e:
	INCBIN "data/data_0fc93e.bin"

SECTION "data_0fc96a", ROMX[$496a], BANK[$3f]
Data_3f_496a:
	INCBIN "data/data_0fc96a.bin"

SECTION "data_0fc974", ROMX[$4974], BANK[$3f]
Data_3f_4974:
	INCBIN "data/data_0fc974.bin"

SECTION "data_0fc9a4", ROMX[$49a4], BANK[$3f]
Data_3f_49a4:
	INCBIN "data/data_0fc9a4.bin"

SECTION "data_0fca04", ROMX[$4a04], BANK[$3f]
Data_3f_4a04:
	INCBIN "data/data_0fca04.bin"

SECTION "data_0fcb28", ROMX[$4b28], BANK[$3f]
Data_3f_4b28:
	INCBIN "data/data_0fcb28.bin"

SECTION "data_0fcb3a", ROMX[$4b3a], BANK[$3f]
Data_3f_4b3a:
	INCBIN "data/data_0fcb3a.bin"

SECTION "data_0fcb4c", ROMX[$4b4c], BANK[$3f]
Data_3f_4b4c:
	INCBIN "data/data_0fcb4c.bin"

SECTION "data_0fcb5e", ROMX[$4b5e], BANK[$3f]
Data_3f_4b5e:
	INCBIN "data/data_0fcb5e.bin"

SECTION "data_0fd282", ROMX[$5282], BANK[$3f]
Data_3f_5282:
	INCBIN "data/data_0fd282.bin"

SECTION "data_0fd5ad", ROMX[$55ad], BANK[$3f]
Data_3f_55ad:
	INCBIN "data/data_0fd5ad.bin"

SECTION "data_0fd5ed", ROMX[$55ed], BANK[$3f]
Data_3f_55ed:
	INCBIN "data/data_0fd5ed.bin"

SECTION "data_0fd6c1", ROMX[$56c1], BANK[$3f]
Data_3f_56c1:
	INCBIN "data/data_0fd6c1.bin"

SECTION "data_0fd79b", ROMX[$579b], BANK[$3f]
Data_3f_579b:
	INCBIN "data/data_0fd79b.bin"

SECTION "data_0fdbdc", ROMX[$5bdc], BANK[$3f]
Data_3f_5bdc:
	INCBIN "data/data_0fdbdc.bin"

SECTION "data_0fdc0a", ROMX[$5c0a], BANK[$3f]
Data_3f_5c0a:
	INCBIN "data/data_0fdc0a.bin"

SECTION "data_0fdc7e", ROMX[$5c7e], BANK[$3f]
Data_3f_5c7e:
	INCBIN "data/data_0fdc7e.bin"

SECTION "data_0fdcde", ROMX[$5cde], BANK[$3f]
Data_3f_5cde:
	INCBIN "data/data_0fdcde.bin"

SECTION "data_0fddb9", ROMX[$5db9], BANK[$3f]
Data_3f_5db9:
	INCBIN "data/data_0fddb9.bin"

SECTION "data_0fdeaa", ROMX[$5eaa], BANK[$3f]
Data_3f_5eaa:
	INCBIN "data/data_0fdeaa.bin"

SECTION "data_0fdf74", ROMX[$5f74], BANK[$3f]
Data_3f_5f74:
	INCBIN "data/data_0fdf74.bin"

SECTION "data_0fe04e", ROMX[$604e], BANK[$3f]
Data_3f_604e:
	INCBIN "data/data_0fe04e.bin"

SECTION "data_0fed78", ROMX[$6d78], BANK[$3f]
Data_3f_6d78:
	INCBIN "data/data_0fed78.bin"
