; Auto-generated by tools/extract.py. Do not edit.

SECTION "names_003b53", ROM0[$3b53]

PrintIndexedName:
	ld e, [hl]
	inc hl
	ld d, [hl]
	inc hl
	push hl
	ld a, [de]
	ld hl, $3b75
	sla a
	add a, l
	ld l, a
	ld a, h
	adc a, $00
	ld h, a
	ld a, [hl+]
	ld h, [hl]
	ld l, a
Func_00_3b67:
	ld a, [hl+]
	or a
	jr z, Func_00_3b71
	ld c, a
	call Func_00_3c77
	jr Func_00_3b67
Func_00_3b71:
	pop hl
	jp Func_00_39c5

SECTION "names_003b75", ROM0[$3b75]

MonsterNamePointers:
	db $83, $3b, $89, $3b, $90, $3b, $95, $3b, $9a, $3b, $a0, $3b, $a6, $3b

SECTION "names_003b83", ROM0[$3b83]

MonsterNames:
	db $54, $69, $67, $65, $72, $00, $4d, $6f, $63, $63, $68, $69, $00, $48, $61, $72
	db $65, $00, $47, $61, $6c, $69, $00, $47, $6f, $6c, $65, $6d, $00, $53, $75, $65
	db $7a, $6f, $00, $50, $68, $65, $6e, $69, $78, $00
