; Auto-generated by tools/extract.py. Do not edit.

SECTION "script_0039c0", ROM0[$39c0]

ScriptDispatcherEnterAfterCall:
	push hl
	call WaitForNextFrame
	pop hl
ScriptDispatcherNext:
	ld c, [hl]
	inc hl
	ld a, c
	cp $ff
	ret z
	cp $20
	jr nc, ScriptTextOutputPath
	sla a
	ld de, $39f0
	add a, e
	ld e, a
	ld a, d
	adc a, $00
	ld d, a
	ld a, [de]
	inc de
	ld c, a
	ld a, [de]
	inc de
	ld b, a
	push bc
	ret
ScriptTextOutputPath:
	call PrintCharacterAtCursor
	push hl
	call DispatchTextRenderer
	call HideUnusedOamSprites
	pop hl
	jp ScriptDispatcherEnterAfterCall

SECTION "script_0039f2", ROM0[$39f2]

Data_00_39f2:
	db $14, $3a, $7d, $3a, $33, $3a, $2d, $3a

SECTION "script_0039fc", ROM0[$39fc]

Data_00_39fc:
	db $a1, $3a, $ba, $3a, $a7, $3a, $c9, $3a, $d2, $3a, $e7, $3a, $fc, $3a, $ad, $3b
	db $0c, $3b, $1b, $3b, $3e, $3b

SECTION "script_003a14", ROM0[$3a14]

ScriptOpcode01Handler_InitTextState:
	ld a, [hl+]
	ld [wTextAnchor], a
	ld [wTextCursor], a
	ld a, [hl+]
	ld [$d615], a
	ld [$d617], a
	ld a, [hl+]
	ld [wTextWidth], a
	ld a, [hl+]
	ld [wTextHeight], a
	jp ScriptDispatcherNext
ScriptOpcode04Handler_WaitForInput:
	call ScriptWaitInputCore
	jp ScriptOpcode02Handler_RenderAnchor
ScriptOpcode03Handler_WaitAndRenderPrep:
	call ScriptWaitInputCore
	jp ScriptDispatcherNext
ScriptWaitInputCore:
	push hl
Func_00_3a3a:
	call WaitForNextFrame
	call ReadJoypad
	call DispatchTextRenderer
	ld a, [$d61a]
	or a
	jr nz, Data_00_3a4e
	ld bc, $8c92
	jr Func_00_3a51

SECTION "script_003a51", ROM0[$3a51]

Func_00_3a51:
	call Func_00_3e10
	call HideUnusedOamSprites
	ldh a, [$ff8c]
	bit 0, a
	jr z, Func_00_3a3a
	push af
	ld a, $0d
	call CallLibFunc
	pop af
	ld hl, $d614
	ld a, [hl+]
	ld h, [hl]
	ld l, a
	ld a, l
	ld [wTextCursor], a
	ld a, h
	ld [$d617], a
	call WaitForNextFrame
	call DispatchTextRenderer
	call HideUnusedOamSprites
	pop hl
	ret
ScriptOpcode02Handler_RenderAnchor:
	push hl
	ld hl, $d614
	ld a, [hl+]
	ld h, [hl]
	ld l, a
	ld a, l
	ld [wTextCursor], a
	ld a, h
	ld [$d617], a
	call DrawTextWindow
	pop hl
	jp ScriptDispatcherNext

SECTION "script_003aa1", ROM0[$3aa1]

ScriptOpcode06Handler_Goto:
	ld a, [hl+]
	ld h, [hl]
	ld l, a
	jp ScriptDispatcherNext
ScriptOpcode08Handler_JumpTable:
	ld e, [hl]
	inc hl
	ld d, [hl]
	inc hl
	ld a, [de]
	sla a
	add a, l
	ld l, a
	ld a, h
	adc a, $00
	ld h, a
	ld a, [hl+]
	ld h, [hl]
	ld l, a
	jp ScriptDispatcherNext
ScriptOpcode07Handler_FarCall:
	ld c, [hl]
	inc hl
	ld b, [hl]
	inc hl
	ld a, [hl+]
	push hl
	push bc
	pop hl
	call CallBankedHL
	pop hl
	jp ScriptDispatcherNext
ScriptOpcode09Handler_WriteWram:
	ld e, [hl]
	inc hl
	ld d, [hl]
	inc hl
	ld a, [hl+]
	ld [de], a
	jp ScriptDispatcherNext
ScriptOpcode0AHandler_JumpIfEqual:
	ld e, [hl]
	inc hl
	ld d, [hl]
	inc hl
	ld a, [de]
	ld e, a
	ld d, [hl]
	inc hl
	ld c, [hl]
	inc hl
	ld b, [hl]
	inc hl
	ld a, d
	cp e
	jr nz, Func_00_3ae4
	push bc
	pop hl
Func_00_3ae4:
	jp ScriptDispatcherNext
ScriptOpcode0BHandler_JumpIfNotEqual:
	ld e, [hl]
	inc hl
	ld d, [hl]
	inc hl
	ld a, [de]
	ld e, a
	ld d, [hl]
	inc hl
	ld c, [hl]
	inc hl
	ld b, [hl]
	inc hl
	ld a, d
	cp e
	jr z, Func_00_3af9
	push bc
	pop hl
Func_00_3af9:
	jp ScriptDispatcherNext
ScriptOpcode0CHandler_CycleCounter:
	ld c, [hl]
	inc hl
	ld a, [wCycleCounter]
	inc a
	cp c
	jr c, Func_00_3b06
	xor a
Func_00_3b06:
	ld [wCycleCounter], a
	jp ScriptDispatcherNext
ScriptOpcode0EHandler_SetRenderer:
	ld a, [hl+]
	ld [wRendererAddr], a
	ld a, [hl+]
	ld [$d61f], a
	ld a, [hl+]
	ld [wRendererBank], a
	jp ScriptDispatcherNext
ScriptOpcode0FHandler_PrintDecimal:
	ld e, [hl]
	inc hl
	ld d, [hl]
	inc hl
	push hl
	ld a, [de]
	ld c, a
	call NumberToDecimal3
	ld a, [wBcdHigh]
	or a
	jr z, Func_00_3b31
	add a, $30
	ld c, a
	call PrintCharacterAtCursor
Func_00_3b31:
	ld a, [wBcdLow]
	add a, $30
	ld c, a
	call PrintCharacterAtCursor
	pop hl
	jp ScriptDispatcherNext
ScriptOpcode10Handler_RepeatChar:
	ld c, [hl]
	inc hl
	push hl
Func_00_3b41:
	push bc
	call WaitForNextFrame
	call DispatchTextRenderer
	call HideUnusedOamSprites
	pop bc
	dec c
	jr nz, Func_00_3b41
	pop hl
	jp ScriptDispatcherNext

SECTION "script_003bad", ROM0[$3bad]

ScriptOpcode0DHandler_Newline:
	ld a, [$d617]
	ld d, a
	ld a, [wTextCursor]
	ld e, a
	ld a, e
	and $e0
	ld e, a
	ld a, [wTextAnchor]
	and $1f
	add a, e
	ld e, a
	ld a, e
	add a, $40
	ld e, a
	ld a, d
	adc a, $00
	ld d, a
	ld a, e
	ld [wTextCursor], a
	ld a, d
	ld [$d617], a
	jp ScriptDispatcherNext
ScriptOpcode05Helper:
	push hl
	ld a, b
	ld [$d622], a
	ld a, c
	ld [wTextStateV2], a
	ld hl, $d627
	ld a, l
	ld [$d623], a
	ld a, h
	ld [$d624], a
	ld hl, $d67b
	ld a, l
	ld [$d625], a
	ld a, h
	ld [$d626], a
	push de
	ld hl, $d627
	ld c, $86
	ld de, $0686
	call WriteWindowRow
	ld a, [wTextStateV2]
	sub $02
Func_00_3c03:
	push af
	ld c, $06
	ld de, $0606
	call WriteWindowRow
	pop af
	dec a
	jr nz, Func_00_3c03
	ld c, $86
	ld de, $0686
	call WriteWindowRow
	ld hl, $d67b
	ld c, $78
	ld de, $7e7b
	call WriteWindowRow
	ld a, [wTextStateV2]
	sub $02
Func_00_3c28:
	push af
	ld c, $79
	ld de, $977c
	call WriteWindowRow
	pop af
	dec a
	jr nz, Func_00_3c28
	ld c, $7a
	ld de, $7f7d
	call WriteWindowRow
	pop de
	ld hl, $d621
	call CopyBgMap
	pop hl
	ret
WriteWindowRow:
	ld [hl], c
	inc hl
	ld a, [$d622]
	sub $02
Func_00_3c4d:
	ld [hl], d
	inc hl
	dec a
	jr nz, Func_00_3c4d
	ld [hl], e
	inc hl
	ret
DrawTextWindow:
	ld a, [$d61a]
	or a
	jr nz, Data_00_3c69
	push hl
	ld hl, $674b
	ld a, $19
	ld de, $9960
	call CopyBgMapBankedA
	pop hl
	ret

SECTION "script_003c77", ROM0[$3c77]

PrintCharacterAtCursor:
	push bc
	push de
	push hl
	ld a, c
	cp $40
	jr z, Data_00_3c98
	ld a, [$d617]
	ld d, a
	ld a, [wTextCursor]
	ld e, a
	call PrintCharacterAtCursor_Helper1
	ld a, c
	call PrintCharacterAtCursor_Helper2
	jr c, Func_00_3c94
	ld hl, $d616
	inc [hl]
Func_00_3c94:
	pop hl
	pop de
	pop bc
	ret

SECTION "script_003ca3", ROM0[$3ca3]

PrintCharacterAtCursor_Helper1:
	push bc
	ld a, c
	call PrintCharacterAtCursor_Helper2
	jr nc, Func_00_3cad

SECTION "script_003cad", ROM0[$3cad]

Func_00_3cad:
	ld a, e
	add a, $20
	ld e, a
	ld a, d
	adc a, $00
	ld d, a
	ld b, $00
	ld hl, $3d10
	add hl, bc
	ld b, [hl]
	ld a, c
	cp $de
	jr z, Func_00_3cd3
	cp $df
	jr z, Func_00_3cd3
	cp $b0
	jr z, Func_00_3cd3
	ld a, [$d61b]
	or a
	jr z, Func_00_3cd3

SECTION "script_003cd3", ROM0[$3cd3]

Func_00_3cd3:
	ld a, $01
	ldh [rVBK], a
	di
	call WaitForHBlank
	ld a, $07
	ld [de], a
	ld a, $00
	ldh [rVBK], a
	ld a, b
	ld [de], a
	ei
	pop bc
	ret
PrintCharacterAtCursor_Helper2:
	cp $de
	jr z, Data_00_3cf1
	cp $df
	jr z, Data_00_3cf1
	xor a
	ret

SECTION "script_003cf3", ROM0[$3cf3]

DispatchTextRenderer:
	ld a, [$7fff]
	push af
	ld a, [wRendererBank]
	ld [$2fff], a
	ld hl, $3d0b
	push hl
	ld hl, $d61e
	ld a, [hl+]
	ld h, [hl]
	ld l, a
	ld a, l
	or h
	ret z
	jp hl
DispatchTextRenderer_Return:
	pop af
	ld [$2fff], a
	ret

; --- $11 opcode handler + monster-name table (folded in from names.asm) ---
SECTION "names_003b53", ROM0[$3b53]

PrintIndexedName:
	ld e, [hl]
	inc hl
	ld d, [hl]
	inc hl
	push hl
	ld a, [de]
	ld hl, MonsterNamePointers
	sla a
	add a, l
	ld l, a
	ld a, h
	adc a, $00
	ld h, a
	ld a, [hl+]
	ld h, [hl]
	ld l, a
.PutChar:
	ld a, [hl+]
	or a
	jr z, .PutCharDone
	ld c, a
	call PrintCharacterAtCursor
	jr .PutChar
.PutCharDone:
	pop hl
	jp ScriptDispatcherNext

MonsterNamePointers:
	dw Name_Tiger
	dw Name_Mocchi
	dw Name_Hare
	dw Name_Gali
	dw Name_Golem
	dw Name_Suezo
	dw Name_Phenix

Name_Tiger:  db "Tiger", 0
Name_Mocchi: db "Mocchi", 0
Name_Hare:   db "Hare", 0
Name_Gali:   db "Gali", 0
Name_Golem:  db "Golem", 0
Name_Suezo:  db "Suezo", 0
Name_Phenix: db "Phenix", 0
